Repository jenkins-infra/jenkins.io, pull requests merged in 2019-10, with the labels that each got.

#2524 Hacktoberfest - Make the event teaser collapsable
  content/css/jenkins.css
  content/events/index.html.haml
Labels: hacktoberfest

#2529 Replace Hacktoberfest 2018 badge with a scaled 2019 version
  content/events/hacktoberfest.adoc
  content/images/hacktoberfest/2019_badge_small.png
Labels: hacktoberfest

#2530 Link to Hacktoberfest contributing to Jenkins slides
  content/events/hacktoberfest/event-kit.adoc
Labels: hacktoberfest

#2526 Hacktoberfest 2019: Add Hacktoberfest issue queries and the experienced developers section
  content/blog/2019/10/2019-10-01-hacktoberfest.adoc
  content/events/hacktoberfest.adoc
Labels: hacktoberfest

#2527 Hacktoberfest 2019 - Add the St. Petersburg JAM on Oct 28
  content/_data/events/2019-10-10-st-petersburg.adoc
  content/events/hacktoberfest.adoc
Labels: hacktoberfest

#2528 Automatically request reviews from the Hacktoberfest team for the Hactoberfest page changes
  .github/CODEOWNERS
Labels: hacktoberfest

#2525 Hacktoberfest - Fixed favicons for main frame
  content/_layouts/frame.html.haml
  content/sites/default/files/images/apple-touch-icon-120x120.png
  content/sites/default/files/images/apple-touch-icon-152x152.png
  content/sites/default/files/images/apple-touch-icon-76x76.png
  content/sites/default/files/images/favicon-16x16.png
  content/sites/default/files/images/favicon-32x32.png
  content/sites/default/files/images/favicon.ico
Labels: hacktoberfest

#2535 fixed link to gitlab
  content/events/hacktoberfest.adoc
Labels: hacktoberfest

#2532 Hacktoberfest 2019 - Add events in Munich, fix St. Petersburg meetup filename
  content/_data/events/2019-10-16-munich-hacktoberfest.adoc
  content/_data/events/2019-10-21-munich-hacktoberfest.adoc
  content/_data/events/2019-10-28-st-petersburg.adoc
  content/events/hacktoberfest.adoc
Labels: hacktoberfest

#2537 Hacktoberfest 2019 - Add links to the introductory slides
  content/events/hacktoberfest.adoc
  content/events/hacktoberfest/event-kit.adoc
Labels: hacktoberfest

#2534 Setup favicons according to realfavicongenerator.net
  content/_layouts/frame.html.haml
  content/android-chrome-192x192.png
  content/android-chrome-512x512.png
  content/apple-touch-icon.png
  content/browserconfig.xml
  content/favicon-16x16.png
  content/favicon-32x32.png
  content/favicon.ico
  content/mstile-150x150.png
  content/safari-pinned-tab.svg
  content/site.webmanifest
  content/sites/default/files/images/apple-touch-icon-120x120.png
  content/sites/default/files/images/apple-touch-icon-152x152.png
  content/sites/default/files/images/apple-touch-icon-76x76.png
  content/sites/default/files/images/favicon-16x16.png
  content/sites/default/files/images/favicon-32x32.png
  content/sites/default/files/images/favicon.ico
  package.json
Labels: hacktoberfest

#2538 [WEBSITE-666] - Hacktoberfest: Update the /participate/code page
  content/participate/code.adoc
  content/participate/index.html.haml
Labels: hacktoberfest

#2542 #hacktoberfest 2019 - Fix choose-your-github-account-organization-and-repository doc links
  content/doc/book/blueocean/creating-pipelines.adoc
Labels: hacktoberfest

#2545 Contributing: Document how to move documentation from Wiki using Pandoc
  CONTRIBUTING.adoc
Labels: hacktoberfest

#2548 Hacktoberfest 2019 - Add FAQ for maintainers and event organizers
  content/events/hacktoberfest/faq.adoc
Labels: hacktoberfest

#2549 Merge help and discuss sections
  content/participate/index.html.haml
Labels: hacktoberfest

#2546 2019 GSoC Blog post from Marky Jackson
  content/_data/authors/markyjackson-taulia.adoc
  content/blog/2019/10/2019-10-08-google-summer-of-code-mentor-and-org-admin-perspective.adoc
Labels: blogpost, gsoc, hacktoberfest

#2550 Move Adding a Logo guideline in Artwork page to contributing guidelines
  CONTRIBUTING.adoc
  content/artwork/index.html.haml
Labels: hacktoberfest

#2552 Added a participate/design page
  content/participate/design.adoc
  content/participate/index.html.haml
Labels: hacktoberfest

#2544 [WEBSITE-654] - Move the plugin documentation hosting info from Wiki to jenkins.io
  content/doc/developer/publishing/_chapter.yml
  content/doc/developer/publishing/documentation.adoc
  content/doc/developer/publishing/preparation.adoc
  content/doc/developer/publishing/requesting-hosting.adoc
  content/doc/developer/publishing/wiki-page.adoc
Labels: hacktoberfest

#2554 Fix invalid URL in 2.73.1 changelog (Hacktoberfest 2019)
  content/_data/upgrades/2-73-1.adoc
Labels: hacktoberfest

#2557 Fix some invalid Github profile links in blog posts (Hacktoberfest 2019)
  content/_data/authors/sladyn98.adoc
  content/blog/2016/2016-03-15-jenkins-certification.adoc
  content/blog/2016/2016-08-08-docker-pipeline-environments.adoc
Labels: hacktoberfest

#2551 [WEBSITE-206] Move guest post disclaimer to the front matter
  CONTRIBUTING.adoc
  content/_ext/asciidocrender.rb
  content/_ext/pipeline.rb
  content/_layouts/post.html.haml
  content/blog/2018/01/2018-01-17-jenkins-world-cfp-open.adoc
  content/blog/2018/02/2018-02-22-cheetah.adoc
  content/blog/2018/04/2018-04-25-configuring-jenkins-pipeline-with-yaml-file.adoc
  content/blog/2018/07/2018-07-13-jenkins-user-conference-china.adoc.adoc
  content/blog/2018/08/2018-08-17-speaker-blog-brent-laster.adoc
  content/blog/2018/09/2018-09-11-speaker-blog-warnings-plugin.adoc
  content/blog/2018/09/2018-09-12-2018-community-survey.adoc
  content/blog/2018/09/2018-09-14-kubernetes-and-secret-agents.adoc
  content/blog/2018/11/2018-11-12-inspecting-binaries-with-jenkins.adoc
  content/blog/2019/01/2019-01-08-mpl-modular-pipeline-library.adoc
  content/blog/2019/02/2019-02-06-ssh-steps-for-jenkins-pipeline.adoc
  content/blog/2019/02/2019-02-26-jenkins-alexa-voice-controlled-cicd.adoc
  content/blog/2019/03/2019-03-01-devops-world-jenkins-world-cfp-open.adoc
  content/blog/2019/05/2019-05-09-templating-engine.adoc
  content/blog/2019/09/2019-09-10-introducing-the-jira-software-plugin-for-jenkins.adoc
Labels: hacktoberfest

#2567 Fix date
  content/_data/changelogs/weekly.yml
Labels: hacktoberfest

#2575 Clarify the pattern for the when-branch condition
  content/doc/book/pipeline/syntax.adoc
Labels: hacktoberfest

#2573 [WEBSITE-670] - Document how to Migrate plugin from Wiki to GitHub
  content/doc/developer/publishing/documentation.adoc
  content/doc/developer/publishing/wiki-page.adoc
Labels: hacktoberfest

#2582 Stop crash when new files are added
  content/_partials/toptoolbar.html.haml
Labels: hacktoberfest

#2566 update clown logo file names
  content/images/logos/clown/clown.png
  content/images/logos/clown/clown.svg
Labels: hacktoberfest

#2578 Update some references from wiki to plugins.io
  content/projects/gsoc/2019/project-ideas/role-strategy-performance.adoc
  content/projects/gsoc/2019/project-ideas/role-strategy-ux.adoc
Labels: hacktoberfest

#2587 update clown logo yml
  content/_data/logo/clown.yml
Labels: hacktoberfest

#2579 Migrate plugin-site page from wiki
  content/doc/developer/publishing/plugin-site.adoc
  content/doc/developer/publishing/releasing.adoc
Labels: hacktoberfest

#2589 Document the Jenkins Wiki Exporter service for plugins
  content/doc/developer/publishing/wiki-page.adoc
Labels: hacktoberfest

#2577 GitHub Plugin Documentation Blogpost
  content/blog/2019/10/2019-10-21-plugin-docs-on-github.adoc
  content/images/post-images/2019-github-documentation/role-strategy-screenshot.png
  content/images/post-images/2019-github-documentation/thumbnail.png
Labels: blogpost, hacktoberfest, work-in-progress

#2576 "Thinking about Jenkins Security" blog post
  content/_data/authors/stackscribe.adoc
  content/blog/2019/10/2019-10-21-thinking-about-jenkins-security.adoc
  content/images/avatars/stackscribe.jpg
  content/images/avatars/wadeck.jpg
  content/images/security/do-not-run-malicious-code.png
Labels: blogpost

#2580 Add sections to navigation in developerbook
  content/_layouts/developerbook.html.haml
Labels: hacktoberfest

#2596 Make Platform Sig meeting time 12:00 UTC
  content/events/index.html.haml
  content/sigs/platform/index.adoc
Labels: hacktoberfest

#2606 Contributing: Extend guidelines for adding new logos
  CONTRIBUTING.adoc
Labels: hacktoberfest

#2605 [WEBSITE-661] Add support of multi-day events
  content/_data/events/2019-12-02-devops-world-jenkins-world-lisbon.adoc
  content/_partials/events.html.haml
  content/css/jenkins.css
Labels: hacktoberfest

#2586 Fill out plugin dev chapter more
  .gitignore
  content/doc/developer/plugin-development/_chapter.yml
  content/doc/developer/plugin-development/choosing-jenkins-baseline.adoc
  content/doc/developer/plugin-development/dependencies-and-class-loading.adoc
  content/doc/developer/plugin-development/index.adoc
  content/doc/developer/plugin-development/mark-a-plugin-incompatible.adoc
  content/doc/developer/plugin-development/optional-dependencies.adoc
  content/doc/developer/plugin-development/pipeline-integration.adoc
  content/doc/developer/plugin-development/plugin-release-tips.adoc
  content/images/developer/optional-dependency-example.png
  content/images/developer/plugin-not-compatible.png
Labels: hacktoberfest
