Repository jenkins-infra/jenkins.io, pull requests merged in 2019-08, with the labels that each got.

#2401 add cdf dropdown menu
  content/_partials/cdf_logo.html.haml
  content/_partials/toptoolbar.html.haml
Labels: on-hold

#2443 Failing build due to illegal filename
  Jenkinsfile
  scripts/blobxfer
Labels: gsoc

#2444 GSoC: Add blog on Role Strategy Plugin Performance improvements
  content/blog/2019/08/2019-08-26-role-strategy-performance.adoc
  content/images/post-images/role-strategy-performance/benchmarks1.png
  content/images/post-images/role-strategy-performance/benchmarks2.png
  content/images/post-images/role-strategy-performance/jcasc-export.png
Labels: gsoc

#2448 * DRAFT Update Jenkins Infrastructure homepage
  content/images/projects/infrastructure/contribution_workflow.png
  content/images/projects/infrastructure/infra_overview.png
  content/projects/infrastructure/index.adoc
Labels: do not merge, enhancement
