Repository jenkins-infra/jenkins.io, pull requests merged in 2019-11, with the labels that each got.

#2604 Separate sections for manual and automated testing
  content/participate/index.html.haml
  content/participate/test.adoc
Labels: hacktoberfest

#2617 Create an event for the DW_JW Hackfest on Dec 02
  content/_data/events/2019-12-02-dw-jw-hackfest.adoc
Labels: events

#2615 Hacktoberfest 2019 - Remove Jumbotron, add notice about end of the event
  content/events/hacktoberfest.adoc
  content/index.html.haml
Labels: hacktoberfest

#2572 [Hacktoberfest] Move "project" related pages to jenkins.io
  content/blog/2015/2015-12-17-fosdem-2016-travel-grant-program.md
  content/blog/2016/2016-08-24-jenkins-world-2016-festivities.adoc
  content/blog/2019/09/2019-09-25-board-elections.adoc
  content/chat.adoc
  content/press.adoc
  content/project/board-election-process.adoc
  content/project/board.adoc
  content/project/conduct.adoc
  content/project/governance.adoc
  content/project/team-leads.adoc
Labels: hacktoberfest

#2598 Updated Review Changes Section in content/participate
  content/participate/index.html.haml
  content/participate/review-changes.adoc
Labels: hacktoberfest

#2602 Jenkins World Lisbon blog post
  content/_data/authors/ignacio_fernandez.adoc
  content/blog/2019/11/2019-11-04-speaker-blog-how-to-build-the-top-mobile-game.adoc
  content/images/avatars/ignaciofernandez.jpg
Labels: blogpost

#2584 Port cli wiki to docs
  Gemfile.lock
  content/doc/developer/cli/_chapter.yml
  content/doc/developer/cli/index.adoc
  content/doc/developer/cli/writing-cli-commands.adoc
Labels: hacktoberfest

#2653 Add Jenkins Online Meetups on Nov 20 and 22
  content/_data/events/2019-11-20-jom-poet-pipeline-lib.adoc
  content/_data/events/2019-11-22-jom-plugin-docs.adoc
Labels: events

#2459 [JENKINS-59115] Documentation for branch when condition with comparator
  content/doc/book/pipeline/syntax.adoc
Labels: enhancement

#2553 Add missing Amsterdam meetup logos to Artwork
  content/_data/logo/amsterdam.yml
  content/images/logos/amsterdam/amsterdam.png
  content/images/logos/amsterdam/amsterdam256.png
Labels: hacktoberfest

#2662 Fix changelog errors and improve formatting
  content/_data/changelogs/weekly.yml
Labels: bug

#2661 Fix CODEOWNERS for GSoC entries
  .github/CODEOWNERS
Labels: gsoc

#2668 Blog for pre-release of matrix
  content/blog/2019/11/2019-11-22-welcome-to-the-matrix.adoc
Labels: blogpost

#2670 Jenkins Health Advisor by CloudBees announcement
  content/_data/authors/aheritier.adoc
  content/blog/2019/11/2019-11-22-jenkins-health-advisor-by-cloudbees.adoc
  content/images/avatars/aheritier.png
  content/images/post-images/jenkins-health-advisor-by-cloudbees/logo.svg
  content/images/post-images/jenkins-health-advisor-by-cloudbees/overview.png
Labels: blogpost

#2672 List regression version in 2.190.3 changelog
  content/_data/changelogs/lts.yml
Labels: bug

#2667 [NFRA-2264] - Create a blogpost for macOS native packaging deprecation
  content/blog/2019/11/2019-11-25-macos-native-installer-deprecation.adoc
Labels: blogpost, on-hold

#2533 [DOCS-1295] Adding a pipeline best practices guide
  content/doc/book/pipeline/_chapter.yml
  content/doc/book/pipeline/pipeline-best-practices.adoc
Labels: hacktoberfest

#2684 Archive 2019 GSOC info
  content/projects/gsoc/2019/index.adoc
Labels: gsoc

#2685 [GSoC 2020] - Rework landing for 2020 + update the application and mailing list links
  content/projects/gsoc/2020/application.md
  content/projects/gsoc/2020/index.adoc
  content/projects/gsoc/index.adoc
  content/projects/gsoc/mentors.adoc
  content/projects/gsoc/students.adoc
Labels: gsoc

#2682 Speaker blog post for DevOps World conference.
  content/_data/authors/woodspeed.adoc
  content/blog/2019/11/2019-11-29-do-plugins-store-credentials-in-a-secure-way.adoc
  content/images/post-images/2019-11-plugin-creds-secure-store/PluginWebForm.png
Labels: blogpost

#2687 Removed redundant copy of artifactory-rest-plugin
  content/projects/gsoc/2020/project-ideas/artifactory-rest-plugin copy.adoc
Labels: gsoc
