Repository jenkins-infra/jenkins.io, pull requests merged in 2020-05, with the labels that each got.

#3148 Update 2018-04-09-whats-in-declarative.adoc
  content/blog/2018/04/2018-04-09-whats-in-declarative.adoc
Labels: blogpost

#3149 GSoD 2020: Publish the application draft on the website
  content/projects/gsoc/2020/application.md
  content/sigs/docs/gsod/2020/application.md
  content/sigs/docs/gsod/index.adoc
Labels: gsoc

#3153 Properly format as Asciidoc
  content/_data/upgrades/2-204-1.adoc
Labels: changelog

#3152 Fix Debian install instructions, add Red Hat & CentOS
  content/doc/book/installing/index.adoc
  content/download/index.html.haml
Labels: documentation

#3154 Use NonNull annotation instead of deprecated Nonnull
  content/blog/2016/2016-05-25-update-plugin-for-pipeline.adoc
  content/blog/2018/08/2018-08-17-code-coverage-api-plugin-1.0-release.adoc
  content/blog/2019/06/2019-06-21-performance-testing-jenkins.adoc
  content/doc/developer/extensibility/action-for-all-projects.adoc
  content/doc/developer/plugin-development/pipeline-integration.adoc
Labels: blogpost, documentation

#3155 Add 2.235 changelog
  content/_data/changelogs/weekly.yml
Labels: changelog

#3158 GSoC 2020: Publish the accepted projects
  content/_data/authors/Sagar2366.adoc
  content/_data/authors/afalko.adoc
  content/_data/authors/ayush_agarwal.adoc
  content/_data/authors/baymac.adoc
  content/_data/authors/buddhikac96.adoc
  content/_data/authors/fcojfernandez.adoc
  content/_data/authors/imoutsatsos.adoc
  content/_data/authors/kwhetstone.adoc
  content/_data/authors/linuxsuren.adoc
  content/_data/authors/loghijiaha.adoc
  content/_data/authors/marckk.adoc
  content/_data/authors/markyjackson-taulia.adoc
  content/_data/authors/mikecirioli.adoc
  content/_data/authors/nextturn.adoc
  content/_data/authors/nikhildarocha.adoc
  content/_data/authors/nodece.adoc
  content/_data/authors/oleg_nenashev.adoc
  content/_data/authors/rishabhbudhouliya.adoc
  content/_data/authors/sharepointoscar.adoc
  content/_data/authors/timja.adoc
  content/_layouts/gsocproject.html.haml
  content/projects/gsoc/2020/project-ideas/github-checks.adoc
  content/projects/gsoc/2020/projects/custom-jenkins-distribution-build-service.adoc
  content/projects/gsoc/2020/projects/external-fingerprint-storage.adoc
  content/projects/gsoc/2020/projects/git-plugin-performance.adoc
  content/projects/gsoc/2020/projects/github-checks.adoc
  content/projects/gsoc/2020/projects/jenkins-x-apps-consolidation.adoc
  content/projects/gsoc/2020/projects/machine-learning.adoc
  content/projects/gsoc/2020/projects/winsw-yaml-configs.adoc
  content/projects/gsoc/index.adoc
Labels: gsoc

#3160 Fix rendering of the subprojects nav menu
  content/_partials/toptoolbar.html.haml
Labels: bug, gsoc

#3156 Use same docker image name for Windows tutorial as used for Linux
  content/doc/book/installing/_docker-for-tutorials.adoc
Labels: changelog, documentation

#3159 GSoC 2020: Update jumbotron, update org admins list
  content/index.html.haml
  content/projects/gsoc/index.adoc
Labels: gsoc

#3163 Roadmap: Add more ongoing and planned Advocacy and Outreach stories
  content/_data/roadmap/roadmap.yml
Labels: roadmap

#3166 [GSoC 2020] Added jenkins distribution service project details
  content/images/post-images/gsoc-custom-jenkins-service-distribution/cds-sequence-diagram.png
  content/projects/gsoc/2020/projects/custom-jenkins-distribution-build-service.adoc
Labels: gsoc

#3167 Add a blog post for Docker agent image renaming
  content/blog/2020/05/2020-05-06-docker-agent-image-renaming.adoc
  content/images/docker/dockerJenkins.png
  content/images/docker/dockerJenkins_social.png
Labels: blogpost

#3161 GSoC 2020: Add a OpenAPI link to the Open API specification project idea
  content/projects/gsoc/2020/project-ideas/automatic-spec-generator-for-jenkins-rest-api.adoc
Labels: gsoc

#3162 Jenkins Roadmap: Add GSoC 2020 projects and project ideas
  content/_data/roadmap/roadmap.yml
Labels: gsoc, roadmap

#3172 Fix the ssh-agent image name in the blogpost
  content/blog/2020/05/2020-05-06-docker-agent-image-renaming.adoc
Labels: blogpost

#3171 Update for jenkins.io
  content/_data/authors/loghijiaha.adoc
  content/projects/gsoc/2020/projects/machine-learning.adoc
Labels: gsoc

#3164 Jenkins Roadmap: Add 2020 elections and the Core Infrastructure Initiative compliance items
  content/_data/roadmap/roadmap.yml
Labels: governance, roadmap

#3173 Include Jenkins Templating Engine Version 2.0 in Roadmap
  content/_data/roadmap/roadmap.yml
Labels: roadmap

#3175 Change Gitter room to github-checks-api
  content/projects/gsoc/2020/projects/github-checks.adoc
Labels: gsoc

#3176 Custom Jenkins Distribution Service gitter link
  content/projects/gsoc/2020/projects/custom-jenkins-distribution-build-service.adoc
Labels: gsoc

#3179 Fix DockerHub links in the blog
  content/blog/2020/05/2020-05-06-docker-agent-image-renaming.adoc
Labels: blogpost, bug

#3180 Add Jenkins Online Meetups to the event calendar
  content/_data/events/2020-05-11-jom-kubernetes-operator copy.adoc
  content/_data/events/2020-05-15-jom-anchore.adoc
Labels: events

#3178 Fix the DockerHub spelling in the blogpost
  content/blog/2020/05/2020-05-06-docker-agent-image-renaming.adoc
Labels: blogpost

#3132 Add Jenkins is the Way case studies to the Jumbotron
  content/index.html.haml
Labels: artwork, blogpost

#3177 Modify git performance improvement project page with updated bio
  content/_data/authors/rishabhbudhouliya.adoc
  content/images/post-images/gsoc-git-performance-improvement/git-additional-behavior.png
  content/projects/gsoc/2020/projects/git-plugin-performance.adoc
Labels: gsoc

#3183 Fix security warnings and broken links
  content/_data/roadmap/roadmap.yml
  content/blog/2019/12/2019-12-14-generic-webhook-trigger-plugin.adoc
  content/doc/book/resources/tutorials/labview-15-build-sys-repo-env-var.PNG
  content/doc/book/resources/tutorials/labview-15-build-sys-repo-env-var.png
  content/doc/developer/publishing/artifact-repository.adoc
  content/doc/tutorials/build-a-labview-app.adoc
  content/participate/test.adoc
  content/projects/gsoc/mentors.adoc
  package-lock.json
  package.json
Labels: blogpost, chore, documentation, gsoc, roadmap

#3121 Update value of url in footer and added option new UX feature
  content/doc/book/managing/system-properties.adoc
Labels: documentation

#3182 [WEBSITE-743] Added External Fingerprint Storage Project Details
  content/images/post-images/gsoc-external-fingerprint-storage-for-jenkins/overview.png
  content/projects/gsoc/2020/projects/external-fingerprint-storage.adoc
Labels: gsoc

#3227 GSoC 2020 External Storage: Fix the Gitter link, add meetings section and merge sentences in the first paragraph
  content/projects/gsoc/2020/projects/external-fingerprint-storage.adoc
Labels: gsoc

#3226 GSoC: Improved GitHub Checks project page
  content/images/post-images/gsoc-github-checks/architecture.png
  content/images/post-images/gsoc-github-checks/workflow.png
  content/projects/gsoc/2020/projects/github-checks.adoc
Labels: gsoc

#3230 Use definition list instead of table for system properties
  content/doc/book/managing/system-properties.adoc
Labels: documentation

#3224 Create initial landing for the UI/UX Hackfest
  content/_data/events/2020-05-25-ui-ux-hackathon.adoc
  content/events/hacktoberfest/faq.adoc
  content/events/online-hackfest/2020-uiux/faq.adoc
  content/events/online-hackfest/2020-uiux/index.adoc
  content/images/post-images/jenkins-is-the-way/hackfest-swag-socks.png
  content/images/post-images/jenkins-is-the-way/hackfest-swag-sticker.png
  content/images/post-images/jenkins-is-the-way/jenkins-is-the-way-hackfest-opengraph.png
Labels: events

#3231 Add details to jenkins-x-apps-consolidation.adoc
  content/projects/gsoc/2020/projects/jenkins-x-apps-consolidation.adoc
Labels: gsoc

#3229 GSoC 2020 External Fingerprint Storage Page: Fix image dimensions
  content/projects/gsoc/2020/projects/external-fingerprint-storage.adoc
Labels: gsoc

#3225 Add Git Plugin Performance project office hours
  content/projects/gsoc/2020/projects/git-plugin-performance.adoc
Labels: gsoc

#3181 Windows docker agents blog article
  content/blog/2020/05/2020-05-11-docker-windows-agents.adoc
Labels: blogpost

#3234 Clarify fork and clone instruction
  content/doc/developer/building/intellij.adoc
Labels: documentation

#3239 GSoD 2020: Update the status, add new opengraph image for the page
  content/images/gsod/gsod_opengraph.png
  content/sigs/docs/gsod/index.adoc
Labels: gsod

#3237 Add changelog for 2.236
  content/_data/changelogs/weekly.yml
Labels: changelog

#3233 Fix broken links, use new domain name
  content/_layouts/changelog.html.haml
  content/_layouts/frame.html.haml
  content/blog/2019/12/2019-12-14-generic-webhook-trigger-plugin.adoc
  content/changelog-stable/index.html.haml
  content/changelog/index.html.haml
  content/projects/gsoc/mentors.adoc
  scripts/check-broken-links
Labels: blogpost, changelog, chore, documentation, gsoc, roadmap

#3238 GSoC External Fingerprint Storage: Meeting Time Added
  content/projects/gsoc/2020/projects/external-fingerprint-storage.adoc
Labels: gsoc

#3241 Update meeting schedule
  content/projects/gsoc/2020/projects/machine-learning.adoc
Labels: gsoc

#3240 Custom Distribution Service: Updated meeting timings and project notes
  content/projects/gsoc/2020/projects/custom-jenkins-distribution-build-service.adoc
Labels: gsoc

#3242 Update Winsw-yaml-config.adoc
  content/projects/gsoc/2020/projects/winsw-yaml-configs.adoc
Labels: gsoc

#3245 Fix reference to library name
  content/doc/developer/handling-requests/stapler-accessible-type.adoc
Labels: documentation

#3244 UI/UX Hackfest announcement
  content/blog/2020/04/2020-04-30-jenkins-is-the-way.adoc
  content/blog/2020/05/2020-05-12-uiux-hackfest-announcement.adoc
  content/events/online-hackfest/2020-uiux/faq.adoc
  content/events/online-hackfest/2020-uiux/index.adoc
  content/images/post-images/jenkins-is-the-way/register-button.png
Labels: blogpost

#3247 UI/UX hackfest: add more links
  content/blog/2020/05/2020-05-12-uiux-hackfest-announcement.adoc
  content/events/online-hackfest/2020-uiux/index.adoc
Labels: blogpost

#3253 Simplify read-only view docs
  content/doc/developer/views/read-only.adoc
Labels: documentation

#3246 Add the project application draft.
  content/projects/gsoc/2020/projects/winsw-yaml-configs.adoc
Labels: gsoc

#3250 Update JTE 2.0 link on roadmap
  content/_data/roadmap/roadmap.yml
Labels: roadmap

#3248 UX SIG: add current project from the roadmap and more SIG members
  content/_data/roadmap/roadmap.yml
  content/events/online-hackfest/2020-uiux/index.adoc
  content/sigs/ux/index.adoc
Labels: roadmap

#3255 [WEBSITE-748] - Add issue templates to jenkins.io
  .github/ISSUE_TEMPLATE/1-documentation.yml
  .github/ISSUE_TEMPLATE/2-wiki-migration.yml
  .github/ISSUE_TEMPLATE/3-enhancement.yml
  .github/ISSUE_TEMPLATE/4-bug.yml
  .github/ISSUE_TEMPLATE/config.yml
Labels: chore

#3258 Fix GitHub issue template extensions
  .github/ISSUE_TEMPLATE/1-documentation.md
  .github/ISSUE_TEMPLATE/2-wiki-migration.md
  .github/ISSUE_TEMPLATE/3-enhancement.md
  .github/ISSUE_TEMPLATE/4-bug.md
Labels: chore

#3259 UI/UX hackfest: Add UX testing and Table-to-divs migration to the projects list
  content/blog/2020/05/2020-05-12-uiux-hackfest-announcement.adoc
  content/events/online-hackfest/2020-uiux/index.adoc
Labels: blogpost

#3165 Jenkins Board Election Process: restructure the page
  content/project/board-election-process.adoc
Labels: governance

#3263 Add Docs office hours
  content/_data/events/2020-05-15-jom-anchore.adoc
  content/events/index.html.haml
  content/sigs/docs/gsod/index.adoc
  content/sigs/docs/index.adoc
Labels: events

#3056 [INFRA-1105] - Rename agent Docker image names
  content/_data/upgrades/2-121-1.adoc
  content/blog/2018/12/2018-12-14-java11-preview-availability.adoc
  content/projects/remoting/index.adoc
Labels: blogpost, changelog, documentation

#3257 Add meeting schedule and notes to the github checks project page
  content/projects/gsoc/2020/projects/github-checks.adoc
Labels: gsoc

#3256 Update windw-yaml-config.adoc
  content/projects/gsoc/2020/projects/winsw-yaml-configs.adoc
Labels: gsoc

#3272 Add May 18 and 19 events
  content/_data/events/2020-05-18-job-plugin-pom-4.adoc
  content/_data/events/2020-05-19-job-dsl.adoc
Labels: events

#3274 Improve the "Report a problem" button so that it uses the issue template
  .github/ISSUE_TEMPLATE/4-bug.md
  content/_layouts/frame.html.haml
Labels: chore

#3126 Fixed distribution link that is not clickable
  content/projects/gsoc/2020/project-ideas/jenkins-distribution-customize-service.adoc
Labels: gsoc

#3269 Add FreeBSD install instructions
  content/doc/book/installing/index.adoc
Labels: documentation

#3277 Add Jenkins Kubernetes Operator logo
  content/_data/logo/kubernetes-operator.yml
  content/images/logos/kubernetes-operator/256.png
  content/images/logos/kubernetes-operator/kubernetes-operator.png
Labels: artwork

#3282 Add office hours & remove unnecessary content
  content/projects/gsoc/2020/projects/jenkins-x-apps-consolidation.adoc
Labels: gsoc

#3286 Add 2.237 changelog
  content/_data/changelogs/weekly.yml
Labels: changelog

#3287 Add CSS for table borders
  content/css/jenkins.css
Labels: documentation

#3290 Update the GitHub App Authentication post: Now in GA
  content/blog/2020/04/2020-04-16-github-app-authentication.adoc
Labels: blogpost

#3268 Update Wiki conversion docs to replace INFRA-2328 text
  CONTRIBUTING.adoc
Labels: documentation

#3291 GSoC 2020 - Update the list of mentors and advisors + redirect for the projects link
  content/_layouts/gsocproject.html.haml
  content/projects/gsoc/2020/projects.adoc
  content/projects/gsoc/2020/projects/custom-jenkins-distribution-build-service.adoc
  content/projects/gsoc/2020/projects/github-checks.adoc
Labels: gsoc

#3292 Jenkins Administrator Guide: Add a page about UI themes
  content/doc/book/managing/_chapter.yml
  content/doc/book/managing/ui-themes.adoc
  content/doc/book/resources/managing/simple-theme-plugin-neo2.png
Labels: documentation

#3281 Add additional read only view docs
  content/doc/developer/views/read-only.adoc
Labels: documentation

#3296 Aborting a build
  content/doc/book/using/_chapter.yml
  content/doc/book/using/aborting-a-build.adoc
Labels: documentation

#3278 Add content to Jenkins Monitoring in System Administration
  content/doc/book/system-administration/monitoring.adoc
Labels: documentation

#3318 Update External Fingerprint Storage Project Page
  content/projects/gsoc/2020/projects/external-fingerprint-storage.adoc
Labels: gsoc

#3276 Remove Windows HTTPS extra sentence
  content/doc/book/installing/_jenkins-command-parameters.adoc
Labels: documentation

#3252 Add how to guide for table => div migration
  content/doc/developer/views/_chapter.yml
  content/doc/developer/views/table-to-div-migration.adoc
Labels: documentation

#3331 Small fixes
  CONTRIBUTING.adoc
  content/doc/book/architecting-for-scale.adoc
Labels: documentation

#3338 update winsw-yaml-config.adoc
  content/projects/gsoc/2020/projects/winsw-yaml-configs.adoc
Labels: gsoc

#3330 Providing valid reference to LTS release
  content/project/governance.adoc
Labels: governance

#3334 Add 2.222.4 changelog and upgrade guide
  content/_data/changelogs/lts.yml
  content/_data/upgrades/2-222-4.adoc
Labels: changelog

#3333 A note to help get the initial password.
  content/doc/book/installing/_setup-wizard.adoc
Labels: documentation

#3342 Add 2.238 changelog
  content/_data/changelogs/weekly.yml
Labels: changelog

#3279 Read only jenkins announcement
  content/blog/2020/05/2020-05-18-read-only-jenkins-announcement.adoc
  content/images/post-images/2020/05-read-only-jenkins-announcement/build-discarder-edit.png
  content/images/post-images/2020/05-read-only-jenkins-announcement/build-discarder-read.png
Labels: blogpost

#3345 UI/UX Hackfest; Fix the Jenkins blog link
  content/events/online-hackfest/2020-uiux/index.adoc
Labels: bug

#3349 ReadOnly UI - Fix the blogpost date
  content/blog/2020/05/2020-05-25-read-only-jenkins-announcement.adoc
Labels: blogpost, bug

#3347 fixes link to pipeline as yaml plugin
  content/projects/gsoc/2020/project-ideas/pipeline-as-yaml-experiment.adoc
Labels: gsoc

#3351 Migrate fingerprints from wiki
  content/doc/book/using/_chapter.yml
  content/doc/book/using/fingerprints.adoc
Labels: documentation

#3358 Fix unnecessarily brittle link directly to resource file
  content/doc/developer/plugin-governance/adopt-a-plugin.adoc
Labels: documentation

#3356 Migrate "Using Local Language" from wiki
  content/doc/book/resources/using/jenkins-in-italian.png
  content/doc/book/using/_chapter.yml
  content/doc/book/using/using-local-language.adoc
Labels: documentation

#3359 Add link to Toulouse JAM on Jenkins Artwork page
  content/_data/logo/toulousejam.yml
Labels: artwork

#3365 cosmetic: no more a table but a list
  content/doc/book/managing/system-properties.adoc
Labels: documentation

#3369 Add link to recording of Hackfest session
  content/blog/2020/03/2020-03-17-ui-plugins.adoc
Labels: blogpost

#3370 Add Custom Distribution Service github project link
  content/projects/gsoc/2020/projects/custom-jenkins-distribution-build-service.adoc
Labels: gsoc

#3360 Add the 2nd common reason for 403: The release already exists
  content/doc/developer/publishing/releasing.adoc
Labels: documentation

#3366 Migrate 'Pipeline CPS method mismatches' wiki page to jenkins.io
  content/doc/book/pipeline/_chapter.yml
  content/doc/book/pipeline/cps-method-mismatches.adoc
  content/redirect/pipeline-cps-method-mismatches.adoc
Labels: documentation

#3374 Expand upon serializability best practices in pipeline docs
  content/doc/book/pipeline/pipeline-best-practices.adoc
Labels: documentation

#3382 UI/UX Hackfest - Fix the link to Advocacy&Outreach SIG
  content/blog/2020/05/2020-05-12-uiux-hackfest-announcement.adoc
Labels: blogpost, bug

#3262 Convert 'Remote access API' wiki page to jenkins.io #3184
  content/doc/book/using/_chapter.yml
  content/doc/book/using/remote-access-api.adoc
  content/doc/book/using/remote-api.adoc
  content/images/using/remote-access-api/file-parameter.png
Labels: documentation

#3316 Migrated 'How to reference another project by name'
  content/doc/book/using/_chapter.yml
  content/doc/book/using/referencing-another-project-by-name.adoc
Labels: documentation

#3378 [migrate] Serialization of anonymous classes
  content/doc/developer/extensibility/_chapter.yml
  content/doc/developer/extensibility/serialization-of-anonymous-classes.adoc
  content/redirect/serialization-of-anonymous-classes.adoc
Labels: documentation

#3377 Use grid-all as selector for tables
  content/css/jenkins.css
  content/projects/gsoc/2019/project-ideas.html.haml
  content/projects/gsoc/2020/project-ideas.html.haml
Labels: gsoc

#3371 Add Project Repository link to External Fingerprint Storage project
  content/projects/gsoc/2020/projects/external-fingerprint-storage.adoc
Labels: gsoc

#3303 Issue #2889 - Item: Add Java version
  content/doc/book/installing/index.adoc
Labels: documentation

#3376 Added anchors for system properties
  content/doc/book/managing/system-properties.adoc
Labels: documentation

#3324 Migrated 'Monitor and restart offline slaves' from wiki
  content/doc/book/managing/nodes.adoc
Labels: documentation

#3361 Update Docker solution
  content/_data/solutions/docker.yml
  content/solutions/docker.adoc
Labels: documentation

#3388 Convert 'Authenticating scripted clients' wiki page to jenkins.io #3201
  content/doc/book/system-administration/_chapter.yml
  content/doc/book/system-administration/authenticating-scripted-clients.adoc
Labels: documentation

#3387 Document how to migrate to using buildsDir
  content/doc/book/managing/system-properties.adoc
Labels: documentation

#3397 Fix another unnecessarily brittle link into another repo
  content/doc/developer/plugin-governance/adopt-a-plugin.adoc
Labels: documentation

#3393 Cleanup system properties page
  content/css/jenkins.css
  content/doc/book/managing/system-properties.adoc
Labels: documentation
