Repository jenkins-infra/jenkins.io, pull requests merged in 2020-10, with the labels that each got.

#3818 Update Governance meeting documentation and add participation guidelines
  content/project/governance-meeting/index.adoc
Labels: documentation, governance

#3826 Fix minor grammar stuff
  Makefile
Labels: chore

#3829 Add WMI Windows agent plugin ref to 2.249.1 upgrade guide
  content/_data/upgrades/2-249-1.adoc
Labels: changelog

#3828 Add 2.249.2 changelog and upgrade guide
  content/_data/changelogs/lts.yml
  content/_data/upgrades/2-249-2.adoc
Labels: changelog

#3848 Change occurrences of master in "Managing Jenkins" chapter
  content/doc/book/managing/cli.adoc
  content/doc/book/managing/index.adoc
  content/doc/book/managing/plugins.adoc
  content/doc/book/managing/script-console.adoc
  content/doc/book/managing/security.adoc
  content/doc/book/managing/system-properties.adoc
Labels: documentation, hacktoberfest

#3850 Fix terminology in "Pipeline" chapter #3836 - Changed references of master to controller
  content/doc/book/pipeline/development.adoc
  content/doc/book/pipeline/index.adoc
  content/doc/book/pipeline/jenkinsfile.adoc
  content/doc/book/pipeline/pipeline-best-practices.adoc
  content/doc/book/pipeline/scaling-pipeline.adoc
  content/doc/book/pipeline/shared-libraries.adoc
  content/doc/book/pipeline/syntax.adoc
Labels: hacktoberfest

#3856 Fix the elections link on the Jumbotron
  content/index.html.haml
Labels: bug

#3822 Installing jenkins on kubernetes
  content/doc/book/installing/_kubernetes.adoc
  content/doc/book/installing/index.adoc
Labels: documentation, squash-merge-me

#3869 Import sublicense & approved trademark usages from wiki
  content/project/governance.adoc
  content/project/index.adoc
  content/project/trademark/approved-usage.adoc
  content/project/trademark/index.adoc
  content/project/trademark/sublicense.adoc
Labels: governance

#3877 Preparing for Plugin Development - changes to improve readability
  content/doc/developer/tutorial/prepare.adoc
Labels: hacktoberfest-accepted

#3883 modify some punctuation discription error in weekly changelog 2.261
  content/_data/changelogs/weekly.yml
Labels: changelog

#3884 Add changelog for Jenkins 2.263
  content/_data/changelogs/weekly.yml
Labels: changelog

#3879 Blog post on sustainable pattern with shared library
  content/blog/2020/10/2020-10-21-a-sustainable-pattern-with-shared-library.adoc
Labels: blogpost

#3889 2020 - Update the candidates list publishing date
  content/blog/2020/09/2020-09-24-board-elections.adoc
  content/project/board-election-process.adoc
Labels: blogpost, governance

#3893 Diagnosing Errors: Add a section for Out Of memory Errors
  content/doc/book/system-administration/diagnosing-errors.adoc
Labels: documentation

#3896 Hacktoberfest: Migrated User Content from wiki to doc page
  content/doc/book/managing/_chapter.yml
  content/doc/book/managing/user-content.adoc
Labels: hacktoberfest-accepted

#2943 [WEBSITE-716] - Update the Jenkins officer role descriptions
  content/project/team-leads.adoc
Labels: governance, on-hold

#3903 Jenkins 2020 elections - candidates announcement blog
  content/blog/2020/09/2020-09-24-board-elections.adoc
  content/blog/2020/10/2020-10-28-election-candidates.adoc
  content/images/governance/elections/2020/opengraph.png
  content/project/board-election-process.adoc
Labels: work-in-progress

#3904 Elections blogpost - Fix spelling in the first paragraph
  content/blog/2020/10/2020-10-28-election-candidates.adoc
Labels: blogpost

#3910 [GSoC 2021] - Initialize the GSoC 2021 project ideas, update landing
  content/projects/gsoc/2021/index.adoc
  content/projects/gsoc/2021/project-ideas.html.haml
  content/projects/gsoc/2021/project-ideas/automatic-spec-generator-for-jenkins-rest-api.adoc
  content/projects/gsoc/2021/project-ideas/plugin-installation-manager-tool.adoc
  content/projects/gsoc/2021/project-ideas/remoting-monitoring.adoc
  content/projects/gsoc/index.adoc
Labels: gsoc

#3911 Tutorial
  content/doc/book/resources/tutorials/IBMCloud/block-cluster.png
  content/doc/book/resources/tutorials/IBMCloud/block-search.png
  content/doc/book/resources/tutorials/IBMCloud/block-storage-create.png
  content/doc/book/resources/tutorials/IBMCloud/cluster-done.png
  content/doc/book/resources/tutorials/IBMCloud/cluster-main.png
  content/doc/book/resources/tutorials/IBMCloud/cluster-prepare.png
  content/doc/book/resources/tutorials/IBMCloud/cluster-select.png
  content/doc/book/resources/tutorials/IBMCloud/create-new.png
  content/doc/book/resources/tutorials/IBMCloud/details-names.png
  content/doc/book/resources/tutorials/IBMCloud/details-namespace.png
  content/doc/book/resources/tutorials/IBMCloud/details-resource.png
  content/doc/book/resources/tutorials/IBMCloud/details-tags.png
  content/doc/book/resources/tutorials/IBMCloud/done.png
  content/doc/book/resources/tutorials/IBMCloud/endpoints.png
  content/doc/book/resources/tutorials/IBMCloud/get-ns.png
  content/doc/book/resources/tutorials/IBMCloud/get-pods.png
  content/doc/book/resources/tutorials/IBMCloud/get-service.png
  content/doc/book/resources/tutorials/IBMCloud/in-progress.png
  content/doc/book/resources/tutorials/IBMCloud/infra-select.png
  content/doc/book/resources/tutorials/IBMCloud/install.png
  content/doc/book/resources/tutorials/IBMCloud/kubernetes-select.png
  content/doc/book/resources/tutorials/IBMCloud/location-avail.png
  content/doc/book/resources/tutorials/IBMCloud/location-geo.png
  content/doc/book/resources/tutorials/IBMCloud/location-worker.png
  content/doc/book/resources/tutorials/IBMCloud/login.png
  content/doc/book/resources/tutorials/IBMCloud/name-new.png
  content/doc/book/resources/tutorials/IBMCloud/parameters.png
  content/doc/book/resources/tutorials/IBMCloud/password.png
  content/doc/book/resources/tutorials/IBMCloud/resource-select.png
  content/doc/book/resources/tutorials/IBMCloud/search.png
  content/doc/book/resources/tutorials/IBMCloud/target-select.png
  content/doc/book/resources/tutorials/IBMCloud/tasg-new.png
  content/doc/book/resources/tutorials/IBMCloud/terminal-install.jpg
  content/doc/book/resources/tutorials/IBMCloud/welcome.png
  content/doc/book/resources/tutorials/IBMCloud/worker-pool.png
  content/doc/tutorials/index.adoc
  content/doc/tutorials/tutorial-for-installing-jenkins-on-IBM-Cloud.adoc
Labels: squash-merge-me

#3845 Jenkins on kubernetes doc skeleton
  content/doc/book/installing/_kubernetes.adoc
  content/doc/book/scaling/_chapter.yml
  content/doc/book/scaling/scaling-jenkins-on-kubernetes.adoc
  content/doc/book/system-administration/_chapter.yml
  content/doc/book/system-administration/administering-jenkins-on-kubernetes.adoc
Labels: documentation
