Repository jenkins-infra/jenkins.io, pull requests merged in 2020-08, with the labels that each got.

#3579 Update External Fingerprint Storage project page
  content/projects/gsoc/2020/projects/external-fingerprint-storage.adoc
Labels: gsoc

#3582 Add page on verifying downloads
  content/download/index.html.haml
  content/download/verify.adoc
Labels: documentation

#3577 Add coding phase 2 blogpost for checks api plugin
  content/blog/2020/08/2020-08-03-github-checks-api-plugin-coding-phase-2.adoc
  content/images/post-images/2020/08-github-checks-api-plugin-coding-phase-2/annotations.png
  content/images/post-images/2020/08-github-checks-api-plugin-coding-phase-2/coverage-details.png
  content/images/post-images/2020/08-github-checks-api-plugin-coding-phase-2/coverage-summary.png
  content/images/post-images/2020/08-github-checks-api-plugin-coding-phase-2/opengraph.png
  content/images/post-images/2020/08-github-checks-api-plugin-coding-phase-2/severity-statistics.png
  content/images/post-images/2020/08-github-checks-api-plugin-coding-phase-2/warning-checks.png
Labels: blogpost, gsoc

#3588 Add Jenkins 2.251 changelog
  content/_data/changelogs/weekly.yml
Labels: changelog, squash-merge-me

#3590 Update Cloud Native platforms roadmap items
  content/_data/roadmap/roadmap.yml
Labels: roadmap

#3591 CDF graduation blogpost
  content/blog/2020/08/2020-08-04-cdf-graduation.adoc
  content/images/logos/graduation/256.png
  content/images/logos/graduation/graduation.png
  content/images/post-images/2020/08-cdf-graduation/opengraph.png
Labels: blogpost, on-hold

#3589 Roadmap - Update the initiative statuses and links
  content/_data/roadmap/roadmap.yml
Labels: roadmap

#3592 CDF Graduation blog - add newsletter links
  content/blog/2020/08/2020-08-04-cdf-graduation.adoc
Labels: blogpost

#3593 Enabling new 'inbound agent' terminology
  content/doc/book/installing/_jenkins-command-parameters.adoc
Labels: documentation

#3594 Remove T-Mobile case study and adopters entry
  content/_data/adopters/TMobile.adoc
  content/blog/2020/02/2020-02-10-t-mobile-case-study.adoc
  content/images/post-images/t-mobile-case-study-opengraph/t-mobile-and-jenkins.png
Labels: blogpost

#3595 Avoid WEBSITE-630 non-deletion of removed files
  content/blog/2020/02/2020-02-10-t-mobile-case-study.adoc
Labels: blogpost

#3596 Remove case study page completely
  content/blog/2020/02/2020-02-10-t-mobile-case-study.adoc
Labels: blogpost

#3612 Add redirect for the Jenkins X sub-project and remove the sub-project
  content/projects/index.adoc
  content/projects/jenkins-x.adoc
Labels: bug

#3613 Redirect deleted case study to 404
  content/blog/2020/02/2020-02-10-t-mobile-case-study.adoc
Labels: blogpost

#3616 Add websocket configuration for nginx reverse proxy
  content/doc/book/system-administration/reverse-proxy-configuration-with-jenkins.adoc
Labels: documentation

#3619 Updates to /doc/book/managing/cli/ esp. w.r.t. -webSocket
  content/doc/book/managing/cli.adoc
Labels: documentation

#3557 Custom Distribution Service BlogPost - Phase 2
  content/blog/2020/08/2020-08-09-custom-distribution-service-phase-2.adoc
  content/images/post-images/gsoc-custom-jenkins-service-distribution/comm-config.png
Labels: blogpost, gsoc

#3626 Fix the OpenGraph link in the Custom Jenkins Distribution build service blogpost
  content/blog/2020/08/2020-08-09-custom-distribution-service-phase-2.adoc
Labels: blogpost, bug

#3627 Updated avatar for profile
  content/images/avatars/loghijiaha.jpeg
Labels: gsoc

#3620 Windows Installer Upgrade blog
  content/_data/authors/vsilverman.adoc
  content/blog/2020/08/2020-08-12-windows-installers-upgrade.adoc
  content/images/avatars/vsilverman.jpg
  content/images/post-images/2020-08-12-win-installers-upgrade/new_installer_1.png
  content/images/post-images/2020-08-12-win-installers-upgrade/new_installer_2.png
  content/images/post-images/2020-08-12-win-installers-upgrade/new_installer_3.png
  content/images/post-images/2020-08-12-win-installers-upgrade/new_installer_4.png
  content/images/post-images/2020-08-12-win-installers-upgrade/new_installer_5.png
  content/images/post-images/2020-08-12-win-installers-upgrade/new_installer_6.png
  content/images/post-images/2020-08-12-win-installers-upgrade/old_installer_1.png
  content/images/post-images/2020-08-12-win-installers-upgrade/old_installer_2.png
  content/images/post-images/2020-08-12-win-installers-upgrade/old_installer_3.png
Labels: blogpost, squash-merge-me

#3586 Add changelog and upgrade guide for 2.235.4
  content/_data/changelogs/lts.yml
  content/_data/upgrades/2-235-4.adoc
Labels: changelog

#3615 Add instructions for creating a redirect
  CONTRIBUTING.adoc
Labels: documentation

#3629 Add @slide to the authors list of the new Windows installer blog
  content/blog/2020/08/2020-08-12-windows-installers-upgrade.adoc
Labels: blogpost

#3633 Adding privilege reqs to Jenkins installer for win
  content/doc/book/installing/index.adoc
Labels: documentation

#3636 Update 2-235-5.adoc
  content/_data/upgrades/2-235-5.adoc
Labels: changelog

#3635 WIP: Update Project page for GSoC Custom Jenkins Distribution Service
  content/projects/gsoc/2020/projects/custom-jenkins-distribution-build-service.adoc
Labels: gsoc

#3638 Fix links to jenkinsci repos in table
  content/doc/developer/publishing/source-code-hosting/forks.adoc
Labels: documentation

#3573 WinSW - YAML Support - GSoC 2020 Phase 2 blog post
  content/blog/2020/07/2020-07-30-winsw-yaml-support-2.adoc
Labels: blogpost, gsoc

#3637 Jenkins 2.253 changelog
  content/_data/changelogs/lts.yml
  content/_data/changelogs/weekly.yml
Labels: changelog

#3651 Fix typo (succeeeded -> succeeded)
  content/doc/pipeline/tour/post.adoc
Labels: documentation

#3652 update system-properties.adoc documentation for historyWidget.descriptionLimit
  content/doc/book/managing/system-properties.adoc
Labels: documentation

#3654 Add 2.254 changelog
  content/_data/changelogs/weekly.yml
Labels: changelog

#3646 External Fingerprint Storage project Phase-3 updates
  content/blog/2020/08/2020-08-25-external-fingerprint-storage-phase-3.adoc
  content/images/post-images/2020/08-external-fingerprint-storage-phase-3/configure.png
  content/images/post-images/2020/08-external-fingerprint-storage-phase-3/opengraph.png
Labels: blogpost

#3647 Update External Fingerprint Storage Project Page
  content/images/post-images/gsoc-external-fingerprint-storage-for-jenkins/config_page.png
  content/images/post-images/gsoc-external-fingerprint-storage-for-jenkins/overview.png
  content/projects/gsoc/2020/projects/external-fingerprint-storage.adoc
Labels: gsoc

#3648 Update windows service wrapper - YAML configuration support project page
  content/projects/gsoc/2020/projects/winsw-yaml-configs.adoc
Labels: gsoc

#3656 Remove platformlabeler from Hacktoberfest list
  content/events/hacktoberfest.adoc
Labels: hacktoberfest

#3649 Added GSoC phase 3 blog post
  content/blog/2020/08/2020-08-27-machine-learning-plugin-coding-phase3.adoc
  content/images/gsoc/2020/machine_learning_plugin/action_image_view.png
  content/projects/gsoc/2020/projects/machine-learning.adoc
Labels: blogpost, gsoc

#3661 Update GitHub checks api project page
  content/projects/gsoc/2020/projects/github-checks.adoc
Labels: gsoc

#3659 Update Custom Distribution Service Project page
  content/projects/gsoc/2020/projects/custom-jenkins-distribution-build-service.adoc
Labels: gsoc

#3657 Create phase 3 blog post
  content/blog/2020/08/2020-08-27-winsw-yaml-support.adoc
Labels: blogpost

#3663 Fix for Jenkins install doc issue #3522
  content/doc/book/installing/index.adoc
Labels: documentation

#3667 Fix broke internal blog links and add phase 3 demo link
  content/projects/gsoc/2020/projects/github-checks.adoc
Labels: gsoc

#3668 Added final demo video
  content/projects/gsoc/2020/projects/machine-learning.adoc
Labels: gsoc

#3669 docs: update Jenkins X consolidate Apps/Addons page
  content/projects/gsoc/2020/projects/jenkins-x-apps-consolidation.adoc
Labels: gsoc

#3662 Update project page to present as a work product
  content/images/post-images/gsoc-git-performance-improvement/git-perf-improv.png
  content/projects/gsoc/2020/projects/git-plugin-performance.adoc
Labels: gsoc

#3672 Add demo to phase-3 blog
  content/blog/2020/08/2020-08-25-external-fingerprint-storage-phase-3.adoc
Labels: blogpost

#3664 [Final Phase Blog] Git Plugin Performance Improvement
  content/blog/2020/08/2020-08-29-git-performance-improvement-phase3.adoc
  content/images/post-images/2020/07-git-plugin-performance-improvement/git-major-perf.png
  content/images/post-images/2020/07-git-plugin-performance-improvement/git-minor-perf.png
  content/images/post-images/2020/07-git-plugin-performance-improvement/git-perf-improv.png
  content/images/post-images/2020/07-git-plugin-performance-improvement/git-repo-diagram.png
Labels: blogpost

#3670 Add logo punkins
  content/_data/logo/punkins.yml
  content/images/logos/punkins/256.png
  content/images/logos/punkins/punkins.png
  content/images/logos/punkins/punkins.svg
Labels: artwork

#3673 [GSoC Project Page] Add phase 3 blog post link to the project page
  content/projects/gsoc/2020/projects/git-plugin-performance.adoc
Labels: gsoc

#3674 WinSW : Update phase 3 blog
  content/blog/2020/08/2020-08-27-winsw-yaml-support.adoc
Labels: blogpost

#3671 Add demo to external fingerprint storage project
  content/projects/gsoc/2020/projects/external-fingerprint-storage.adoc
Labels: gsoc

#3676 Update blog post pull request Link for Custom Distribution Service [GSoC 2020]
  content/projects/gsoc/2020/projects/custom-jenkins-distribution-build-service.adoc
Labels: gsoc

#3666 Add phase-3 blog post for GitHub checks API project
  content/blog/2020/08/2020-08-31-github-checks-api-plugin-coding-phase-3.adoc
  content/images/post-images/2020/08-github-checks-api-plugin-coding-phase-3/failed-checks.png
  content/images/post-images/2020/08-github-checks-api-plugin-coding-phase-3/opengraph.png
  content/images/post-images/2020/08-github-checks-api-plugin-coding-phase-3/pipeline-check.png
Labels: artwork, blogpost, gsoc, squash-merge-me

#3640 GSoC [2020] : Custom Distribution Service Phase Three BlogPost
  content/blog/2020/08/2020-08-31-custom-distribution-service.adoc
Labels: blogpost

#3675 Update WinSW project page
  content/projects/gsoc/2020/projects/winsw-yaml-configs.adoc
Labels: gsoc

#3677 WinSW : Update project page
  content/projects/gsoc/2020/projects/winsw-yaml-configs.adoc
Labels: gsoc
