Repository jenkins-infra/jenkins.io, pull requests merged in 2020-11, with the labels that each got.

#3925 [2020 Elections] - Update jumbotron, add register buttons
  content/blog/2020/09/2020-09-24-board-elections.adoc
  content/blog/2020/10/2020-10-28-election-candidates.adoc
  content/index.html.haml
Labels: blogpost, governance

#3934 Roadmap: Tables to Divs migration is now in preview
  content/_data/roadmap/roadmap.yml
Labels: roadmap

#3898 Blogpost to announce Installing Jenkins on Kubernetes Section/Splitting Intalling Jenkins Sections on Jenkins.io
  content/blog/2020/11/2020-11-05-installing-jenkins-on-kubernetes.adoc
  content/images/post-images/2020/2020-10-30-installing-jenkins-on-kubernetes/installing-jenkins-chapter-after-splitting.png
  content/images/post-images/2020/2020-10-30-installing-jenkins-on-kubernetes/installing-jenkins-chapter-before-splitting.png
  content/images/post-images/2020/2020-10-30-installing-jenkins-on-kubernetes/installing-jenkins-on-kubernetes-section.png
Labels: blogpost, squash-merge-me

#3891 Install Jenkins using Jenkins operator
  content/doc/book/installing/_kubernetes.adoc
  content/doc/book/installing/kubernetes.adoc
Labels: squash-merge-me

#3947 [2020 Elections] - Extend the voting sign-up until Nov 24
  content/blog/2020/09/2020-09-24-board-elections.adoc
  content/blog/2020/10/2020-10-28-election-candidates.adoc
  content/index.html.haml
  content/project/board-election-process.adoc
Labels: blogpost, governance

#3880 Blog post about Spring Security and XStream updates
  content/blog/2020/11/2020-11-10-spring-xstream.adoc
Labels: blogpost

#3890 Amend changelogs based on 2.249.3 backporting review
  content/_data/changelogs/weekly.yml
Labels: changelog

#3863 add warning to string interpolation section
  content/doc/book/pipeline/jenkinsfile.adoc
Labels: documentation

#3951 Add Jenkins events: Elections, Kubecon, Jenkins Day Japan, Dev.Wednesday, and FOSDEM
  content/_data/events/2020-11-17-kubecon.adoc
  content/_data/events/2020-11-24-jenkins-elections.adoc
  content/_data/events/2020-11-25-swiss-devwednesday.adoc
  content/_data/events/2020-12-04-jenkins-day-japan.adoc
  content/_data/events/2021-02-06-fosdem.adoc
  content/events/fosdem/archive/2020.adoc
  content/events/fosdem/archive/2021.adoc
  content/events/fosdem/index.adoc
Labels: events

#3943 Major changes in weekly release line
  content/blog/2020/11/2020-11-10-major-changes-in-weekly-releases.adoc
  content/images/post-images/2020-11-10-major-changes-in-weekly-releases/help-test-jenkins.png
  content/images/post-images/2020-11-10-major-changes-in-weekly-releases/ui-using-divs.png
  content/images/post-images/2020-11-10-major-changes-in-weekly-releases/ui-using-tables.png
Labels: blogpost

#3974 Fix pipeline library blog link
  content/blog/2020/10/2020-10-21-a-sustainable-pattern-with-shared-library.adoc
Labels: blogpost

#3946 Opened dind port 3000 to enable more tutorials
  content/doc/book/installing/_docker-for-tutorials.adoc
Labels: documentation

#3422 wiki-migration, new section to cli page
  content/doc/book/managing/cli.adoc
Labels: documentation

#3984 Fix text for GitHub links, incorrectly labeled as Twitter
  content/blog/2020/10/2020-10-28-election-candidates.adoc
Labels: blogpost

#3986 Note that tables-to-div is live as of 2.264
  content/doc/developer/views/table-to-div-migration.adoc
Labels: documentation

#3989 March 2021 expected to be first LTS with table to div
  content/doc/developer/views/table-to-div-migration.adoc
Labels: documentation

#3990 Add warning about divBasedFormLayout not always being set
  content/doc/developer/views/table-to-div-migration.adoc
Labels: documentation

#3987 Add a troubleshooting section for tables-to-divs
  content/doc/developer/views/table-to-div-migration.adoc
Labels: documentation
