Repository jenkins-infra/jenkins.io, pull requests merged in 2020-09, with the labels that each got.

#3679 Add 2.255 changelog
  content/_data/changelogs/weekly.yml
Labels: changelog

#3655 Recommend specific core versions for the dependency (more aggressive recommendations)
  content/_layouts/corebaseline.html.haml
  content/doc/developer/plugin-development/choosing-jenkins-baseline.adoc
  scripts/fetch-external-resources
Labels: chore, documentation

#3685 Custom distro: fix links to blog posts
  content/projects/gsoc/2020/projects/custom-jenkins-distribution-build-service.adoc
Labels: gsoc

#3687 Jenkins 2.256 changelog
  content/_data/changelogs/weekly.yml
Labels: changelog

#3684 Changelog and upgrade guide for 2.249.1
  content/_data/changelogs/lts.yml
  content/_data/changelogs/weekly.yml
  content/_data/upgrades/2-249-1.adoc
Labels: changelog, squash-merge-me

#3691 Create 2020-09-09-jenkins-continuous-evolution-cdcon.adoc
  content/_data/authors/cdfoundation.adoc
  content/blog/2020/09/2020-09-10-jenkins-continuous-evolution-cdcon.adoc
  content/images/avatars/cdfoundation.jpg
  content/images/post-images/2020/cdcon-register.png
  content/images/post-images/2020/jenkins-cdcon.png
Labels: blogpost

#3688 Adding blogpost for Jenkins 2.249.1 release
  content/blog/2020/09/2020-09-12-new-jenkins-release-observations.adoc
  content/images/post-images/2020/2020-09-09-new-jenkins-release-observations/inbound-agent-configuration.png
  content/images/post-images/2020/2020-09-09-new-jenkins-release-observations/install-agent-as-a-service.png
  content/images/post-images/2020/2020-09-09-new-jenkins-release-observations/install-controller-as-service-from-manage-jenkins.png
  content/images/post-images/2020/2020-09-09-new-jenkins-release-observations/javaws-prompt-for-remoting-agent.png
  content/images/post-images/2020/2020-09-09-new-jenkins-release-observations/launch-inbound-agent-from-jenkins.png
  content/images/post-images/2020/2020-09-09-new-jenkins-release-observations/opengraph.png
  content/images/post-images/2020/2020-09-09-new-jenkins-release-observations/tcp-port-for-inbound-agents.png
  content/images/post-images/2020/2020-09-09-new-jenkins-release-observations/upgrade-jenkins-from-manage-jenkins.png
Labels: blogpost

#3696 Document 'since' information for some more system properties
  content/doc/book/managing/system-properties.adoc
Labels: documentation

#3698 Add Jenkins 2.257 changelog
  content/_data/changelogs/weekly.yml
Labels: changelog

#3700 Update glossary with controller terminology
  content/doc/book/glossary/index.adoc
Labels: documentation

#3699 Update Asciidoctor to 2.0.10
  Gemfile
  Gemfile.lock
  content/doc/book/blueocean/activity.adoc
  content/doc/book/managing/plugins.adoc
  content/doc/book/managing/security.adoc
  content/doc/book/pipeline/getting-started.adoc
  content/doc/book/pipeline/index.adoc
  content/doc/book/pipeline/jenkinsfile.adoc
  content/doc/book/pipeline/shared-libraries.adoc
  content/doc/book/pipeline/syntax.adoc
  content/doc/developer/plugin-development/build-process.adoc
  content/doc/pipeline/tour/hello-world.adoc
  content/projects/evergreen/index.adoc
Labels: chore, documentation

#3703 [GSoC 2020] - Park GSoC pages and update the project statuses
  content/index.html.haml
  content/projects/gsoc/2020/index.adoc
  content/projects/gsoc/2020/projects/custom-jenkins-distribution-build-service.adoc
  content/projects/gsoc/2020/projects/external-fingerprint-storage.adoc
  content/projects/gsoc/2020/projects/git-plugin-performance.adoc
  content/projects/gsoc/2020/projects/github-checks.adoc
  content/projects/gsoc/2020/projects/jenkins-x-apps-consolidation.adoc
  content/projects/gsoc/2020/projects/machine-learning.adoc
  content/projects/gsoc/2020/projects/winsw-yaml-configs.adoc
  content/projects/gsoc/index.adoc
Labels: gsoc

#3706 Create 2020-09-22-virtual.adoc
  content/_data/events/2020-09-22-virtual.adoc
Labels: events

#3697 Add statusFilter and alternate URL to 2.249.1 upgrade guide
  content/_data/upgrades/2-249-1.adoc
Labels: changelog

#3708 Jenkins roadmap: Update statuses of the Roadmap items
  content/_data/roadmap/archive.yml
  content/_data/roadmap/roadmap.yml
Labels: roadmap

#3711 Terminology corrections
  content/blog/2016/2016-05-10-jenkins-20-vjam.adoc
  content/blog/2016/2016-12-20-jenkins-puppet-enterprise-plugin.adoc
  content/blog/2018/07/2018-07-30-introducing-cloud-native-sig.adoc
  content/blog/2020/05/2020-05-11-docker-windows-agents.adoc
Labels: blogpost, documentation

#3710 Create 2020-09-17-jenkins-at-devops-world-2020.adoc
  content/blog/2020/09/2020-09-19-jenkins-at-devops-world-2020.adoc
Labels: blogpost

#3724 Update Hacktoberfest landing page for 2020
  content/_data/events/2020-10-01-hacktoberfest.adoc
  content/events/hacktoberfest.adoc
  content/events/hacktoberfest/event-kit.adoc
  content/events/hacktoberfest/faq.adoc
  content/images/hacktoberfest/2020_badge_small.png
  content/images/hacktoberfest/2020_social.png
  content/index.html.haml
Labels: events, squash-merge-me

#3734 Include statusFilter upgrade content provided with pull request
  content/_data/upgrades/2-249-1.adoc
Labels: changelog

#3738 Roadmap: Update the Jenkins packaging stories
  content/_data/roadmap/roadmap.yml
Labels: roadmap

#3739 Roadmap: Update/Extend the Jenkins roadmap for Cloud Platforms
  content/_data/roadmap/roadmap.yml
Labels: roadmap

#3740 Add changelog for 2.258
  content/_data/changelogs/weekly.yml
Labels: changelog

#3712 Update the Board and Officer election process doc
  content/project/board-election-process.adoc
Labels: governance

#3762 Update the elections process page
  content/project/board-election-process.adoc
Labels: governance, on-hold

#3761 Add a 2020 elections announcement blogpost
  content/blog/2020/09/2020-09-24-board-elections.adoc
  content/images/governance/elections/2020/opengraph.png
  content/project/board-election-process.adoc
Labels: blogpost, governance, on-hold

#3765 Replace many mirrors references with get.jenkins.io
  content/blog/2015/2015-02-25-100k-celebration-podcast.html
  content/blog/2019/11/2019-11-25-macos-native-installer-deprecation.adoc
  content/doc/book/installing/index.adoc
  content/doc/pipeline/tour/getting-started.adoc
  content/download/lts/macos.html.haml
  content/download/mirrors.adoc
  content/podcast.xml
  content/press.adoc
Labels: blogpost, documentation

#3763 Documenting Jenkins on kubernetes Introductory blog post
  content/blog/2020/09/2020-09-25-document-jenkins-on-kubernetes-introduction.adoc
Labels: blogpost

#3770 Replace DevOps World with cdCon on Jumbotron
  content/blog/2020/09/2020-09-19-jenkins-at-devops-world-2020.adoc
  content/images/conferences/DWLogo_globe_warm_p.png
  content/images/conferences/cdCon.png
  content/index.html.haml
Labels: blogpost

#3810 Add Jumbotron for 2020 Elections
  content/index.html.haml
Labels: governance

#3811 Add cdCon to the Jenkins events list
  content/_data/events/2020-10-07-cdcon.adoc
Labels: events

#3813 2020 Elections: Increment the number of elected governance board members
  content/blog/2020/09/2020-09-24-board-elections.adoc
  content/project/board-election-process.adoc
Labels: blogpost, governance

#3815 Add changelog for 2.259
  content/_data/changelogs/weekly.yml
Labels: changelog

#3817 Add Plugin Site, Jenkinsfile Runner and Terminology cleanup as featured projects
  content/events/hacktoberfest.adoc
Labels: hacktoberfest

#3819 Propose jenkinsci/helm-charts for hacktoberfest
  content/events/hacktoberfest.adoc
Labels: hacktoberfest

#3821 Update getting-started.adoc
  content/doc/pipeline/tour/getting-started.adoc
Labels: documentation
