Repository jenkins-infra/jenkins.io, pull requests merged in 2020-07, with the labels that each got.

#3477 Jenkins Code of Conduct update
  content/project/conduct.adoc
Labels: governance, on-hold

#3502 Remove stray bracket in Writing Pipeline-Compatible Plugins
  content/doc/developer/plugin-development/pipeline-integration.adoc
Labels: documentation

#3496 Jenkins Roadmap - Update statuses of the projects which are now in preview
  content/_data/roadmap/roadmap.yml
Labels: roadmap

#3500 Add terminology updates to the roadmap
  content/_data/roadmap/roadmap.yml
Labels: roadmap

#3503 GSoC 2020 - Remove inactive mentors from the GitHub Checks API project
  content/projects/gsoc/2020/projects/github-checks.adoc
Labels: gsoc

#3507 Add 2.244 changelog
  content/_data/changelogs/weekly.yml
Labels: changelog

#3505 Add Mentor
  content/_data/authors/omkar_dsd.adoc
  content/images/avatars/omkar_dsd.jpg
  content/projects/gsoc/2020/projects/git-plugin-performance.adoc
Labels: do not merge, gsoc

#3509 New Jenkins Adopters page
  content/_data/adopters/Anchore.adoc
  content/_data/adopters/Avoris-Travel.adoc
  content/_data/adopters/CERN.adoc
  content/_data/adopters/CloudBees.adoc
  content/_data/adopters/D4Science.adoc
  content/_data/adopters/JDcom.adoc
  content/_data/adopters/KP-Labs.adoc
  content/_data/adopters/Preply.adoc
  content/_data/adopters/TMobile.adoc
  content/_data/adopters/Tymit.adoc
  content/_data/adopters/Wright.adoc
  content/_partials/company-card.html.haml
  content/images/adopters/Anchore.jpg
  content/images/adopters/Avoris-Travel.jpg
  content/images/adopters/CERN.jpg
  content/images/adopters/CloudBees.jpg
  content/images/adopters/D4Science.jpeg
  content/images/adopters/JDcom.jpg
  content/images/adopters/KP-Labs.png
  content/images/adopters/Preply.png
  content/images/adopters/TMobile.png
  content/images/adopters/Tymit.png
  content/images/adopters/Wright.png
  content/images/adopters/stackshare.png
  content/project/adopters.html.haml
Labels: governance

#3510 Updated node docker image version
  content/doc/book/pipeline/docker.adoc
  content/doc/pipeline/tour/agents.adoc
Labels: documentation

#3408 Parameterized build fixups
  content/doc/book/using/remote-access-api.adoc
  content/images/using/remote-access-api/file-parameter.png
Labels: documentation

#3384 Convert 'Executor Starvation' wiki page to jenkins.io
  content/doc/book/using/_chapter.yml
  content/doc/book/using/executor-starvation.adoc
  content/images/using/starvation.png
Labels: documentation

#3487 GSoC-2020 WinSW YAML Support : Phase - 01 Blog Post
  content/blog/2020/07/2020-07-08-winsw-yaml-support.adoc
  content/images/post-images/2020-07-08-winsw-yaml-support/opengraph.png
Labels: blogpost, gsoc, squash-merge-me

#3513 Add JSON metadata for shields.io badges
  content/changelog-stable/badge.json.haml
  content/changelog/badge.json.haml
Labels: changelog

#3515 Update GSoC 2020 - WinSW : YAML Support Project Page
  content/projects/gsoc/2020/projects/winsw-yaml-configs.adoc
Labels: gsoc

#3498 Jenkins Roadmap: Update the project governance roadmap
  content/_data/roadmap/roadmap.yml
Labels: roadmap

#3499 Phase-1 blog post for GitHub Checks API Plugin
  content/_data/authors/XiongKezhi.adoc
  content/blog/2020/07/2020-07-09-github-checks-api-plugin-coding-phase-1.adoc
  content/images/avatars/XiongKezhi.jpeg
  content/images/post-images/2020/07-github-checks-api-plugin-coding-phase-1/created-check-run.png
  content/images/post-images/2020/07-github-checks-api-plugin-coding-phase-1/github-check-annotations.png
  content/images/post-images/2020/07-github-checks-api-plugin-coding-phase-1/github-check-run.png
  content/images/post-images/2020/07-github-checks-api-plugin-coding-phase-1/source-view.png
Labels: blogpost, gsoc, squash-merge-me

#3501 Add a blogpost for GSoC-2020 Phase-1: Git Plugin Performance Improvement
  content/_data/authors/rishabhbudhouliya.adoc
  content/blog/2020/07/2020-07-09-git-performance-improvement-phase1.adoc
  content/images/avatars/rishabhbudhouliya.jpg
  content/images/post-images/2020/07-git-plugin-performance-improvement/git-fetch-results.png
  content/images/post-images/2020/07-git-plugin-performance-improvement/git-intro.png
  content/images/post-images/2020/07-git-plugin-performance-improvement/gsoc-git-opengraph.png
Labels: blogpost, gsoc, squash-merge-me

#3520 Add Jenkins 2.235.2 changelog and upgrade guide
  content/_data/changelogs/lts.yml
  content/_data/upgrades/2-235-2.adoc
Labels: changelog

#3433 item note added
  content/doc/book/installing/_setup-wizard.adoc
Labels: documentation

#3525 Infrastucture services list: link ci.jenkins.io user documentation
  content/projects/infrastructure/index.adoc
Labels: documentation

#3529 Add 2020-07-15 blog post on XSS severity
  content/blog/2020/07/2020-07-15-xss-severity.adoc
Labels: blogpost

#3517 Restructure the Downloads page
  .github/workflows/compress-images-in-PRs.yml
  content/download/index.html.haml
Labels: chore, documentation

#3526 Pipeline Authoring Roadmap - Use links from initiative metadata, extend descriptions
  content/_data/roadmap/roadmap.yml
  content/project/roadmap/index.html.haml
Labels: governance, roadmap

#3523 JEP-14 - Add support for archiving roadmap items, expand status descriptions
  content/_data/roadmap/archive.yml
  content/_data/roadmap/roadmap.yml
  content/project/roadmap/index.html.haml
Labels: governance, roadmap

#3530 Add the announcement tag to the Jul 15 security blogpost
  content/blog/2020/07/2020-07-15-xss-severity.adoc
Labels: blogpost

#3524 UX Roadmap - Add the Plugin management UI improvements initiative details
  content/_data/roadmap/roadmap.yml
  content/sigs/ux/index.adoc
Labels: roadmap

#3527 JEP-14 - Add Roadmap reference to the Governance doc, remove work-in-progress disclaimer
  content/project/governance.adoc
  content/project/roadmap/index.html.haml
Labels: governance, roadmap

#3533 Add checksum for war download
  content/download/index.html.haml
Labels: documentation

#3535 Discourage use of @Grab in trusted Pipeline libraries
  content/doc/book/pipeline/pipeline-best-practices.adoc
  content/doc/book/pipeline/shared-libraries.adoc
Labels: documentation

#3539 Fix some broken links in 2020 blog posts
  content/blog/2020/05/2020-05-11-docker-windows-agents.adoc
  content/blog/2020/06/2020-06-03-machine-learning-plugin-community-bonding.adoc
Labels: blogpost, bug

#3542 Improve the Adopters page: Better layout and contributing guidelines
  content/_data/adopters/Anchore.adoc
  content/_data/adopters/Avoris-Travel.adoc
  content/_data/adopters/CERN.adoc
  content/_data/adopters/CloudBees.adoc
  content/_data/adopters/D4Science.adoc
  content/_data/adopters/JDcom.adoc
  content/_data/adopters/KP-Labs.adoc
  content/_data/adopters/Preply.adoc
  content/_data/adopters/TMobile.adoc
  content/_data/adopters/Tymit.adoc
  content/_data/adopters/Wright.adoc
  content/_data/adopters/ZZZ_add_your_company.adoc
  content/_partials/company-card.html.haml
  content/images/adopters/ZZZ_add_your_company.png
  content/project/adopters/contributing.adoc
  content/project/adopters/index.html.haml
Labels: governance

#3546 Adopters: Ensure that Adopters are always sorted
  content/project/adopters/index.html.haml
Labels: bug, governance

#3551 Fix typo in github app blog
  content/blog/2020/04/2020-04-16-github-app-authentication.adoc
Labels: blogpost

#3550 Changelog badges: Ensure the shields.io schema is followed
  content/changelog-stable/badge.json.haml
  content/changelog/badge.json.haml
Labels: changelog

#3543 Updating "Installing Docker" section
  content/doc/book/installing/index.adoc
Labels: documentation

#3545 Add changelog for 2.246, 2.247, 2.248
  content/_data/changelogs/weekly.yml
Labels: changelog

#3554 [JENKINS-42816] replace "slave" with "agent" in governance doc
  content/project/governance.adoc
Labels: governance

#3386 Create 'Reverse proxy configuration' page(s) on jenkins.io #3204
  content/doc/book/system-administration/_chapter.yml
  content/doc/book/system-administration/reverse-proxy-configuration-with-jenkins.adoc
Labels: documentation

#3556 Fix 2.237 changelog entries
  content/_data/changelogs/weekly.yml
Labels: changelog

#3549 Update the Governance document
  content/participate/code.adoc
  content/project/governance.adoc
Labels: governance

#3555 Blog post for Windows Support Policy updates and .NET 2.0 support removal
  content/blog/2020/07/2020-07-23-windows-support-updates.adoc
  content/images/post-images/2020/07-windows-support-updates/header_image.png
  content/images/post-images/2020/07-windows-support-updates/opengraph.png
  content/images/post-images/2020/07-windows-support-updates/winsw-logo.png
Labels: blogpost, work-in-progress

#3553 Replace the whitelist/blacklist terminology in the changelogs
  content/_data/changelogs/lts.yml
  content/_data/changelogs/weekly.yml
Labels: changelog

#3559 Add changelog for Jenkins 2.249
  content/_data/changelogs/weekly.yml
Labels: changelog

#3541 External Fingerprint Storage phase 2 blog post
  content/blog/2020/07/2020-07-24-external-fingerprint-storage-phase-2.adoc
  content/images/post-images/2020/07-external-fingerprint-storage-phase-2/cleanup_disable.png
  content/images/post-images/2020/07-external-fingerprint-storage-phase-2/fingerprint_storage_engine_dropdown.png
Labels: blogpost, gsoc

#3560 Suggested fix for grammatical typo
  content/doc/book/pipeline/docker.adoc
Labels: documentation

#3558 Reference the Windows Support Policy updates blogpost in the 2.248 changelog
  content/_data/changelogs/weekly.yml
Labels: changelog

#3561 Windows Support Policy blog: Fix typo and wording
  content/blog/2020/07/2020-07-23-windows-support-updates.adoc
Labels: blogpost, bug

#3563 Blog, changelog, and upgrade guide for Jenkins 2.235.3
  content/_data/changelogs/lts.yml
  content/_data/upgrades/2-235-3.adoc
  content/blog/2020/07/2020-07-27-repository-signing-keys-changing.adoc
  content/images/post-images/2020/07-repository-signing-keys-change/opengraph.png
Labels: blogpost, changelog, squash-merge-me

#3565 Add new opengraph image for External Fingerprint Storage phase-2
  content/blog/2020/07/2020-07-24-external-fingerprint-storage-phase-2.adoc
  content/images/post-images/2020/07-external-fingerprint-storage-phase-2/opengraph.png
Labels: blogpost

#3566 Use correct blog post location
  content/_data/upgrades/2-235-3.adoc
Labels: changelog

#3508 Custom Distribution Service (Phase 1 Summary)
  content/blog/2020/06/2020-07-27-custom-distribution-service.adoc
  content/images/gsoc/2020/custom_distribution_service/cds_gsoc.png
Labels: blogpost, gsoc

#3567 Add link to rc release in External Fingerprint Storage phase-2 blogpost
  content/blog/2020/07/2020-07-24-external-fingerprint-storage-phase-2.adoc
Labels: blogpost

#3562 Phase 2 blog post
  content/blog/2020/07/2020-07-27-machine-learning-plugin-coding-phase2.adoc
  content/projects/gsoc/2020/projects/machine-learning.adoc
Labels: blogpost, gsoc

#3568 Small doc change
  content/doc/book/pipeline/getting-started.adoc
Labels: documentation

#3569 Add 2.250 changelog
  content/_data/changelogs/weekly.yml
Labels: changelog

#3574 Fix broke link to plugin label allowlist
  content/doc/developer/publishing/documentation.adoc
  content/doc/developer/publishing/plugin-site.adoc
Labels: documentation

#3571 Windows installer now available for 2.250
  content/_data/changelogs/lts.yml
  content/_data/changelogs/weekly.yml
Labels: changelog

#3570 Updated open-graph for machine learning plugin
  content/blog/2020/07/2020-07-27-machine-learning-plugin-coding-phase2.adoc
  content/images/gsoc/2020/machine_learning_plugin/jenkins-gsoc-machine-learning-opengraph.png
Labels: blogpost

#3572 Replacing outdated JNLP terminology for docker based installations
  content/doc/book/installing/_docker.adoc
Labels: documentation

#3575 Fix code reference to match description
  content/doc/developer/security/secrets.adoc
Labels: documentation

#3576 Phase 2 Blog for the Git Plugin Performance Improvement Project
  content/blog/2020/07/2020-07-29-git-performance-improvement-phase2.adoc
  content/images/post-images/2020/07-git-plugin-performance-improvement/git-multiple-platforms.png
Labels: blogpost, gsoc

#3581 Fix issue #3580 - broken links in Git plugin blog post
  content/blog/2020/07/2020-07-29-git-performance-improvement-phase2.adoc
Labels: blogpost
