Repository jenkins-infra/jenkins.io, pull requests merged in 2021-09, with the labels that each got.

#4535 Update 2.308 changelog for consistency
  content/_data/changelogs/weekly.yml
Labels: changelog

#4536 Update Hacktoberfest pages towards the 2021 edition
  content/events/hacktoberfest.adoc
  content/events/hacktoberfest/event-kit.adoc
  content/events/hacktoberfest/faq.adoc
Labels: hacktoberfest

#4537 Initialize landing for the Oct 02 contributor summit
  content/events/contributor-summit/archive/2021-06.adoc
  content/events/contributor-summit/index.adoc
Labels: events

#4538 Add bullseye to 2.303.1 upgrade guide
  content/_data/upgrades/2-303-1.adoc
Labels: changelog

#4518 Add links to built-in node migration docs
  content/_data/changelogs/weekly.yml
Labels: changelog, squash-merge-me

#4541 Update _docker.adoc
  content/doc/book/installing/_docker.adoc
Labels: documentation

#4539 Update gsoc 21 git credentials binding work report
  content/blog/2021/08/2021-08-19-git-credentials-binding-work-report.adoc
Labels: blogpost

#4542 Replace obsolete docker tags with current tags
  content/doc/book/installing/_docker-for-tutorials.adoc
  content/doc/book/installing/_docker.adoc
Labels: documentation

#4543 Sort plugins and don't return the list of plugins
  content/doc/book/system-administration/diagnosing-errors.adoc
  content/participate/report-issue.adoc
Labels: documentation

#4544 Add blog describing response to wiki attack
  content/blog/2021/09/2021-09-04-wiki-attacked.adoc
Labels: blogpost

#4545 Add simple discourse support
  content/_partials/discuss.html.haml
  content/blog/2021/09/2021-09-04-wiki-attacked.adoc
Labels: blogpost

#4553 Add a note about minikube permissions for persistent data.
  content/doc/book/installing/_kubernetes.adoc
Labels: documentation

#4552 Add notes about the behavior of Pipeline: Nodes and Processes
  content/doc/book/managing/built-in-node-migration.adoc
Labels: documentation

#4554 Pass values to ListBoxModel#add in correct order
  content/doc/developer/forms/jelly-form-controls.adoc
Labels: documentation

#4555 Note that 2.310 release was not delivered
  content/_data/changelogs/weekly.yml
Labels: changelog

#4562 Adapt Java upgrade instructions to recent changes
  content/doc/administration/requirements/upgrade-java-guidelines.adoc
Labels: documentation

#4558 Use blue ocean 1.25.0 instead of 1.24.7
  content/doc/book/installing/_docker-for-tutorials.adoc
  content/doc/book/installing/_docker.adoc
Labels: documentation

#4563 Undo failed cleanups
  content/doc/developer/handling-requests/actions.adoc
  content/doc/developer/handling-requests/stapler-accessible-type.adoc
Labels: documentation

#4559 [2021-09-20] Announce beginning of Jenkins Election 2021
  content/blog/2021/09/2021-09-20-election-period-opened.adoc
  content/images/governance/elections/2021/opengraph.png
Labels: blogpost

#4569 Announce DevOps World 2021
  content/blog/2021/09/2021-09-21-jenkins-at-devops-world.adoc
Labels: blogpost

#4573 Add Jenkins Contributor Summit to events
  content/_data/events/2021-10-02-contributor-summit-part-1.adoc
Labels: events

#4575 New blog post: Jenkins Health Advisor by CloudBees
  content/blog/2021/09/2021-09-23-jenkins-health-advisor-by-cloudbees.adoc
Labels: blogpost

#4577 [fix] Use the project logo instead of the angry jenkins
  content/blog/2021/09/2021-09-23-jenkins-health-advisor-by-cloudbees.adoc
Labels: blogpost

#4576 GSoC 2021 recap and congratulations post
  content/blog/2021/09/2021-09-24-gsoc-report.adoc
  content/images/gsoc/2021/gsoc-harshit-chopra.jpg
  content/images/gsoc/2021/gsoc-shruti-chaturvedi.jpg
Labels: blogpost

#4578 fix typo
  content/blog/2021/09/2021-09-24-gsoc-report.adoc
Labels: blogpost

#4579 Update for Pipeline: Nodes and Processes 2.40
  content/doc/book/managing/built-in-node-migration.adoc
Labels: documentation

#4582 Hudson was renamed Jenkins in 1.396
  content/_data/changelogs/lts.yml
  content/_data/changelogs/weekly.yml
  content/_data/upgrades/2-289-1.adoc
Labels: changelog

#4585 Update link to the correct location on jenkins.io
  content/doc/book/using/remote-access-api.adoc
Labels: documentation

#4586 Changelog and upgrade guide for 2.303.2
  content/_data/changelogs/lts.yml
  content/_data/changelogs/weekly.yml
  content/_data/upgrades/2-303-2.adoc
Labels: changelog
