Repository jenkins-infra/jenkins.io, pull requests merged in 2021-04, with the labels that each got.

#4218 add --storage-driver option for linux build
  content/doc/book/installing/_docker-for-tutorials.adoc
  content/doc/book/installing/_docker.adoc
Labels: documentation

#4220 Fix typo
  content/doc/book/using/using-agents.adoc
Labels: documentation

#4228 Tidy up instance info reporting
  content/doc/book/system-administration/diagnosing-errors.adoc
Labels: documentation

#4226 Reference channels for newcomer contributors, #jenkins-release and Slack in the /chat page
  content/chat.adoc
Labels: documentation

#4225 June 2021 contributor summit - prepare landing
  content/events/contributor-summit/index.adoc
  content/images/conferences/contributor_summit.png
Labels: events

#4224 Add SheCodeAfrica Contributhon participants blog
  content/blog/2021/04/2021-04-07-contributhon-participants.adoc
  content/images/post-images/2020-04-contributhon-participants/cynthia-iradukunda.png
  content/images/post-images/2020-04-contributhon-participants/esther-ejidike.jpg
  content/images/post-images/2020-04-contributhon-participants/onyinye-ezike.jpg
  content/images/post-images/2020-04-contributhon-participants/sharon-jebitok.jpg
Labels: blogpost, squash-merge-me

#4230 GSoC 2021 - Fix chat and mailing list links in the Jenkins Operator project idea
  content/projects/gsoc/2021/project-ideas/jenkins-operator-security.adoc
Labels: bug, gsoc

#4229 Fix the SIG reference in the Tekton Pipelines project idea
  content/projects/gsoc/2021/project-ideas/tekton-client-plugin.adoc
Labels: bug, gsoc

#4232 Change the Governance meeting time to 7PM UTC
  content/project/governance-meeting/index.adoc
Labels: governance

#4233 Build jenkinsciinfra/jenkinsio Docker image
  Dockerfile
  Gemfile
  Gemfile.lock
  Jenkinsfile_k8s
  Makefile
  docker/default.conf
  scripts/groovy
  scripts/release.rss.groovy
  scripts/release.rss.rb
  updateCli/updateCli.d/charts.yaml
  updateCli/values.yaml
Labels: chore

#4236 Adding Angelique Jard as blog author.
  content/_data/authors/ajard.adoc
  content/blog/2021/04/2021-04-07-contributhon-participants.adoc
  content/images/avatars/ajard.jpg
Labels: blogpost

#4239 Add image resources used in Jenkins deployment for ci.networkupstools.org
  content/_data/logo/nut.yml
  content/images/logos/nut/jenkins-nut-large-squared.png
  content/images/logos/nut/jenkins-nut-small-256px.png
  content/images/logos/nut/jenkins-nut-small.png
  content/images/logos/nut/jenkins-nut-transparent-bg-40px.png
  content/images/logos/nut/jenkins-nut.txt
Labels: artwork

#4243 Use archiveArtifacts instead of deprecated archive
  content/doc/book/blueocean/pipeline-run-details.adoc
Labels: documentation

#4242 [JENKINS-65107] old password encoding support removed
  content/_data/upgrades/2-277-1.adoc
Labels: changelog

#4245 Avoid space in item name
  content/doc/pipeline/tour/hello-world.adoc
Labels: documentation

#4248 2.288 changelog
  content/_data/changelogs/weekly.yml
Labels: changelog

#4240 Make links relative
  Dockerfile
  Makefile
  content/_config/site.yml
  content/_ext/activenav.rb
  content/_ext/atom.xml.haml
  content/_layouts/frame.html.haml
  content/_layouts/post.html.haml
  content/_partials/toptoolbar.html.haml
  content/changelog-stable/rss.xml.haml
  content/changelog/rss.xml.haml
Labels: changelog, chore

#4251 Add changelog and upgrade guide for 2.277.3
  content/_data/changelogs/lts.yml
  content/_data/upgrades/2-277-3.adoc
Labels: changelog

#4252 Document security considerations for environment variables
  content/doc/book/system-administration/security.adoc
  content/doc/book/system-administration/security/environment-variables.adoc
  content/redirect/environment-variables-security.adoc
Labels: documentation

#4253 Several minor fixes
  content/doc/book/blueocean/getting-started.adoc
  content/doc/book/blueocean/pipeline-editor.adoc
Labels: documentation

#4249 Chore: Enable updatecli pipeline on Jenkins Infra
  Jenkinsfile_k8s
  updatecli/updatecli.d/charts.yaml
  updatecli/values.yaml
Labels: on-hold

#4254 Add upcoming webinars to the Jenkins calendar
  content/_data/events/2021-04-29-redhat-webinar.adoc
  content/_data/events/2021-05-12-cdf-jte.adoc
Labels: events

#4244 Jenkins Kubernetes Operator sub-project annoucement blog post
  content/blog/2021/04/2021-04-15-jenkins-operator-sub-project.adoc
  content/images/logos/kubernetes-operator/kubernetes-operator-header.jpeg
  content/images/logos/kubernetes-operator/kubernetes-operator-wide.png
  content/images/post-images/2021-04-jenkins-operator/tshirt-logo.jpg
Labels: blogpost

#4257 Fix blog post spelling error
  content/blog/2021/02/2021-02-16-contributor-summit-online.adoc
Labels: blogpost

#4255 docs(index.adoc): fix "contact us" link
  content/projects/gsoc/index.adoc
Labels: gsoc

#4261 Use blue ocean 1.24.6 in Docker install
  content/doc/book/installing/_docker-for-tutorials.adoc
  content/doc/book/installing/_docker.adoc
  content/doc/book/pipeline/docker.adoc
  content/doc/book/pipeline/syntax.adoc
  content/doc/tutorials/build-a-java-app-with-maven.adoc
Labels: documentation

#4262 Fix maven and nodeJS tutorials
  content/doc/book/pipeline/docker.adoc
  content/doc/book/pipeline/syntax.adoc
  content/doc/tutorials/build-a-java-app-with-maven.adoc
  content/doc/tutorials/build-a-node-js-and-react-app-with-npm.adoc
Labels: documentation

#4271 +justinharringa 2021 git credential binding mentor
  content/projects/gsoc/2020/project-ideas/git-plugin-performance.adoc
  content/projects/gsoc/2021/project-ideas/git-credentials-binding-for-pipeline.adoc
Labels: gsoc

#4273 Correct Esther Ejidike GitHub ID
  content/blog/2021/04/2021-04-07-contributhon-participants.adoc
Labels: blogpost

#4274 Update pipeline-run-details.adoc
  content/doc/book/blueocean/pipeline-run-details.adoc
Labels: documentation

#4272 2.289 changelog
  content/_data/changelogs/weekly.yml
Labels: changelog

#4275 Add DAGsHub branch source plugin to the multibranch doc
  content/doc/book/pipeline/multibranch.adoc
Labels: documentation

#4265 Using consistent number of the plugin count
  content/doc/developer/index.html.haml
Labels: documentation

#4277 Add the Release team to the list of teams in /project
  content/project/index.adoc
Labels: governance

#4278 GSoC 2021: Update the main page to reflect the current status, add org admin links, remove jumbotron
  content/index.html.haml
  content/projects/gsoc/index.adoc
Labels: gsoc

#4269 fix: add a blog on using the tekton plugin
  content/blog/2021/04/2021-04-21-tekton-plugin.adoc
  content/images/jenkins-x/logo-with-text.svg
  content/images/projects/tekton-client-plugin/example.png
  content/images/projects/tekton-client-plugin/logo.png
  content/images/projects/tekton-client-plugin/opengraph_jx.png
Labels: blogpost

#4279 Fix the Tekton Client plugin links
  content/blog/2021/04/2021-04-21-tekton-plugin.adoc
Labels: blogpost, bug

#4281 Fix the incorrect command-line instruction
  content/doc/book/using/using-agents.adoc
Labels: documentation

#4276 Propose Jenkins Awards Blog post
  content/blog/2021/04/2021-04-23-jenkins-contributor-awards.adoc
  content/images/post-images/2021/jenkins-awards-2021.png
Labels: blogpost

#4283 Migrate security documentation to its own chapter
  .github/CODEOWNERS
  content/_partials/toptoolbar.html.haml
  content/doc/book/_book.yml
  content/doc/book/managing/_chapter.yml
  content/doc/book/managing/security.adoc
  content/doc/book/security/_chapter.yml
  content/doc/book/security/build-authorization.adoc
  content/doc/book/security/configuring-content-security-policy.adoc
  content/doc/book/security/environment-variables.adoc
  content/doc/book/security/index.adoc
  content/doc/book/security/managing-security.adoc
  content/doc/book/security/securing-jenkins.adoc
  content/doc/book/system-administration/_chapter.yml
  content/doc/book/system-administration/security.adoc
  content/doc/book/system-administration/security/build-authorization.adoc
  content/doc/book/system-administration/security/configuring-content-security-policy.adoc
  content/doc/book/system-administration/security/environment-variables.adoc
Labels: chore, documentation

#4284 Add help explaining how to use bundled resource files on the UI
  content/doc/developer/views/_chapter.yml
  content/doc/developer/views/exposing-bundled-resources.adoc
Labels: documentation

#4288 Make these documentation pages proper 'sections' of the doc
  content/doc/book/security/build-authorization.adoc
  content/doc/book/security/configuring-content-security-policy.adoc
Labels: documentation

#4289 Document AssetManager
  content/doc/developer/views/exposing-bundled-resources.adoc
Labels: documentation

#4282 Archive GSoD 2021 info, fix #4266
  content/_data/roadmap/roadmap.yml
  content/sigs/docs/gsod/2020/index.adoc
  content/sigs/docs/gsod/2021/application.md
  content/sigs/docs/gsod/index.adoc
  content/sigs/docs/index.adoc
Labels: roadmap

#4296 Create a separate page for CSRF protection
  content/doc/book/resources/managing/configure-global-security-prevent-csrf-after-2.1.76.2.png
  content/doc/book/resources/managing/configure-global-security-prevent-csrf.png
  content/doc/book/security/_chapter.yml
  content/doc/book/security/csrf-protection.adoc
  content/doc/book/security/managing-security.adoc
  content/doc/book/security/securing-jenkins.adoc
Labels: documentation

#4298 Migrate Markup Formatter documentation to its own page
  content/doc/book/security/_chapter.yml
  content/doc/book/security/managing-security.adoc
  content/doc/book/security/markup-formatter.adoc
  content/doc/book/security/securing-jenkins.adoc
Labels: documentation

#4300 Add IRC Chat and references to the Hosting Team page
  content/project/teams/hosting.adoc
Labels: governance

#4301 Fix typo in the IRC Bot documentation
  content/projects/infrastructure/ircbot.adoc
Labels: bug

#4295 Add /doc/developer/security/ to the security team
  .github/CODEOWNERS
Labels: chore

#4302 Replace obsolete terminology in changelog
  content/_data/changelogs/lts.yml
  content/_data/changelogs/weekly.yml
  content/_partials/changelog-old.html
Labels: changelog

#4304 Update namespace to jenkins
  content/doc/tutorials/kubernetes/installing-jenkins-on-kubernetes/jenkins-volume.yaml
Labels: documentation

#4305 Add namespace for ServiceAccount
  content/doc/tutorials/kubernetes/installing-jenkins-on-kubernetes/jenkins-sa.yaml
Labels: documentation

#4307 Add 2.290 changelog
  content/_data/changelogs/weekly.yml
Labels: changelog

#4294 Add Access Control chapter
  content/doc/book/security/_chapter.yml
  content/doc/book/security/access-control.adoc
Labels: documentation

#4306 Add Controller Isolation section (distributed builds, A2C security)
  content/doc/book/resources/managing/configure-global-security-access-control-rules.png
  content/doc/book/resources/managing/configure-global-security-enable-agent-master.png
  content/doc/book/resources/managing/configure-global-security-prevent-csrf.png
  content/doc/book/resources/managing/configure-global-security.png
  content/doc/book/resources/security/configure-global-security-agent-controller-rules.png
  content/doc/book/resources/security/configure-global-security-agent-controller-toggle.png
  content/doc/book/resources/security/configure-global-security-agent-controller.png
  content/doc/book/resources/security/configure-global-security-matrix-authorization.png
  content/doc/book/resources/security/configure-global-security-prevent-csrf.png
  content/doc/book/resources/security/configure-global-security-whitelist-commands.png
  content/doc/book/resources/security/configure-global-security.png
  content/doc/book/security/_chapter.yml
  content/doc/book/security/agent-to-controller.adoc
  content/doc/book/security/controller-isolation.adoc
  content/doc/book/security/csrf-protection.adoc
  content/doc/book/security/managing-security.adoc
Labels: documentation

#4291 Documentation: Handbook: Using Docker with Pipeline: Keep workspace synchronized (reuseNode)
  content/doc/book/pipeline/docker.adoc
Labels: documentation

#4308 Add chkconfig package to Fedora install
  content/doc/book/installing/linux.adoc
Labels: documentation

#4309 Make security team the codeowners of security handbook resources
  .github/CODEOWNERS
Labels: chore

#4317 cdCon Jenkins Contributor Awards - update the nominations deadline
  content/blog/2021/04/2021-04-23-jenkins-contributor-awards.adoc
  content/index.html.haml
Labels: blogpost

#4316 Fix Fedora install guide
  content/doc/book/installing/linux.adoc
Labels: documentation

#4314 Update links to their modern canonical URLs in the /security/ URLs
  content/doc/book/installing/_docker-for-tutorials.adoc
  content/doc/book/installing/_docker.adoc
  content/projects/gsoc/2020/project-ideas/pipeline-step-documentation-generator.adoc
  content/security/advisory/2010-07-05.adoc
  content/security/advisory/2013-02-16.adoc
  content/security/advisory/2015-10-01.adoc
  content/security/advisory/2015-11-11.adoc
  content/security/advisory/2015-12-09.adoc
  content/security/advisory/2016-07-27.adoc
  content/security/advisory/2017-02-01.adoc
  content/security/advisory/2017-04-10.adoc
  content/security/advisory/2018-03-26.adoc
  content/security/advisory/2018-05-09.adoc
  content/security/advisory/2019-04-10.adoc
  content/security/advisory/2019-07-31.adoc
  content/security/advisory/2019-08-07.adoc
  content/security/advisory/2020-01-29.adoc
  content/security/advisory/2020-02-12.adoc
  content/security/advisory/2020-03-09.adoc
  content/security/advisory/2020-03-25.adoc
  content/security/advisory/2020-05-06.adoc
  content/security/advisory/2020-09-23.adoc
  content/security/advisory/2020-10-08.adoc
  content/security/advisory/2021-01-26.adoc
  content/security/for-administrators.adoc
  content/security/index.adoc
  content/security/reporting.adoc
  content/security/team.adoc
Labels: documentation, gsoc

#4310 Add an overview of the sections of the security chapter to the index
  content/doc/book/security/index.adoc
Labels: documentation

#4318 Use correct method in example @DataBoundSetter
  content/doc/developer/plugin-development/pipeline-integration.adoc
Labels: documentation
