Repository jenkins-infra/jenkins.io, pull requests merged in 2021-12, with the labels that each got.

#4740 Additional Jenkins API usage recommendations
  content/doc/developer/security/misc.adoc
Labels: documentation

#4742 2021 Election Results
  content/blog/2021/12/2021-12-03-election-results.adoc
  content/project/board.html.haml
Labels: blogpost, governance

#4744 enable comments on election results post
  content/blog/2021/12/2021-12-03-election-results.adoc
Labels: blogpost

#4745 Term ends Dec 2023 for new board members
  content/blog/2021/12/2021-12-03-election-results.adoc
Labels: blogpost

#4749 Move developer items to end of 2.324 changelog
  content/_data/changelogs/weekly.yml
Labels: changelog

#4751 Embed install tutorial videos
  content/doc/book/installing/linux.adoc
  content/doc/book/installing/windows.adoc
Labels: documentation

#4753 chore: explicite which download file to use
  content/doc/pipeline/tour/getting-started.adoc
Labels: documentation

#4754 fix: remove ending dots to facilitate code copy
  content/doc/pipeline/tour/getting-started.adoc
Labels: documentation

#4750 Use containers as Jenkins build agents
  content/blog/2021/12/2021-12-08-containers-as-build-agents.adoc
  content/images/post-images/2021-12-docker-containers/docker-containers-as-build-agents.png
Labels: blogpost

#4757 Use correct opengraph image
  content/blog/2021/12/2021-12-08-containers-as-build-agents.adoc
Labels: blogpost

#4623 Creating your Docker agent on Windows added
  content/doc/book/using/using-agents.adoc
Labels: documentation

#4760 CVE-2021-44228 blog post
  content/blog/2021/12/2021-12-10-log4j2-rce-CVE-2021-44228.adoc
Labels: blogpost

#4763 Add bio for Hervé Le Meur
  content/_data/authors/hlemeur.adoc
  content/blog/2021/12/2021-12-10-log4j2-rce-CVE-2021-44228.adoc
  content/images/avatars/hlemeur.jpg
Labels: blogpost

#4752 JCasC page in "Managing Jenkins"
  content/doc/book/managing/_chapter.yml
  content/doc/book/managing/casc.adoc
Labels: documentation, squash-merge-me

#4764 Update tool versions
  STYLEGUIDE.adoc
  content/doc/book/installing/_docker-for-tutorials.adoc
  content/doc/book/installing/_docker.adoc
  content/doc/book/pipeline/docker.adoc
  content/doc/pipeline/tour/agents.adoc
  content/doc/pipeline/tour/hello-world.adoc
Labels: documentation

#4766 Documentation on installing Jenkins with Jenkins Operator
  content/doc/book/installing/_kubernetes.adoc
  content/doc/book/installing/_setup-wizard.adoc
Labels: documentation

#4767 Make single discourse link
  content/_layouts/frame.html.haml
  content/_partials/discuss.html.haml
Labels: bug

#4768 Update Log4j blog post to also cover the GH issues
  content/blog/2021/12/2021-12-10-log4j2-rce-CVE-2021-44228.adoc
Labels: blogpost

#4770 Reorder 2.325 changelog entries
  content/_data/changelogs/weekly.yml
Labels: changelog

#4771 Update java.adoc
  content/doc/administration/requirements/java.adoc
Labels: documentation

#4774 Note safe-batch-environment-filter plugin
  content/doc/book/security/environment-variables.adoc
Labels: documentation

#4780 Reorder 2.326 changelog entries
  content/_data/changelogs/weekly.yml
Labels: changelog

#4256 Announce deprecation of non-Java plugins and runtimes
  content/blog/2021/12/2021-12-22-deprecated-ruby-runtime.adoc
  content/images/post-images/2021-12-deprecating-non-java-runtimes.png
Labels: blogpost, documentation, squash-merge-me

#4781 Prep for supporting netlify pr sites
  .node-version
  .ruby-version
  scripts/node
  scripts/ruby
Labels: chore

#4785 Add reference to nvim-jenkinsfile-linter plugin
  content/doc/book/pipeline/development.adoc
Labels: documentation

#4787 Add developer documentation for JEP-214
  content/doc/developer/_book.yml
  content/doc/developer/telemetry/_chapter.yml
  content/doc/developer/telemetry/index.adoc
Labels: documentation

#4790 Document agent-to-controller security bypass
  content/doc/book/managing/system-properties.adoc
Labels: documentation
