Repository jenkins-infra/jenkins.io, pull requests merged in 2021-08, with the labels that each got.

#4487 Changelog 2.305
  content/_data/changelogs/weekly.yml
Labels: changelog

#4491 Fix typo
  content/doc/book/system-administration/reverse-proxy-configuration-iptables.adoc
Labels: documentation

#4469 [JENKINS-66177] JavaVersionRecommendationAdminMonitor.disable
  content/doc/book/managing/system-properties.adoc
Labels: documentation

#4492 grammar and punctuation fixes
  content/doc/book/blueocean/dashboard.adoc
  content/doc/book/blueocean/getting-started.adoc
Labels: documentation

#4493 Fix rendering
  content/doc/developer/publishing/releasing-cd.adoc
Labels: documentation

#4494 Improve rendering
  content/doc/developer/publishing/releasing-cd.adoc
Labels: documentation

#4499 Changelog 2.306
  content/_data/changelogs/weekly.yml
Labels: changelog

#4502 Add ability to use ruby without docker
  scripts/ruby
Labels: chore

#4503 Removed broken links for logos
  content/_data/logo/JCasC.yml
  content/_data/logo/alien.yml
  content/_data/logo/atomium.yml
  content/_data/logo/austin.yml
  content/_data/logo/balloon.yml
  content/_data/logo/beekeeper.yml
  content/_data/logo/belarus.yml
  content/_data/logo/chatterbox.yml
  content/_data/logo/cosmonaut.yml
  content/_data/logo/cowboy.yml
  content/_data/logo/evergreen.yml
  content/_data/logo/formal.yml
  content/_data/logo/jenkinstein.yml
  content/_data/logo/magician.yml
  content/_data/logo/magritte.yml
  content/_data/logo/miner.yml
  content/_data/logo/musketeer.yml
  content/_data/logo/oktoberfest.yml
  content/_data/logo/paris-eiffel.yml
  content/_data/logo/peter-the-great.yml
  content/_data/logo/plumber.yml
  content/_data/logo/raleigh.yml
  content/_data/logo/russian.yml
  content/_data/logo/san-diego.yml
  content/_data/logo/santa-claus.yml
  content/_data/logo/sherlock.yml
  content/_data/logo/snow.yml
Labels: artwork

#4506 Include epel-release repo in CentOS instructions
  content/doc/book/installing/linux.adoc
Labels: documentation

#4507 Add Civo logo and URL to marketplace app
  content/download/index.html.haml
  content/images/civo.png
Labels: enhancement

#4508 Link to correct GitHub plugin
  content/doc/book/pipeline/multibranch.adoc
Labels: documentation

#4496 Terminology cleanup: Docs for built-in node migration
  content/doc/book/managing/built-in-node-migration.adoc
  content/redirect/built-in-node-migration.adoc
Labels: on-hold, documentation

#4510 Fix typo
  content/doc/book/scaling/architecting-for-manageability.adoc
Labels: documentation

#4511 Add Java 11 Docker image blog post
  content/blog/2021/08/2021-08-17-docker-images-use-jdk-11-by-default.adoc
  content/images/post-images/2021-08-docker-images-use-jdk-11-by-default/docker-images-use-jdk-11-by-default.png
Labels: blogpost

#4513 Add Jenkins 2.307 changelog
  content/_data/changelogs/weekly.yml
Labels: changelog

#4501 CloudEvents Plugin for Jenkins Phase I Blog
  content/blog/2021/08/2021-08-02-cloudevents-plugin-phase-I.adoc
  content/images/post-images/2021-08-cloudevents-plugin/configure_system.png
  content/images/post-images/2021-08-cloudevents-plugin/jcdevents.JPG
  content/images/post-images/2021-08-cloudevents-plugin/manage_jenkins.png
  content/images/post-images/2021-08-cloudevents-plugin/sink-type.png
Labels: blogpost

#4509 GSOC-2021 work report for git-credentials-binding project
  content/blog/2021/08/2021-08-19-git-credentials-binding-work-report.adoc
  content/images/post-images/2021-08-git-credentials-binding/git-credentials-binding.png
Labels: gsoc, blogpost

#4516 GSOC-2021 Project Page for Git Credentials Binding
  content/images/gsoc/2021/git-credentials/GitUsernamePassword.png
  content/images/gsoc/2021/git-credentials/freestyle-gitUsernamePassword.png
  content/images/gsoc/2021/git-credentials/ssh-private-key-freestyle-job.png
  content/images/gsoc/2021/git-credentials/ssh-private-key-pipeline-job.png
  content/images/gsoc/2021/git-credentials/usernamepassword-binding-freestyle-project.png
  content/images/gsoc/2021/git-credentials/usernamepassword-binding-pipline-job.png
  content/projects/gsoc/2021/projects/git-credentials-binding.adoc
Labels: gsoc

#4515 GSOC-21 update conventional commits project page
  content/projects/gsoc/2021/projects/conventional-commits-plugin.adoc
Labels: gsoc

#4519 Gsoc 21 work report update for Git Credentials Binding project
  content/blog/2021/08/2021-08-19-git-credentials-binding-work-report.adoc
Labels: blogpost

#4520 GSoC21 Remoting Monitoring: update project page for the final report.
  content/images/gsoc/2021/remoting-monitoring/demo-loki.png
  content/images/gsoc/2021/remoting-monitoring/demo-prometheus.png
  content/images/gsoc/2021/remoting-monitoring/goal.png
  content/projects/gsoc/2021/projects/remoting-monitoring.adoc
Labels: gsoc

#4504 Changelog and upgrade guide for 2.303.1
  content/_data/changelogs/lts.yml
  content/_data/upgrades/2-303-1.adoc
Labels: changelog

#4521 GSoC 21 Security Validator : Added work report
  content/blog/2021/08/2021-08-23-jenkins-operator-security-work-report.adoc
Labels: gsoc, blogpost

#4533 add mentor to gsoc cloudevents plugin
  content/projects/gsoc/2021/projects/cloudevents-plugin.adoc
Labels: gsoc

#4532 [JENKINS-66490] Note rpm dependency added in 2.303.1 installer
  content/_data/upgrades/2-303-1.adoc
Labels: changelog
