Repository jenkins-infra/jenkins.io, pull requests merged in 2021-06, with the labels that each got.

#4386 Update GSOC 2021 Conventional Commits Project Page
  content/projects/gsoc/2021/projects/conventional-commits-plugin.adoc
Labels: gsoc

#4390 Update using-credentials.adoc
  content/doc/book/using/using-credentials.adoc
Labels: documentation

#4389 Changelog 2.296
  content/_data/changelogs/weekly.yml
Labels: changelog, squash-merge-me

#4388 Update GSoC 2021 Remoting Monitoring project page
  content/projects/gsoc/2021/projects/remoting-monitoring.adoc
Labels: gsoc

#4383 Changelog and upgrade guide 2.289.1
  content/_data/changelogs/lts.yml
  content/_data/upgrades/2-289-1.adoc
Labels: changelog

#4391 Jenkins and Kubernetes - Secret Agents in the Clouds page - Correct a typo in the example
  content/blog/2018/09/2018-09-14-kubernetes-and-secret-agents.adoc
Labels: blogpost

#4379 Update JTE 2.0 to released on the roadmap
  content/_data/roadmap/roadmap.yml
Labels: roadmap

#4394 Add SSHD module unbundling, extend the new icons guide
  content/_data/upgrades/2-289-1.adoc
Labels: changelog

#4395 commons-digester:2.1 removal
  content/blog/2021/06/2020-06-04-digester-removal.adoc
Labels: blogpost

#4398 Updating gitSshPrivateKey implementation
  content/projects/gsoc/2021/project-ideas/git-credentials-binding-for-pipeline.adoc
Labels: gsoc

#4397 Apache Commons Digester removal blogpost fix and copy edits
  content/blog/2021/06/2020-06-04-digester-removal.adoc
  content/blog/2021/06/2021-06-04-digester-removal.adoc
Labels: blogpost

#4378 Update donations page to LFX Crowdfunding, reference it from /participate
  content/donate.adoc
  content/images/governance/funding/lfx_crowdfunding.png
  content/participate/index.html.haml
Labels: documentation

#4400 GSoC21 Remoting page: Add a new mentor and link
  content/_data/authors/cyrille-leclerc.adoc
  content/projects/gsoc/2021/projects/remoting-monitoring.adoc
Labels: gsoc

#4401 Also list plugins that was not served anymore already
  content/blog/2021/06/2021-06-04-digester-removal.adoc
Labels: blogpost

#4402 Adding opengraph image for commons-digester:2.1 removal
  content/blog/2021/06/2021-06-04-digester-removal.adoc
  content/images/post-images/2021-06-digester-removal/commons-digester-2.1-removal.jpg
Labels: blogpost

#4405 Fix DSL footnote
  content/doc/book/pipeline/index.adoc
Labels: documentation

#4403 Changelog 2.297
  content/_data/changelogs/weekly.yml
Labels: changelog

#4412 Updating office hours
  content/projects/gsoc/2021/projects/git-credentials-binding.adoc
Labels: gsoc

#4409 Changelog 2.297 (Updated)
  content/_data/changelogs/weekly.yml
Labels: changelog

#4411 Alyssa's blog post
  content/blog/2021/06/2021-06-10-jenkins-is-the-way-ebook-2.adoc
  content/images/post-images/jenkins-is-the-way/ebook/ebook2_front.png
  content/images/post-images/jenkins-is-the-way/ebook/ebook2_opengraph.png
Labels: blogpost, squash-merge-me

#4415 Updating documentation to reflect jenkinsci/jenkins#5047.
  content/doc/book/installing/other.adoc
Labels: documentation

#4416 Changelog 2.298
  content/_data/changelogs/weekly.yml
Labels: changelog

#4420 Update the 2.296 changelog to mark the Bytecode Compatibility Transfo…
  content/_data/changelogs/weekly.yml
Labels: changelog

#4421 Include Docker instructions for Windows
  content/doc/book/installing/_docker-for-tutorials.adoc
  content/doc/book/installing/_docker.adoc
Labels: documentation

#4423 Git Username and Password Binding Update
  content/images/gsoc/2021/git-credentials/UsernameandPassword.png
  content/projects/gsoc/2021/projects/git-credentials-binding.adoc
Labels: gsoc

#4424 Support for embedding Discourse topics in blogposts and project pages
  content/_layouts/post.html.haml
  content/_layouts/project.html.haml
  content/_partials/discuss.html.haml
  content/blog/2021/06/2021-06-10-jenkins-is-the-way-ebook-2.adoc
  content/events/contributor-summit/index.adoc
  content/projects/gsoc/2021/projects/remoting-monitoring.adoc
Labels: blogpost, gsoc

#4425 Blog the move to Libera.chat
  content/blog/2021/06/2021-06-17-libera-chat.adoc
  content/images/post-images/2021-06-libera-chat/jenkins-irc-on-libera-chat-opengraph.png
Labels: blogpost

#4399 CloudEvents Plugin Doc Update
  content/projects/gsoc/2021/projects/cloudevents-plugin.adoc
Labels: gsoc

#4427 Add agent tutorial videos to agent docs
  content/doc/book/managing/nodes.adoc
  content/doc/book/using/using-agents.adoc
Labels: documentation

#4430 Fix rendering of the end user panel in the landing
  content/events/contributor-summit/index.adoc
Labels: bug

#4431 Contributor Summit: Add anchors + More typo fixes
  content/events/contributor-summit/index.adoc
Labels: bug

#4432 [GSOC-21] Git Username and Password doc
  content/images/gsoc/2021/git-credentials/GitUsernamePassword.png
  content/images/gsoc/2021/git-credentials/UsernameandPassword.png
  content/images/gsoc/2021/git-credentials/freestyle-gitUsernamePassword.png
  content/projects/gsoc/2021/projects/git-credentials-binding.adoc
Labels: gsoc

#4433 Indent file by one
  content/_data/changelogs/weekly.yml
Labels: changelog

#4434 Remove image compression workflow
  .github/workflows/compress-images-in-PRs.yml
Labels: chore

#4419 Blog post for the student project in Jenkins security
  content/_data/authors/jphilip.adoc
  content/_data/authors/kguerroudj.adoc
  content/_data/authors/mheyries.adoc
  content/_data/authors/qparra.adoc
  content/blog/2021/06/2021-06-21-student-luminy-project-security.adoc
  content/images/post-images/2021/2021-06-21-student-luminy-project-security.png
Labels: blogpost

#4437 Changelog 2.299
  content/_data/changelogs/weekly.yml
Labels: changelog

#4436 Reference Terminology Cleanup project in the Advocacy&Outreach SIG
  content/_data/roadmap/roadmap.yml
  content/events/hacktoberfest.adoc
  content/sigs/advocacy-and-outreach/index.adoc
Labels: roadmap

#4439 Fix typo
  content/doc/book/blueocean/pipeline-editor.adoc
Labels: documentation

#4440 Add a Discourse reference to the Jenkins Security post
  content/blog/2021/06/2021-06-21-student-luminy-project-security.adoc
Labels: blogpost

#4443 docs: nginx to IIS
  content/doc/book/system-administration/reverse-proxy-configuration-iis.adoc
Labels: documentation

#4438 Request reviews from the Jenkins Governance board in roadmap item changes
  .github/CODEOWNERS
Labels: chore, roadmap

#4435 Add 2.289.2 changelog and upgrade guide
  content/_data/changelogs/lts.yml
  content/_data/upgrades/2-289-2.adoc
Labels: changelog
