Repository jenkins-infra/jenkins.io, pull requests merged in 2021-07, with the labels that each got.

#4442 docs: change layout to section
  content/doc/book/security/access-control.adoc
  content/doc/book/security/build-authorization.adoc
  content/doc/book/security/environment-variables.adoc
  content/doc/book/security/services.adoc
Labels: documentation

#4453 Marking `hudson.util.Digester2.UNSAFE` as obsolete
  content/doc/book/managing/system-properties.adoc
Labels: documentation

#4451 Marking `hudson.ClassicPluginStrategy.noBytecodeTransformer` as obsolete
  content/doc/book/managing/system-properties.adoc
Labels: documentation

#4454 Changelog 2.301
  content/_data/changelogs/weekly.yml
Labels: changelog

#4455 Remove superflous `a`
  content/doc/book/pipeline/index.adoc
Labels: documentation

#4446 Clarify the version-dependent default behavior
  content/doc/developer/security/form-validation.adoc
Labels: documentation

#4457 Updates to `/doc/developer/plugin-development/dependencies-and-class-loading/`
  content/doc/developer/plugin-development/dependencies-and-class-loading.adoc
Labels: documentation

#4460 Changelog 2.302
  content/_data/changelogs/weekly.yml
Labels: changelog

#4449 Revert "Work around 2021-06-30 Artifactory issues (#4448)"
  content/download/index.html.haml
Labels: on-hold

#4464 gsoc 2021 midterm demos blog post
  content/blog/2021/07/2021-07-16-gsoc-midterm-presentation.adoc
  content/images/gsoc/2021/gsoc-aditya-srivastava.png
  content/images/gsoc/2021/gsoc-akihiro-kiuchi.jpg
  content/images/gsoc/2021/gsoc-daniel-ko.jpg
  content/images/gsoc/2021/gsoc-pulkit-sharma.jpg
Labels: blogpost

#4463 Add 2.289.3 upgrade guide
  content/_data/upgrades/2-289-3.adoc
Labels: changelog

#4462 Add instructions for the encrypted password from Artifactory
  content/doc/developer/publishing/releasing-manually.adoc
Labels: documentation

#4466 Remove OpenJ9 JVM support from roadmap
  content/_data/roadmap/roadmap.yml
  content/sigs/platform/index.adoc
Labels: roadmap

#4452 Marking `hudson.TreeView` as obsolete
  content/doc/book/managing/system-properties.adoc
Labels: documentation

#4467 Use extension 0.9.0 for Stapler javadoc URL creation
  Gemfile
  Gemfile.lock
  content/blog/2015/2015-09-19-office-hour-on-form-handling-in-jenkins.md
  content/blog/2016/2016-09-20-jom-plugin-development.adoc
  content/blog/2019/08/2019-08-23-introduce-react-plugin-template.adoc
  content/blog/2020/03/2020-03-17-ui-plugins.adoc
  content/doc/book/using/referencing-another-project-by-name.adoc
  content/doc/developer/architecture/web.adoc
  content/doc/developer/development-environment/taglibs.adoc
  content/doc/developer/handling-requests/index.adoc
  content/doc/developer/handling-requests/responses.adoc
  content/doc/developer/handling-requests/routing.adoc
  content/doc/developer/internationalization/i18n-jelly-views.adoc
  content/doc/developer/javadoc.html.haml
  content/doc/developer/plugin-development/pipeline-integration.adoc
  content/projects/gsoc/2020/project-ideas/automatic-spec-generator-for-jenkins-rest-api.adoc
  content/projects/gsoc/2021/project-ideas/automatic-spec-generator-for-jenkins-rest-api.adoc
Labels: blogpost, chore, documentation, gsoc

#4470 Changelog 2.303
  content/_data/changelogs/weekly.yml
Labels: changelog

#4456 Add section on common mistakes when configuring authentication and authorization
  content/doc/book/security/access-control.adoc
  content/doc/book/security/access-control/permissions.adoc
Labels: documentation

#4472 Add 2.289.3 changelog
  content/_data/changelogs/lts.yml
Labels: changelog

#4473 grammar and punctuation fixes
  content/doc/administration/requirements/java.adoc
Labels: documentation

#4477 Fixed link for "Handling Environment Variables"
  content/doc/book/security/securing-jenkins.adoc
Labels: documentation

#4476 [GSoC-2021] Git Credentials Binding Phase-1 Blog
  content/blog/2021/07/2021-07-27-git-credentials-binding-phase-1.adoc
  content/images/post-images/2021-07-git-credentials-binding-phase-1/git-credentials-binding-phase-1-opengraph.png
Labels: blogpost

#4478 Changelog 2.304
  content/_data/changelogs/weekly.yml
Labels: changelog

#4474 grammar and punctuation fixes
  content/doc/administration/requirements/upgrade-java-guidelines.adoc
Labels: documentation

#4479 Use correct caps for example
  content/blog/2021/07/2021-07-27-git-credentials-binding-phase-1.adoc
Labels: blogpost

#4481 Add remoting 4.10 to 2.302 changelog
  content/_data/changelogs/weekly.yml
Labels: changelog

#4475 Add conventional commits plugin blog
  content/blog/2021/07/2021-07-30-introducing-conventional-commits-plugin-for-jenkins.adoc
  content/images/gsoc/2021/conventional-commits/conventionalCommitsPluginForJenkins.png
Labels: blogpost

#4483 fix: update video url
  content/blog/2021/07/2021-07-30-introducing-conventional-commits-plugin-for-jenkins.adoc
Labels: blogpost

#4485 Update conventional commits blog video URL
  content/blog/2021/07/2021-07-30-introducing-conventional-commits-plugin-for-jenkins.adoc
Labels: blogpost

#4484 grammar and punctuation fixes
  content/doc/administration/requirements/web-browsers.adoc
  content/doc/administration/requirements/windows.adoc
  content/doc/book/blueocean/activity.adoc
  content/doc/book/blueocean/creating-pipelines.adoc
Labels: documentation

#4482 GSoC 2021 Remoting Monitoring phase 1 blog
  content/blog/2021/07/2021-07-31-remoting-monitoring-phase-1.adoc
  content/images/post-images/2021-07-31-remoting-monitoring-phase-1/goal.png
  content/images/post-images/2021-07-31-remoting-monitoring-phase-1/install-monitoring-engine-when-provisioning.png
  content/images/post-images/2021-07-31-remoting-monitoring-phase-1/jaeger-spans.png
  content/images/post-images/2021-07-31-remoting-monitoring-phase-1/opengraph.png
  content/images/post-images/2021-07-31-remoting-monitoring-phase-1/prometheus-metrics.png
  content/images/post-images/2021-07-31-remoting-monitoring-phase-1/sending-monitoring-program-via-remoting.png
  content/images/post-images/2021-07-31-remoting-monitoring-phase-1/user-survey.png
Labels: blogpost

#4486 Fixed Typo
  content/doc/book/using/aborting-a-build.adoc
Labels: documentation
