Repository jenkins-infra/jenkins.io, pull requests merged in 2021-11, with the labels that each got.

#4664 Define controller, node, agent, executor
  content/doc/book/managing/nodes.adoc
Labels: documentation, hacktoberfest-accepted

#4676 Summarize Hacktoberfest results in a blog post
  content/blog/2021/10/2021-10-31-hacktoberfest-results-2021.adoc
  content/images/post-images/2021/2021-10-31-hacktoberfest-results-2021.png
Labels: blogpost

#4682 UpstreamCause should be BuildUpstreamCause
  content/doc/book/pipeline/syntax.adoc
Labels: documentation

#4683 Use blue ocean 1.25.1 - latest
  content/doc/book/installing/_docker-for-tutorials.adoc
  content/doc/book/installing/_docker.adoc
Labels: documentation

#4687 Data Fixes: changelogs
  content/_data/changelogs/lts.yml
  content/_data/changelogs/weekly.yml
Labels: changelog

#4694 Two extra points are added to Replay features
  content/doc/book/pipeline/development.adoc
Labels: documentation

#4696 Reduce changelog white space differences
  content/_data/changelogs/weekly.yml
Labels: changelog

#4697 Cleanup changelog.yaml data
  content/_data/changelogs/lts.yml
  content/_data/changelogs/weekly.yml
Labels: changelog

#4698 Replace all the refresh layouts with redirect
  content/100k.adoc
  content/_layouts/refresh.html.haml
  content/account.adoc
  content/blog/2015/2015-11-04-jenkins-and-docker.adoc
  content/blog/2016/2016-08-17-jenkins-world-speaker-blog-aquient.adoc
  content/blog/index.adoc
  content/blog/take-2015-jenkins-survey.adoc
  content/conduct.adoc
  content/doc/book/pipeline/overview.adoc
  content/doc/book/securing-jenkins.html.haml
  content/doc/pipeline/index.adoc
  content/friend.adoc
  content/welcome.adoc
Labels: blogpost, governance, documentation

#4699 Make sure redirects are not included in sitemap
  content/_config/sitemap.yml
  content/_ext/pipeline.rb
  content/_ext/sitemap.rb
Labels: blogpost, governance, changelog

#4675 Replace deprecated apt-key usage
  content/doc/book/installing/linux.adoc
Labels: documentation, hacktoberfest-accepted

#4706 Use correct repo for Debian weekly instructions
  content/doc/book/installing/linux.adoc
Labels: documentation

#4705 Cobertura plugin was never actually affected
  content/_data/upgrades/2-303-3.adoc
Labels: changelog

#4709 Revise and reorder 2.320 changelog
  content/_data/changelogs/weekly.yml
Labels: changelog

#4677 Update advanced plugin deployment docs for jenkinsci/jenkins#5862
  content/doc/book/managing/plugins.adoc
  content/doc/book/resources/managing/plugin-manager-upload.png
Labels: documentation

#4640 [JEP-233] Blog post about Guava library upgrade
  content/_data/authors/basil.adoc
  content/blog/2021/11/2021-11-09-guava-upgrade.adoc
  content/images/post-images/2021-11-guava-upgrade/guava-upgrade-opengraph.png
  content/images/post-images/2021-11-guava-upgrade/guava-upgrade.png
Labels: blogpost

#4710 Reference JENKINS-36779 in guava update changelog entry
  content/_data/changelogs/weekly.yml
Labels: changelog

#4711 Blog: duchess interview at hacktoberfest 2021
  content/_data/authors/ajard.adoc
  content/blog/2021/11/2021-11-12-interview-duchess-hacktoberfest.adoc
  content/images/avatars/ajard.jpg
  content/images/post-images/2021-11-duchess-hacktoberfest/al.jpg
  content/images/post-images/2021-11-duchess-hacktoberfest/jenkins-and-duchess.png
  content/images/post-images/2021-11-duchess-hacktoberfest/pl.jpg
  content/images/post-images/2021-11-duchess-hacktoberfest/tb.jpg
Labels: blogpost

#4714 Clean up blog post (remove all the extra +)
  content/blog/2013/2013-10-09-jenkins-at-netflix-juc-speaker-interview.adoc
Labels: blogpost

#4715 grammar and punctuation fixes
  content/doc/book/blueocean/index.adoc
Labels: documentation

#4722 Update 2.321 changelog
  content/_data/changelogs/weekly.yml
Labels: changelog

#4727 Fix some broken wiki refs
  content/events/fosdem/archive/2016.adoc
  content/events/fosdem/archive/2017.adoc
  content/events/fosdem/archive/2018.adoc
  content/events/fosdem/archive/2019.adoc
  content/project/governance-meeting/archives/2011.adoc
  content/project/governance-meeting/archives/2012.adoc
  content/project/governance-meeting/archives/2013.adoc
  content/project/governance-meeting/archives/2014.adoc
  content/project/governance-meeting/archives/2015.adoc
  content/project/governance-meeting/archives/2016.adoc
  content/project/governance-meeting/archives/2017.adoc
  content/project/governance-meeting/archives/2018.adoc
  content/project/governance-meeting/archives/2019.adoc
Labels: governance

#4723 Add user time zone setting description in Change System Time Zone page
  content/doc/book/managing/change-system-timezone.adoc
  content/doc/book/resources/managing/change-system-timezone-user-defined-timezone-2.png
  content/doc/book/resources/managing/change-system-timezone-user-defined-timezone.png
Labels: documentation

#4732 Revise 2.322 changelog
  content/_data/changelogs/weekly.yml
Labels: changelog

#4729 Add redirect URL for jenkinsci/jenkins#5890
  content/redirect/permitted-agent-to-controller-file-access.adoc
Labels: on-hold

#4734 Add reading and writing files to script console doc
  content/doc/book/managing/script-console.adoc
Labels: documentation

#4730 2.319.1 changelog
  content/_data/changelogs/lts.yml
  content/_data/upgrades/2-319-1.adoc
  content/doc/book/managing/_built-in-node-migration.adoc
  content/doc/book/managing/built-in-node-migration.adoc
Labels: changelog, documentation

#4739 Fix release date in change log
  content/_data/changelogs/lts.yml
Labels: changelog

#4741 Update 2.323 changelog
  content/_data/changelogs/weekly.yml
Labels: changelog
