Repository jenkins-infra/jenkins.io, pull requests merged in 2021-10, with the labels that each got.

#4592 Update time for contributor summit part 2
  content/_data/events/2021-10-09-contributor-summit-part-2.adoc
Labels: events

#4598 panadoc doesn't properly read this file because the horizonal lines are not seperated by blank lines
  content/blog/2015/2015-11-06-mitigating-unauthenticated-remote-code-execution-0-day-in-jenkins-cli.md
Labels: blogpost

#4599 Cleanup markdown posts
  content/blog/2010/2010-02-10-keeping-your-configuration-and-data-in-subversion.md
  content/blog/2010/2010-02-15-hudson-1-346-released.md
  content/blog/2010/2010-02-17-getting-started-building-android-apps-with-hudson.md
  content/blog/2010/2010-02-22-hudson-1-347-released.md
  content/blog/2010/2010-02-24-hudson-at-pycon.md
  content/blog/2010/2010-03-01-hudson-1-348-released.md
  content/blog/2010/2010-03-08-hudson-1-349-released.md
  content/blog/2010/2010-03-15-hudson-1-350-released.md
  content/blog/2010/2010-03-22-hudson-1-352-released.md
  content/blog/2010/2010-03-31-hudson-1-353-released.md
  content/blog/2010/2010-04-16-hudson-1-354-released.md
  content/blog/2010/2010-04-24-hudson-1-355-released.md
  content/blog/2010/2010-06-14-hudson-1-362-released.md
  content/blog/2010/2010-06-22-hudson-1-363-released.md
  content/blog/2010/2010-08-17-hudson-1-372-sets-sail.md
  content/blog/2011/2011-04-04-the-final-two-run-off-vote-for-the-new-jenkins-logo.md
  content/blog/2015/2015-10-25-jenkins-2-0-proposal-introduce-a-policy-for-api-deprecation.md
Labels: blogpost

#4602 Fix broken link in remote-access-api page
  content/doc/book/using/remote-access-api.adoc
Labels: documentation

#4606 add georgia
  content/_data/logo/georgia.yml
  content/images/logos/georgia/256.png
  content/images/logos/georgia/georgia.png
  content/images/logos/georgia/georgia.svg
Labels: hacktoberfest, artwork

#4610 Fix 100k page.
  content/blog/2015/2015-02-09-jenkins-celebration-day-is-february-26.adoc
Labels: blogpost

#4607 Make css image paths relative to the css file
  content/css/changelog.css
  content/css/download.css
  content/css/jenkins.css
Labels: changelog

#4608 Remove reference to Jenkins.1.x
  content/doc/book/security/securing-jenkins.adoc
Labels: documentation

#4617 Fix up a bunch of old content
  content/_data/authors/abayer.adoc
  content/blog/2010/2010-02-08-hudson-1-344-released.adoc
  content/blog/2010/2010-03-01-learn-about-ci-with-hudson-sf-java-user-group.adoc
  content/blog/2010/2010-04-24-hudson-1-355-released.adoc
  content/blog/2010/2010-06-10-subversion-repository-change-notification-push-vs-pull.adoc
  content/blog/2010/2010-06-14-hudson-1-362-released.adoc
  content/blog/2010/2010-07-08-a-python-love-story-virtualenv-and-hudson.adoc
  content/blog/2010/2010-07-28-hosting-your-hudson-plugin-at-github.adoc
  content/blog/2010/2010-08-02-dogfooding-hudson-were-looking-for-slaves.adoc
  content/blog/2010/2010-08-17-hudson-anonymous-usage-data.adoc
  content/blog/2010/2010-08-26-cloudbees-announce-hudson-as-a-service.adoc
  content/blog/2010/2010-08-31-hudson-at-javazone-meetup-in-oslo.adoc
  content/blog/2010/2010-09-01-copenhagen-hudson-user-meetup.adoc
  content/blog/2011/2011-02-14-upcoming-jenkins-events-in-tokyo.adoc
  content/projects/gsoc/2019/project-ideas/ext-workspace-manager-cloud-features.adoc
Labels: gsoc, blogpost

#4614 Fix: possible solution for Nginx's 'No such file or directory' error
  content/doc/book/system-administration/reverse-proxy-configuration-nginx.adoc
Labels: documentation

#4618 chore: add Hacktoberfest 2021 to the roadmap
  content/_data/roadmap/roadmap.yml
Labels: hacktoberfest, events, roadmap, hacktoberfest-accepted

#4619 Docker for Windows installation commands updated
  content/doc/book/installing/_docker.adoc
Labels: documentation

#4673 Remove AJP documentation
  content/doc/book/installing/_jenkins-command-parameters.adoc
  content/doc/book/system-administration/reverse-proxy-configuration-apache.adoc
Labels: documentation

#4674 Update Docker installation in Dockerfiles
  content/doc/book/installing/_docker-for-tutorials.adoc
  content/doc/book/installing/_docker.adoc
Labels: documentation
