Repository jenkins-infra/jenkins.io, pull requests merged in 2022-08, with the labels that each got.

#5325 Improve markup in spawning-processes.adoc
  content/doc/book/managing/spawning-processes.adoc
Labels: documentation

#5326 Fix self href for releases.rss, add www where needed
  scripts/release.rss.rb
Labels: chore

#5327 Revise 2.362 changelog
  content/_data/changelogs/weekly.yml
Labels: changelog

#5329 Add anchors to artwork page's artwork so they can be direct linked to
  content/_ext/id_generator.rb
  content/_ext/pipeline.rb
  content/artwork/index.html.haml
Labels: artwork

#5328 [DOCS-5944] Updating Blue Ocean index page
  content/doc/book/blueocean/index.adoc
Labels: documentation

#5333 fix the documention of post
  content/doc/book/pipeline/syntax.adoc
Labels: documentation

#5337 Blog summary of She Code Africa 2022
  .typos.toml
  content/_data/authors/zaycodes.adoc
  content/_data/changelogs/weekly.yml
  content/blog/2022/08/2022-08-04-expanding-open-source-in-Africa.adoc
  content/doc/book/blueocean/getting-started.adoc
  content/images/avatars/zaycodes.jpg
  content/images/post-images/2022-08-04-expanding-open-source-in-africa/open-source-in-africa.png
Labels: blogpost, changelog, documentation

#5338 Use latest blue ocean and docker workflow plugins
  content/doc/book/installing/_docker-for-tutorials.adoc
  content/doc/book/installing/_docker.adoc
Labels: documentation

#5311 2.346.3 LTS changelog and upgrade guide
  content/_data/changelogs/lts.yml
  content/_data/upgrades/2-346-3.adoc
Labels: changelog

#5340 Update monitoring.adoc
  content/doc/book/system-administration/monitoring.adoc
Labels: documentation

#5339 [Blog] Manage Jenkins agents with Kubernetes native PodTemplate
  content/blog/2022/08/2022-08-05-manage-jenkins-agents-with-podtemplate.adoc
Labels: blogpost

#5349 Describing `hpi.compatibleSinceVersion` in CD-enabled plugins
  content/doc/developer/plugin-development/mark-a-plugin-incompatible.adoc
  content/doc/developer/publishing/releasing-cd.adoc
Labels: documentation

#5350 Add Blue Ocean admonition to more locations
  content/doc/book/blueocean/_blue-ocean-status.adoc
  content/projects/blueocean/about/index.adoc
  content/projects/index.adoc
Labels: documentation

#5352 Revise 2.363 changelog
  content/_data/changelogs/weekly.yml
Labels: changelog

#5353 Remove hyphen from lowercase
  content/doc/book/pipeline/shared-libraries.adoc
Labels: documentation

#5354 Remove hyphen from lowercase
  CONTRIBUTING.adoc
  content/doc/book/using/using-credentials.adoc
Labels: documentation

#5348 [DOCS-5908] updating activity view page
  content/doc/book/blueocean/activity.adoc
  content/doc/book/resources/blueocean/activity/branch-filter.png
  content/doc/book/resources/blueocean/activity/branches.png
  content/doc/book/resources/blueocean/activity/navigation-bars.png
  content/doc/book/resources/blueocean/activity/overview.png
Labels: documentation

#5358 Correct the Apache reverse proxy configuration with mod_rewrite
  content/doc/book/system-administration/reverse-proxy-configuration-apache.adoc
Labels: documentation

#5357 [blog] DevOps World talk on Plugin Health Scoring project
  content/_data/authors/jleon.adoc
  content/blog/2022/08/2022-08-11-plugin-health-scoring.adoc
Labels: blogpost

#5356 [DOCS-5910] Update to Blue Ocean editor doc
  content/doc/book/blueocean/pipeline-editor.adoc
Labels: documentation

#5363 Add Captain artwork by Mehdi-BR
  content/_data/logo/captain.yml
  content/images/logos/captain/256.png
  content/images/logos/captain/captain.png
Labels: artwork

#5368 Explain why Jira is needed despite GH issue tracking
  content/doc/developer/publishing/preparation.adoc
Labels: documentation

#5371 Noting jenkinsci/workflow-cps-plugin#543 in the upgrade guide
  content/_data/upgrades/2-346-3.adoc
Labels: changelog

#5369 Fix ambiguous label
  content/_data/changelogs/weekly.yml
Labels: changelog

#5374 DevOps World Jenkins Community talks blog post
  content/blog/2022/08/2022-08-19-dw-community-presentations.adoc
  content/images/post-images/DW_2022.png
Labels: blogpost

#5373 Delete giant script
  content/doc/book/managing/nodes.adoc
Labels: documentation

#5382 Update release notes with OpenJDK issues
  content/_data/upgrades/2-346-3.adoc
Labels: changelog

#5380 docs: Update design library documentation
  content/doc/developer/views/symbols.adoc
Labels: documentation

#5378 add blue ocean status to create a pipeline in Blue Ocean tutorial
  content/doc/tutorials/create-a-pipeline-in-blue-ocean.adoc
Labels: documentation

#5383 Reorder 2.365 changelog entries
  content/_data/changelogs/weekly.yml
Labels: changelog

#5384 Improvements to "Require Java 11 or newer" blog post
  content/blog/2022/06/2022-06-28-require-java-11.adoc
Labels: blogpost

#5386 Add 'What's next for Jenkins' blog post - DevOps World 2022
  content/_data/authors/janfaracik.adoc
  content/_partials/blogcardlist.html.haml
  content/blog/2022/08/2022-08-26-jenkins-design.adoc
  content/images/avatars/janfaracik.jpg
  content/images/avatars/timja.jpg
  content/images/post-images/jenkins-redesign-preview-social.png
  content/images/post-images/jenkins-redesign-preview.png
Labels: blogpost

#5389 Add description for opengraph for UX DevOps world blog
  content/_partials/blogcardlist.html.haml
  content/blog/2022/08/2022-08-26-jenkins-design.adoc
Labels: blogpost

#5393 Fixed typo (woiuld -> would)
  content/doc/book/using/using-jmeter-with-jenkins.adoc
Labels: documentation

#5392 Added a space between code and text
  content/doc/book/installing/_docker.adoc
Labels: documentation

#5387 Revamp the blog post design
  Gemfile
  Gemfile.lock
  content/_ext/authorship.rb
  content/_layouts/frame.html.haml
  content/_layouts/post.html.haml
  content/_partials/author.html.haml
  content/_partials/avatar.html.haml
  content/_partials/blogcardlist.html.haml
  content/_partials/social-media-buttons.html.haml
  content/css/jenkins.css
  content/stylesheets/abstracts/_all.scss
  content/stylesheets/abstracts/_breakpoints.scss
  content/stylesheets/abstracts/_theme.scss
  content/stylesheets/base/_all.scss
  content/stylesheets/base/_display.scss
  content/stylesheets/components/_all.scss
  content/stylesheets/components/_author.scss
  content/stylesheets/components/_avatar.scss
  content/stylesheets/components/_back-link.scss
  content/stylesheets/components/_chips.scss
  content/stylesheets/components/_social-media.scss
  content/stylesheets/components/_tags.scss
  content/stylesheets/core/_all.scss
  content/stylesheets/core/_link.scss
  content/stylesheets/pages/_all.scss
  content/stylesheets/pages/_blog.scss
  content/stylesheets/pages/_post.scss
  content/stylesheets/styles.scss
Labels: chore

#5395 2.346.3-2 was released
  content/_data/upgrades/2-346-3.adoc
Labels: changelog

#5390 Update prepare.adoc
  content/doc/developer/tutorial/prepare.adoc
Labels: documentation

#5398 Announcing DW2022 talk about Jenkins Performance with Java 11
  content/blog/2022/08/2022-08-31-DW_java11_performance.adoc
Labels: blogpost
