Repository jenkins-infra/jenkins.io, pull requests merged in 2022-01, with the labels that each got.

#4793 Switch hosting project to GitHub issues
  content/doc/developer/publishing/requesting-hosting.adoc
  content/project/teams/hosting.adoc
  content/projects/infrastructure/ircbot.adoc
Labels: governance, documentation

#4794 Expanded JEP-229 instructions
  content/doc/developer/publishing/releasing-cd.adoc
Labels: documentation

#4798 Simplify JRE requirements description for better readability.
  content/doc/administration/requirements/java.adoc
Labels: documentation

#4782 Preview support
  .dockerignore
  Dockerfile
  Jenkinsfile_k8s
  Makefile
  content/blog/2010/2010-02-25-spotlight-on-springsource.adoc
  content/blog/2012/2012-05-28-jenkins-a-besoin-de-vous.adoc
  package-lock.json
  package.json
  scripts/node
Labels: blogpost, chore, squash-merge-me

#4795 Add 2.319.2 changelog and upgrade guide
  content/_data/changelogs/lts.yml
  content/_data/upgrades/2-319-2.adoc
Labels: changelog

#4800 GSoC 2022 documentation
  content/projects/gsoc/2021/index.adoc
  content/projects/gsoc/2021/projects/cloudevents-plugin.adoc
  content/projects/gsoc/2021/projects/conventional-commits-plugin.adoc
  content/projects/gsoc/2021/projects/git-credentials-binding.adoc
  content/projects/gsoc/2021/projects/jenkins-operator-security.adoc
  content/projects/gsoc/2021/projects/remoting-monitoring.adoc
  content/projects/gsoc/2022/index.adoc
  content/projects/gsoc/2022/project-ideas.html.haml
  content/projects/gsoc/2022/project-ideas/automatic-spec-generator-for-jenkins-rest-api.adoc
  content/projects/gsoc/2022/project-ideas/pipeline-step-documentation-generator.adoc
  content/projects/gsoc/2022/project-ideas/plugin-installation-manager-tool.adoc
  content/projects/gsoc/index.adoc
  content/sigs/gsoc/index.adoc
Labels: gsoc

#4808 GSoC 2022 Blog post
  content/blog/2022/01/2022-01-06-gsoc-2022.adoc
  content/projects/gsoc/proposing-project-ideas.adoc
Labels: gsoc, blogpost

#4773 Add overview of pages in Managing Jenkins chapter
  content/doc/book/managing/_chapter.yml
  content/doc/book/managing/about-jenkins.adoc
  content/doc/book/managing/index.adoc
  content/doc/book/managing/script-approval.adoc
  content/doc/book/managing/system-info.adoc
  content/doc/book/managing/users.adoc
Labels: documentation

#4810 Fix the lower case of last blog title
  content/blog/2022/01/2022-01-07-gsoc-2022.adoc
Labels: blogpost

#4814 Make netlify deploys safe
  Jenkinsfile_k8s
  package-lock.json
  package.json
Labels: chore

#4789 Add documentation for JEP-235
  content/doc/book/security/controller-isolation.adoc
  content/doc/book/security/controller-isolation/agent-to-controller.adoc
  content/doc/book/security/controller-isolation/jep-235.adoc
  content/redirect/AdminWhitelistRule.adoc
Labels: documentation

#4819 Update index.adoc
  content/doc/book/using/index.adoc
Labels: documentation

#4821 Happy New Year - Jenkins in 2021
  content/blog/2022/01/2022-01-14-happy-new-year.adoc
  content/images/post-images/2022-01-14-new-year/community-site.png
  content/images/post-images/2022-01-14-new-year/gsoc-2021-students.png
  content/images/post-images/2022-01-14-new-year/jenkins-is-the-way-map.png
Labels: blogpost

#4812 Adding dev doc for managing HTTP/Json API
  content/doc/developer/handling-requests/_chapter.yml
  content/doc/developer/handling-requests/json.adoc
Labels: documentation

#4826 Update NodeJS tutorial
  content/doc/book/installing/_docker-for-tutorials.adoc
  content/doc/book/installing/_docker.adoc
  content/doc/tutorials/build-a-node-js-and-react-app-with-npm.adoc
Labels: documentation

#4837 Fix spelling error #4831
  content/doc/book/managing/index.adoc
Labels: documentation

#4836 Remove markdown from weekly changelog
  content/_data/changelogs/weekly.yml
Labels: changelog

#4839 [documentation] Update dev doc with after merge feedbacks.
  content/doc/developer/handling-requests/json.adoc
Labels: documentation

#4824 Update the GSoC 2022 project proposals
  content/_data/authors/jleon.adoc
  content/_data/authors/krisstern.adoc
  content/images/avatars/jleon.jpg
  content/projects/gsoc/2022/project-ideas/JCasC-drift-detector.adoc
  content/projects/gsoc/2022/project-ideas/automatic-git-cache-maintenance.adoc
  content/projects/gsoc/2022/project-ideas/automating-plugin-buildmetadata-updates.adoc
  content/projects/gsoc/2022/project-ideas/pipeline-step-documentation-generator.adoc
  content/projects/gsoc/2022/project-ideas/plugin-health-scoring-system.adoc
  content/projects/gsoc/2022/project-ideas/plugin-installation-manager-tool.adoc
  content/projects/gsoc/2022/project-ideas/prj-idea-template.adoc_text
Labels: gsoc

#4838 Add GSoC 2022 project idea for Jenkinsfile Runner Action
  content/projects/gsoc/2022/project-ideas/jenkinsfile-runner-action-for-github-actions.adoc
Labels: gsoc

#4842 Update doc to reflect current terms
  content/projects/gsoc/students.adoc
Labels: gsoc

#4845 Fix typos in GSoC 2022 docs
  content/projects/gsoc/2022/project-ideas/automatic-spec-generator-for-jenkins-rest-api.adoc
  content/projects/gsoc/2022/project-ideas/jenkinsfile-runner-action-for-github-actions.adoc
Labels: gsoc

#4849 chore: replace `updatebot@olblak.com`
  updatecli/values.yaml
Labels: chore

#4820 refresh the documentation of the plugin adoption process
  content/doc/developer/plugin-governance/adopt-a-plugin.adoc
Labels: documentation

#4850 Update project ideas page
  content/projects/gsoc/2022/project-ideas.html.haml
Labels: gsoc

#4853 roles-and-responsibilities.adoc
  content/projects/gsoc/roles-and-responsibilities.adoc
Labels: gsoc

#4852 Update index.adoc
  content/projects/gsoc/index.adoc
Labels: gsoc

#4846 Update plugin documentation migration steps in Plugin Wiki Pages page
  content/doc/developer/publishing/wiki-page.adoc
Labels: documentation

#4851 Update `releasing-cd.adoc`
  content/doc/developer/publishing/releasing-cd.adoc
Labels: documentation

#4859 grammar and punctuation fixes
  content/doc/book/blueocean/pipeline-editor.adoc
  content/doc/book/blueocean/pipeline-run-details.adoc
Labels: documentation

#4860 Update CD troubleshooting INFRA issue link
  content/doc/developer/publishing/releasing-cd.adoc
Labels: documentation

#4832 Clarify use of BOM and Dependabot for dependency management
  content/doc/developer/plugin-development/dependency-management.adoc
Labels: documentation

#4865 Exchange a few buttons and icons
  content/_layouts/changelog.html.haml
  content/_layouts/frame.html.haml
  content/_partials/downloadbanner.html.haml
  content/_partials/logo.html.haml
  content/blog/2011/2011-08-08-jenkins-user-conference.adoc
  content/blog/2012/2012-02-21-sponsor-a-jenkins-user-conference.adoc
  content/images/changelog/feed-icon.png
  content/images/changelog/feed-icon.svg
  content/images/github-mark-32px.png
  content/images/jar.png
  content/images/jar.svg
  content/images/user.gif
  content/projects/blueocean/index.html.haml
  content/projects/index.adoc
  content/sigs/hw-and-eda/index.adoc
  content/sigs/pipeline-authoring/index.adoc
  content/sigs/ux/index.adoc
  content/templates/downloads.html.haml
Labels: blogpost, changelog

#4868 Fix English typo
  content/doc/developer/publishing/releasing-cd.adoc
Labels: documentation

#4864 Update JCasC Drift detector project
  content/projects/gsoc/2022/project-ideas/JCasC-drift-detector.adoc
Labels: gsoc

#4827 Drop IE 11 support in browser policy, promote edge to L1
  content/doc/administration/requirements/web-browsers.adoc
Labels: documentation

#4870 Propose developer guide for icon removal from core
  content/doc/developer/views/_chapter.yml
  content/doc/developer/views/icon-path-to-icon-class-migration.adoc
Labels: documentation

#4866 GSoC mentor page update
  content/projects/gsoc/mentors.adoc
Labels: gsoc

#4873 [doc]Updating json examples with the final version.
  content/doc/developer/handling-requests/json.adoc
Labels: documentation

#4862 Use infra help desk repo, not Jira issues
  content/_data/changelogs/lts.yml
  content/_data/changelogs/weekly.yml
  content/doc/book/pipeline/syntax.adoc
  content/doc/developer/plugin-governance/deprecating-or-removing-plugin.adoc
  content/doc/developer/plugin-governance/managing-permissions.adoc
  content/events/hacktoberfest.adoc
  content/project/governance.adoc
  content/projects/gsoc/2021/project-ideas/pipeline-step-documentation-generator.adoc
  content/projects/gsoc/2022/project-ideas/pipeline-step-documentation-generator.adoc
  content/projects/infrastructure/index.adoc
Labels: gsoc, governance, changelog, documentation
