Repository jenkins-infra/jenkins.io, pull requests merged in 2022-03, with the labels that each got.

#4952 Remove incorrect // in mailto links
  content/blog/2019/12/2019-12-16-board-election-results.adoc
  content/blog/2020/12/2020-12-03-election-results.adoc
  content/project/board.html.haml
Labels: blogpost, governance

#4953 Fix updates versions list appearance
  content/_layouts/developerguide.html.haml
  content/css/jenkins.css
  content/doc/developer/views/symbols.adoc
Labels: documentation

#4958 Add Shubham Kumar (imskr) as GSoC Mentor
  content/_data/authors/imskr.adoc
  content/images/avatars/imskr.jpg
  content/projects/gsoc/2022/project-ideas/jenkinsfile-runner-action-for-github-actions.adoc
Labels: gsoc

#4961 Clarify release drafter configuration changes
  content/doc/developer/publishing/releasing-cd.adoc
Labels: documentation

#4962 Note concrete change for JCasC
  content/doc/book/security/controller-isolation/jep-235.adoc
Labels: documentation

#4963 Link to config page for RD App
  content/doc/developer/publishing/releasing-cd.adoc
Labels: documentation

#4933 Describe how to manually manage parts of the version number
  content/doc/developer/publishing/releasing-cd.adoc
Labels: documentation

#4964 Add instructions how to obtain your encrypted Artifactory password using curl
  content/doc/developer/publishing/preparation.adoc
  content/doc/developer/publishing/releasing-manually.adoc
Labels: documentation

#3381 added agents with win scheduler content from wiki
  content/doc/book/managing/nodes.adoc
Labels: documentation

#3392 migrated spawning processes
  content/doc/book/managing/_chapter.yml
  content/doc/book/managing/spawning-processes.adoc
Labels: documentation

#4965 Note when people may have gotten a bad release-drafter config
  content/doc/developer/publishing/releasing-cd.adoc
Labels: documentation

#4968 Announce Jenkins in GSoC 2022
  content/blog/2022/03/2022-03-08-gsoc2022-announcement.adoc
  content/images/gsoc/2022/here-we-come.png
Labels: blogpost, squash-merge-me

#4969 correct accepted mentoring orgs #
  content/blog/2022/03/2022-03-08-gsoc2022-announcement.adoc
Labels: blogpost

#4973 Add 'Managing systemd services' page
  content/doc/book/system-administration/_chapter.yml
  content/doc/book/system-administration/systemd-services.adoc
Labels: documentation

#4972 Use systemd for LTS
  content/doc/book/installing/linux.adoc
  content/doc/tutorials/tutorial-for-installing-jenkins-on-AWS.adoc
Labels: documentation

#4960 Changelog and upgrade guide for 2.332.1
  content/_data/changelogs/lts.yml
  content/_data/upgrades/2-332-1.adoc
Labels: changelog

#4975 Note usage of `mvn validate`
  content/doc/developer/publishing/releasing-cd.adoc
Labels: documentation

#4966 Fix broken links
  content/_data/authors/dduportal.adoc
  content/_data/upgrades/2-289-1.adoc
  content/blog/2016/2016-05-23-external-workspace-manager-plugin.adoc
  content/blog/2016/2016-06-30-ewm-alpha-version.adoc
  content/blog/2020/08/2020-08-27-machine-learning-plugin-coding-phase3.adoc
  content/blog/2020/12/2020-12-22-gsoc-report.adoc
  content/blog/2021/04/2021-04-21-tekton-plugin.adoc
  content/blog/2021/06/2021-06-17-libera-chat.adoc
  content/blog/2021/08/2021-08-28-conventional-commits-plugin-project-report.adoc
  content/blog/2021/10/2021-10-25-jenkins-elections.adoc
  content/doc/book/installing/_docker-for-tutorials.adoc
  content/doc/book/installing/_docker.adoc
  content/doc/book/installing/war-file.adoc
  content/doc/book/security/configuring-content-security-policy.adoc
  content/doc/book/security/securing-jenkins.adoc
  content/download/lts/index.adoc
  content/events/fosdem/archive/2018.adoc
  content/events/fosdem/archive/2019.adoc
  content/events/online-hackfest/2020-uiux/index.adoc
  content/participate/connect.adoc
  content/project/board-election-process.adoc
  content/project/governance-meeting/archives/2015.adoc
  content/project/governance-meeting/archives/2016.adoc
  content/project/governance-meeting/archives/2018.adoc
  content/projects/gsoc/2020/projects/winsw-yaml-configs.adoc
  content/projects/gsoc/2021/projects/conventional-commits-plugin.adoc
  content/projects/infrastructure/index.adoc
  content/security/for-administrators.adoc
Labels: gsoc, blogpost, governance, changelog, documentation

#4977 Add systemd upgrade guide
  content/_data/upgrades/2-332-1.adoc
Labels: changelog

#4978 Add a missing 2.332.1 backport changelog entry
  content/_data/changelogs/lts.yml
Labels: changelog

#4976 Troubleshooting jenkins section
  content/_partials/toptoolbar.html.haml
  content/doc/book/_book.yml
  content/doc/book/system-administration/_chapter.yml
  content/doc/book/system-administration/diagnosing-errors.adoc
  content/doc/book/system-administration/obtaining-a-thread-dump.adoc
  content/doc/book/troubleshooting/_chapter.yml
  content/doc/book/troubleshooting/diagnosing-errors.adoc
  content/doc/book/troubleshooting/index.adoc
  content/doc/book/troubleshooting/obtaining-a-thread-dump.adoc
  content/doc/book/using/index.adoc
Labels: documentation

#4981 Add preview page for changelog
  content/_partials/release-header.html.haml
  content/changelog-old/index.html.haml
  content/changelog-preview/index.html.haml
  content/changelog-stable/index.html.haml
  content/changelog/index.html.haml
Labels: changelog

#4823 Add Linux support policy
  content/doc/administration/requirements/linux.adoc
Labels: documentation, squash-merge-me

#4980 Update GSoC links
  content/projects/gsoc/index.adoc
Labels: gsoc

#4988 Link to Linux Support Policy, same as Windows
  content/doc/book/installing/_installation_requirements.adoc
Labels: documentation

#4991 Add Logo googly jenkins 👀🤪
  content/_data/logo/googly.yml
  content/images/logos/googly/256.png
  content/images/logos/googly/googly.png
  content/images/logos/googly/googly.svg
Labels: artwork, squash-merge-me

#4992 Don't need the /images/ prefix
  CONTRIBUTING.adoc
Labels: artwork

#4994 Remove @oleg-nenashev from the "Automatic Specification Generator for Jenkins REST API" project idea
  content/projects/gsoc/2022/project-ideas/automatic-spec-generator-for-jenkins-rest-api.adoc
Labels: gsoc

#4998 add Tasneem Koushar as GSOC Mentor
  content/_data/authors/koushartasneem.adoc
  content/projects/gsoc/2022/project-ideas/pipeline-step-documentation-generator.adoc
Labels: gsoc

#5005 Update how we determine who to show as maintainer
  content/doc/developer/publishing/documentation.adoc
Labels: documentation

#5003 Add troubleshooting information for Jenkins Security Scan
  content/doc/developer/security/scan.adoc
Labels: documentation

#5007 Update description after repository restructuring
  content/doc/developer/security/scan.adoc
Labels: documentation

#5010 Remove duplicate security entry from dev docs
  content/doc/developer/architecture/_chapter.yml
  content/doc/developer/architecture/security.adoc
Labels: documentation

#5012 Announce Jenkins Award nominations
  content/blog/2022/03/2022-03-22-jenkins-contributor-awards.adoc
  content/images/post-images/2022/jenkins-awards-2022.png
Labels: blogpost

#5006 Typos checking in jenkins (github action doesn't do annotations atm)
  .github/workflows/spell-check.yaml
  .typos.toml
  Jenkinsfile
Labels: chore

#5015 fix(blogpost): correct links for cdf Jenkins awards 2022
  content/blog/2022/03/2022-03-22-jenkins-contributor-awards.adoc
Labels: blogpost

#5016 Add MSI parameters packaging fix to 2.338 changelog
  content/_data/changelogs/weekly.yml
Labels: changelog

#5017 Include `remove` label in changelogs
  content/_data/changelogs/lts.yml
  content/_data/changelogs/weekly.yml
  content/_data/upgrades/2-332-1.adoc
Labels: changelog

#5019 Migrate object persistence documentation from old wiki
  content/doc/developer/persistence/_chapter.yml
  content/doc/developer/persistence/backward-compatibility.adoc
  content/doc/developer/persistence/custom-converter.adoc
  content/doc/developer/persistence/incompatible-releases.adoc
  content/doc/developer/persistence/index.adoc
Labels: documentation

#5024 Rephrase to make this easier to understand
  content/doc/developer/security/scan.adoc
Labels: documentation

#5020 Improve 2.332.1 LTS upgrade guide
  content/_data/upgrades/2-332-1.adoc
Labels: changelog

#5021 Document key store config when enabling HTTP/2
  content/doc/book/installing/_jenkins-command-parameters.adoc
Labels: documentation

#4707 Adapt documentation to jenkinsci/remoting#490
  content/doc/book/managing/system-properties.adoc
  content/doc/developer/security/remoting-callables.adoc
Labels: documentation, squash-merge-me

#5018 Document Pipeline: Nodes and Processes tunables
  content/doc/book/managing/system-properties.adoc
Labels: documentation

#5022 `systemd` migration blog post and documentation updates
  content/_data/upgrades/2-332-1.adoc
  content/blog/2022/03/2022-03-25-systemd-migration.adoc
  content/doc/book/system-administration/systemd-services.adoc
Labels: blogpost, changelog, documentation

#5032 Fixups to `agent kubernetes` example
  content/doc/book/pipeline/syntax.adoc
Labels: documentation

#5034 Jenkins Award nominations extended to April 11, 2022
  content/blog/2022/03/2022-03-29-jenkins-contributor-awards.adoc
Labels: blogpost

#5035 Using consistent number of the plugin count
  content/doc/developer/index.html.haml
  content/participate/code.adoc
Labels: documentation

#5038 Add explanation for checks unexpectedly passing
  content/doc/developer/security/scan.adoc
Labels: documentation

#5044 Exchange jelly with xml syntax highlighting
  content/doc/developer/internationalization/i18n-jelly-views.adoc
Labels: documentation
