Repository jenkins-infra/jenkins.io, pull requests merged in 2022-04, with the labels that each got.

#5049 Align Groovy i18n documentation with Jelly
  content/doc/developer/internationalization/i18n-groovy-views.adoc
Labels: documentation

#5043 Update 2022-03-08-gsoc2022-announcement.adoc
  content/blog/2022/03/2022-03-08-gsoc2022-announcement.adoc
Labels: blogpost

#5045 2.332.2 changelog and upgrade guide
  content/_data/changelogs/lts.yml
  content/_data/changelogs/weekly.yml
  content/_data/upgrades/2-332-2.adoc
Labels: changelog, squash-merge-me

#5052 Use ionicons for symbols, system fonts for text
  Makefile
  content/2.0.html.haml
  content/_data/steps/firststart.yml
  content/_layouts/developerbook.html.haml
  content/_layouts/developerchapter.html.haml
  content/_layouts/frame.html.haml
  content/css/font-icons.css
  content/css/fonts/icomoon.eot
  content/css/fonts/icomoon.svg
  content/css/fonts/icomoon.ttf
  content/css/fonts/icomoon.woff
  content/css/jenkins.css
  content/doc/developer/book.html.haml
  content/download/index.html.haml
  content/images/conference.svg
  content/images/developer.svg
  content/images/download.svg
  content/images/jar.svg
  content/images/visitor.svg
  content/index.html.haml
  package-lock.json
  package.json
Labels: chore, documentation

#5061 minor typo in the range provided with the explanation
  content/doc/book/pipeline/running-pipelines.adoc
Labels: documentation

#5060 minor typo with variable name reference
  content/doc/book/pipeline/jenkinsfile.adoc
Labels: documentation

#5064 Move ionicons to cdn
  Makefile
  content/_layouts/frame.html.haml
  package-lock.json
  package.json
Labels: chore

#5062 She Code Africa Contributhon blog post
  content/blog/2022/04/2022-04-11-She-Code-Africa-contributhon.adoc
  content/images/post-images/2022-04-contributhon-participants/afi-gbadago.jpg
  content/images/post-images/2022-04-contributhon-participants/catherine-kiiru.jpg
  content/images/post-images/2022-04-contributhon-participants/miracle-ugorji.jpg
  content/images/post-images/2022-04-contributhon-participants/nafeesat-jimoh.jpg
  content/images/post-images/2022-04-contributhon-participants/peace-okafor.jpg
  content/images/post-images/2022-04-contributhon-participants/shecodeafrica-participants.png
  content/images/post-images/2022-04-contributhon-participants/somaa-chukwu.jpg
  content/images/post-images/2022-04-contributhon-participants/sophia-okito.jpg
Labels: blogpost

#5063 Update Jenkins is the Way links
  content/_data/adopters/Anchore.adoc
  content/_data/adopters/Avoris-Travel.adoc
  content/_data/adopters/CERN.adoc
  content/_data/adopters/JDcom.adoc
  content/_data/adopters/KP-Labs.adoc
  content/_data/adopters/Preply.adoc
  content/_data/adopters/Topdanmark.adoc
  content/_data/adopters/Tymit.adoc
  content/_data/adopters/Wright.adoc
  content/_data/indexpage/carousel.yml
  content/_data/logo/jenkins-is-the-way.yml
  content/project/adopters/index.html.haml
Labels: governance, artwork

#5066 add Darin Pope video to java upgrade guide
  content/doc/administration/requirements/upgrade-java-guidelines.adoc
Labels: documentation

#5069 Reorder changelog entries, remove spurious entry
  content/_data/changelogs/weekly.yml
Labels: changelog

#5070 adding video on managing systemd
  content/doc/book/system-administration/systemd-services.adoc
Labels: documentation, squash-merge-me

#5074 [Docs 5375] - Adding Multibranch Video to Jenkins Docs
  content/doc/book/pipeline/multibranch.adoc
Labels: documentation

#5073 [DOCS-5375] adding credentials youtube video to page
  content/doc/book/using/using-credentials.adoc
Labels: documentation

#5078 .github/release-drafter.yml is not required
  content/doc/developer/publishing/releasing-cd.adoc
Labels: documentation

#5077 Update releasing-manually.adoc
  content/doc/developer/publishing/releasing-manually.adoc
Labels: documentation

#5076 Noting that storing AWS credentials is sketchy
  content/doc/book/pipeline/jenkinsfile.adoc
Labels: documentation

#5075 Align icon path -> icon class transition examples
  content/doc/developer/views/icon-path-to-icon-class-migration.adoc
Labels: documentation

#5082 Fix Jenkinsfile Windows example with '%' character
  content/doc/book/pipeline/jenkinsfile.adoc
Labels: documentation

#5085 Use spring framework changelog link
  content/_data/changelogs/weekly.yml
Labels: changelog

#5087 Add information about Stapler debugging flags
  content/doc/book/managing/system-properties.adoc
  content/doc/developer/handling-requests/routing.adoc
  content/doc/developer/views/index.adoc
Labels: documentation

#5090 Added image of a cossack to the artwork gallery
  content/_data/logo/cossack.yml
  content/images/logos/cossack/256.png
  content/images/logos/cossack/cossack.png
  content/images/logos/cossack/cossack.svg
Labels: artwork

#5091 Fixed spelling typo
  content/doc/book/installing/_jenkins-command-parameters.adoc
Labels: documentation

#5094 Use correct destination version in changelog
  content/_data/changelogs/weekly.yml
Labels: changelog

#5088 It's usually called SpringShell
  content/blog/2022/03/2022-03-31-spring-rce-CVE-2022-22965.adoc
  content/images/post-images/2022-03-31-spring-rce-CVE-2022-22965/spring-rce-CVE-2022-22965.png
Labels: blogpost
