Repository jenkins-infra/jenkins.io, pull requests merged in 2022-11, with the labels that each got.

#5618 Jenkins 2.361.3 changelog and upgrade guide
  content/_data/changelogs/lts.yml
  content/_data/upgrades/2-361-3.adoc
Labels: changelog

#5570 Add simple left side navigation list to dev docs to improve layout
  .gitignore
  content/_layouts/developer.html.haml
  content/_layouts/developerbook.html.haml
  content/_layouts/developerchapter.html.haml
  content/_layouts/developerextension.html.haml
  content/_layouts/developerguide.html.haml
  content/_layouts/developersection.html.haml
  content/doc/book/getting-started/index.adoc
  content/doc/book/pipeline/index.adoc
  content/doc/book/scaling/index.adoc
  content/doc/book/system-administration/index.adoc
  content/doc/book/using/index.adoc
  content/doc/developer/architecture/extensions.adoc
  content/doc/developer/architecture/model.adoc
  content/doc/developer/architecture/remoting.adoc
  content/doc/developer/architecture/web.adoc
  content/doc/developer/book.html.haml
  content/doc/developer/cli/writing-cli-commands.adoc
  content/doc/developer/extensibility/action-for-all-projects.adoc
  content/doc/developer/extensibility/serialization-of-anonymous-classes.adoc
  content/doc/developer/guides.html.haml
  content/doc/developer/internationalization/prepare-a-groovy-view.adoc
  content/doc/developer/internationalization/prepare-a-java-source-file.adoc
  content/doc/developer/internationalization/prepare-a-jelly-view.adoc
  content/doc/developer/plugin-development/index.adoc
  content/doc/developer/plugin-development/mark-a-plugin-incompatible.adoc
  content/doc/developer/plugin-development/pipeline-integration.adoc
  content/doc/developer/plugin-development/updating-parent.adoc
  content/doc/developer/plugin-development/writing-an-scm-plugin.adoc
  content/doc/developer/plugin-governance/index.adoc
  content/doc/developer/publishing/new-plugin.adoc
  content/doc/developer/publishing/preparation.adoc
  content/doc/developer/publishing/releasing-cd.adoc
  content/doc/developer/publishing/releasing-experimental-updates.adoc
  content/doc/developer/publishing/releasing-manually.adoc
  content/doc/developer/publishing/releasing.adoc
  content/doc/developer/publishing/removing-from-distribution.adoc
  content/doc/developer/publishing/requesting-hosting.adoc
  content/doc/developer/scheduling/index.adoc
  content/doc/developer/security/csp.adoc
  content/doc/developer/security/form-validation.adoc
  content/doc/developer/security/misc.adoc
  content/doc/developer/security/read-access.adoc
  content/doc/developer/security/remoting-callables.adoc
  content/doc/developer/security/rendering-user-content.adoc
  content/doc/developer/security/scan.adoc
  content/doc/developer/security/secrets.adoc
  content/doc/developer/security/xss-prevention.adoc
  content/doc/developer/security/xss-prevention/Cause-getShortDescription.adoc
  content/doc/developer/tutorial/create.adoc
  content/doc/developer/tutorial/index.adoc
  content/doc/developer/tutorial/prepare.adoc
  content/doc/developer/tutorial/run.adoc
  content/doc/developer/views/exposing-bundled-resources.adoc
  content/doc/developer/views/icon-path-to-icon-class-migration.adoc
  content/doc/developer/views/read-only.adoc
  content/doc/developer/views/symbols.adoc
  content/doc/developer/views/table-to-div-migration.adoc
Labels: hacktoberfest, documentation, hacktoberfest-accepted

#5643 Add Jenkins Related Books section
  content/_data/books/jenkins-the-definitive-guide-continuous_integration_for_the_masses.yml
  content/_data/books/jenkins2-up-and-running.yml
  content/_partials/toptoolbar.html.haml
  content/awards.html.haml
  content/books.html.haml
  content/images/books/jenkins-the-definitive-guide-continuous_integration_for_the_masses.jpeg
  content/images/books/jenkins2-up-and-running.jpeg
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#5651 Update link to artwork
  content/blog/2016/2016-02-06-scale14x-conference-report.adoc
Labels: blogpost

#5637 Jenkins - Update election process content for 2022
  content/project/board-election-process.adoc
Labels: governance

#5588 Jenkins - updating Blue Ocean "Creating Pipelines" text
  content/doc/book/blueocean/creating-pipelines.adoc
Labels: documentation

#5647 More inclusive wording
  content/project/governance.adoc
Labels: governance

#5659 Remove Hacktoberfest 2022 from Jumbotron
  content/_data/indexpage/carousel.yml
Labels: chore

#5658 Add term View
  content/doc/book/glossary/index.adoc
Labels: documentation

#5663 Fix javadoc links for LTS versions
  content/doc/developer/javadoc.html.haml
Labels: documentation

#5662 Jenkins - Add Declarative vs Scripted syntax video
  content/doc/book/pipeline/syntax.adoc
Labels: documentation

#5660 Make headings visible in project idea
  content/projects/gsoc/2022/project-ideas/automating-plugin-buildmetadata-updates.adoc
Labels: gsoc

#5669 Link Updated: Apache Maven Website
  content/doc/developer/tutorial/prepare.adoc
Labels: documentation

#5666 feat(documentation) First draft of the October newsletter.
  content/blog/2022/11/2022-11-04-jenkins-newsletter.adoc
  content/images/post-images/2022-11-04-jenkins-newsletter/image10.png
  content/images/post-images/2022-11-04-jenkins-newsletter/image11.png
  content/images/post-images/2022-11-04-jenkins-newsletter/image5.png
  content/images/post-images/2022-11-04-jenkins-newsletter/image6.png
  content/images/post-images/2022-11-04-jenkins-newsletter/image9.png
Labels: blogpost

#5670 Use most recent spotbugs improvements in tutorial
  content/doc/developer/tutorial-improve/add-more-spotbugs-checks.adoc
Labels: documentation

#5664 Jenkins - Add retry video to "Running Multiple Steps" tour page
  content/doc/pipeline/tour/running-multiple-steps.adoc
Labels: documentation

#5672 Jenkins voter registration group update
  content/blog/2022/10/2022-10-20-jenkins-election-announcement.adoc
  content/project/board-election-process.adoc
Labels: blogpost, governance

#5673 Jenkins newsletter - adding previous editions link
  content/blog/2022/11/2022-11-04-jenkins-newsletter.adoc
  content/images/post-images/2022-11-04-jenkins-newsletter/image12.png
Labels: blogpost

#5675 Add discourse links to newsletters so people can follow up/crosspost to community
  content/blog/2022/10/2022-10-13-jenkins-newsletter.adoc
  content/blog/2022/11/2022-11-04-jenkins-newsletter.adoc
Labels: blogpost

#5676 Simplify enabling dependabot in CD setup
  content/doc/developer/publishing/releasing-cd.adoc
Labels: documentation

#5619 issue#4703 - upgraded haproxy config as per 2.6.6
  content/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-haproxy.adoc
Labels: hacktoberfest, documentation, hacktoberfest-accepted

#5667 chore(helpdesk-3087) switch URL of the pipeline generated steps to reports.jenkins.io
  scripts/fetch-external-resources
Labels: dependencies, chore, documentation

#5677 fix(developer docs) use long flags for `curl` commands in releasing-cd
  content/doc/developer/publishing/releasing-cd.adoc
Labels: documentation

#5682 Jenkins - Update 2.377 changelog entries
  content/_data/changelogs/weekly.yml
Labels: changelog

#5687 Changelog and upgrade guide for 2.361.4
  content/_data/changelogs/lts.yml
  content/_data/changelogs/weekly.yml
  content/_data/upgrades/2-361-4.adoc
Labels: changelog

#5690 GSoC 2023 blog post
  content/blog/2022/11/2022-11-16-gsoc-2023.adoc
  content/projects/gsoc/2023/index.adoc
  content/projects/gsoc/2023/project-ideas.html.haml
  content/projects/gsoc/2023/project-ideas/plugin-installation-manager-tool.adoc
  content/projects/gsoc/2023/project-ideas/prj-idea-template.adoc_text
Labels: gsoc, blogpost

#5702 Use archteype 1.15 in new plugin tutorial
  content/doc/developer/tutorial/create.adoc
Labels: documentation

#5700 Jenkins - adding candidate announcement blog post
  content/blog/2022/11/2022-11-17-jenkins-election-candidates.adoc
Labels: blogpost

#5703 Better URL for the Jenkins Elections results annoucement
  content/blog/2022/11/2022-11-17-jenkins-election-candidates-and-results.adoc
Labels: blogpost

#5685 Jenkins - creating Hacktoberfest recap blog post
  content/blog/2022/11/2022-11-14-hacktoberfest-recap.adoc
  content/images/post-images/2022-11-14-hacktoberfest-recap/kayla.png
  content/images/post-images/2022-11-14-hacktoberfest-recap/krisstern.png
  content/images/post-images/2022-11-14-hacktoberfest-recap/omkar.png
  content/images/post-images/2022-11-14-hacktoberfest-recap/teona.png
Labels: blogpost

#5705 Jenkins - updating hacktoberfest blog post date
  content/blog/2022/11/2022-11-17-hacktoberfest-recap.adoc
Labels: blogpost

#5701 Update GSoC main page for 2023
  content/projects/gsoc/2023/project-ideas.html.haml
  content/projects/gsoc/index.adoc
Labels: gsoc

#5707 Clarify GSoC duration and participation rules
  content/projects/gsoc/index.adoc
Labels: gsoc

#5698 Add JENKINS_HOME path control to war file install instructions
  content/doc/book/installing/war-file.adoc
Labels: documentation

#5436 Update Bootstrap to 5.2, replace Tether with Popper
  Makefile
  content/_layouts/chapter.html.haml
  content/_layouts/frame.html.haml
  content/_layouts/section.html.haml
  content/_partials/_feedback-footer.html
  content/_partials/downloadbanner.html.haml
  content/_partials/dropdown.html.haml
  content/_partials/media.html.haml
  content/_partials/steps.html.haml
  content/_partials/toptoolbar.html.haml
  content/css/jenkins.css
  content/css/roadmap.css
  content/download/index.html.haml
  content/js/blueocean-landing-script.js
  content/js/roadmap.js
  content/project/roadmap/index.html.haml
  content/projects/blueocean/index.html.haml
  package-lock.json
  package.json
Labels: governance, chore, roadmap

#5714 Fix spelling errors
  .typos.toml
  content/blog/2022/11/2022-11-17-hacktoberfest-recap.adoc
  content/doc/book/managing/ui-themes.adoc
  content/project/board-election-process.adoc
  content/security/advisory/2022-10-19.adoc
Labels: blogpost, governance, documentation

#5716 Revert "Update Bootstrap to 5.2, replace Tether with Popper (#5436)"
  Makefile
  content/_layouts/chapter.html.haml
  content/_layouts/frame.html.haml
  content/_layouts/section.html.haml
  content/_partials/_feedback-footer.html
  content/_partials/downloadbanner.html.haml
  content/_partials/dropdown.html.haml
  content/_partials/media.html.haml
  content/_partials/steps.html.haml
  content/_partials/toptoolbar.html.haml
  content/css/jenkins.css
  content/css/roadmap.css
  content/download/index.html.haml
  content/js/blueocean-landing-script.js
  content/js/roadmap.js
  content/project/roadmap/index.html.haml
  content/projects/blueocean/index.html.haml
  package-lock.json
  package.json
Labels: governance, chore, roadmap

#5720 Jenkins 2.379 - update author info
  content/_data/changelogs/weekly.yml
Labels: changelog

#5723 Blog post on efficient GSoC preparation
  content/blog/2022/11/2022-11-23-get-prepared-for-gsoc.adoc
Labels: gsoc, blogpost

#5729 Jenkins - Creating sponsor thanks & appreciation post
  content/blog/2022/11/2022-11-24-jenkins-sponsor-appreciation.adoc
  content/images/post-images/2022-11-24-jenkins-sponsor-appreciation/jenkins-sponsor-thanksgiving.png
  content/images/sponsors/1password.png
  content/images/sponsors/algolia.png
  content/images/sponsors/atlassian.png
  content/images/sponsors/aws.png
  content/images/sponsors/cdf.png
  content/images/sponsors/cloudbees.png
  content/images/sponsors/datadog.png
  content/images/sponsors/digital-ocean.png
  content/images/sponsors/docker.png
  content/images/sponsors/fastly.png
  content/images/sponsors/github.png
  content/images/sponsors/jfrog.png
  content/images/sponsors/linux-foundation.png
  content/images/sponsors/netlify.png
  content/images/sponsors/oracle.png
  content/images/sponsors/pagerduty.png
  content/images/sponsors/rackspace.png
  content/images/sponsors/redhat.png
Labels: blogpost

#5732 Add Jenkins pride logo
  content/_data/logo/pride.yml
  content/images/logos/pride/256.png
  content/images/logos/pride/pride.png
  content/images/logos/pride/pride.svg
Labels: artwork

#5734 fix opengraph image
  content/blog/2022/11/2022-11-24-jenkins-sponsor-appreciation.adoc
Labels: blogpost

#5731 Default to k8s for agent selection in tutorials
  content/doc/developer/publishing/continuous-integration.adoc
  content/doc/developer/tutorial-improve/add-a-jenkinsfile.adoc
Labels: documentation

#5738 Revert "Default to k8s for agent selection in tutorials"
  content/doc/developer/publishing/continuous-integration.adoc
  content/doc/developer/tutorial-improve/add-a-jenkinsfile.adoc
Labels: documentation

#5721 Jenkins 2.375.1 - adding changelog & upgrade guide
  content/_data/changelogs/lts.yml
  content/_data/upgrades/2-375-1.adoc
Labels: changelog

#5748 Fix index page of GSoC2022 archive
  content/projects/gsoc/2022/index.adoc
Labels: gsoc

#5744 Jenkins 2.380 - Weekly changelog update draft
  content/_data/changelogs/weekly.yml
Labels: changelog

#5751 RUN_SCRIPTS is no longer used
  content/doc/book/managing/script-console.adoc
Labels: documentation

#5739 Correct that newer jenkins versions use UTF-8
  content/doc/developer/internationalization/i18n-jelly-views.adoc
Labels: documentation

#5752 Minor 2.375.1 changelog phrasing improvement
  content/_data/changelogs/lts.yml
Labels: changelog

#5747 Document servlet container support
  content/doc/administration/requirements/servlet-containers.adoc
  content/doc/book/installing/_chapter.yml
  content/doc/book/installing/_installation_requirements.adoc
  content/doc/book/installing/index.adoc
  content/doc/book/installing/other.adoc
  content/doc/book/installing/servlet-containers.adoc
  content/doc/book/installing/war-file.adoc
Labels: documentation

#5755 Document Winstone 6.6 changes in 2.375.1 upgrade guide
  content/_data/upgrades/2-375-1.adoc
Labels: changelog
