Repository jenkins-infra/jenkins.io, pull requests merged in 2022-06, with the labels that each got.

#5190 Update GSoC Project page for "Plugin Health Scoring system"
  content/projects/gsoc/2022/projects/plugin-health-scoring-system.adoc
Labels: gsoc

#5192 [DOCS-5646] adding Java 11 requirement info
  content/doc/administration/requirements/java.adoc
Labels: documentation

#5195 Changelog for 2.350
  content/_data/changelogs/weekly.yml
Labels: changelog

#5193 [DOCS-5646] adding in java 11 requirement text
  content/doc/administration/requirements/upgrade-java-guidelines.adoc
  content/doc/pipeline/tour/getting-started.adoc
Labels: documentation

#5198 Add details for Pipeline Steps Doc project
  content/projects/gsoc/2022/projects/pipeline-step-documentation-generator.adoc
Labels: gsoc

#5194 [DOCS-5624] updated POD template screen
  content/doc/book/resources/scaling-jenkins-on-kubernetes/pod-template-configuration.png
Labels: documentation

#5189 [DOCS-5624] update kubernetes plugin screen
  content/doc/book/resources/scaling-jenkins-on-kubernetes/kubernetes-plugin-configuration.png
Labels: documentation

#5187 [DOCS-5624] update multibranch screenshots
  content/doc/book/resources/pipeline/classic-ui-left-column.png
  content/doc/book/resources/pipeline/multibranch-branch-indexing.png
  content/doc/book/resources/pipeline/multibranch-branch-source-configuration.png
  content/doc/book/resources/pipeline/multibranch-branch-source.png
  content/doc/book/resources/pipeline/new-item-multibranch-creation.png
Labels: documentation

#5180 [DOCS-5624] update docker label screenshot
  content/doc/book/resources/pipeline/configure-docker-label.png
Labels: documentation

#5179 [DOCS-5624] update replay screens
  content/doc/book/resources/pipeline/replay-left-bar.png
  content/doc/book/resources/pipeline/replay-previous-run.png
Labels: documentation

#5197 [DOCS-5624] updating security screenshots for new ui
  content/doc/book/resources/security/configure-global-security-matrix-authorization.png
  content/doc/book/resources/security/configure-global-security-prevent-csrf.png
  content/doc/book/resources/security/configure-global-security.png
Labels: documentation

#5200 Added details for Git Cache Maintenance Project
  content/projects/gsoc/2022/projects/automatic-git-cache-maintenance.adoc
Labels: gsoc

#5206 add note about context of script approval
  content/doc/book/managing/script-approval.adoc
Labels: documentation

#5211 add the meeting url for weekly project-specific office hours
  content/projects/gsoc/2022/projects/jenkinsfile-runner-action-for-github-actions.adoc
Labels: gsoc

#5218 Include remoting 3025.vf64a_a_3da_6b_55 in 2.354 changelog
  content/_data/changelogs/weekly.yml
Labels: changelog

#5216 Make GSoC Org Admin runbook writable again
  content/projects/gsoc/index.adoc
Labels: gsoc

#5213 [DOCS-5624] update language example
  content/doc/book/resources/using/jenkins-in-italian.png
Labels: documentation

#5220 ignore recommendations for API plugins
  content/doc/developer/plugin-development/choosing-jenkins-baseline.adoc
Labels: documentation

#5223 Fix multibranch pipeline tutorial
  content/doc/book/installing/_docker-for-tutorials.adoc
  content/doc/book/installing/_docker.adoc
Labels: documentation

#5224 Replace working jenkinsistheway.io links with stories.jenkins.io
  content/_data/adopters/Avoris-Travel.adoc
  content/_data/adopters/KP-Labs.adoc
  content/blog/2020/04/2020-04-30-jenkins-is-the-way.adoc
  content/blog/2020/05/2020-05-12-uiux-hackfest-announcement.adoc
  content/blog/2020/10/2020-10-20-Cross-Industry-DevOps-3-Firms-Get-It-Right-with-Jenkins.adoc
  content/blog/2020/12/2020-12-03-election-results.adoc
  content/blog/2020/12/2020-12-05-3-Cases-Jenkins-Success-stories-from-the-community.adoc
  content/blog/2021/01/2021-01-12-new-year-report.adoc
  content/blog/2021/01/2021-01-26-new-ebook-build-deploy-and-automate-great-stuff-with-jenkins.adoc
  content/blog/2021/06/2021-06-10-jenkins-is-the-way-ebook-2.adoc
  content/blog/2021/09/2021-09-22-fortune-500-real-world-results.adoc
  content/blog/2022/01/2022-01-14-happy-new-year.adoc
  content/events/online-hackfest/2020-uiux/index.adoc
  content/project/adopters/contributing.adoc
Labels: blogpost, governance

#5229 Correctly tag allowUnsupportedRemotingVersions escape hatch
  content/doc/book/managing/system-properties.adoc
Labels: documentation

#5230 Create 2022-07-28-los-angels.adoc
  content/_data/events/2022-07-28-los-angeles.adoc
Labels: events

#5231 Add DevOps World 2022 event Sep 26, 2022
  content/_data/events/2022-06-09-contributor-summit.adoc
  content/_data/events/2022-07-28-los-angeles.adoc
  content/_data/events/2022-09-26-devops-world-2022.adoc
Labels: events

#5232 Add Contributor Summit event at DevOps World Sep 27, 2022
  CONTRIBUTING.adoc
  content/_data/events/2022-09-27-contributor-summit.adoc
Labels: events

#5151 2.346.1 LTS changelog & upgrade guide
  content/_data/changelogs/lts.yml
  content/_data/changelogs/weekly.yml
  content/_data/upgrades/2-346-1.adoc
Labels: changelog

#5201 [DOCS-5639] SVG migration blog post
  content/blog/2022/06/2022-06-20-svg-icon-migration.adoc
  content/images/post-images/2022-06-svg-migration/2022-06-svg-migration.png
  content/images/post-images/2022-06-svg-migration/abandoned-plugin.png
Labels: blogpost, documentation

#5235 [DOCS-5691] updating jenkins on java 11 links
  content/_data/upgrades/2-164-1.adoc
  content/blog/2018/06/2018-06-17-running-jenkins-with-java10-11.adoc
  content/blog/2018/12/2018-12-14-java11-preview-availability.adoc
  content/blog/2019/03/2019-03-11-let-s-celebrate-java-11-support.adoc
  content/doc/administration/requirements/jenkins-on-java-11.adoc
  content/doc/administration/requirements/upgrade-java-guidelines.adoc
Labels: blogpost, changelog, documentation

#5241 Update changelog to describe packaging changes
  content/_data/changelogs/lts.yml
  content/_data/upgrades/2-346-1.adoc
Labels: changelog

#5253 Remove suggestion for PEM encoded certs
  content/doc/book/installing/_jenkins-command-parameters.adoc
Labels: documentation

#5252 Remove incorrect documentation about certificates
  content/doc/book/installing/_jenkins-command-parameters.adoc
Labels: documentation

#5215 [DOCS-5691] update jenkins parameters
  content/doc/book/installing/_jenkins-command-parameters.adoc
Labels: documentation

#5234 [DOCS-5689] Updating Tutorial screenshots
  content/doc/book/resources/pipeline/classic-ui-left-column.png
  content/doc/developer/building/intellij.adoc
  content/doc/pipeline/tour/hello-world.adoc
  content/images/developer/building/intellij/build2.png
Labels: documentation

#5256 Remove reference to install-plugins.sh
  content/doc/book/installing/offline.adoc
Labels: documentation

#5259 Fix remoting reference for LTS
  content/_data/changelogs/lts.yml
Labels: changelog

#5260 [JEP-236] [JENKINS-68570] Require Java 11 or newer
  content/blog/2022/06/2022-06-28-require-java-11.adoc
  content/images/post-images/2022-06-require-java-11/jenkins-requires-java-11.png
  content/images/post-images/2022-06-require-java-11/jvms.png
Labels: blogpost

#5261 more java 8 removal
  content/doc/administration/requirements/java.adoc
  content/doc/administration/requirements/upgrade-java-guidelines.adoc
  content/doc/book/installing/_jenkins-command-parameters.adoc
  content/doc/pipeline/tour/getting-started.adoc
Labels: documentation

#5265 [JEP-230] Modules now of historical interest only
  content/doc/developer/plugin-development/dependencies-and-class-loading.adoc
Labels: documentation

#5266 Governance meeting moves to Monday
  content/project/governance-meeting/index.adoc
Labels: governance
