Repository jenkins-infra/jenkins.io, pull requests merged in 2022-10, with the labels that each got.

#5524 Fix: Broken links to documentation model
  CONTRIBUTING.adoc
Labels: hacktoberfest

#5523 Extend agent and related glossary entries with links to documentation sections
  content/doc/book/glossary/index.adoc
Labels: hacktoberfest, documentation

#5498 Guide minikube users to community forum for issues
  content/doc/book/installing/kubernetes.adoc
Labels: documentation

#5528 Update create a plugin tutorial to use latest archetype version
  content/doc/developer/tutorial/create.adoc
Labels: documentation

#5529 Use Rouge as syntax highlighter
  Gemfile
  Gemfile.lock
  content/_config/site.yml
  content/doc/pipeline/examples.html.haml
  content/stylesheets/components/_all.scss
  content/stylesheets/components/_code-highlight.scss
  content/stylesheets/pages/_post.scss
Labels: chore, documentation

#5536 Fix: Broken Link Pipelines/ Getting Started
  content/doc/book/glossary/index.adoc
Labels: documentation

#5538 Add test timeout example
  content/doc/developer/testing/index.adoc
Labels: documentation

#5532 Clarified allowed HOOK values
  content/doc/book/managing/groovy-hook-scripts.adoc
Labels: documentation

#5533 Fixed Issue 3650
  content/doc/pipeline/tour/hello-world.adoc
Labels: documentation

#5542 Fixed a text in build-a-python-app-with-pyinstaller.adoc
  content/doc/tutorials/build-a-python-app-with-pyinstaller.adoc
Labels: documentation

#5521 feat(blog) First draft of the new AWS post.
  content/_data/authors/xparticle.adoc
  content/blog/2022/10/2022-10-03-scaling-out-iOS-builds-on-AWS-with-EC2-mac.adoc
  content/images/avatars/xparticle.png
  content/images/post-images/2022-09-30-scaling-out-iOS-builds-on-AWS-with-EC2-mac/image1.png
  content/images/post-images/2022-09-30-scaling-out-iOS-builds-on-AWS-with-EC2-mac/image2.png
  content/images/post-images/2022-09-30-scaling-out-iOS-builds-on-AWS-with-EC2-mac/image3.png
  content/images/post-images/2022-09-30-scaling-out-iOS-builds-on-AWS-with-EC2-mac/image4.png
  content/images/post-images/2022-09-30-scaling-out-iOS-builds-on-AWS-with-EC2-mac/image5.png
  content/images/post-images/2022-09-30-scaling-out-iOS-builds-on-AWS-with-EC2-mac/image6.png
Labels: blogpost

#5540 Address reported issues with hello world tutorial
  content/doc/pipeline/tour/hello-world.adoc
Labels: hacktoberfest, documentation, hacktoberfest-accepted

#5530 Add 2021 Hacktoberfest link, update 2020 link
  content/events/hacktoberfest.adoc
Labels: hacktoberfest

#5544 Remove requirement for docker label
  content/doc/pipeline/tour/hello-world.adoc
Labels: documentation

#5545 update plugin build step
  content/doc/developer/publishing/continuous-integration.adoc
Labels: documentation

#5546 typo fix: Load --> Loads
  content/doc/developer/publishing/documentation.adoc
Labels: documentation

#5551 Update documentation on themes
  content/doc/book/managing/ui-themes.adoc
Labels: documentation

#5471 LTS 2.361.2 add changelog and upgrade guide
  content/_data/changelogs/lts.yml
  content/_data/upgrades/2-361-2.adoc
Labels: changelog

#5552 add Nerd Jenkins logo
  content/_data/logo/nerd.yml
  content/images/logos/nerd/256.png
  content/images/logos/nerd/nerd.png
  content/images/logos/nerd/nerd.svg
Labels: hacktoberfest, artwork

#5553 add Turkish Jenkins logo
  content/_data/logo/turkey.yml
  content/images/logos/turkey/256.png
  content/images/logos/turkey/Turkey.png
  content/images/logos/turkey/Turkey.svg
Labels: hacktoberfest, artwork

#5558 add explanations for `403 Forbidden`
  content/doc/developer/publishing/releasing-cd.adoc
Labels: documentation

#5564 Changed the redirect link in linux.adoc
  content/doc/administration/requirements/linux.adoc
Labels: documentation

#5556 Improve CSP docs
  content/doc/developer/security/csp.adoc
  content/doc/developer/views/index.adoc
Labels: documentation

#5565 Changed the redirect link for `plugins site` in requesting-hosting.adoc
  content/doc/developer/publishing/requesting-hosting.adoc
Labels: documentation

#5566 Remove ppc64le from roadmap and example platforms
  content/_data/roadmap/roadmap.yml
  content/doc/administration/requirements/linux.adoc
Labels: documentation, roadmap

#5567 Extend description of global vars in pipeline
  content/doc/book/pipeline/shared-libraries.adoc
Labels: documentation

#5569 Added youtube link
  content/doc/book/pipeline/jenkinsfile.adoc
Labels: documentation

#5572 Add troubleshooting steps for missing Local Security Policy on Windows Home
  content/doc/book/installing/windows.adoc
Labels: documentation

#5440 Dheeraj's GSoC blog
  content/_data/authors/dheerajodha.adoc
  content/blog/2022/10/2022-10-10-plugin-health-scoring-system-report.adoc
  content/images/gsoc/2022/plugin-health-score/introducing-the-plugin-health-scoring-system.png
Labels: do not merge, blogpost

#5550 Added blog for Vihaan's GSoC project
  content/_data/authors/vihaanthora.adoc
  content/blog/2022/10/2022-10-10-pipeline-steps-improvement-gsoc-report.adoc
  content/images/avatars/vihaanthora.jpg
Labels: blogpost

#5575 Document `--paramsFromStdIn`
  content/doc/book/installing/_jenkins-command-parameters.adoc
Labels: documentation

#5577 Updated broken link
  content/blog/2020/03/2020-03-17-ui-plugins.adoc
Labels: blogpost

#5579 Updated broken link for github olivergondza
  content/blog/2019/12/2019-12-16-board-election-results.adoc
Labels: blogpost

#5580 updated link to microsoft reactor space
  content/blog/2016/2016-05-12-sf-jam-jenkins-and-azure.adoc
Labels: blogpost

#5576 Removed broken link to community tracks
  content/blog/2016/2016-08-10-rails-cd-with-pipeline.adoc
Labels: blogpost

#5584 Jenkins 2.373 - make edits for weekly changelog
  content/_data/changelogs/weekly.yml
Labels: changelog

#5585 Remove dashes from changelog entries of 2.373
  content/_data/changelogs/weekly.yml
Labels: changelog

#5574 #Hacktoberfest: Fixed issue 5376 to improve AWS security group documentation
  content/doc/tutorials/tutorial-for-installing-jenkins-on-AWS.adoc
Labels: documentation

#5587 Add anchor for ip address step in AWS tutorial
  content/doc/tutorials/tutorial-for-installing-jenkins-on-AWS.adoc
Labels: documentation

#5589 chore: Use a modern baseline for CD sample
  content/doc/developer/publishing/releasing-cd.adoc
Labels: documentation

#5591 Updated CD setup instructions
  content/doc/developer/publishing/releasing-cd.adoc
Labels: documentation

#5590 Jenkins newsletter September 2022
  content/blog/2022/10/2022-10-13-jenkins-newsletter.adoc
  content/images/post-images/2022-10-13-jenkins-newsletter/image1.png
  content/images/post-images/2022-10-13-jenkins-newsletter/image2.png
  content/images/post-images/2022-10-13-jenkins-newsletter/image3.png
  content/images/post-images/2022-10-13-jenkins-newsletter/image5.png
  content/images/post-images/2022-10-13-jenkins-newsletter/image6.png
  content/images/post-images/2022-10-13-jenkins-newsletter/image7.png
Labels: blogpost

#5593 Jenkins Blog: remove unnecessary text
  content/blog/2022/10/2022-10-13-jenkins-newsletter.adoc
Labels: blogpost

#5595 Updating "jenkins.ui.refresh" due to removal
  content/doc/book/managing/system-properties.adoc
Labels: documentation

#5596 chore(version dependency): some may need to upgrade the version too
  content/doc/developer/tutorial-improve/update-base-jenkins-version.adoc
Labels: documentation

#5597 chore(reviewers): use github handle as reviewer name
  content/doc/developer/tutorial-improve/automate-dependency-update-checks.adoc
Labels: documentation

#5600 [WEBSITE-751] Issue #3335 Groovy Remote Control
  content/doc/book/managing/script-console.adoc
Labels: documentation

#5598 Jenkins Blog: attempt to update opengraph image
  content/blog/2022/10/2022-10-13-jenkins-newsletter.adoc
  content/images/post-images/2022-10-13-jenkins-newsletter/centered-newsletter.png
Labels: blogpost

#5599 Add notice what to do if you do not get email
  content/doc/developer/publishing/preparation.adoc
Labels: hacktoberfest, documentation

#5603 add minimum apache maven info to IntelliJ setup
  content/doc/developer/building/intellij.adoc
Labels: documentation

#5611 Jenkins 2.374 - updating weekly changelog
  content/_data/changelogs/weekly.yml
Labels: changelog

#5612 Update RSS icon matching core changes
  content/images/changelog/feed-icon.svg
Labels: changelog

#5568 Update weather icons to match Jenkins
  content/images/changelog/cloudy.svg
  content/images/changelog/storm.svg
  content/images/changelog/sunny.svg
Labels: changelog

#5614 Fixed broken extension link
  content/doc/developer/extensibility/index.adoc
Labels: hacktoberfest, documentation

#5615 Jenkins: 2022 Election Announcement blog post
  content/blog/2022/10/2022-10-20-jenkins-election-announcement.adoc
  content/images/governance/elections/2022/2022-opengraph.png
Labels: blogpost

#5621 Fix several typos in the documentation
  content/doc/book/managing/script-console.adoc
  content/doc/book/system-administration/systemd-services.adoc
  content/doc/book/using/using-credentials.adoc
  content/doc/developer/forms/structured-form-submission.adoc
  content/doc/developer/persistence/incompatible-releases.adoc
  content/doc/developer/tutorial-improve/add-more-spotbugs-checks.adoc
  content/doc/tutorials/create-a-pipeline-in-blue-ocean.adoc
  content/doc/tutorials/tutorial-for-installing-jenkins-on-AWS.adoc
Labels: documentation

#5601 Update Git Cache Maintenance Blog page
  content/projects/gsoc/2022/projects/automatic-git-cache-maintenance.adoc
Labels: gsoc

#5624 Correct CoC link
  content/project/conduct.adoc
Labels: governance

#5625 Revert "Modularise more classes + increase usage of CSS variables (#5…
  content/_partials/projectcarousel.html.haml
  content/css/jenkins.css
  content/index.html.haml
  content/solutions/index.html.haml
  content/stylesheets/core/_all.scss
  content/stylesheets/core/_base.scss
  content/stylesheets/core/_headings.scss
  content/stylesheets/pages/_all.scss
  content/stylesheets/pages/_use-cases.scss
Labels: documentation

#5613 Updated the extensions section
  content/doc/developer/architecture/extensions.adoc
Labels: hacktoberfest, documentation

#5631 Publish changelog for 2.375
  content/_data/changelogs/weekly.yml
Labels: changelog

#5635 Jenkins- Update formatting for election process page
  content/project/board-election-process.adoc
Labels: governance

#5634 Remove server-specific reverse proxy pages from ToC
  content/_ext/handbook.rb
  content/_ext/pipeline.rb
  content/_layouts/subsection.html.haml
  content/_layouts/subsectiondocumentation.html.haml
  content/doc/book/system-administration/_chapter.yml
  content/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/_section.yml
  content/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/index.adoc
  content/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-apache.adoc
  content/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-haproxy.adoc
  content/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-iis.adoc
  content/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-iptables.adoc
  content/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-nginx.adoc
  content/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-squid.adoc
Labels: hacktoberfest, documentation, hacktoberfest-accepted

#5638 Add space to make bold work
  content/doc/book/managing/about-jenkins.adoc
Labels: hacktoberfest, documentation, hacktoberfest-accepted

#5636 Edit intro to Blue Ocean to reflect new status
  content/doc/book/blueocean/index.adoc
Labels: hacktoberfest, documentation, hacktoberfest-accepted

#5629 updated Jenkins on AWS tutorial documentation
  content/doc/book/resources/tutorials/AWS/add_access_secret_access_keys.png
  content/doc/book/resources/tutorials/AWS/configure_cloud_add_ec2_credentials.png
  content/doc/book/resources/tutorials/AWS/configure_cloud_region_private_key.png
  content/doc/book/resources/tutorials/AWS/ec2_choose_ami.png
  content/doc/book/resources/tutorials/AWS/ec2_review_instance_launch.png
  content/doc/book/resources/tutorials/AWS/enter_private_key.png
  content/doc/book/resources/tutorials/AWS/jenkins_credentials_provider_aws_credentials.png
  content/doc/book/resources/tutorials/AWS/private_key_enter_directly.png
  content/doc/book/resources/tutorials/AWS/ssh_username.png
  content/doc/book/resources/tutorials/AWS/test_connection.png
  content/doc/tutorials/tutorial-for-installing-jenkins-on-AWS.adoc
Labels: hacktoberfest, documentation, hacktoberfest-accepted

#5548 Updated kubernetes.adoc with latest implementation method as the previous one was outdated.
  content/doc/book/installing/kubernetes.adoc
Labels: hacktoberfest, documentation, hacktoberfest-accepted
