Repository jenkins-infra/jenkins.io, pull requests merged in 2022-12, with the labels that each got.

#5759 Use 2.361.4 as jenkins.version in tutorials and guides
  content/doc/developer/publishing/releasing-cd.adoc
  content/doc/developer/tutorial-improve/update-base-jenkins-version.adoc
  content/doc/developer/tutorial-improve/use-plugin-bill-of-materials.adoc
Labels: documentation

#5753 Document how to use agents in tests
  content/doc/developer/testing/index.adoc
Labels: documentation

#5762 Add Winstone 6.5 and 6.6 to 2.375.1 changelog
  content/_data/changelogs/lts.yml
Labels: changelog

#5765 Add details on dependabot auto labeling config
  content/doc/developer/tutorial-improve/automate-dependency-update-checks.adoc
Labels: documentation

#5768 Remove irrelevant auto-tagging comments
  content/doc/developer/tutorial-improve/automate-dependency-update-checks.adoc
Labels: documentation

#5770 Create "GSoC - the gift of mentorship" blog post
  content/blog/2022/12/2022-12-09-GSoC-the-gift-of-mentorship.adoc
  content/images/gsoc/Merry_Mentor.png
Labels: gsoc, blogpost

#5769 blog: add a new post about 2022-12 jfrog maintenance with downtime
  content/blog/2022/12/2022-12-09-jfrog-maintenance.adoc
Labels: blogpost

#5774 Jenkins - Updating Jenkinsfile configuration sample
  content/doc/developer/publishing/continuous-integration.adoc
  content/doc/developer/tutorial-improve/add-a-jenkinsfile.adoc
Labels: documentation

#5775 Jenkins - Update to CloudBees logo in thanksgiving blog post
  content/blog/2022/11/2022-11-24-jenkins-sponsor-appreciation.adoc
Labels: blogpost

#5781 feat(developers doc) clarify how to use 'docker' for plugin tests
  content/doc/developer/publishing/continuous-integration.adoc
  content/doc/developer/tutorial-improve/add-a-jenkinsfile.adoc
Labels: documentation

#5782 Clarify that the thin-backup plugin is being maintained
  content/doc/book/system-administration/backing-up.adoc
Labels: documentation

#5787 Fix 3 broken links
  content/blog/2020/01/2020-01-29-gsoc-report.adoc
  content/doc/book/system-administration/backing-up.adoc
Labels: blogpost, documentation

#5789 fix: correct helpdesk issue link in crowdin-integration.adoc
  content/doc/developer/crowdin/crowdin-integration.adoc
Labels: documentation

#5788 fix: correct helpdesk issue link in managing-permissions.adoc
  content/doc/developer/plugin-governance/managing-permissions.adoc
Labels: documentation

#5790 Remove "build metadata" GSoC Project idea
  content/projects/gsoc/2023/project-ideas/automating-plugin-buildmetadata-updates.adoc
Labels: gsoc

#5786 Update deprecating-or-removing-plugin.adoc
  content/doc/developer/plugin-governance/deprecating-or-removing-plugin.adoc
Labels: documentation

#5791 Require Java 11 or newer for plugin development
  content/blog/2022/12/2022-12-14-require-java-11.adoc
  content/images/post-images/2022-12-require-java-11/jvms.png
Labels: blogpost

#5794 Move Hacktoberfest 2022 to completed on roadmap
  content/_data/roadmap/roadmap.yml
  content/events/hacktoberfest.adoc
Labels: roadmap

#5815 Update docker-builder to 2.1.41
  .node-version
  .ruby-version
  Dockerfile
  Gemfile.lock
  Jenkinsfile_k8s
  scripts/node
  scripts/ruby
Labels: chore

#5817 Update faraday components
  Gemfile
  Gemfile.lock
Labels: chore

#5783 feat(documentation) Better describes the docker-compose project for GSoC 2023
  content/projects/gsoc/2023/project-ideas/docker-compose-build.adoc
Labels: gsoc

#5780 feat(documentation) Moves Plugin Health Score to "Published"
  content/projects/gsoc/2023/project-ideas/add-probes-to-plugin-health-score.adoc
Labels: gsoc

#5823 Fix a few typos highlighted by the typo checker
  .typos.toml
  Jenkinsfile
  content/blog/2022/11/2022-11-23-get-prepared-for-gsoc.adoc
  content/projects/gsoc/2023/project-ideas/add-probes-to-plugin-health-score.adoc
  content/security/reporting.adoc
Labels: gsoc, blogpost, chore

#5822 Bump asciidoc to 2.0.18
  Gemfile
  Gemfile.lock
Labels: chore

#5824 Keep the typo check step up to date
  .typos.toml
  Jenkinsfile
  content/_partials/changelog-old.html
  content/blog/2011/2011-05-12-ruby-plugins-hack-session-5-12-2011.adoc
  content/security/advisory/2018-05-09.adoc
Labels: blogpost, chore, changelog

#5821 Bump node to 18.x
  .node-version
  Dockerfile
  Jenkinsfile_k8s
  renovate.json
  scripts/node
Labels: chore

#5820 Bump rubyzip to 2.3.2
  Gemfile
  Gemfile.lock
Labels: chore

#5826 Update a few NPM dependencies
  package-lock.json
  package.json
Labels: chore

#5819 Bump liquid to 5.4.0
  Gemfile
  Gemfile.lock
Labels: chore

#5828 Update bundler version
  Gemfile.lock
Labels: chore

#5830 Create 2023-03-09-pasadena.adoc
  content/_data/events/2023-03-09-pasadena.adoc
Labels: events

#5831 Update Blue Ocean, Pipeline Groovy, and Maven in tutorials
  content/doc/book/installing/_docker-for-tutorials.adoc
  content/doc/book/installing/_docker.adoc
  content/doc/book/pipeline/docker.adoc
  content/doc/book/pipeline/syntax.adoc
  content/doc/tutorials/build-a-java-app-with-maven.adoc
Labels: documentation

#5833 Adding agent_reconnection_exponential_backoff project as draft
  content/projects/gsoc/2023/project-ideas/agent_reconnections_exponential_backoff.adoc
Labels: gsoc

#5837 remove extra asterisk
  content/_data/changelogs/weekly.yml
  content/doc/book/scaling/architecting-for-manageability.adoc
Labels: changelog, documentation

#5838 Promoting GSoC project from "discussion" to "draft"
  content/projects/gsoc/2023/project-ideas/buiilding-android-app.adoc
  content/projects/gsoc/2023/project-ideas/buiilding-ios-app.adoc
Labels: gsoc

#5836 Add "GitLab plugin modernization" as GSoC project idea
  content/projects/gsoc/2023/project-ideas.html.haml
  content/projects/gsoc/2023/project-ideas/gitlab-plugin-modernization.adoc
Labels: gsoc

#5628 feat(documentation) Adding a few screenshots to illustrate "Performing a Plugin Release manually"
  content/doc/developer/publishing/releasing-manually.adoc
  content/images/developer/publishing/artifactory-login.png
  content/images/developer/publishing/artifactory-set-me-up.png
  content/images/developer/publishing/download-snippet.png
  content/images/developer/publishing/generate-settings.png
  content/images/developer/publishing/generated-xml.png
  content/images/developer/publishing/select-maven.png
  content/images/developer/publishing/unlock.png
Labels: documentation

#5366 seems to be fixed
  content/doc/book/using/using-agents.adoc
Labels: documentation

#5847 Add berviantoleo as a mentor
  content/_data/authors/berviantoleo.adoc
  content/images/avatars/berviantoleo.jpg
  content/projects/gsoc/2023/project-ideas/docker-compose-build.adoc
Labels: gsoc

#5846 Switch to faraday 2.x
  Gemfile
  Gemfile.lock
  scripts/fetch-external-resources
  scripts/release.rss.rb
Labels: chore

#5841 updated the title for better search results
  content/doc/developer/publishing/continuous-integration.adoc
Labels: documentation

#5754 feat(documentation) Adds a blog post about running a Jenkins agent as a service
  content/blog/2022/12/2022-12-27-run-jenkins-agent-as-a-service.adoc
  content/images/post-images/2022-12-02-run-jenkins-agent-as-a-service/java-command-to-launch-the-agent.png
  content/images/post-images/2022-12-02-run-jenkins-agent-as-a-service/manage-nodes-and-clouds.png
  content/images/post-images/2022-12-02-run-jenkins-agent-as-a-service/new-node-looks-fine.png
  content/images/post-images/2022-12-02-run-jenkins-agent-as-a-service/new-node.png
  content/images/post-images/2022-12-27-run-jenkins-agent-as-a-service/curl-and-java-launch-agent.svg
Labels: blogpost

#5849 added reference link to docs about agents
  content/doc/book/scaling/architecting-for-scale.adoc
Labels: documentation

#5852 Document removal of '--daemon' flag
  content/_data/changelogs/weekly.yml
Labels: changelog

#5853 Add iamrajiv as a mentor
  content/_data/authors/iamrajiv.adoc
  content/images/avatars/iamrajiv.jpg
  content/projects/gsoc/2023/project-ideas/alternative-jenkinsio-build-tool.adoc
Labels: gsoc

#5857 Use same maven in tutorial as is used elsewhere
  content/doc/pipeline/tour/hello-world.adoc
Labels: documentation
