Repository jenkins-infra/jenkins.io, pull requests merged in 2022-09, with the labels that each got.

#5403 Better link to file new issue
  content/doc/book/pipeline/cps-method-mismatches.adoc
Labels: documentation

#5410 Remove Java 17 preview page
  content/blog/2022/03/2022-03-21-java17-preview-availability.adoc
  content/doc/administration/requirements/jenkins-on-java-17.adoc
Labels: blogpost, documentation

#5414 Fix the Jenkins Board and Officers page
  content/_partials/community-role-holder.html.haml
  content/project/board.html.haml
  content/stylesheets/components/_author.scss
Labels: governance

#5420 Rephrase Java version requirements for Maven Plugin etc.
  content/doc/administration/requirements/java.adoc
Labels: documentation

#5417 governance should own plugin governance
  .github/CODEOWNERS
Labels: chore

#5416 Make explicit that abandoned plugins with no maintainers can be adopt…
  content/doc/developer/plugin-governance/adopt-a-plugin.adoc
Labels: documentation

#5415 Modularise more classes + increase usage of CSS variables
  content/_partials/projectcarousel.html.haml
  content/css/jenkins.css
  content/index.html.haml
  content/solutions/index.html.haml
  content/stylesheets/core/_all.scss
  content/stylesheets/core/_base.scss
  content/stylesheets/core/_headings.scss
  content/stylesheets/pages/_all.scss
  content/stylesheets/pages/_use-cases.scss
Labels: documentation

#5422 Update run.adoc
  content/doc/developer/tutorial/run.adoc
Labels: documentation

#5425 Remove java.level property from examples
  content/doc/developer/persistence/incompatible-releases.adoc
  content/doc/developer/plugin-development/mark-a-plugin-incompatible.adoc
Labels: documentation

#5402 Add Yiming's GSoC blog
  content/_data/authors/YimingGong.adoc
  content/blog/2022/09/2022-09-07-jenkinsfile-runner-as-github-actions.adoc
Labels: blogpost

#5370 LTS 2.361.1 changelog & upgrade guide
  content/_data/changelogs/lts.yml
  content/_data/upgrades/2-361-1.adoc
Labels: changelog

#5428 Update Pipeline steps project page
  content/projects/gsoc/2022/projects/pipeline-step-documentation-generator.adoc
Labels: gsoc

#5423 Update jenkinsfile-runner github actions project page for GSoC submission
  content/projects/gsoc/2022/projects/jenkinsfile-runner-action-for-github-actions.adoc
Labels: gsoc

#5409 [JENKINS-68565] removing Java 8 from user docs
  content/doc/administration/requirements/java.adoc
  content/doc/administration/requirements/upgrade-java-guidelines.adoc
  content/doc/book/installing/_jenkins-command-parameters.adoc
  content/doc/pipeline/tour/getting-started.adoc
Labels: documentation

#5429 Minor grammar fix in CSP doc
  content/doc/developer/security/csp.adoc
Labels: documentation

#5437 More verbose description of finding backup plugins
  content/doc/book/system-administration/backing-up.adoc
Labels: documentation

#5439 changed .net to .io for https://htmlunit.sourceforge.io/
  content/doc/developer/testing/index.adoc
Labels: documentation

#5443 Remove leading dash from changelog entry
  content/_data/changelogs/weekly.yml
Labels: changelog

#5441 feat(blog) Add a blog post about Jenkins Contributor Summit at DevOps…
  content/blog/2022/09/2022-09-13-jenkins-contributor-summit-2022-agenda-orlando-florida.adoc
Labels: blogpost

#5444 Update references to the recently renamed IntelliJ IDEA plugin
  content/doc/developer/development-environment/ide-configuration.adoc
  content/doc/developer/tutorial/prepare.adoc
Labels: documentation

#5445 Contributor summit aws blog post
  content/_data/authors/glenduca.adoc
  content/_data/authors/kursonsk.adoc
  content/blog/2022/09/2022-09-14-create-iOS-unity-build-pipelines-on-AWS-with-Jenkins-and-EC2-Mac-instances.adoc
  content/images/avatars/glenduca.jpg
  content/images/avatars/kursonsk.jpg
  content/images/post-images/2022-09-14-Create-iOS-Unity-build-pipelines/image1.png
  content/images/post-images/2022-09-14-Create-iOS-Unity-build-pipelines/image10.png
  content/images/post-images/2022-09-14-Create-iOS-Unity-build-pipelines/image11.png
  content/images/post-images/2022-09-14-Create-iOS-Unity-build-pipelines/image2.png
  content/images/post-images/2022-09-14-Create-iOS-Unity-build-pipelines/image3.png
  content/images/post-images/2022-09-14-Create-iOS-Unity-build-pipelines/image4.png
  content/images/post-images/2022-09-14-Create-iOS-Unity-build-pipelines/image5.png
  content/images/post-images/2022-09-14-Create-iOS-Unity-build-pipelines/image6.png
  content/images/post-images/2022-09-14-Create-iOS-Unity-build-pipelines/image7.png
  content/images/post-images/2022-09-14-Create-iOS-Unity-build-pipelines/image8.png
  content/images/post-images/2022-09-14-Create-iOS-Unity-build-pipelines/image9.png
Labels: blogpost

#5447 Add hacktoberfest 2022 announcement blog post
  content/blog/2022/09/2022-09-15-preptember.adoc
  content/events/hacktoberfest.adoc
  content/events/hacktoberfest/event-kit.adoc
  content/events/hacktoberfest/faq.adoc
  content/images/hacktoberfest/hacktoberfest_2022.svg
Labels: hacktoberfest, blogpost, events

#5449 fix(blog) First try at getting collapsible source code.
  content/blog/2022/09/2022-09-14-create-iOS-unity-build-pipelines-on-AWS-with-Jenkins-and-EC2-Mac-instances.adoc
Labels: blogpost

#5451 Added links
  content/blog/2022/09/2022-09-14-create-iOS-unity-build-pipelines-on-AWS-with-Jenkins-and-EC2-Mac-instances.adoc
Labels: blogpost

#5452 Use site local links
  content/blog/2022/09/2022-09-14-create-iOS-unity-build-pipelines-on-AWS-with-Jenkins-and-EC2-Mac-instances.adoc
Labels: blogpost

#5461 Resolves #5456 - Add a "Kubernetes" entry to the glossary
  content/doc/book/glossary/index.adoc
Labels: documentation

#5459 [DOCS-5907] Updating blue ocean dashboard page
  content/doc/book/blueocean/dashboard.adoc
Labels: documentation

#5460 Resolves #5453 - Remove the Appendix page - empty and will remain empty
  content/doc/book/_book.yml
  content/doc/book/appendix/_chapter.yml
  content/doc/book/appendix/index.adoc
Labels: documentation

#5462 Resolves #5455 - Link from "Step" glossary entry to Pipeline pages
  content/doc/book/glossary/index.adoc
Labels: documentation

#5463 Use latest blue ocean and docker workflow plugins in tutorial
  content/doc/book/installing/_docker-for-tutorials.adoc
  content/doc/book/installing/_docker.adoc
Labels: documentation

#5464 Use node:lts-alpine in tutorial
  content/doc/book/installing/_docker-for-tutorials.adoc
  content/doc/tutorials/build-a-multibranch-pipeline-project.adoc
Labels: documentation

#5465 Fix GitHub capitalization
  content/blog/2022/09/2022-09-15-preptember.adoc
Labels: blogpost

#5468 [WEBSITE-728] Remove wiki references from governance document
  content/project/governance.adoc
Labels: governance

#5470 Java 8 - fixed case for admonition title
  content/doc/administration/requirements/java.adoc
Labels: documentation

#5448 [DOCS 6486] - Adding DigitalOcean sponsorship blog post
  content/blog/2022/09/2022-09-19-digital-ocean-sponsorship.adoc
  content/images/post-images/2022-09-19-digital-ocean-sponsorship/DO-horizontal.png
  content/images/post-images/2022-09-19-digital-ocean-sponsorship/DO_Logo_Vertical_Blue.png
Labels: blogpost

#5458 Update Project Page Automatic Git Cache Maintenance.
  content/_data/authors/HrushikeshRao.adoc
  content/images/avatars/HrushikeshRao.jpeg
  content/images/post-images/gsoc-git-cache-maintenance/architecture-diagram.png
  content/images/post-images/gsoc-git-cache-maintenance/maintenance-config.png
  content/images/post-images/gsoc-git-cache-maintenance/maintenance-records.png
  content/images/post-images/gsoc-git-cache-maintenance/maintenance.png
  content/projects/gsoc/2022/projects/automatic-git-cache-maintenance.adoc
Labels: gsoc

#5472 [JENKINS-69638] Update HTTP/2 documentation
  content/doc/book/installing/_jenkins-command-parameters.adoc
Labels: documentation

#5475 Update 2022-09-19-digital-ocean-sponsorship.adoc
  content/blog/2022/09/2022-09-19-digital-ocean-sponsorship.adoc
Labels: blogpost

#5473 Remove trailing dash from heading
  content/projects/gsoc/2022/projects/automatic-git-cache-maintenance.adoc
Labels: gsoc

#5477 Updating automated changelog for 2.369
  content/_data/changelogs/weekly.yml
Labels: changelog

#4806 Improve a plugin tutorial and blog post
  content/_data/authors/dheerajodha.adoc
  content/_layouts/corebaseline.html.haml
  content/blog/2022/09/2022-09-21-improve-a-plugin-tutorial.adoc
  content/doc/developer/_book.yml
  content/doc/developer/index.html.haml
  content/doc/developer/plugin-development/choosing-jenkins-baseline.adoc
  content/doc/developer/tutorial-improve/_chapter.yml
  content/doc/developer/tutorial-improve/_create-a-branch.adoc
  content/doc/developer/tutorial-improve/_create-a-pull-request.adoc
  content/doc/developer/tutorial-improve/add-a-configuration-as-code-automated-test.adoc
  content/doc/developer/tutorial-improve/add-a-contributing-guide.adoc
  content/doc/developer/tutorial-improve/add-a-jenkinsfile.adoc
  content/doc/developer/tutorial-improve/add-a-link-to-report-an-issue.adoc
  content/doc/developer/tutorial-improve/add-a-round-trip-test-for-configuration.adoc
  content/doc/developer/tutorial-improve/add-more-spotbugs-checks.adoc
  content/doc/developer/tutorial-improve/automate-dependency-update-checks.adoc
  content/doc/developer/tutorial-improve/convert-api-dependencies-to-plugin-dependencies.adoc
  content/doc/developer/tutorial-improve/convert-translations.adoc
  content/doc/developer/tutorial-improve/enable-incrementals.adoc
  content/doc/developer/tutorial-improve/improve-pipeline-documentation.adoc
  content/doc/developer/tutorial-improve/index.adoc
  content/doc/developer/tutorial-improve/migrate-documentation-to-github.adoc
  content/doc/developer/tutorial-improve/move-description-to-index.adoc
  content/doc/developer/tutorial-improve/replace-jsr-305-annotations.adoc
  content/doc/developer/tutorial-improve/review-build-status.adoc
  content/doc/developer/tutorial-improve/update-base-jenkins-version.adoc
  content/doc/developer/tutorial-improve/update-parent-pom.adoc
  content/doc/developer/tutorial-improve/update-scm-url.adoc
  content/doc/developer/tutorial-improve/use-plugin-bill-of-materials.adoc
  content/images/developer/tutorial-adopt/image1.png
  content/images/developer/tutorial-adopt/image2.png
  content/images/developer/tutorial-adopt/image3.png
  content/images/developer/tutorial-adopt/image4.png
  content/images/developer/tutorial-adopt/image5.png
  content/images/developer/tutorial-adopt/image6.png
  content/images/post-images/improve-a-plugin-2022.png
Labels: blogpost, documentation, squash-merge-me

#5478 Add information about silent install on Windows
  content/doc/book/installing/windows.adoc
Labels: documentation

#5483 Add information re plugin description moving
  content/doc/developer/tutorial-improve/move-description-to-index.adoc
Labels: documentation

#5501 [DOCS-5909] Updating blue ocean run details
  content/doc/book/blueocean/pipeline-run-details.adoc
  content/doc/book/resources/blueocean/pipeline-run-details/overview.png
Labels: documentation

#5510 Update _kubernetes.adoc
  content/doc/book/installing/_kubernetes.adoc
Labels: documentation

#5511 Move hardware recommendations after architecting for scale
  content/doc/book/scaling/_chapter.yml
Labels: documentation

#5512 Update casc.adoc
  content/doc/book/managing/casc.adoc
Labels: documentation

#5507 Shorten the example exclusion
  content/doc/developer/tutorial-improve/add-more-spotbugs-checks.adoc
Labels: documentation

#5514 Document removal of `hudson.Util.useNativeChmodAndMode`
  content/doc/book/managing/system-properties.adoc
Labels: documentation

#5515 Document `hudson.ClassicPluginStrategy.useAntClassLoader`
  content/doc/book/managing/system-properties.adoc
Labels: documentation

#5509 Update reverse-proxy-configuration-with-jenkins.adoc
  content/doc/book/system-administration/reverse-proxy-configuration-with-jenkins.adoc
Labels: documentation

#5518 Fix formatting of old security changelog entries, link advisories
  content/_partials/changelog-old.html
Labels: changelog
