Repository jenkins-infra/jenkins.io, pull requests merged in 2022-07, with the labels that each got.

#5240 [DOCS-5689] Update Jenkins on AWS tutorial
  content/doc/book/resources/tutorials/AWS/add-amazon-cloud.png
  content/doc/book/resources/tutorials/AWS/configure_cloud.png
  content/doc/book/resources/tutorials/AWS/install_ec2_plugin.png
  content/doc/book/resources/tutorials/AWS/manage-jenkins-configure-clouds.png
  content/doc/book/resources/tutorials/AWS/manage-jenkins.png
  content/doc/book/resources/tutorials/AWS/manage-nodes-and-clouds.png
  content/doc/tutorials/tutorial-for-installing-jenkins-on-AWS.adoc
Labels: documentation

#5247 [DOCS-5689] update IBM jenkins screens
  content/doc/book/resources/tutorials/IBMCloud/login.png
  content/doc/book/resources/tutorials/IBMCloud/welcome.png
  content/doc/tutorials/tutorial-for-installing-jenkins-on-IBM-Cloud.adoc
Labels: documentation

#5276 Fix links to plugins site
  content/doc/developer/publishing/documentation.adoc
Labels: documentation

#5277 Add: search for steps reference
  content/doc/pipeline/steps/index.html.haml
Labels: documentation

#5279 Increase searchbox width
  content/doc/pipeline/steps/index.html.haml
Labels: documentation

#5282 add more introduction details and explict examples about how to use t…
  content/projects/gsoc/2022/projects/jenkinsfile-runner-action-for-github-actions.adoc
Labels: gsoc

#5275 [DOCS-5813] "create a pipeline" text update
  content/doc/tutorials/create-a-pipeline-in-blue-ocean.adoc
Labels: documentation

#5286 [DOCS-5816] Jmeter with Jenkins content update
  content/doc/book/resources/jmeter/jmeter-00.png
  content/doc/book/resources/jmeter/jmeter-01.png
  content/doc/book/resources/jmeter/jmeter-02.png
  content/doc/book/resources/jmeter/jmeter-03.png
  content/doc/book/resources/jmeter/jmeter-04.png
  content/doc/book/resources/jmeter/jmeter-05.png
  content/doc/book/resources/jmeter/jmeter-06.png
  content/doc/book/resources/jmeter/jmeter-07.png
  content/doc/book/resources/jmeter/jmeter-08.png
  content/doc/book/using/using-jmeter-with-jenkins.adoc
Labels: documentation

#5295 Noting that `archetype:generate` can hang depending on mirror settings
  content/doc/developer/tutorial/create.adoc
Labels: documentation

#5298 Retire wiki-exporter from docs
  CONTRIBUTING.adoc
  content/_data/authors/halkeye.adoc
  content/doc/developer/publishing/wiki-page.adoc
  content/events/hacktoberfest.adoc
  content/events/online-hackfest/2020-uiux/index.adoc
  content/projects/infrastructure/index.adoc
Labels: documentation

#5209 [DOCS-5624] inclusive naming screenshot update inbound agent
  content/doc/book/resources/hardware-recommendations/inbound-agent.png
  content/doc/book/resources/hardware-recommendations/jnlp-agent.png
  content/doc/book/resources/hardware-recommendations/jnlp-slave.png
  content/doc/book/scaling/architecting-for-scale.adoc
Labels: documentation

#5304 Use controller, not master in glossary
  content/doc/book/glossary/index.adoc
Labels: documentation

#5288 [DOCS-5843] Adding Blue Ocean statement
  content/doc/book/blueocean/_blue-ocean-status.adoc
  content/doc/book/blueocean/activity.adoc
  content/doc/book/blueocean/creating-pipelines.adoc
  content/doc/book/blueocean/dashboard.adoc
  content/doc/book/blueocean/getting-started.adoc
  content/doc/book/blueocean/index.adoc
  content/doc/book/blueocean/pipeline-editor.adoc
  content/doc/book/blueocean/pipeline-run-details.adoc
Labels: documentation

#5308 Include more plugins in the themes page
  content/doc/book/managing/ui-themes.adoc
Labels: documentation

#5312 Add midterm presentation link
  content/projects/gsoc/2022/projects/jenkinsfile-runner-action-for-github-actions.adoc
Labels: gsoc

#5306 [DOCS-5905] Updating getting started in blue ocean doc
  content/doc/book/blueocean/getting-started.adoc
Labels: documentation

#5320 More quickly pick up new LTS releases in version recommendations
  content/_layouts/corebaseline.html.haml
  scripts/fetch-external-resources
Labels: chore

#5315 Removing Evergreen project page
  content/_data/logo/evergreen.yml
  content/blog/2018/09/2018-09-18-automatically-upgrading-with-evergreen.adoc
  content/blog/2018/10/2018-10-01-hacktoberfest.adoc
  content/blog/2018/10/2018-10-09-telemetry.adoc
  content/blog/2018/12/2018-12-14-java11-preview-availability.adoc
  content/blog/2018/12/2018-12-25-year-in-review.adoc
  content/blog/2019/03/2019-03-11-let-s-celebrate-java-11-support.adoc
  content/images/evergreen/evergreen-starting.png
  content/images/evergreen/evergreen-status.png
  content/images/evergreen/magician_256.png
  content/images/logos/evergreen/256.png
  content/images/logos/evergreen/evergreen.png
  content/images/logos/evergreen/evergreen.svg
  content/images/superpowers/evergreen-ship.png
  content/projects/evergreen/index.adoc
  content/projects/gsoc/2019/plugin-installation-manager-tool-cli.adoc
Labels: gsoc, blogpost, artwork

#5310 Dev ops world2022
  content/_data/authors/gounthar.adoc
  content/blog/2022/07/2022-07-27-jenkins-contributor-summit-at-devops-world-2022-call-for-participation.adoc
  content/images/avatars/gounthar.png
  content/images/post-images/Jenkins-DevOps.png
Labels: blogpost

#5301 [JENKINS-60866] Add initial guidelines how to make code compatible with CSP
  content/doc/developer/security/_chapter.yml
  content/doc/developer/security/csp.adoc
Labels: documentation

#5307 Use a 3 part Blue ocean admonition
  content/doc/book/blueocean/_blue-ocean-status.adoc
  content/doc/book/blueocean/activity.adoc
  content/doc/book/blueocean/creating-pipelines.adoc
  content/doc/book/blueocean/dashboard.adoc
  content/doc/book/blueocean/getting-started.adoc
  content/doc/book/blueocean/index.adoc
  content/doc/book/blueocean/pipeline-editor.adoc
  content/doc/book/blueocean/pipeline-run-details.adoc
  content/doc/book/pipeline/development.adoc
  content/doc/book/pipeline/getting-started.adoc
  content/doc/book/pipeline/running-pipelines.adoc
Labels: documentation
