Repository jenkins-infra/jenkins.io, pull requests merged in 2023-05, with the labels that each got.

#6336 Android and jenkins series. Blog post #2.
  content/blog/2023/05/02/2023-05-02-android-and-jenkins-releases.adoc
  content/images/post-images/2023/05/02/2023-05-02-android-and-jenkins-releases/too-many-releases.png
Labels: blogpost

#6314 Jenkins.io - adding LTS 2.387.3 changelog & upgrade guide
  content/_data/changelogs/lts.yml
  content/_data/upgrades/2-387-3.adoc
Labels: changelog

#6354 List members of the hosting team
  content/project/teams/hosting.adoc
Labels: governance, documentation

#6353 Reword plugin hosting request reviewers
  content/doc/developer/publishing/requesting-hosting.adoc
Labels: documentation

#6357 Fix issue number in 2.387.3 release notes
  content/_data/changelogs/lts.yml
Labels: changelog

#6358 Announcing GSoC 2023 selected projects and contributors
  content/_data/authors/null_gsoc_contributor.adoc
  content/_data/indexpage/carousel.yml
  content/blog/2023/05/04/2023-05-04-gsoc2023-projects-announcement.adoc
  content/images/gsoc/gsoc_projects_contributors_selected.png
  content/projects/gsoc/2023/projects/add-probes-to-plugin-health-score.adoc
  content/projects/gsoc/2023/projects/alternative-jenkinsio-build-tool.adoc
  content/projects/gsoc/2023/projects/docker-compose-build.adoc
  content/projects/gsoc/2023/projects/gitlab-plugin-modernization.adoc
  content/projects/gsoc/index.adoc
Labels: gsoc, blogpost

#6360 Fix broken URLs on GSoC blog post
  content/blog/2023/05/04/2023-05-04-gsoc2023-projects-announcement.adoc
Labels: blogpost

#6361 Update legacy google group URL syntax
  content/blog/2014/2014-05-27-acceptance-test-project-progress-report.adoc
  content/blog/2014/2014-05-30-adopt-a-plugin.adoc
  content/blog/2015/2015-06-22-new-wiki-url-requirement-for-plugins.adoc
  content/blog/2015/2015-11-11-new-jenkins-releases-with-important-security-fixes.adoc
  content/blog/2016/2016-04-07-2.0-release-candidate.adoc
  content/blog/2016/2016-05-23-external-workspace-manager-plugin.adoc
  content/blog/2016/2016-05-26-introducing-blue-ocean.adoc
  content/blog/2016/2016-06-13-gsoc-usage-stats-analysis.adoc
  content/blog/2016/2016-11-16-security-updates-addressing-zero-day.adoc
  content/blog/2016/2016-12-31-what-a-year.adoc
  content/blog/2017/08/2017-08-23-pull-requests-and-more.adoc
  content/blog/2018/05/2018-05-01-gsoc2018-projects-announcement.adoc
  content/blog/2018/07/2018-07-30-introducing-cloud-native-sig.adoc
  content/blog/2018/12/2018-12-26-gsoc-2019-call-for-mentors.adoc
  content/blog/2019/08/2019-08-23-introducing-gitlab-branch-source-plugin.adoc
  content/blog/2019/11/2019-11-08-board-elections.adoc
  content/blog/2019/11/2019-11-22-jenkins-health-advisor-by-cloudbees.adoc
  content/blog/2019/12/2019-12-16-board-election-results.adoc
  content/blog/2020/03/2020-03-02-pipeline-authoring-sig-update.adoc
  content/blog/2020/05/2020-05-12-uiux-hackfest-announcement.adoc
  content/blog/2022/05/2022-05-20-gsoc2022-projects-announcement.adoc
  content/doc/book/blueocean/index.adoc
  content/doc/developer/plugin-governance/managing-permissions.adoc
  content/events/online-meetup/index.adoc
  content/participate/review-changes.adoc
  content/project/governance-meeting/index.adoc
  content/project/team-leads.adoc
  content/projects/blueocean/contribute/index.adoc
  content/projects/gsoc/gsoc2016.adoc
  content/projects/gsoc/students.adoc
  content/security/for-administrators.adoc
  content/security/index.adoc
Labels: chore

#6366 Fix phrasing based on feedback report
  content/doc/book/system-administration/backing-up.adoc
Labels: documentation

#6367 Add new GSoC contributor bio
  content/_data/authors/jagruti.adoc
  content/images/avatars/jagruti.jpg
Labels: gsoc

#6364 Update author page and GSoC project description
  content/_data/authors/harsh-ps-2003.adoc
  content/images/avatars/harsh-ps-2003.jpg
  content/projects/gsoc/2023/projects/gitlab-plugin-modernization.adoc
Labels: gsoc

#6369 April 2023 newsletter.
  content/blog/2023/05/10/2023-05-10-jenkins-april-newsletter.adoc
  content/images/post-images/2023/05/10/2023-05-10-jenkins-april-newsletter/image1.png
Labels: blogpost

#6377 Add a blog post about removing Prototype from Jenkins
  content/blog/2023/05/12/2023-05-12-removing-prototype-from-jenkins.adoc
  content/images/post-images/2023/05/12/2023-05-12-removing-prototype-from-jenkins.png
Labels: blogpost

#6378 Add GSoC contributor bio
  content/_data/authors/vandit1604.adoc
  content/images/avatars/vandit1604.jpeg
Labels: gsoc

#6380 Update GSoC project page
  content/_data/authors/vandit1604.adoc
  content/projects/gsoc/2023/projects/alternative-jenkinsio-build-tool.adoc
  content/projects/gsoc/index.adoc
Labels: gsoc

#6387 Updated number of plugins to be consistent
  content/doc/book/scaling/architecting-for-manageability.adoc
Labels: documentation

#6385 Update GSoC 2023 page for "Adding probes to Plugin health score" project
  content/projects/gsoc/2023/projects/add-probes-to-plugin-health-score.adoc
Labels: gsoc

#6383 Add GSoC contributor blog post
  content/blog/2023/05/17/2023-05-17-vandit1604-introduction-blog-post.adoc
  content/images/gsoc/2023/contributor_blogpost_vandit.png
Labels: gsoc, blogpost

#6388 Add GSoC contributor blog post
  content/blog/2023/05/18/2023-05-18-harsh-ps-2003-introduction-blog-post.adoc
Labels: gsoc, blogpost

#6389 Fix parameter to environment variable example
  content/doc/book/pipeline/syntax.adoc
Labels: documentation

#6390 Fix typo in license and update by-sa banner
  LICENSE.adoc
Labels: chore

#6391 Update docker-compose-build.adoc
  content/projects/gsoc/2023/projects/docker-compose-build.adoc
  content/projects/gsoc/index.adoc
Labels: gsoc

#6393 Add new layout for GSoC projects
  content/_layouts/gsocproject3.html.haml
  content/projects/gsoc/2023/projects/docker-compose-build.adoc
Labels: gsoc

#6394 Add GSoC 2023 contributor introductory blog for Plugin Health Scoring System project
  content/blog/2023/05/22/2023-05-22-jagruti-introduction-blog-post.adoc
  content/images/gsoc/2023/jagruti/blog_20230522.png
Labels: gsoc, blogpost

#6397 Fixed adoc syntax in Add GSoC 2023 contributor introductory blog for Plugin Health Scoring System project blog
  content/blog/2023/05/22/2023-05-22-jagruti-introduction-blog-post.adoc
Labels: blogpost

#6396 fix(documentation): Artifactory UI does not work anymore.
  content/doc/developer/publishing/releasing-manually.adoc
  content/images/developer/publishing/artifactory-login.png
  content/images/developer/publishing/artifactory-set-me-up.png
  content/images/developer/publishing/download-snippet.png
  content/images/developer/publishing/generate-settings.png
  content/images/developer/publishing/generated-xml.png
  content/images/developer/publishing/select-maven.png
  content/images/developer/publishing/unlock.png
Labels: documentation

#6398 Remove '$' from console copy/paste samples
  content/_data/upgrades/2-387-2.adoc
  content/blog/2015/2015-12-03-pipeline-as-code-with-multibranch-workflows-in-jenkins.adoc
  content/blog/2017/05/2017-05-18-pipeline-dev-tools.adoc
  content/blog/2019/07/2019-07-11-remoting-kafka-kubernetes-phase-1.adoc
  content/blog/2019/08/2019-08-30-jenkins-cli.adoc
  content/blog/2020/03/2020-03-30-azure-key-vault-cred-provider.adoc
  content/blog/2020/06/2020-06-30-machine-learning-plugin-coding-phase1.adoc
  content/blog/2022/03/2022-03-25-systemd-migration.adoc
  content/blog/2022/12/2022-12-27-run-jenkins-agent-as-a-service.adoc
  content/blog/2023/03/2023-03-27-repository-signing-keys-changing.adoc
  content/blog/2023/03/30/2023-03-30-android-and-jenkins.adoc
  content/blog/2023/05/12/2023-05-12-removing-prototype-from-jenkins.adoc
  content/doc/book/installing/_kubernetes.adoc
  content/doc/book/installing/linux.adoc
  content/doc/book/installing/war-file.adoc
  content/doc/book/managing/cli.adoc
  content/doc/book/scaling/scaling-jenkins-on-kubernetes.adoc
  content/doc/book/system-administration/systemd-services.adoc
  content/doc/developer/plugin-development/dependency-management.adoc
  content/doc/developer/publishing/releasing-manually.adoc
  content/doc/developer/tutorial-improve/_create-a-branch.adoc
  content/doc/developer/tutorial-improve/_create-a-pull-request.adoc
  content/doc/developer/tutorial-improve/add-more-spotbugs-checks.adoc
  content/doc/developer/tutorial-improve/automate-dependency-update-checks.adoc
  content/doc/developer/tutorial-improve/convert-translations.adoc
  content/doc/developer/tutorial-improve/enable-incrementals.adoc
  content/doc/developer/tutorial-improve/move-description-to-index.adoc
  content/doc/developer/tutorial-improve/replace-jsr-305-annotations.adoc
  content/doc/developer/tutorial-improve/update-parent-pom.adoc
  content/doc/developer/tutorial-improve/use-plugin-bill-of-materials.adoc
  content/doc/developer/tutorial/create.adoc
Labels: documentation

#6402 Publish GH sponsor blogpost
  content/blog/2023/05/25/2023-05-25-github-sponsors-jenkinsci-org.adoc
  content/images/post-images/2023/05/25/2023-05-25-github-sponsors-jenkinsci-org.png
Labels: blogpost

#6407 Update GSoC weekly project meeting time
  content/_layouts/gsocproject.html.haml
  content/_layouts/gsocproject2.html.haml
  content/_partials/connect-links.html.haml
  content/projects/gsoc/2023/projects/add-probes-to-plugin-health-score.adoc
  content/projects/gsoc/2023/projects/alternative-jenkinsio-build-tool.adoc
  content/projects/gsoc/2023/projects/docker-compose-build.adoc
  content/projects/gsoc/2023/projects/gitlab-plugin-modernization.adoc
Labels: gsoc

#6400 Internationalization and localization improvements
  content/doc/developer/_book.yml
  content/doc/developer/crowdin/_chapter.yml
  content/doc/developer/crowdin/index.adoc
  content/doc/developer/crowdin/translating-plugins.adoc
  content/doc/developer/internationalization/_chapter.yml
  content/doc/developer/internationalization/index.adoc
  content/doc/developer/internationalization/internationalization-and-localization.adoc
  content/doc/developer/internationalization/prepare-a-jelly-view.adoc
  content/doc/developer/internationalization/translate-a-help-file.adoc
  content/doc/developer/internationalization/translate-a-properties-file.adoc
  content/images/developer/internationalization-and-localization/download_jenkins_dev_support.png
Labels: documentation

#6411 Clarify Windows support policy
  content/doc/administration/requirements/windows.adoc
Labels: documentation

#6408 2.401.1 changelog and upgrade guide
  content/_data/changelogs/lts.yml
  content/_data/changelogs/weekly.yml
  content/_data/upgrades/2-401-1.adoc
Labels: changelog

#6404 Add GSoC contributor blog post
  content/blog/2023/05/26/2023-05-26-ash-sxn-introduction-blog-post.adoc
Labels: gsoc, blogpost

#6418 Fix minor typo in blueocean/dashboard.adoc
  content/doc/book/blueocean/dashboard.adoc
Labels: documentation

#6417 Document autolink references
  content/doc/developer/publishing/requesting-hosting.adoc
  content/images/developer/plugin-development/hosting/jira-auto-reference.png
Labels: documentation

#6420 Mention the default value for the choice parameter
  content/doc/book/pipeline/syntax.adoc
Labels: documentation

#6421 Fix date
  content/_data/changelogs/lts.yml
Labels: changelog
