Repository jenkins-infra/jenkins.io, pull requests merged in 2023-01, with the labels that each got.

#5860 Use Apache Maven 3.8.7 for examples, not 3.8.6
  content/doc/book/pipeline/docker.adoc
  content/doc/book/pipeline/syntax.adoc
  content/doc/pipeline/tour/hello-world.adoc
  content/doc/tutorials/build-a-java-app-with-maven.adoc
Labels: documentation

#5855 Added content to section for security testing
  content/doc/developer/testing/index.adoc
Labels: documentation

#5854 Add mentor for agent reconnection gsoc 2023 project
  content/_data/authors/loghijiaha.adoc
  content/projects/gsoc/2023/project-ideas/agent_reconnections_exponential_backoff.adoc
Labels: gsoc

#5865 Remove version specifier from demo plugin installs
  content/doc/book/installing/_docker-for-tutorials.adoc
  content/doc/book/installing/_docker.adoc
Labels: documentation

#5871 Update board and officers page
  content/project/board.html.haml
Labels: governance

#5850 added typo check and removed htaccess files
  .gitignore
  CONTRIBUTING.adoc
  Jenkinsfile
  Makefile
  content/.htaccess
  content/doc/developer/.htaccess
  content/doc/developer/404.html.haml
Labels: chore, documentation

#5874 Remove broken artwork credit links
  content/_data/logo/cowboy.yml
  content/_data/logo/yaroslavl.yml
Labels: governance, artwork

#5872 fix(reverse-proxy/apache): The rewrite rule was incorrect
  content/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-apache.adoc
Labels: documentation

#5876 Update site generator idea details
  content/projects/gsoc/2023/project-ideas/alternative-jenkinsio-build-tool.adoc
Labels: gsoc

#5726 Fixed horizontal scroll issue on mobile
  content/css/jenkins.css
Labels: enhancement

#5885 Rewrite PHP guide to use Jenkinsfile based setup
  content/_data/solutions/php.yml
  content/solutions/php.adoc
Labels: documentation

#5889 PHP Solution: Fix non-sensical introduction paragraph
  content/solutions/php.adoc
Labels: documentation

#5891 Address ruby deprecations
  content/_layouts/corebaseline.html.haml
  content/_partials/changelog-changes.xml.haml
  content/download/index.html.haml
  content/security/advisories/rss.xml.haml
Labels: chore

#5893 doc: `user-site` no longer needed
  CONTRIBUTING.adoc
  Makefile
  scripts/user-site-deploy.sh
Labels: chore

#5689 Allow up to 2 elected board members from a single company
  content/project/board-election-process.adoc
Labels: governance

#5793 Jenkins 2.375.2 - Adding changelog & upgrade guide
  content/_data/changelogs/lts.yml
  content/_data/upgrades/2-375-2.adoc
Labels: changelog

#5508 Define jenkins-pv storageClass
  content/doc/tutorials/kubernetes/installing-jenkins-on-kubernetes/jenkins-volume.yaml
Labels: documentation

#5902 fix: image and text disposition on https://www.jenkins.io/doc/book/installing/windows/
  content/doc/book/installing/windows.adoc
Labels: documentation

#5904 Fix example node version from docker agent docs
  content/doc/book/pipeline/docker.adoc
Labels: documentation

#5907 Remove more archived mailing lists
  content/blog/2013/2013-01-26-report-jenkins-meet-up-seoul.adoc
  content/blog/2018/10/2018-10-14-gsoc2018-results.adoc
  content/blog/2018/12/2018-12-14-java11-preview-availability.adoc
  content/blog/2018/12/2018-12-26-gsoc-2019-call-for-mentors.adoc
  content/blog/2019/03/2019-03-04-gsoc2019-announcement.adoc
  content/blog/2019/03/2019-03-11-let-s-celebrate-java-11-support.adoc
  content/blog/2021/03/2021-03-17-gsoc2021-announcement.adoc
  content/blog/2022/03/2022-03-21-java17-preview-availability.adoc
  content/doc/administration/requirements/linux.adoc
  content/doc/administration/requirements/servlet-containers.adoc
  content/projects/gsoc/2019/application.md
  content/projects/gsoc/2020/application.md
  content/projects/gsoc/2020/project-ideas/jenkins-x-apps-consolidation.adoc
  content/projects/gsoc/2020/project-ideas/jenkins-x-boot-apps.adoc
  content/projects/gsoc/students.adoc
  content/sigs/gsoc/index.adoc
  content/sigs/hw-and-eda/index.adoc
  content/sigs/platform/index.adoc
Labels: gsoc, blogpost, documentation

#5905 [GSoC 2023] [Mentor] Freyam Mehta
  content/_data/authors/freyam.adoc
  content/images/avatars/freyam.jpg
  content/projects/gsoc/2023/project-ideas/agent_reconnections_exponential_backoff.adoc
  content/projects/gsoc/2023/project-ideas/alternative-jenkinsio-build-tool.adoc
  content/projects/gsoc/2023/project-ideas/plugin-installation-manager-tool.adoc
Labels: gsoc

#5910 Missing a close bracket
  content/doc/developer/security/xss-prevention.adoc
Labels: documentation

#5912 Correct publication year of 2.375.2
  content/_data/changelogs/lts.yml
Labels: changelog

#5886 feat(documentation) 2022 Recap Newsletter
  content/blog/2023/01/2023-01-12-jenkins-newsletter.adoc
  content/images/post-images/2023/01/12/jenkins-newsletter/governance.png
  content/images/post-images/2023/01/12/jenkins-newsletter/image5.png
  content/images/post-images/2023/01/12/jenkins-newsletter/image6.png
  content/images/post-images/2023/01/12/jenkins-newsletter/image7.png
  content/images/post-images/2023/01/12/jenkins-newsletter/infrastructure.png
  content/images/post-images/2023/01/12/jenkins-newsletter/jenkins-crowdin.png
  content/images/post-images/2023/01/12/jenkins-newsletter/jenkins-io-improvements.png
  content/images/post-images/2023/01/12/jenkins-newsletter/jenkins-modern-look-2.png
  content/images/post-images/2023/01/12/jenkins-newsletter/jenkins-modern-look.png
  content/images/post-images/2023/01/12/jenkins-newsletter/localization-simplification.png
  content/images/post-images/2023/01/12/jenkins-newsletter/outreach-and-advocacy.png
  content/images/post-images/2023/01/12/jenkins-newsletter/platform-modernization.png
  content/images/post-images/2023/01/12/jenkins-newsletter/recap.png
  content/images/post-images/2023/01/12/jenkins-newsletter/security.png
  content/images/post-images/2023/01/12/jenkins-newsletter/ui_ux.png
Labels: blogpost

#5914 chore: correct case for SCALE 20x event
  content/_data/events/2023-03-09-pasadena.adoc
Labels: events

#5920 Added svg files for Jenkins Eiffel and Atomium
  content/_data/logo/atomium.yml
  content/_data/logo/paris-eiffel.yml
  content/images/logos/atomium/atomium.svg
  content/images/logos/paris-eiffel/paris-eiffel.svg
Labels: artwork

#5926 add "plugin health score display" GSoC project idea
  content/projects/gsoc/2023/project-ideas/displaying_plugin_health_scores.adoc
Labels: gsoc

#5931 Update GSoC project idea template
  content/projects/gsoc/2023/project-ideas/prj-idea-template.adoc_text
Labels: gsoc

#5928 Improve the explanation of section 'agent' in pipeline syntax
  content/doc/book/pipeline/syntax.adoc
Labels: documentation

#5925 Don't recommend EOL baselines for new plugins
  content/_layouts/corebaseline.html.haml
  content/doc/developer/plugin-development/choosing-jenkins-baseline.adoc
Labels: documentation

#5935 Adds myself as mentor on Plugin Health Scoring related GSoC idea
  content/projects/gsoc/2023/project-ideas/add-probes-to-plugin-health-score.adoc
  content/projects/gsoc/2023/project-ideas/displaying_plugin_health_scores.adoc
Labels: gsoc

#5938 Adding myself as a mentor for Alternative build options for Jenkins project
  content/projects/gsoc/2023/project-ideas/alternative-jenkinsio-build-tool.adoc
Labels: gsoc

#5939 Added new svg files for Jenkins Musketeer and Oktoberfest and link to profile
  content/_data/logo/alien.yml
  content/_data/logo/atomium.yml
  content/_data/logo/austin.yml
  content/_data/logo/balloon.yml
  content/_data/logo/beekeeper.yml
  content/_data/logo/belarus.yml
  content/_data/logo/chatterbox.yml
  content/_data/logo/cosmonaut.yml
  content/_data/logo/cossack.yml
  content/_data/logo/cowboy.yml
  content/_data/logo/formal.yml
  content/_data/logo/jenkinstein.yml
  content/_data/logo/magician.yml
  content/_data/logo/magritte.yml
  content/_data/logo/miner.yml
  content/_data/logo/musketeer.yml
  content/_data/logo/oktoberfest.yml
  content/_data/logo/paris-eiffel.yml
  content/_data/logo/peter-the-great.yml
  content/_data/logo/plumber.yml
  content/_data/logo/raleigh.yml
  content/_data/logo/russian.yml
  content/_data/logo/san-diego.yml
  content/_data/logo/santa-claus.yml
  content/_data/logo/sherlock.yml
  content/_data/logo/snow.yml
  content/images/logos/musketeer/musketeer.svg
  content/images/logos/oktoberfest/oktoberfest.svg
Labels: artwork

#5919 Pipeline Syntax page - Document that parameters become environment variables
  content/doc/book/pipeline/syntax.adoc
Labels: documentation

#5899 Prevent absolute links from adoc to www.jenkins.io and jenkins.io
  Jenkinsfile
  Makefile
  content/events/hacktoberfest.adoc
  content/participate/report-issue.adoc
  content/participate/test.adoc
  content/project/conduct.adoc
  content/project/team-leads.adoc
  content/redirect/oracle-account-signup.adoc
  content/redirect/pipeline-cps-method-mismatches.adoc
  content/security/plugins.adoc
  content/security/reporting.adoc
  content/solutions/php.adoc
  content/templates/updates.adoc
  scripts/check-hard-coded-URL-references
Labels: governance, chore, documentation

#5944 Only check dependencies once a month
  content/doc/developer/tutorial-improve/automate-dependency-update-checks.adoc
Labels: documentation

#5950 [doc/developer/handling-requests] Add missing description of parameter
  content/doc/developer/handling-requests/json.adoc
Labels: documentation

#5955 Update alternative-jenkinsio-build-tool doc to use exclusively Antora
  content/projects/gsoc/2023/project-ideas/alternative-jenkinsio-build-tool.adoc
Labels: gsoc

#5959 [GSoC] Promote Plugin Health Score UI project idea to draft
  content/images/gsoc/2023/plugin_health_score_UI-wireframe1.png
  content/images/gsoc/2023/plugin_health_score_UI-wireframe2.png
  content/projects/gsoc/2023/project-ideas/displaying_plugin_health_scores.adoc
Labels: gsoc

#5936 Use Ruby 3.2.0
  .ruby-version
  Dockerfile
  Gemfile
  Gemfile.lock
  Makefile
  content/_ext/handbook.rb
  content/_ext/pipeline.rb
  content/_ext/releases.rb
  content/doc/pipeline/examples.html.haml
  scripts/ruby
Labels: chore, documentation

#5963 [GSoC] fix project size of "exponential" project idea
  content/projects/gsoc/2023/project-ideas/agent_reconnections_exponential_backoff.adoc
Labels: gsoc

#5966 Update plugin archetype version
  content/doc/developer/tutorial/create.adoc
Labels: documentation

#5964 [GSoC] reverting gitlab plugin modernization to discussion
  content/projects/gsoc/2023/project-ideas/gitlab-plugin-modernization.adoc
Labels: gsoc

#5969 Update haml and tilt
  Gemfile
  Gemfile.lock
  content/_ext/activenav.rb
  content/_ext/get_plugins.rb
  content/_ext/pipeline.rb
  content/download/index.html.haml
  content/project/roadmap/index.html.haml
  content/security/advisories.html.haml
  content/security/advisories/rss.xml.haml
Labels: governance, chore, roadmap

#5972 Extend plugin install mgr project idea
  content/projects/gsoc/2023/project-ideas/plugin-installation-manager-tool.adoc
Labels: gsoc

#5960 [GSoC] Mentor volunteers update
  content/_data/authors/sbostandoust.adoc
  content/projects/gsoc/2023/project-ideas/JCasC-drift-detector.adoc
  content/projects/gsoc/2023/project-ideas/add-probes-to-plugin-health-score.adoc
  content/projects/gsoc/2023/project-ideas/alternative-jenkinsio-build-tool.adoc
  content/projects/gsoc/2023/project-ideas/buiilding-android-app.adoc
  content/projects/gsoc/2023/project-ideas/buiilding-ios-app.adoc
  content/projects/gsoc/2023/project-ideas/docker-compose-build.adoc
  content/projects/gsoc/2023/project-ideas/gitlab-plugin-modernization.adoc
Labels: gsoc

#5976 [doc/developer/handling-requests] Modernize JSON HTTP API documentation
  content/doc/developer/handling-requests/json.adoc
Labels: documentation

#5978 Add markewaite as GitLab plugin project mentor
  content/projects/gsoc/2023/project-ideas/gitlab-plugin-modernization.adoc
Labels: gsoc

#5982 Introduce RPU acronym
  content/doc/developer/plugin-governance/adopt-a-plugin.adoc
Labels: documentation

#5812 Correct description of controller/built-in node
  content/doc/book/managing/nodes.adoc
Labels: documentation

#5940 Proposal to remove the reward/gift aspect for vulnerabilities
  content/donate.adoc
  content/project/team-leads.adoc
  content/security/gift.adoc
  content/security/index.adoc
  content/security/reporting.adoc
Labels: governance

#5987 Fix regression in `make run` from webrick 1.8.0
  Gemfile
  Gemfile.lock
Labels: chore

#5983 Jenkins.io - update events officer on team leads page
  content/project/team-leads.adoc
Labels: governance
