Repository jenkins-infra/jenkins.io, pull requests merged in 2023-02, with the labels that each got.

#5989 [Blog] GSoC new phase announcement
  content/blog/2023/02/2023-02-01-gsoc-update.adoc
Labels: blogpost

#5993 GSoC: Promote most project ideas to "published" status
  content/projects/gsoc/2023/project-ideas/JCasC-drift-detector.adoc
  content/projects/gsoc/2023/project-ideas/add-probes-to-plugin-health-score.adoc
  content/projects/gsoc/2023/project-ideas/agent_reconnections_exponential_backoff.adoc
  content/projects/gsoc/2023/project-ideas/alternative-jenkinsio-build-tool.adoc
  content/projects/gsoc/2023/project-ideas/buiilding-android-app.adoc
  content/projects/gsoc/2023/project-ideas/displaying_plugin_health_scores.adoc
  content/projects/gsoc/2023/project-ideas/docker-compose-build.adoc
  content/projects/gsoc/2023/project-ideas/gitlab-plugin-modernization.adoc
  content/projects/gsoc/2023/project-ideas/screenshot-automation.adoc
Labels: gsoc

#5932 Jenkins 2.375.3 - adding changelog and upgrade guide
  content/_data/changelogs/lts.yml
  content/_data/upgrades/2-375-3.adoc
Labels: changelog

#5999 Clarify that HotSpot JVM is required
  content/doc/administration/requirements/java.adoc
Labels: documentation

#5991 Clarify top level Pipeline examples of options
  content/doc/book/pipeline/syntax.adoc
Labels: documentation

#6004 Fixing literal syntax
  content/doc/book/pipeline/syntax.adoc
Labels: documentation

#5998 Edit Alternative jenkins.io build tool doc for GSoC 2023
  content/projects/gsoc/2023/project-ideas/alternative-jenkinsio-build-tool.adoc
  content/projects/gsoc/2023/project-ideas/plugin-installation-manager-tool.adoc
Labels: gsoc

#6011 Update Awestruct to 0.6.5
  Gemfile
  Gemfile.lock
Labels: chore

#6005 Add 'Securing Builds' Section to security documentation
  content/doc/book/security/_chapter.yml
  content/doc/book/security/index.adoc
  content/doc/book/security/securing-builds.adoc
Labels: documentation

#6000 feat(documentation): January 2023 newsletter.
  content/blog/2023/02/2023-02-07-jenkins-newsletter.adoc
  content/images/post-images/2023/02/07/2023-02-07-jenkins-newsletter/centered-newsletter.png
Labels: blogpost

#6018 Improve plugin install mgr tool idea
  content/projects/gsoc/2023/project-ideas/plugin-installation-manager-tool.adoc
Labels: gsoc

#6014 Update syntax.adoc
  content/doc/book/pipeline/syntax.adoc
Labels: documentation

#6020 January 2023 newsletter documentation banner was not the right one
  content/blog/2023/02/2023-02-07-jenkins-newsletter.adoc
  content/images/post-images/2023/02/07/2023-02-07-jenkins-newsletter/documentation.png
Labels: blogpost

#6002 Expand context path instructions for reverse proxies
  content/doc/book/system-administration/reverse-proxy-configuration-troubleshooting.adoc
  content/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/_context_path.adoc
  content/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-apache.adoc
  content/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-haproxy.adoc
  content/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-nginx.adoc
  content/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-squid.adoc
Labels: documentation

#6015 Edit Plugin Health Score related GSoC project idea pages
  content/projects/gsoc/2023/project-ideas/add-probes-to-plugin-health-score.adoc
  content/projects/gsoc/2023/project-ideas/displaying_plugin_health_scores.adoc
Labels: gsoc

#6026 Fix broken links on attribution page
  content/project/trademark/index.adoc
Labels: governance

#6032 Include Java version and vendor in bug report snippet
  content/doc/book/troubleshooting/diagnosing-errors.adoc
  content/participate/report-issue.adoc
Labels: documentation

#6023 Add Nginx reverse proxy video
  content/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-nginx.adoc
Labels: documentation

#6024 Add HAproxy reverse proxy video
  content/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-haproxy.adoc
Labels: documentation

#6025 Include Alma and Rocky, reduce CentOS references
  content/_partials/legacy/download.html.haml
  content/doc/book/installing/linux.adoc
  content/doc/book/managing/casc.adoc
  content/doc/book/pipeline/docker.adoc
  content/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-iptables.adoc
  content/download/index.html.haml
  content/download/verify.adoc
Labels: documentation

#6022 Add Apache reverse proxy video
  content/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-apache.adoc
Labels: documentation

#6039 Exchange Gitter namespace URL with matrix home
  content/chat.adoc
  content/project/conduct.adoc
Labels: chore

#6037 Update GSoC page with current status
  content/projects/gsoc/2022/index.adoc
  content/projects/gsoc/index.adoc
Labels: gsoc

#6045 Use Maven 3.9.0 in examples
  content/doc/book/pipeline/docker.adoc
  content/doc/book/pipeline/syntax.adoc
  content/doc/pipeline/tour/hello-world.adoc
  content/doc/tutorials/build-a-java-app-with-maven.adoc
Labels: documentation

#6047 fixing broken link #12 from issue #3335
  content/blog/2019/05/2019-05-11-docs-sig-announcement.adoc
Labels: blogpost

#6049 Add missing detail regarding jenkins.io components
  content/projects/gsoc/2023/project-ideas/alternative-jenkinsio-build-tool.adoc
Labels: gsoc

#6052 Remove Ubuntu 18 reference
  content/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-iptables.adoc
Labels: documentation

#6050 Outline how to use GH releases on plugin-release-tips page
  content/doc/developer/plugin-development/plugin-release-tips.adoc
Labels: documentation

#6048 Fosdem 2023 thoughts.
  content/_data/authors/gounthar.adoc
  content/_data/authors/smerle33.adoc
  content/blog/2023/02/2023-02-21-thoughts-on-FOSDEM-2023.adoc
  content/images/avatars/smerle33.png
  content/images/post-images/2023/02/21/2023-02-21-thoughts-on-FOSDEM-2023/alexander-brandes-on-the-booth.png
  content/images/post-images/2023/02/21/2023-02-21-thoughts-on-FOSDEM-2023/image1.jfif
  content/images/post-images/2023/02/21/2023-02-21-thoughts-on-FOSDEM-2023/image10.png
  content/images/post-images/2023/02/21/2023-02-21-thoughts-on-FOSDEM-2023/image11.png
  content/images/post-images/2023/02/21/2023-02-21-thoughts-on-FOSDEM-2023/image12.png
  content/images/post-images/2023/02/21/2023-02-21-thoughts-on-FOSDEM-2023/image13.png
  content/images/post-images/2023/02/21/2023-02-21-thoughts-on-FOSDEM-2023/image14.png
  content/images/post-images/2023/02/21/2023-02-21-thoughts-on-FOSDEM-2023/image15.png
  content/images/post-images/2023/02/21/2023-02-21-thoughts-on-FOSDEM-2023/image2.png
  content/images/post-images/2023/02/21/2023-02-21-thoughts-on-FOSDEM-2023/image3.jpg
  content/images/post-images/2023/02/21/2023-02-21-thoughts-on-FOSDEM-2023/image4.png
  content/images/post-images/2023/02/21/2023-02-21-thoughts-on-FOSDEM-2023/image5.png
  content/images/post-images/2023/02/21/2023-02-21-thoughts-on-FOSDEM-2023/image7.png
  content/images/post-images/2023/02/21/2023-02-21-thoughts-on-FOSDEM-2023/image8.png
  content/images/post-images/2023/02/21/2023-02-21-thoughts-on-FOSDEM-2023/image9.png
  content/images/post-images/2023/02/21/2023-02-21-thoughts-on-FOSDEM-2023/smerle-on-the-booth.png
Labels: blogpost

#6059 docs(pipeline): Add a missing intro to abort previous build option
  content/doc/book/pipeline/syntax.adoc
Labels: documentation

#5970 Add Jenkinsfile Runner GitHub Action tutorial
  content/doc/book/resources/tutorials/jenkinsfile-runner-github-actions-01-access-workflow-logs.jpeg
  content/doc/tutorials/index.adoc
  content/doc/tutorials/using-jenkinsfile-runner-github-action-to-build-jenkins-pipeline.adoc
Labels: documentation

#6061 GSoC 2023 status update
  content/projects/gsoc/index.adoc
Labels: gsoc

#6058 feat(documentation): CDF awards blog post.
  content/blog/2023/02/2023-02-23-cdf-awards.adoc
  content/images/post-images/2023/02/23/2023-02-23-cdf-awards/image1.png
Labels: blogpost

#6063 Blog post announcing the selection of Jenkins as GSoC Mentoring Org.
  content/blog/2023/02/2023-02-23-gsoc2023-announcement.adoc
  content/images/gsoc/2023/GSoC2023-here_we_come.png
Labels: blogpost

#6064 Update groupId wording for hosting requests
  content/doc/developer/publishing/style-guides.adoc
Labels: documentation

#6065 Deleted repetition of the word "the" in a sentence
  content/blog/2023/02/2023-02-23-gsoc2023-announcement.adoc
Labels: blogpost

#6073 Remove a link to a suspended plugin
  content/doc/book/managing/script-console.adoc
Labels: documentation

#6074 Fix link syntax
  content/blog/2022/06/2022-06-28-require-java-11.adoc
Labels: blogpost

#6070 GSoC23 mentor request(Screenshot Automation for Jenkins Docs)
  content/_data/authors/mostafaashraf.adoc
  content/images/avatars/mostafaashraf.jpg
  content/projects/gsoc/2023/project-ideas/screenshot-automation.adoc
Labels: gsoc

#6079 Fix broken URL on docker-based jenkins quickstart examples GSoC page
  content/projects/gsoc/2023/project-ideas/docker-compose-build.adoc
Labels: gsoc

#6080 Break hardlinks to jenkins.io
  content/blog/2018/06/2018-06-15-simple-pull-request-plugin.adoc
  content/blog/2022/11/2022-11-23-get-prepared-for-gsoc.adoc
  content/blog/2022/12/2022-12-09-GSoC-the-gift-of-mentorship.adoc
  content/blog/2022/12/2022-12-09-jfrog-maintenance.adoc
  content/blog/2023/02/2023-02-21-thoughts-on-FOSDEM-2023.adoc
  content/doc/tutorials/using-jenkinsfile-runner-github-action-to-build-jenkins-pipeline.adoc
  content/projects/gsoc/2023/project-ideas/buiilding-android-app.adoc
  content/security/advisory/2022-04-12.adoc
  content/security/advisory/2022-05-17.adoc
Labels: chore

#6076 pdfs is not a make target
  CONTRIBUTING.adoc
  Makefile
Labels: chore

#6091 Manual fixup of hard link cleanup
  content/_data/authors/aheritier.adoc
  content/blog/2010/2010-07-12-updated-chrome-extension.adoc
  content/blog/2010/2010-07-13-monitor-hudson-from-your-android.adoc
  content/blog/2010/2010-07-28-hosting-your-hudson-plugin-at-github.adoc
  content/blog/2010/2010-08-16-hudsonmobi-2-0-hits-the-android-market.adoc
  content/blog/2010/2010-09-05-hudsonmobi-dons-a-black-turtleneck-and-jumps-to-ios4.adoc
  content/blog/2010/2010-09-09-lets-talk-about-hudson-at-javaone.adoc
  content/blog/2018/04/2018-04-18-blueocean-1-5-0.adoc
  content/blog/2019/02/2019-02-06-ssh-steps-for-jenkins-pipeline.adoc
  content/blog/2019/08/2019-08-25-jenkinsworld-contrib-summit-ask-the-expert-booth.adoc
  content/blog/2022/12/2022-12-09-jfrog-maintenance.adoc
  content/doc/book/pipeline/multibranch.adoc
  content/doc/developer/security/remoting-callables.adoc
  content/merchandise.adoc
  content/project/governance-meeting/archives/2017.adoc
  content/security/advisory/2015-11-11.adoc
Labels: chore

#6067 Build locally msi
  content/blog/2023/02/2023-02-28-build-msi-locally.adoc
Labels: blogpost
