Repository jenkins-infra/jenkins.io, pull requests merged in 2023-06, with the labels that each got.

#6427 Update reference to `pipeline-github-lib`
  content/doc/book/pipeline/shared-libraries.adoc
Labels: documentation

#6432 Update archetypes version
  content/doc/developer/tutorial/create.adoc
Labels: documentation

#6447 Revise hosting team requirements and prerequisites
  content/project/teams/hosting.adoc
Labels: governance, documentation

#6451 Get the fallback release command closer to what the GH release action does
  content/doc/developer/publishing/releasing-cd.adoc
Labels: documentation

#6458 Don't warn about conflicts in changelog PRs
  .github/workflows/label-conflicting-prs.yml
Labels: chore

#6457 Document CD PR part
  content/doc/developer/publishing/releasing-cd.adoc
Labels: documentation

#6459 Remove detailed theme compatibility recommendation
  content/doc/book/managing/ui-themes.adoc
Labels: documentation

#6456 Move pluggable storage to "Using Jenkins"
  content/doc/book/using/_chapter.yml
  content/doc/book/using/pluggable-storage.adoc
  content/sigs/cloud-native/pluggable-storage.adoc
Labels: documentation

#5314 [JENKINS-54250] Disable restarting stages in jenkinsfile optionally
  content/doc/book/pipeline/syntax.adoc
Labels: work-in-progress, on-hold, documentation

#6464 Fix changelog updating bot name
  .github/workflows/label-conflicting-prs.yml
Labels: chore

#6465 Mention that `/build` can be used to trigger scan of organization folders and mutlibranch pipelines
  content/doc/book/using/remote-access-api.adoc
Labels: documentation

#6471 cleanup(roadmap): remove `customize.jenkins.io` and "Custom Jenkins distribution build service"
  content/_data/roadmap/roadmap.yml
Labels: roadmap

#6476 Remove 2020 tables to divs disclaimer
  content/doc/book/managing/index.adoc
Labels: documentation

#6463 feat(blog): May newsletter.
  content/blog/2023/06/20/2023-06-20-jenkins-may-newsletter.adoc
  content/images/post-images/2023/06/20/2023-06-20-jenkins-may-newsletter/image1.jpg
  content/images/post-images/2023/06/20/2023-06-20-jenkins-may-newsletter/image2.png
  content/images/post-images/2023/06/20/2023-06-20-jenkins-may-newsletter/image3.png
Labels: blogpost

#6460 feat(blog): How to remove outdated plugins while using docker
  content/blog/2023/06/20/2023-06-20-remove-outdated-plugins-while-using-docker.adoc
  content/images/post-images/2023/06/20/2023-06-20-remove-outdated-plugins-while-using-docker/bootstrap4-can-be-uninstalled.png
  content/images/post-images/2023/06/20/2023-06-20-remove-outdated-plugins-while-using-docker/opengraph.png
  content/images/post-images/2023/06/20/2023-06-20-remove-outdated-plugins-while-using-docker/pending-uninstallation.png
  content/images/post-images/2023/06/20/2023-06-20-remove-outdated-plugins-while-using-docker/popper-can-be-uninstalled.png
  content/images/post-images/2023/06/20/2023-06-20-remove-outdated-plugins-while-using-docker/popper-can-t-be-uninstalled.png
  content/images/post-images/2023/06/20/2023-06-20-remove-outdated-plugins-while-using-docker/remove-the-plugin-binary.png
  content/images/post-images/2023/06/20/2023-06-20-remove-outdated-plugins-while-using-docker/the-following-plugins-are-deprecated-once-more.png
  content/images/post-images/2023/06/20/2023-06-20-remove-outdated-plugins-while-using-docker/the-following-plugins-are-deprecated.png
  content/images/post-images/2023/06/20/2023-06-20-remove-outdated-plugins-while-using-docker/who-is-my-daddy.png
Labels: blogpost

#6481 Move "Pipeline as Code" to Pipeline section
  content/doc/book/pipeline/_chapter.yml
  content/doc/book/pipeline/pipeline-as-code.adoc
  content/redirect/pipeline-as-code.adoc
Labels: documentation

#6482 Advise to use numeric autolink references
  content/blog/2023/05/25/2023-05-25-github-sponsors-jenkinsci-org.adoc
  content/doc/developer/publishing/requesting-hosting.adoc
Labels: blogpost, documentation

#6477 Convert 'Administering Jenkins' wiki page to jenkins.io
  content/doc/book/managing/system-configuration.adoc
  content/doc/book/using/_chapter.yml
  content/doc/book/using/working-with-projects.adoc
  content/images/system-administration/administering-jenkins/home-dir.png
Labels: documentation

#6483 Add a blog post for Jenkins Mirrors IP change
  content/blog/2023/06/22/2023-06-22-mirrors-jenkins-new-IP.adoc
Labels: blogpost

#6484 Updating bom version in tutorial-improve to current latest version
  content/doc/developer/tutorial-improve/update-base-jenkins-version.adoc
Labels: documentation

#6486 Fix check-typos false positive
  .typos.toml
Labels: bug

#6502 Update Linux installation for Java 17
  content/doc/book/installing/linux.adoc
Labels: documentation
