Repository jenkins-infra/jenkins.io, pull requests merged in 2023-11, with the labels that each got.

#6720 feat(blog): Marc s napkin upgrade guide
  content/_data/authors/mwp565733.adoc
  content/blog/2023/10/31/2023-10-31-marc-s-napkin-upgrade-guide.adoc
  content/images/avatars/mwp565733.jpg
  content/images/post-images/2023/10/31/upgrade-guide-this-is-the-way.png
  content/images/post-images/2023/10/31/upgrade-jenkins-from-manage-jenkins.png
Labels: blogpost

#6794 docs: Formatting
  content/doc/book/managing/spawning-processes.adoc
Labels: documentation

#6806 fix(documentation): Misprint.
  content/blog/2023/10/31/2023-10-31-marc-s-napkin-upgrade-guide.adoc
Labels: blogpost

#6805 chore(changelog): add a note about the addition of short `-jdk17` LTS Docker image tags
  content/_data/changelogs/lts.yml
Labels: chore, changelog

#6677 Delete obsolete files on deploy
  Jenkinsfile
Labels: chore

#6808 Revert "Delete obsolete files on deploy"
  Jenkinsfile
Labels: chore

#6810 Revert "Revert "Delete obsolete files on deploy""
  Jenkinsfile
Labels: chore

#6809 [Blog post] Introducing the 2 + 2 + 2 Java support plan
  content/blog/2023/11/2023-11-06-introducing-2-2-2-java-support-plan.adoc
  content/images/post-images/2023/11/06/introducing-2-2-2-java-support-plan-figure1.svg
  content/images/post-images/2023/11/06/introducing-2-2-2-java-support-plan-figure2.svg
  content/images/post-images/2023/11/06/introducing-2-2-2-java-support-plan-figure3.svg
  content/images/post-images/2023/11/06/introducing-2-2-2-java-support-plan-figure4.svg
  content/images/post-images/2023/11/06/introducing-2-2-2-java-support-plan.png
Labels: blogpost

#6816 Delete content/redirects directory
  content/redirects/distributed-builds.adoc
Labels: chore

#6815 Remove quotation marks in archetype filters
  content/doc/developer/tutorial/create.adoc
Labels: documentation

#6817 chore: add redirections for removed outdated content
  content/doc/book/appendix.adoc
  content/doc/book/installing/advanced-installation.adoc
  content/doc/book/pipeline-as-code.adoc
  content/doc/book/reverse-proxy-configuration-apache.adoc
  content/doc/book/reverse-proxy-configuration-haproxy.adoc
  content/doc/book/reverse-proxy-configuration-iis.adoc
  content/doc/book/reverse-proxy-configuration-iptables.adoc
  content/doc/book/reverse-proxy-configuration-nginx.adoc
  content/doc/book/reverse-proxy-configuration-squid.adoc
  content/doc/book/security/agent-to-controller.adoc
  content/doc/book/security/permissions.adoc
  content/doc/book/using/remote-api.adoc
  content/security/gift.adoc
Labels: documentation

#6819 fixup: correct folder for reverse-proxy redirections
  content/doc/book/system-administration/reverse-proxy-configuration-apache.adoc
  content/doc/book/system-administration/reverse-proxy-configuration-haproxy.adoc
  content/doc/book/system-administration/reverse-proxy-configuration-iis.adoc
  content/doc/book/system-administration/reverse-proxy-configuration-iptables.adoc
  content/doc/book/system-administration/reverse-proxy-configuration-nginx.adoc
  content/doc/book/system-administration/reverse-proxy-configuration-squid.adoc
Labels: documentation

#6822 Add a banner in weekly changelog about Java 17 by default for the Windows image
  content/_data/changelogs/weekly.yml
Labels: changelog

#6755 feat(dependencies): Tracks Jenkins' last split/oldest weekly/oldest LTS versions thanks to `updatecli`.
  updatecli/scripts/jenkins-split.sh
  updatecli/updatecli.d/jenkins-lts.yaml
Labels: chore

#6824 Add note about including the ssh-XXX prefix
  content/doc/book/using/using-agents.adoc
Labels: documentation

#6827 Add clarification to Java platform blog post
  content/blog/2023/11/2023-11-06-introducing-2-2-2-java-support-plan.adoc
Labels: blogpost

#6823 feat(documentation): October Newsletter
  content/blog/2023/11/10/2023-11-10-jenkins-october-newsletter.adoc
Labels: blogpost

#6802 Jenkins LTS 2.426.1 - creating changelog & upgrade guide
  content/_data/changelogs/lts.yml
  content/_data/upgrades/2-426-1.adoc
Labels: changelog

#6830 feat(documentation): Adds a github-actions section in the dependabot sample file.
  content/doc/developer/tutorial-improve/automate-dependency-update-checks.adoc
Labels: documentation

#6829 feat: Replace gsoc redirection with actual contents for 2023
  content/projects/gsoc/2023/index.adoc
Labels: gsoc

#6831 Use consistent page titles for GSoC summaries
  content/projects/gsoc/2022/index.adoc
  content/projects/gsoc/2023/index.adoc
Labels: gsoc

#6832 Link to GSoC 2024 ideas
  content/projects/gsoc/students.adoc
Labels: gsoc

#6835 Remove version specific detail from text
  content/doc/developer/tutorial/create.adoc
Labels: documentation

#6828 Blog post: Jenkins Contributor Summit (FOSDEM)
  content/blog/2023/11/2023-11-10-Jenkins-Contributor-Summit-in-Brussels.adoc
  content/images/post-images/2023/11/ContribSummit/20180918_062844.jpg
  content/images/post-images/2023/11/ContribSummit/Contributor_summit_2024.png
  content/images/post-images/2023/11/ContribSummit/Jenkins_at_fosdem.jpg
  content/images/post-images/2023/11/ContribSummit/Jenkins_desk.jpg
  content/images/post-images/2023/11/ContribSummit/fosdem.videobox.logo.svg
  content/images/post-images/2023/11/ContribSummit/image.jpg
Labels: blogpost

#6836 Remove clear of proxy set header connection
  content/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-nginx.adoc
Labels: bug, documentation

#6840 Document obsolescence of jenkins.CLI.disabled flag
  content/doc/book/managing/system-properties.adoc
Labels: documentation

#6844 Add a banner in 2.426.1 LTS changelog about noticeable changes for the Windows images
  content/_data/changelogs/lts.yml
Labels: changelog

#6845 Remove extra entry from 2.426.1 changelog
  content/_data/changelogs/lts.yml
Labels: bug, changelog

#6847 Document JCasC requires changes due to Appearance
  content/_data/upgrades/2-426-1.adoc
Labels: changelog

#6850 Add Java 21 support to changelog and upgrade guide
  content/_data/changelogs/lts.yml
  content/_data/upgrades/2-426-1.adoc
Labels: bug, changelog

#6851 Fix link to Prototype epic, update plugins with known issues
  content/_data/upgrades/2-426-1.adoc
Labels: changelog

#6852 Update the oldest LTS supported version to the latest patch
  updatecli/scripts/jenkins-oldest-supported-version.sh
  updatecli/updatecli.d/jenkins-lts.yaml
Labels: chore

#6857 chore(documentation): Choosing a Jenkins version
  updatecli/updatecli.d/jenkins-lts.yaml
Labels: chore, updatecli

#6864 Feat: Add GSoC 2024 project idea drafts
  content/_data/authors/rahulsom.adoc
  content/_data/authors/sghill.adoc
  content/projects/gsoc/2024/project-ideas/adding-additional-probes-to-plugin-health-score.adoc
  content/projects/gsoc/2024/project-ideas/automatic-specification-generator-for-jenkins-rest-api.adoc
  content/projects/gsoc/2024/project-ideas/buiilding-ios-app.adoc
  content/projects/gsoc/2024/project-ideas/cloudevents-plugin.adoc
  content/projects/gsoc/2024/project-ideas/enhancing-an-existing-llm-model-with-domain-specific-jenkins-knowledge.adoc
  content/projects/gsoc/2024/project-ideas/implementing-ui-for-jenkins-infra-statistics.adoc
  content/projects/gsoc/2024/project-ideas/using-bearer-token-authentication-for-the-git-plugin-and-git-client-plugin.adoc
  content/projects/gsoc/2024/project-ideas/using-moderne_io-to-modernize-jenkins-plugins-in-an-industrial-way.adoc
  content/projects/gsoc/2024/project-ideas/using-openrewrite-recipes-for-plugin-modernization-or-automation-plugin-build-metadata-updates.adoc
  content/projects/gsoc/2024/project-ideas/using-opentelemetry-for-jenkins-jobs-on-ci_jenkins_io.adoc
Labels: gsoc, documentation

#6866 Prevent symbol substitution
  content/doc/developer/architecture/remoting.adoc
Labels: documentation

#6871 Document the outcome if 'ssh -T git@github.com' was successful
  content/doc/developer/publishing/releasing-manually.adoc
Labels: documentation

#6872 Update archetypes version to 1.22
  content/doc/developer/tutorial/create.adoc
Labels: documentation

#6875 Make nomination phase a step before the voter phase starts
  content/_data/authors/uhafner.adoc
  content/images/avatars/uhafner.jpg
  content/project/board-election-process.adoc
  content/project/election-walkthrough.adoc
Labels: governance

#6876 Redirect distributed-builds to "Architecting for Scale"
  content/doc/book/security/controller-isolation.adoc
  content/redirect/distributed-builds.adoc
Labels: documentation

#6880 jenkins.io - add packaging entry to weekly 2.434 changelog
  content/_data/changelogs/weekly.yml
Labels: changelog

#6881 Jenkins.io - adding contributor spotlight blog post
  content/blog/2023/11/2023-11-29-jenkins-contributor-spotlight.adoc
  content/images/post-images/2023/11/ContributorSpotlight/jenkins-contributor-spotlight.png
Labels: blogpost

#6884 Remove references to archived `executable-war` GitHub repository
  content/doc/book/managing/system-properties.adoc
  content/doc/developer/initialization/embedded-container.adoc
  content/doc/developer/initialization/index.adoc
Labels: documentation

#6886 Mark JENKINS-63286 as released
  content/_data/roadmap/roadmap.yml
Labels: roadmap

#6885 Migrate documentation about splitting a plugin from the old wiki
  content/doc/developer/plugin-development/_chapter.yml
  content/doc/developer/plugin-development/split-plugin-from-core.adoc
Labels: documentation

#6888 Remove unused code to compute core baseline recommendations
  content/_layouts/corebaseline.html.haml
  content/doc/developer/plugin-development/choosing-jenkins-baseline.adoc
Labels: documentation
