Repository jenkins-infra/jenkins.io, pull requests merged in 2023-10, with the labels that each got.

#6730 script update for prototype js removal
  content/blog/2023/05/12/2023-05-12-removing-prototype-from-jenkins.adoc
Labels: blogpost

#6675 [JEP-237] Introduce initial documentation for FIPS-140
  content/doc/book/managing/system-properties.adoc
  content/doc/book/system-administration/FIPS-140.adoc
  content/doc/book/system-administration/_chapter.yml
  content/doc/developer/FIPS-140/_chapter.yml
  content/doc/developer/FIPS-140/index.adoc
  content/doc/developer/_book.yml
Labels: documentation

#6717 feat(dependencies): Tracks Jenkins' three last LTS versions.
  content/_layouts/corebaseline.html.haml
  content/doc/developer/plugin-development/choosing-jenkins-baseline.adoc
  content/doc/developer/tutorial-improve/update-base-jenkins-version.adoc
  updatecli/scripts/jenkins-lts.sh
  updatecli/updatecli.d/jenkins-lts.yaml
Labels: chore, documentation

#6741 Update node.js from 18.x to 20.x
  .github/renovate.json
  .node-version
  Dockerfile
  Jenkinsfile_k8s
  scripts/node
Labels: dependencies, chore

#6751 Restore placeholder calculation for version selection page
  content/doc/developer/plugin-development/choosing-jenkins-baseline.adoc
Labels: bug, documentation

#6742 Add "Prototype removed" blog post
  content/blog/2023/10/09/2023-10-09-prototype-removed.adoc
Labels: blogpost

#6762 Update release date for 2.427
  content/_data/changelogs/weekly.yml
Labels: changelog

#6743 Updating 'report issues' page with the link to report helpdesk issues
  content/participate/report-issue.adoc
Labels: hacktoberfest, hacktoberfest-accepted

#6761 Jenkins LTS 2.414.3 - creating changelog & upgrade guide
  content/_data/changelogs/lts.yml
  content/_data/upgrades/2-414-3.adoc
Labels: changelog

#6754 Add documentation regarding logging secrets
  content/doc/developer/security/misc.adoc
Labels: documentation

#6747 feat(blog): September newsletter.
  content/blog/2023/10/12/2023-10-12-jenkins-september-newsletter.adoc
  content/images/post-images/2023/10/12/2023-10-12-jenkins-september-newsletter/image1.png
  content/images/post-images/2023/10/12/2023-10-12-jenkins-september-newsletter/image2.jpg
Labels: blogpost

#6768 Jenkins.io - LTS 2.414.3 add winstone & jetty upgrade entry
  content/_data/changelogs/lts.yml
Labels: changelog

#6633 Download the Debian/Ubuntu repository signature with wget, not curl
  content/doc/book/installing/linux.adoc
Labels: documentation

#6771 Link from changelog to CVE-2023-44487
  content/_data/changelogs/lts.yml
Labels: changelog

#6777 Restore note on hostname, fix formatting
  content/doc/developer/publishing/releasing-manually.adoc
Labels: documentation

#6786 Fix: Update meta tag name to property for description and og image
  content/_layouts/frame.html.haml
Labels: hacktoberfest

#6778 Improved Section Headline Clarity by Removing Italic Style
  content/doc/book/security/access-control.adoc
Labels: documentation

#6789 Add a note to LTS 2.414.3 changelog to warn about short tags and Java 17
  content/_data/changelogs/lts.yml
Labels: changelog

#6792 Proposes blog post for PHS display in plugin-site
  content/blog/2023/10/25/2023-10-25-what-is-the-plugin-health-score.adoc
  content/images/post-images/2023/10/25/2023-10-25-what-is-the-plugin-health-score/plugin-health-score-mailer.png
  content/images/post-images/2023/10/25/2023-10-25-what-is-the-plugin-health-score/plugin-health-scoring-system.png
Labels: blogpost

#6795 Update GSoC main page for 2024
  content/projects/gsoc/2024/application.adoc
  content/projects/gsoc/2024/index.adoc
  content/projects/gsoc/2024/project-ideas.html.haml
  content/projects/gsoc/2024/project-ideas/buiilding-android-app.adoc
  content/projects/gsoc/2024/project-ideas/buiilding-ios-app.adoc
  content/projects/gsoc/2024/project-ideas/plugin-installation-manager-tool.adoc
  content/projects/gsoc/2024/project-ideas/prj-idea-template.adoc_text
  content/projects/gsoc/2024/project-ideas/screenshot-automation.adoc
  content/projects/gsoc/index.adoc
Labels: hacktoberfest, gsoc

#5900 Added a lighttpd reverse proxy example
  content/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/index.adoc
  content/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-lighttpd.adoc
Labels: documentation

#6799 #6259 Improve link title
  content/doc/book/index.html.haml
Labels: documentation
