Repository jenkins-infra/jenkins.io, pull requests merged in 2023-08, with the labels that each got.

#6566 Add Pomerium reverse proxy guide
  content/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/_section.yml
  content/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/index.adoc
  content/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-pomerium.adoc
Labels: documentation

#6562 Jenkins.io - Create blog post for Java 17 transition
  content/blog/2023/08/01/2023-08-01-documentation-transition-to-java-17.adoc
  content/images/post-images/2023/08/01/jenkins-supports-java-17.png
Labels: blogpost

#6455 feature(dependencies): Adds updatecli to track dependencies
  .github/dependabot.yml
  .github/workflows/updatecli.yaml
  content/doc/book/installing/_docker-for-tutorials.adoc
  updatecli/updatecli.d/blueocean.yaml
  updatecli/updatecli.d/docker-workflow.yaml
  updatecli/updatecli.d/golang.yaml
  updatecli/updatecli.d/maven.yaml
  updatecli/updatecli.d/node.yaml
  updatecli/updatecli.d/php.yaml
  updatecli/updatecli.d/python.yaml
  updatecli/updatecli.d/ruby.yaml
  updatecli/values.github-action.yaml
Labels: chore, documentation, roadmap

#6570 feature(documentation): July 2023 Newsletter
  content/blog/2023/08/02/2023-08-02-jenkins-july-newsletter.adoc
  content/images/post-images/2023/08/02/2023-08-02-jenkins-july-newsletter/image1.png
Labels: blogpost

#6585 Add an example how to test shared pipeline library changes
  content/doc/book/pipeline/shared-libraries.adoc
Labels: documentation

#6587 Jenkins.io - 2.417 changelog adding entry from packaging
  content/_data/changelogs/weekly.yml
Labels: changelog

#6546 Adapt CSP documentation to jenkinsci/jenkins#8273
  content/doc/book/security/configuring-content-security-policy.adoc
Labels: documentation

#6602 Explicitly note removal of System V init scripts
  content/_data/changelogs/lts.yml
  content/_data/changelogs/weekly.yml
Labels: changelog

#6605 Align LTS javadoc list with baseline recommendations
  content/doc/developer/javadoc.html.haml
Labels: documentation

#6606 Remove proxy_buffering directive from nginx config
  content/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-nginx.adoc
Labels: documentation

#6608 Update Windows installation screenshots
  content/doc/book/installing/windows.adoc
  content/doc/book/resources/tutorials/windows-finish-install.png
  content/doc/book/resources/tutorials/windows-install.png
  content/doc/book/resources/tutorials/windows-installation-destination.png
  content/doc/book/resources/tutorials/windows-installation-progress.png
  content/doc/book/resources/tutorials/windows-installation-setup-wizard.png
  content/doc/book/resources/tutorials/windows-jenkins-logon-credentials.jpg
  content/doc/book/resources/tutorials/windows-jenkins-logon-credentials.png
  content/doc/book/resources/tutorials/windows-select-features-to-install.png
  content/doc/book/resources/tutorials/windows-select-jdk-installation.png
  content/doc/book/resources/tutorials/windows-select-port.png
Labels: documentation

#6614 Jenkins.io - Update weekly.yml entries for 2.419
  content/_data/changelogs/weekly.yml
Labels: changelog

#6615 Jenkins.io - weekly 2.419 changelog adding entries based on github release notes
  content/_data/changelogs/weekly.yml
Labels: changelog

#6616 Fix typo in docker.adoc
  content/doc/book/pipeline/docker.adoc
Labels: documentation

#6624 Announce Linux container images rebuilt
  content/blog/2023/08/22/2023-08-22-linux-containers-rebuilt.adoc
  content/images/post-images/2023/08/22/2023-08-22-linux-containers-rebuilt/linux-containers-rebuilt.png
Labels: blogpost

#6627 Update system-properties.adoc
  content/doc/book/managing/system-properties.adoc
Labels: documentation

#6597 Jenkins LTS 2.414.1 - Adding changelog & upgrade guide
  content/_data/changelogs/lts.yml
  content/_data/upgrades/2-414-1.adoc
Labels: changelog

#6618 Blog post for the summer internship in Jenkins security
  content/_data/authors/andreachiera.adoc
  content/blog/2023/08/23/2023-08-23-summer-internship-in-jenkins-security.adoc
  content/images/avatars/andreachiera.jpg
  content/images/post-images/2023/08/23/2023-08-23-summer-internship-in-jenkins-security.png
Labels: blogpost

#6632 Minor updated to the CoC
  content/project/conduct.adoc
Labels: governance

#6631 Include 2.414.1 in SECURITY-3188 list of releases with fix
  content/_data/changelogs/lts.yml
  content/security/advisory/2023-07-26.adoc
Labels: changelog

#6628 Add final blog for GitLab Plugin Modernization project
  content/blog/2023/08/24/2023-08-24-gitlab-plugin-modernization-report.adoc
Labels: gsoc, blogpost

#6636 Added missing link to Pull Request
  content/blog/2023/08/24/2023-08-24-gitlab-plugin-modernization-report.adoc
Labels: blogpost

#6634 GSoC Docker Quickstart Project Blog
  content/blog/2023/08/24/2023-08-24-gsoc-docker-based-quickstart.adoc
  content/images/post-images/2023/08/24/2023-08-24-Screenshot-custom-container.png
  content/images/post-images/2023/08/24/2023-08-24-Screenshot-docker-in-docker.png
  content/images/post-images/2023/08/24/2023-08-24-Screenshot-dockerfile.png
Labels: blogpost

#6641 Footnote to GitHub branch source, not deprecated plugin
  content/doc/book/pipeline/index.adoc
Labels: documentation

#6649 Correct a single spelling error for fastly
  content/blog/2022/11/2022-11-24-jenkins-sponsor-appreciation.adoc
Labels: blogpost

#6635 feat(documention): Blog post about RISC-V and JDK21
  content/blog/2023/08/30/2023-08-30-a-glimpse-of-the-future.adoc
  content/images/post-images/2023/08/30/2023-08-30-a-glimpse-of-the-future/a-glimpse-of-the-future.png
  content/images/post-images/2023/08/30/2023-08-30-a-glimpse-of-the-future/image1.png
  content/images/post-images/2023/08/30/2023-08-30-a-glimpse-of-the-future/image2.png
  content/images/post-images/2023/08/30/2023-08-30-a-glimpse-of-the-future/image3.png
Labels: blogpost
