Repository jenkins-infra/jenkins.io, pull requests merged in 2023-09, with the labels that each got.

#6657 DevOps World Tour 2023 blog post
  content/blog/2023/09/05/2023-09-06-devops-world-tour.adoc
  content/images/post-images/2023/09/05/2023-09-05-devops-world-tour.png
Labels: blogpost

#6659 Update 2023-09-06-devops-world-tour.adoc
  content/blog/2023/09/05/2023-09-06-devops-world-tour.adoc
Labels: blogpost

#6658 Announce Artifactory bandwidth reduction
  content/blog/2023/09/06/2023-09-06-artifactory-bandwidth-reduction.adoc
  content/images/post-images/2023/09/06/2023-09-06-artifactory-bandwidth-reduction.png
Labels: blogpost

#6661 Fix minor blog post error
  content/blog/2023/09/06/2023-09-06-artifactory-bandwidth-reduction.adoc
Labels: bug, blogpost

#6653 GSoC 2023: JSR-305 probe blog
  content/blog/2023/09/09/2023-09-09-jsr305-probe-blog.adoc
  content/images/gsoc/2023/jagruti/jsr-305-probe-image.png
Labels: gsoc, blogpost

#6664 Remove incorrect reference to SPI
  content/press.adoc
Labels: bug

#6667 jenkins.io - Adding 2.414.2 changelog & upgrade guide
  content/_data/changelogs/lts.yml
  content/_data/upgrades/2-414-2.adoc
Labels: changelog

#6671 Update archetypes version
  content/doc/developer/tutorial/create.adoc
Labels: documentation

#6679 Break new hard links
  content/blog/2019/02/2019-02-06-ssh-steps-for-jenkins-pipeline.adoc
  content/blog/2020/03/2020-03-02-pipeline-authoring-sig-update.adoc
  content/blog/2023/02/2023-02-28-build-msi-locally.adoc
  content/blog/2023/04/12/2023-04-12-jenkins-march-newsletter.adoc
  content/blog/2023/05/04/2023-05-04-gsoc2023-projects-announcement.adoc
  content/blog/2023/07/22/2023-07-22-gsoc-2023-midterm.adoc
  content/doc/book/scaling/architecting-for-scale.adoc
  content/merchandise.adoc
Labels: chore

#6663 Publish election announcement 2023
  content/_data/indexpage/carousel.yml
  content/blog/2023/09/18/2023-09-18-board-officer-election-announcement.adoc
  content/images/governance/elections/2023/2023-announcement-opengraph.svg
Labels: blogpost

#6681 doc: book: pipeline: syntax: Fix 'when' directive list formatting
  content/doc/book/pipeline/syntax.adoc
Labels: documentation

#6684 Hacktoberfest 2023 announcement blog
  content/blog/2023/09/20/2023-09-20-Hacktoberfest-2023.adoc
Labels: blogpost

#6687 Remove WMI Windows Agent reference
  content/doc/book/scaling/architecting-for-scale.adoc
Labels: bug, documentation

#6644 GSoC contributor blog for Renovate probe
  content/blog/2023/09/20/2023-09-20-renovate-bot-probe-blog.adoc
  content/images/gsoc/2023/jagruti/renovate-probe.jpg
Labels: gsoc, blogpost

#6694 jenkins.io - two small fixes in hacktoberfest blog
  content/blog/2023/09/20/2023-09-20-Hacktoberfest-2023.adoc
Labels: blogpost

#6674 feat(blog): August Newsletter
  content/blog/2023/09/21/2023-09-21-jenkins-august-newsletter.adoc
Labels: blogpost

#6696 Test with Java 17 and Java 21
  content/doc/developer/tutorial-improve/add-a-jenkinsfile.adoc
Labels: documentation

#6662 GSoC 2023: Incremental build detection blog post
  content/blog/2023/09/09/2023-09-09-incremental-build-detection-probe.adoc
  content/images/gsoc/2023/jagruti/incremental-build-detection-probe.png
Labels: blogpost

#6697 jenkins.io - update publication date in filename and move to correct directory
  content/blog/2023/09/2023-09-22-incremental-build-detection-probe.adoc
Labels: blogpost

#6685 Jenkins.io - Create platform information section
  content/blog/2018/06/2018-06-17-running-jenkins-with-java10-11.adoc
  content/blog/2018/12/2018-12-14-java11-preview-availability.adoc
  content/blog/2022/03/2022-03-21-java17-preview-availability.adoc
  content/blog/2023/01/2023-01-12-jenkins-newsletter.adoc
  content/blog/2023/05/30/2023-05-30-operating-system-end-of-life.adoc
  content/blog/2023/08/02/2023-08-02-jenkins-july-newsletter.adoc
  content/doc/administration/requirements/java.adoc
  content/doc/administration/requirements/linux.adoc
  content/doc/administration/requirements/servlet-containers.adoc
  content/doc/administration/requirements/upgrade-java-guidelines.adoc
  content/doc/administration/requirements/upgrade-java-to-17.adoc
  content/doc/administration/requirements/web-browsers.adoc
  content/doc/administration/requirements/windows.adoc
  content/doc/book/_book.yml
  content/doc/book/installing/_installation_requirements.adoc
  content/doc/book/installing/index.adoc
  content/doc/book/installing/linux.adoc
  content/doc/book/installing/other.adoc
  content/doc/book/installing/servlet-containers.adoc
  content/doc/book/installing/war-file.adoc
  content/doc/book/managing/nodes.adoc
  content/doc/book/platform-information/_chapter.yml
  content/doc/book/platform-information/index.adoc
  content/doc/book/platform-information/support-policy-java.adoc
  content/doc/book/platform-information/support-policy-linux.adoc
  content/doc/book/platform-information/support-policy-servlet-containers.adoc
  content/doc/book/platform-information/support-policy-web-browsers.adoc
  content/doc/book/platform-information/support-policy-windows.adoc
  content/doc/book/platform-information/upgrade-java-to-11.adoc
  content/doc/book/platform-information/upgrade-java-to-17.adoc
  content/sigs/platform/index.adoc
Labels: blogpost, documentation

#6701 Blog Post for GSoC Building Jenkins.io with Alternative Tools
  content/blog/2023/09/24/2023-09-24-building-jenkinsio-with-alternative-tools.adoc
Labels: gsoc, blogpost

#6703 Document a Branch API plugin flag.
  content/doc/book/managing/system-properties.adoc
Labels: documentation

#6708 Correct bad copy-paste in August newsletter
  content/blog/2023/09/21/2023-09-21-jenkins-august-newsletter.adoc
Labels: blogpost

#6709 Guest blog Mergify - Supercharge Your Jenkins Workflow with Mergify
  content/_data/authors/jd.adoc
  content/blog/2023/09/2023-09-26-Supercharge-Your-Jenkins-Workflow-with-Mergify.adoc
  content/images/avatars/jd.jpg
  content/images/post-images/feature-mergify.png
Labels: blogpost

#6722 Include fontconfig in RHEL and Fedora Linux installs
  content/doc/book/installing/linux.adoc
Labels: documentation

#6721 Include fontconfig in Debian Linux install
  content/doc/book/installing/linux.adoc
Labels: documentation

#6719 Update Java platform support documentation
  content/doc/book/installing/windows.adoc
  content/doc/book/managing/system-properties.adoc
  content/doc/book/platform-information/support-policy-java.adoc
  content/doc/developer/handling-requests/deprecated-reflective-access.adoc
  content/doc/developer/internationalization/i18n-jelly-views.adoc
  content/doc/developer/tutorial-improve/review-build-status.adoc
  content/doc/developer/tutorial-improve/update-parent-pom.adoc
  content/doc/developer/tutorial/prepare.adoc
  content/doc/pipeline/tour/getting-started.adoc
  content/doc/tutorials/tutorial-for-installing-jenkins-on-AWS.adoc
Labels: documentation
