Repository jenkins-infra/jenkins.io, pull requests merged in 2023-03, with the labels that each got.

#6096 Unlink hard links in changelog and roadmap
  content/_data/changelogs/lts.yml
  content/_data/changelogs/weekly.yml
  content/_data/logo/chatterbox.yml
  content/_data/roadmap/roadmap.yml
  content/blog/2017/04/2017-04-27-columbia.adoc
  content/blog/2020/01/2020-01-29-gsoc-report.adoc
  content/projects/advocacy-and-outreach/outreach-programs.adoc
  content/projects/blueocean/roadmap/index.adoc
Labels: chore

#6098 Use non-deprecated property for ping interval
  content/doc/book/system-administration/monitoring.adoc
Labels: documentation

#6086 Switch to GH issue form syntax
  .github/ISSUE_TEMPLATE/1-documentation.md
  .github/ISSUE_TEMPLATE/1-documentation.yml
  .github/ISSUE_TEMPLATE/2-wiki-migration.md
  .github/ISSUE_TEMPLATE/2-wiki-migration.yml
  .github/ISSUE_TEMPLATE/3-enhancement.md
  .github/ISSUE_TEMPLATE/3-enhancement.yml
  .github/ISSUE_TEMPLATE/4-bug.md
  .github/ISSUE_TEMPLATE/4-bug.yml
  content/_layouts/frame.html.haml
Labels: chore

#6106 Update archetypes version
  content/doc/developer/tutorial/create.adoc
Labels: documentation

#6102 Describe Temurin preference of the Jenkins project
  content/doc/administration/requirements/java.adoc
Labels: documentation

#6107 fix(Developer Documentation - Plugin Release Tips) correct invalid link to CD
  content/doc/developer/plugin-development/plugin-release-tips.adoc
Labels: bug, documentation

#6097 feat(documentation): miniJen introductory post.
  content/blog/2023/03/03/2023-03-03-miniJen-is-alive.adoc
  content/images/post-images/2023/03/03/2023-03-03-miniJen-is-alive/NanoPi_Duo2-2.png
  content/images/post-images/2023/03/03/2023-03-03-miniJen-is-alive/NanoPi_R5S-01B.png
  content/images/post-images/2023/03/03/2023-03-03-miniJen-is-alive/fosdem_2023_booth_display.jpg
  content/images/post-images/2023/03/03/2023-03-03-miniJen-is-alive/image2.png
  content/images/post-images/2023/03/03/2023-03-03-miniJen-is-alive/mq-pro.png
  content/images/post-images/2023/03/03/2023-03-03-miniJen-is-alive/mq-quad.png
  content/images/post-images/2023/03/03/2023-03-03-miniJen-is-alive/pine-power.png
  content/images/post-images/2023/03/03/2023-03-03-miniJen-is-alive/round-booth-display-2023-02-02-transparent.png
Labels: blogpost

#6105 Use non-deprecated property for ping interval
  content/doc/book/system-administration/monitoring.adoc
Labels: documentation

#6093 Jenkins.io - Add 2.387.1 changelog and upgrade guide
  content/_data/changelogs/lts.yml
  content/_data/upgrades/2-387-1.adoc
Labels: changelog

#6116 Jenkins.io blog - fix outreach label on FOSDEM post
  content/blog/2023/02/2023-02-21-thoughts-on-FOSDEM-2023.adoc
Labels: blogpost

#6078 Label conflicting PRs
  .github/workflows/label-conflicting-prs.yml
Labels: chore

#6087 Extend the documentation to html files
  content/doc/developer/internationalization/i18n-jelly-views.adoc
Labels: documentation

#6118 [Bug] - Fixed Broken Links [#3335]
  content/blog/2016/2016-05-10-jenkins-20-vjam.adoc
Labels: chore

#6117 [Bug] - Fixed Broken Links
  content/_data/changelogs/lts.yml
  content/_data/changelogs/weekly.yml
  content/blog/2021/12/2021-12-22-deprecated-ruby-runtime.adoc
  content/blog/2022/10/2022-10-03-scaling-out-iOS-builds-on-AWS-with-EC2-mac.adoc
  content/doc/book/managing/spawning-processes.adoc
Labels: chore

#6122 Declare manually controlled prefix for CD as optional
  content/doc/developer/publishing/releasing-cd.adoc
Labels: documentation

#6130 indent opengraph image data
  content/blog/2023/02/2023-02-07-jenkins-newsletter.adoc
  content/blog/2023/02/2023-02-21-thoughts-on-FOSDEM-2023.adoc
  content/blog/2023/02/2023-02-23-cdf-awards.adoc
  content/blog/2023/03/03/2023-03-03-miniJen-is-alive.adoc
  content/blog/2023/03/03/2023-03-09-jira-donation.adoc
Labels: blogpost, squash-merge-me

#6126 Jenkins Awards - New blog post announcing nominees & voting
  content/blog/2023/03/09/2023-03-09-jenkins-awards-2023-candidates.adoc
  content/blog/2023/03/09/2023-03-09-jira-donation.adoc
Labels: blogpost

#6123 February Newsletter blog post
  content/blog/2023/03/10/2023-03-09-jenkins-newsletter.adoc
  content/images/post-images/2023/03/10/2023-03-10-jenkins-newsletter/image3.png
  content/images/post-images/2023/03/10/2023-03-10-jenkins-newsletter/image4.png
Labels: blogpost

#6132 Jenkins.io - February newsletter update for security
  content/blog/2023/03/09/2023-03-09-jenkins-newsletter.adoc
Labels: blogpost

#6133 Jenkins.io - update security author for Feb. blog post
  content/blog/2023/03/09/2023-03-09-jenkins-newsletter.adoc
Labels: blogpost

#6134 Jenkins.io - Fix list formatting in newsletter
  content/blog/2023/03/09/2023-03-09-jenkins-newsletter.adoc
Labels: blogpost

#6136 AWS-tutorial spelling correction
  content/doc/tutorials/tutorial-for-installing-jenkins-on-AWS.adoc
Labels: documentation

#6027 Update Node, ruby and builder image
  .node-version
  .ruby-version
  Dockerfile
  Jenkinsfile_k8s
  scripts/node
  scripts/ruby
Labels: chore

#6114 Minijen and riscv
  content/blog/2023/03/10/2023-03-10-miniJen-and-RISC-V.adoc
  content/images/post-images/2023/03/10/2023-03-10-miniJen-and-RISC-V/docker-on-arm.png
  content/images/post-images/2023/03/10/2023-03-10-miniJen-and-RISC-V/docker-supported-architectures.png
  content/images/post-images/2023/03/10/2023-03-10-miniJen-and-RISC-V/giveaway.png
  content/images/post-images/2023/03/10/2023-03-10-miniJen-and-RISC-V/openjdk-job.png
  content/images/post-images/2023/03/10/2023-03-10-miniJen-and-RISC-V/proposal.png
  content/images/post-images/2023/03/10/2023-03-10-miniJen-and-RISC-V/simplest-riscv-job-possible.png
  content/images/post-images/2023/03/10/2023-03-10-miniJen-and-RISC-V/temurin-supported-architectures.png
  content/images/post-images/2023/03/10/2023-03-10-miniJen-and-RISC-V/temurin.png
Labels: blogpost

#6077 docs: Update content to align with new Manage Jenkins naming
  content/doc/book/blueocean/getting-started.adoc
  content/doc/book/installing/_docker-for-tutorials.adoc
  content/doc/book/installing/_docker.adoc
  content/doc/book/installing/_setup-wizard.adoc
  content/doc/book/installing/war-file.adoc
  content/doc/book/installing/windows.adoc
  content/doc/book/managing/casc.adoc
  content/doc/book/managing/cli.adoc
  content/doc/book/managing/index.adoc
  content/doc/book/managing/plugins.adoc
  content/doc/book/managing/ui-themes.adoc
  content/doc/book/managing/users.adoc
  content/doc/book/pipeline/scaling-pipeline.adoc
  content/doc/book/pipeline/shared-libraries.adoc
  content/doc/book/pipeline/syntax.adoc
  content/doc/book/scaling/architecting-for-manageability.adoc
  content/doc/book/scaling/scaling-jenkins-on-kubernetes.adoc
  content/doc/book/security/controller-isolation.adoc
  content/doc/book/security/controller-isolation/agent-to-controller.adoc
  content/doc/book/security/csrf-protection.adoc
  content/doc/book/security/managing-security.adoc
  content/doc/book/security/markup-formatter.adoc
  content/doc/book/security/services.adoc
  content/doc/book/security/user-content.adoc
  content/doc/book/system-administration/backing-up.adoc
  content/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-iis.adoc
  content/doc/book/using/using-credentials.adoc
  content/doc/book/using/using-jmeter-with-jenkins.adoc
  content/doc/developer/testing/index.adoc
  content/doc/developer/tutorial/run.adoc
  content/doc/pipeline/tour/hello-world.adoc
  content/doc/tutorials/build-a-labview-app.adoc
  content/doc/tutorials/tutorial-for-installing-jenkins-on-AWS.adoc
  content/participate/report-issue.adoc
  content/pipeline/getting-started-pipelines.adoc
  content/projects/gsoc/2020/projects/external-fingerprint-storage.adoc
  content/templates/updates.adoc
Labels: documentation

#6108 (1)Experimental Plugin Releases - superseded by incrementals, & (2)Correct description of controller/built-in node
  content/doc/book/managing/nodes.adoc
  content/doc/developer/publishing/releasing-experimental-updates.adoc
Labels: documentation

#6062 [JENKINS-69955] Add documentation about jenkins.websocket properties
  content/doc/book/managing/system-properties.adoc
Labels: documentation

#5958 Add information about implied dependencies and detached plugin
  content/doc/book/managing/plugins.adoc
  content/doc/book/resources/managing/hover-for-implied-dependencies.png
Labels: documentation

#5985 Update View Logs page in System Administration section
  content/doc/book/system-administration/viewing-logs.adoc
Labels: documentation

#6155 Move renovate.json to .github folder
  .github/renovate.json
Labels: chore

#6139 chore: bump `awestruct-ibeams` version to v0.4.5
  Gemfile
  Gemfile.lock
Labels: chore

#6165 GSoC alternative build tools for jenkins.io - removing myself from mentors
  content/projects/gsoc/2023/project-ideas/alternative-jenkinsio-build-tool.adoc
Labels: gsoc

#6169 Linkify 'osi-approved'
  content/doc/developer/publishing/preparation.adoc
  content/doc/developer/publishing/source-code-hosting.adoc
  content/project/governance.adoc
Labels: governance, documentation

#6174 Fix typo in today's security advisory
  content/security/advisory/2023-03-21.adoc
Labels: chore

#6175 Add support for non-CI (especially Mac OS) use of typos in make check
  Makefile
  scripts/check-typos
Labels: chore, squash-merge-me

#6164 Made changes to 'Upgrading Jenkins' documentation
  content/doc/administration/requirements/upgrade-java-guidelines.adoc
  content/doc/book/blueocean/creating-pipelines.adoc
Labels: documentation

#6170 Update datatables to 1.13.4
  content/doc/developer/publishing/source-code-hosting.adoc
  content/doc/developer/publishing/source-code-hosting/forks.adoc
Labels: chore, documentation

#6180 Advise users to test their SSH connection before performing a release
  content/doc/developer/publishing/releasing-manually.adoc
Labels: documentation

#6181 Withdraw 3 GSoC 2023 project ideas as discussed and announced
  content/projects/gsoc/2023/project-ideas/JCasC-drift-detector.adoc
  content/projects/gsoc/2023/project-ideas/agent_reconnections_exponential_backoff.adoc
  content/projects/gsoc/2023/project-ideas/displaying_plugin_health_scores.adoc
Labels: gsoc

#6183 Add copy to clipboard button for SHA256 on download page
  content/download/index.html.haml
  content/js/download.js
Labels: enhancement

#6159 `Managing plugins` screenshot update
  content/doc/book/resources/blueocean/intro/blueocean-plugins-filtered.png
  content/doc/book/resources/managing/hover-for-implied-dependencies.png
  content/doc/book/resources/managing/plugin-manager-disable.png
  content/doc/book/resources/managing/plugin-manager-uninstall.png
  content/doc/book/resources/managing/plugin-manager-update.png
Labels: documentation

#6205 Announce deb & rpm signing key change
  content/blog/2023/03/2023-03-27-repository-signing-keys-changing.adoc
  content/doc/book/installing/linux.adoc
  content/doc/tutorials/tutorial-for-installing-jenkins-on-AWS.adoc
  content/images/post-images/2023/03-repository-signing-keys-change/opengraph.png
  docker/default.conf
Labels: blogpost, documentation

#6185 Track jsdeliver dependencies via renovate
  .github/renovate.json
Labels: chore

#6210 Use correct key install instructions
  content/blog/2023/03/2023-03-27-repository-signing-keys-changing.adoc
Labels: blogpost

#6208 Updated screenshot for the page `using-jmeter-with-jenkins`
  content/doc/book/resources/jmeter/jmeter-00.png
  content/doc/book/resources/jmeter/jmeter-01.png
Labels: documentation

#6220 Updating GSoC mentors
  content/projects/gsoc/2023/project-ideas/add-probes-to-plugin-health-score.adoc
  content/projects/gsoc/2023/project-ideas/buiilding-android-app.adoc
  content/projects/gsoc/2023/project-ideas/docker-compose-build.adoc
  content/projects/gsoc/2023/project-ideas/gitlab-plugin-modernization.adoc
Labels: gsoc

#6162 Android and Jenkins: what is the limit?
  content/blog/2023/03/29/2023-03-29-android-and-jenkins.adoc
  content/images/post-images/2023/03/29/2023-03-22-android-and-jenkins/love.png
Labels: blogpost

#6173 Jenkins.io - adding LTS 2.387.2 changelog & upgrade guide
  content/_data/changelogs/lts.yml
  content/_data/upgrades/2-387-2.adoc
Labels: changelog

#6223 Jenkins.io - updating filename to match actual publish date for blog post
  content/blog/2023/03/30/2023-03-30-android-and-jenkins.adoc
Labels: blogpost
