Repository jenkins-infra/jenkins.io, pull requests merged in 2023-07, with the labels that each got.

#6511 Fix dates in operating system end of life blog post
  content/blog/2023/05/30/2023-05-30-operating-system-end-of-life.adoc
Labels: blogpost

#6512 Jenkins.io - Updating Docker installation guide
  content/doc/book/installing/_docker-for-tutorials.adoc
  content/doc/book/installing/_docker.adoc
  content/doc/book/installing/docker.adoc
  content/doc/book/scaling/scaling-jenkins-on-kubernetes.adoc
Labels: documentation

#6521 Jenkins.io - update Docker documentation for Java 17
  content/doc/book/pipeline/docker.adoc
Labels: documentation

#6513 feature(documentation): June 2023 newsletter
  content/blog/2023/07/10/2023-07-10-jenkins-june-newsletter.adoc
Labels: blogpost

#6525 Jenkins.io - Update "Viewing Logs" to use java 17
  content/doc/book/system-administration/viewing-logs.adoc
Labels: documentation

#6524 Jenkins.io - updating Pipeline Syntax for Java 17
  content/doc/book/pipeline/syntax.adoc
Labels: documentation

#6528 Jenkins.io - Update "Managing systemd services" to use java17
  content/doc/book/system-administration/systemd-services.adoc
Labels: documentation

#6532 blog: add an article about the 2023-07-07 outage
  content/blog/2023/06/22/2023-06-22-mirrors-jenkins-new-IP.adoc
  content/blog/2023/07/10/2023-07-12-jenkins-mirrors-postmortem-outage.adoc
Labels: blogpost

#6478 Add best practices page
  content/doc/book/using/_chapter.yml
  content/doc/book/using/best-practices.adoc
Labels: documentation

#6542 Revise brew installation
  content/_partials/osx-brew-installer.html.haml
  content/blog/2019/11/2019-11-25-macos-native-installer-deprecation.adoc
Labels: documentation

#6544 Add reference to system property docs to CSP page
  content/doc/book/security/configuring-content-security-policy.adoc
Labels: documentation

#6533 Jenkins LTS 2.401.3 - add changelog & upgrade guide
  content/_data/changelogs/lts.yml
  content/_data/upgrades/2-401-3.adoc
Labels: changelog

#6543 Jenkins.io - add Java 17 upgrade instructions
  content/doc/administration/requirements/upgrade-java-to-17.adoc
Labels: documentation

#6538 GSoC contributor blog for Third-party repository detection probe
  content/blog/2023/07/16/2023-07-16-third-party-repository-detection-probe.adoc
  content/images/gsoc/2023/jagruti/blog_20230716.png
Labels: blogpost

#6553 Jenkins.io - update to GSoC blog post publish date
  content/blog/2023/07/20/2023-07-20-third-party-repository-detection-probe.adoc
Labels: blogpost

#6554 Fixing “JEP 229” link
  content/_data/upgrades/2-375-1.adoc
Labels: changelog

#6539 GSoC contributor blog for Security Scan Probe
  content/blog/2023/07/16/2023-07-16-security-scan-probe-blog.adoc
  content/images/gsoc/2023/jagruti/blog_20230716-ssp.png
Labels: blogpost

#6507 GSoC contributor blog for Unreleased Production changes probe
  content/blog/2023/07/16/2023-07-16-unreleased-production-changes-probe.adoc
  content/images/gsoc/2023/jagruti/blog_20230702.png
Labels: blogpost

#6556 Add examples of PRs for adding CD to repos
  content/doc/developer/publishing/releasing-cd.adoc
Labels: documentation

#6555 Add GSoC 2023 midterm recap blog post
  content/blog/2023/07/22/2023-07-22-gsoc-2023-midterm.adoc
Labels: blogpost

#6552 Jenkins.io - Update "Build a Java app with Maven" for Java 17
  content/doc/tutorials/build-a-java-app-with-maven.adoc
Labels: documentation

#6558 Document how to nominate and vote people in elections
  content/project/election-walkthrough-screenshots/activate-civs-account.png
  content/project/election-walkthrough-screenshots/confirm-civs-account.png
  content/project/election-walkthrough-screenshots/join-election-group.png
  content/project/election-walkthrough-screenshots/new-message.png
  content/project/election-walkthrough-screenshots/proceed-to-vote.png
  content/project/election-walkthrough-screenshots/send-message.png
  content/project/election-walkthrough-screenshots/voting-successful.png
  content/project/election-walkthrough.adoc
  content/project/index.adoc
Labels: governance, documentation

#6559 Document how to create a poll in CIVS
  content/project/board-election-process.adoc
Labels: governance
