Repository jenkins-infra/jenkins.io, pull requests merged in 2023-04, with the labels that each got.

#6226 Fix class path typo in system info page
  content/doc/book/managing/index.adoc
Labels: chore, documentation

#6228 Unify line endings
  .gitattributes
  content/_data/authors/ayush_agarwal.adoc
  content/_data/authors/berviantoleo.adoc
  content/_data/authors/cyberax.adoc
  content/_partials/release-header.html.haml
  content/blog/2016/2016-01-27-jenkins-world-call-for-papers.adoc
  content/blog/2018/07/2018-07-25-contributor-summit.adoc
  content/blog/2018/08/2018-08-06-serverless-cicd-jenkins.adoc
  content/blog/2018/08/2018-08-21-contributor-summit-nice.adoc
  content/blog/2018/08/2018-08-30-speaker-blog-kubernetes-plugin.adoc
  content/blog/2018/10/2018-10-18-contributor-summit-summary.adoc
  content/blog/2020/08/2020-08-12-windows-installers-upgrade.adoc
  content/changelog-preview/index.html.haml
  content/images/fire-jenkins.svg
  content/images/github-mark.svg
  content/images/jams/SevilleJAM/Seville-JAM_logo.svg
  content/images/jams/SevilleJAM/Seville-JAM_logo_text.svg
  content/images/jar.svg
  content/images/jenkins-x-logo.svg
  content/images/post-images/2020-03-contributhon/she-code-africa-logo.svg
  content/sites/default/files/js/js_a1536c16f414c3cb401d8f77ce2a972d.js
  content/sites/default/files/js/js_e2ad89a451a86d1fc077b476d7498a8f.js
  content/stylesheets/components/_code-highlight.scss
  content/templates/downloads.html.haml
Labels: chore

#6219 Don't consider empty checkRoles as a vulnerability
  content/doc/developer/security/remoting-callables.adoc
  content/security/reporting.adoc
Labels: documentation

#6195 Fixed Broken links #3335
  content/doc/book/installing/_jenkins-command-parameters.adoc
  content/projects/gsoc/2020/project-ideas/pipeline-as-yaml-experiment.adoc
  content/sigs/cloud-native/pluggable-storage.adoc
Labels: gsoc, blogpost, changelog, documentation, squash-merge-me

#6236 Update ruby to 3.2.2
  .node-version
  .ruby-version
  Dockerfile
  Jenkinsfile_k8s
  scripts/node
  scripts/ruby
Labels: chore

#6243 Fix 2.387.2 release date
  content/_data/changelogs/lts.yml
Labels: changelog

#6244 Remove "archive site" stage
  Jenkinsfile
Labels: chore

#6245 Add instructions for Amazon Linux 2023
  content/doc/tutorials/tutorial-for-installing-jenkins-on-AWS.adoc
Labels: documentation

#6247 Add cdCon and Hacktoberfest events
  content/_data/events/2023-05-08-cdcon.adoc
  content/_data/events/2023-10-01-hacktoberfest.adoc
Labels: events

#6249 Added Option for LTS Release
  content/blog/2023/03/2023-03-27-repository-signing-keys-changing.adoc
Labels: blogpost

#6251 Link from LTS changelog to LTS upgrade guide, not blog post
  content/_data/changelogs/lts.yml
  content/_data/upgrades/2-387-2.adoc
Labels: changelog

#6202 Building Android apps with Jenkins: an introduction
  content/blog/2023/04/07/2023-04-07-android-and-jenkins-discovery.adoc
  content/images/post-images/2023/04/07/2023-04-07-android-and-jenkins-discovery/2023-03_plugins.png
  content/images/post-images/2023/04/07/2023-04-07-android-and-jenkins-discovery/profile_of_cicd_users.png
Labels: blogpost

#6255 Reword image compression paragraph to fix page layout
  CONTRIBUTING.adoc
Labels: chore

#6256 Fix CODEOWNERS scope
  .github/CODEOWNERS
Labels: chore

#6258 Keep track of typo action
  .github/renovate.json
Labels: chore

#6229 Update the design of the Blog page
  content/_ext/authorship.rb
  content/_ext/pipeline.rb
  content/_layouts/post.html.haml
  content/_partials/avatar.html.haml
  content/_partials/blogcardlist.html.haml
  content/_partials/blogs.html.haml
  content/_partials/events.html.haml
  content/blog/2022/01/2022-01-07-gsoc-2022.adoc
  content/blog/2022/05/2022-05-27-docker-image-new-lifecycle.adoc
  content/blog/2022/09/2022-09-07-jenkinsfile-runner-as-github-actions.adoc
  content/blog/2022/10/2022-10-10-pipeline-steps-improvement-gsoc-report.adoc
  content/blog/2022/10/2022-10-31-jenkins-google-summer-of-code-archive-2022.adoc
  content/blog/2022/11/2022-11-16-gsoc-2023.adoc
  content/blog/2022/12/2022-12-09-jfrog-maintenance.adoc
  content/blog/2022/12/2022-12-14-require-java-11.adoc
  content/blog/2023/01/2023-01-12-jenkins-newsletter.adoc
  content/blog/2023/02/2023-02-23-cdf-awards.adoc
  content/blog/2023/02/2023-02-28-build-msi-locally.adoc
  content/blog/2023/03/10/2023-03-10-miniJen-and-RISC-V.adoc
  content/blog/2023/04/07/2023-04-07-android-and-jenkins-discovery.adoc
  content/css/jenkins.css
  content/index.html.haml
  content/node/index.html.haml
  content/stylesheets/abstracts/_breakpoints.scss
  content/stylesheets/components/_all.scss
  content/stylesheets/components/_app-bar.scss
  content/stylesheets/components/_author.scss
  content/stylesheets/components/_avatar.scss
  content/stylesheets/components/_buttons.scss
  content/stylesheets/components/_cards.scss
  content/stylesheets/components/_chips.scss
  content/stylesheets/components/_events.scss
  content/stylesheets/components/_pagination.scss
  content/stylesheets/pages/_blog.scss
Labels: enhancement

#6266 Remove UX SIG mailing list entry from table to div page
  content/doc/developer/blueocean-plugin-development/index.adoc
  content/doc/developer/views/icon-path-to-icon-class-migration.adoc
  content/doc/developer/views/table-to-div-migration.adoc
Labels: documentation

#6275 Clarify verb usage in style guide
  content/_data/changelogs/_STYLEGUIDE.adoc
Labels: changelog

#6274 Jenkins.io - correct weekly changelog entries
  content/_data/changelogs/weekly.yml
Labels: changelog

#6252 feat(documentation): March newsletter.
  content/blog/2023/04/10/2023-04-10-jenkins-newsletter.adoc
  content/images/post-images/2023/04/10/2023-04-10-jenkins-newsletter/image1.png
  content/images/post-images/2023/04/10/2023-04-10-jenkins-newsletter/image2.jpg
  content/images/post-images/2023/04/10/2023-04-10-jenkins-newsletter/image3.jpg
  content/images/post-images/2023/04/10/2023-04-10-jenkins-newsletter/image4.jpg
  content/images/post-images/2023/04/10/2023-04-10-jenkins-newsletter/image5.jpg
Labels: blogpost

#6281 Jenkins.io - adding digital ocean appreciation blog post
  content/blog/2023/04/07/2023-04-12-digital-ocean-continued-sponsorship.adoc
Labels: blogpost

#6283 Jenkins.io - update April blog post folders and dates
  content/blog/2023/04/12/2023-04-12-digital-ocean-continued-sponsorship.adoc
  content/blog/2023/04/12/2023-04-12-jenkins-march-newsletter.adoc
Labels: blogpost

#6288 HeroForge 3D model
  content/artwork/index.html.haml
  content/merchandise.adoc
Labels: artwork

#6273 Restore 'Modularise more classes + increase usage of CSS variables (#5415)'
  content/_partials/projectcarousel.html.haml
  content/css/jenkins.css
  content/solutions/index.html.haml
  content/stylesheets/core/_all.scss
  content/stylesheets/core/_base.scss
  content/stylesheets/core/_headings.scss
  content/stylesheets/pages/_all.scss
  content/stylesheets/pages/_use-cases.scss
Labels: documentation

#6289 Use latest bom-2.375.x in examples
  content/doc/developer/plugin-development/dependency-management.adoc
  content/doc/developer/tutorial-improve/update-base-jenkins-version.adoc
  content/doc/developer/tutorial-improve/use-plugin-bill-of-materials.adoc
Labels: documentation

#6294 abhyudayasharma not available as GSoC 2023 mentor
  content/projects/gsoc/2023/project-ideas/plugin-installation-manager-tool.adoc
Labels: gsoc

#6291 Inline Awestruct Ibeams library
  Gemfile
  Gemfile.lock
  content/_config/site.yml
  content/_ext/asciidoc_handler_monkeypatch.rb
  content/_ext/asciidoc_sections.rb
  content/_ext/pipeline.rb
Labels: chore

#6300 Remove more references to inactive SIGs
  content/_data/roadmap/roadmap.yml
  content/blog/2018/07/2018-07-25-contributor-summit.adoc
  content/events/hacktoberfest.adoc
  content/projects/gsoc/2020/project-ideas/jenkins-distribution-customize-service.adoc
  content/projects/infrastructure/index.adoc
  content/sigs/cloud-native/pluggable-storage.adoc
  content/sigs/docs/index.adoc
Labels: gsoc, blogpost, roadmap

#6262 Revise Makefile and add 'help' goal
  CONTRIBUTING.adoc
  Makefile
Labels: enhancement, chore

#5485 Architecting for scale
  content/doc/book/scaling/architecting-for-scale.adoc
Labels: documentation, stalled

#6260 Copy to clipboard button in source block
  content/_layouts/chapter.html.haml
  content/_layouts/developer.html.haml
  content/_layouts/frame.html.haml
  content/_layouts/section.html.haml
  content/_layouts/subsection.html.haml
  content/css/copy-to-clipboard.css
  content/doc/book/installing/_docker-for-tutorials.adoc
  content/doc/book/installing/_docker.adoc
  content/doc/book/installing/_kubernetes.adoc
  content/doc/book/installing/_setup-wizard-for-tutorials.adoc
  content/doc/book/installing/other.adoc
  content/doc/book/installing/war-file.adoc
  content/doc/book/managing/change-system-timezone.adoc
  content/doc/book/managing/nodes.adoc
  content/doc/book/managing/plugins.adoc
  content/doc/book/managing/spawning-processes.adoc
  content/doc/book/pipeline/syntax.adoc
  content/doc/book/scaling/scaling-jenkins-on-kubernetes.adoc
  content/doc/book/system-administration/monitoring.adoc
  content/doc/book/troubleshooting/diagnosing-errors.adoc
  content/doc/book/using/using-jmeter-with-jenkins.adoc
  content/doc/developer/building/intellij.adoc
  content/doc/developer/extensibility/serialization-of-anonymous-classes.adoc
  content/doc/developer/handling-requests/actions.adoc
  content/doc/developer/handling-requests/json.adoc
  content/doc/developer/publishing/continuous-integration.adoc
  content/doc/developer/publishing/releasing-manually.adoc
  content/doc/developer/publishing/style-guides.adoc
  content/doc/developer/security/index.adoc
  content/doc/developer/tutorial-improve/_create-a-pull-request.adoc
  content/doc/developer/tutorial-improve/add-a-link-to-report-an-issue.adoc
  content/doc/developer/tutorial-improve/enable-incrementals.adoc
  content/doc/developer/tutorial-improve/update-parent-pom.adoc
  content/doc/developer/tutorial-improve/update-scm-url.adoc
  content/doc/developer/tutorial/create.adoc
  content/doc/developer/tutorial/prepare.adoc
  content/doc/developer/tutorial/run.adoc
  content/images/octicons-16.svg
  content/js/copy-to-clipboard.js
Labels: documentation

#6319 Updates stages allowed location
  content/doc/book/pipeline/syntax.adoc
Labels: documentation

#6323 Turn down renovate
  .github/renovate.json
Labels: chore

#6325 Updated jenkinsfile.adoc, incorrect referral fixed
  content/doc/book/pipeline/jenkinsfile.adoc
Labels: documentation

#6332 Remove link to Google cloud build tutorial
  content/doc/tutorials/tutorials-for-installing-jenkins-on-Google-Cloud.adoc
Labels: documentation

#6331 Redirect IBM cloud tutorial to Kubernetes install
  content/doc/tutorials/index.adoc
  content/doc/tutorials/tutorial-for-installing-jenkins-on-IBM-Cloud.adoc
  content/download/index.html.haml
Labels: documentation

#6334 Jenkins.io - update for Unlocking Jenkins section of `_setup-wizard.adoc`
  content/doc/book/installing/_setup-wizard.adoc
Labels: documentation

#6338 Fix gitter URLs in contributing.adoc
  CONTRIBUTING.adoc
Labels: bug

#6337 Use node:18.16.0-alpine in examples
  STYLEGUIDE.adoc
  content/doc/book/pipeline/docker.adoc
  content/doc/pipeline/tour/agents.adoc
  content/doc/pipeline/tour/hello-world.adoc
Labels: documentation
