Repository jenkins-infra/jenkins.io, pull requests merged in 2023-12, with the labels that each got.

#6899 Jenkins - LTS 2.426.2 adding changelog and upgrade guide
  content/_data/changelogs/lts.yml
  content/_data/upgrades/2-426-2.adoc
Labels: changelog

#6901 Move Guice 6.x Upgrade to 2.401.2
  content/_data/changelogs/lts.yml
Labels: changelog

#6902 Restore javax.inject to jakarta.inject to 2.414.1
  content/_data/changelogs/lts.yml
Labels: changelog

#6908 Fix 2.428 release date in changelog
  content/_data/changelogs/weekly.yml
Labels: changelog

#6906 Create 2023-12-05-google-summer-of-code-a-call-for-mentors.adoc
  content/blog/2023/12/2023-12-05-google-summer-of-code-a-call-for-mentors.adoc
  content/images/post-images/2023/12/gsoc-call-for-mentors.png
Labels: blogpost

#6910 Jenkins.io - Adding publication schedule to blog post about contributor spotlight
  content/blog/2023/11/2023-11-29-jenkins-contributor-spotlight.adoc
Labels: blogpost

#6889 Cross-posting 'Log from Jenkins Jobs to GitHub Pull Requests as Checks'
  content/_data/authors/tslmy.adoc
  content/blog/2023/11/2023-11-29-jenkins-to-github.adoc
  content/images/avatars/tslmy.png
  content/images/post-images/2023/11/29/Screenshot-of-a-GitHub-Action-as-a-PR-Check.png
  content/images/post-images/2023/11/29/Screenshot-of-a-JUnit-report-on-PR-Checks-tab.png
  content/images/post-images/2023/11/29/Screenshot-of-a-SonarCloud-Code-Analysis-as-a-GitHub-PR-Check.png
  content/images/post-images/2023/11/29/Screenshot-of-a-list-of-commit-statuses.png
  content/images/post-images/2023/11/29/Screenshot-of-a-typical-PR-Checks-list.png
Labels: blogpost

#6915 Update architecting-for-scale.adoc. Fix typo
  content/doc/book/scaling/architecting-for-scale.adoc
Labels: documentation

#6911 Announce board member changes
  content/blog/2023/12/2023-12-08-basil-crow-board-announcement.adoc
  content/images/governance/elections/2023/2023-governance-board-changes.svg
  content/project/board.html.haml
Labels: blogpost, governance

#6914 Jenkins.io blog - Update publish date and paths, add opengraph image for cross-post blog
  content/blog/2023/12/2023-12-06-jenkins-to-github.adoc
  content/images/post-images/2023/12/06/Screenshot-of-a-GitHub-Action-as-a-PR-Check.png
  content/images/post-images/2023/12/06/Screenshot-of-a-JUnit-report-on-PR-Checks-tab.png
  content/images/post-images/2023/12/06/Screenshot-of-a-SonarCloud-Code-Analysis-as-a-GitHub-PR-Check.png
  content/images/post-images/2023/12/06/Screenshot-of-a-list-of-commit-statuses.png
  content/images/post-images/2023/12/06/Screenshot-of-a-typical-PR-Checks-list.png
  content/images/post-images/2023/12/06/jenkins-to-github-checks.png
Labels: blogpost

#6918 Add berviantoleo to some topic ideas
  content/projects/gsoc/2024/project-ideas/automatic-specification-generator-for-jenkins-rest-api.adoc
  content/projects/gsoc/2024/project-ideas/cloudevents-plugin.adoc
  content/projects/gsoc/2024/project-ideas/using-opentelemetry-for-jenkins-jobs-on-ci_jenkins_io.adoc
Labels: gsoc

#6924 Add myself as possible mentor
  content/_data/authors/jonesbusy.adoc
  content/projects/gsoc/2024/project-ideas/adding-additional-probes-to-plugin-health-score.adoc
  content/projects/gsoc/2024/project-ideas/plugin-installation-manager-tool.adoc
  content/projects/gsoc/2024/project-ideas/using-bearer-token-authentication-for-the-git-plugin-and-git-client-plugin.adoc
  content/projects/gsoc/2024/project-ideas/using-openrewrite-recipes-for-plugin-modernization-or-automation-plugin-build-metadata-updates.adoc
Labels: gsoc

#6929 adding myself as potential mentor for GSoC 2024
  content/_data/authors/harsh-ps-2003.adoc
  content/projects/gsoc/2024/project-ideas/enhancing-an-existing-llm-model-with-domain-specific-jenkins-knowledge.adoc
  content/projects/gsoc/2024/project-ideas/using-opentelemetry-for-jenkins-jobs-on-ci_jenkins_io.adoc
Labels: gsoc

#6925 Allow public-domain-equivalent licenses
  content/doc/developer/publishing/preparation.adoc
  content/doc/developer/publishing/source-code-hosting.adoc
  content/project/governance.adoc
Labels: governance, documentation

#6935 Publish RPU draft
  content/projects/gsoc/2024/project-ideas/automating-rpu-for-jenkinsci-organization.adoc
Labels: gsoc

#6937 Add myself as a potential mentor
  content/projects/gsoc/2024/project-ideas/implementing-ui-for-jenkins-infra-statistics.adoc
  content/projects/gsoc/2024/project-ideas/using-opentelemetry-for-jenkins-jobs-on-ci_jenkins_io.adoc
Labels: gsoc

#6854 Fixed The aspect ratio of large images isn't preserved on mobile #6316
  content/css/jenkins.css
Labels: bug

#6930 First draft of the November newsletter.
  content/blog/2023/12/15/2023-12-15-jenkins-november-newsletter.adoc
Labels: blogpost

#6946 Fix link to end of Java support changelog entry for 2.426.2
  content/_data/changelogs/lts.yml
Labels: changelog

#6947 chore: add a step to purge cached CSS
  Jenkinsfile
Labels: chore

#6952 fix: correct RSS icon height in /changelog
  content/_layouts/changelog.html.haml
Labels: bug, changelog

#6948 chore(dependencies): Now finds the latest baseline.
  updatecli/scripts/jenkins-lts-baseline.sh
  updatecli/updatecli.d/jenkins-lts.yaml
Labels: chore

#6954 Render footnote correctly
  content/doc/developer/plugin-development/build-process.adoc
Labels: documentation

#6956 Remove reference to `globalMaskClasses`
  content/doc/developer/plugin-development/dependencies-and-class-loading.adoc
Labels: documentation

#6957 Outline which CD format is the standard
  content/doc/developer/publishing/releasing-cd.adoc
Labels: documentation

#6961 Remove reference to Python 2
  content/doc/tutorials/build-a-python-app-with-pyinstaller.adoc
Labels: documentation

#6962 Update support-policy-java.adoc LTS release for Java 11+17+21
  content/doc/book/platform-information/support-policy-java.adoc
Labels: documentation

#6965 Rmfossi legolas logo
  content/_data/logo/legolas.yml
  content/images/logos/legolas/256.png
  content/images/logos/legolas/legolas.png
Labels: artwork

#6968 Fix Link to GSoC 2023 Project Ideas page
  content/projects/gsoc/2023/index.adoc
Labels: gsoc

#6973 Describe how to list installed plugins and their versions
  content/doc/book/managing/plugins.adoc
Labels: documentation
