Repository jenkins-infra/jenkins.io, pull requests merged in 2024-07, with the labels that each got.

#7396 Add refs to 2.466 changelog
  content/_data/changelogs/weekly.yml
Labels: changelog

#7387 feat(sponsors): Keep the list of donors up to date.
  updatecli/scripts/retrieve-donors.sh
  updatecli/updatecli.d/find-donors.yaml
Labels: chore

#7398 Add 2.452.3 changelog and upgrade guide
  content/_data/changelogs/lts.yml
  content/_data/upgrades/2-452-3.adoc
Labels: changelog

#7404 Fix 2.467 changelog date
  content/_data/changelogs/weekly.yml
Labels: changelog

#7410 Update durability wording
  content/doc/book/pipeline/scaling-pipeline.adoc
Labels: documentation

#7413 Bump archetypes version
  content/doc/developer/tutorial/create.adoc
Labels: documentation

#7415 fix(tutorials): Improve cleanup instructions and add explanation for --remove-orphans option
  content/doc/tutorials/build-a-java-app-with-maven.adoc
  content/doc/tutorials/build-a-multibranch-pipeline-project.adoc
  content/doc/tutorials/build-a-node-js-and-react-app-with-npm.adoc
  content/doc/tutorials/build-a-python-app-with-pyinstaller.adoc
Labels: documentation

#7419 Link to the OpenJDK upgrade issue in Jira
  content/_data/upgrades/2-440-2.adoc
Labels: changelog

#7417 Announce Amazon donation to Jenkins
  content/blog/2024/07/2024-07-24-amazon-donates-to-jenkins.adoc
  content/images/post-images/2024/07/24/2024-07-24-amazon-donates-to-jenkins.png
Labels: blogpost

#7421 chore(Jenkinsfile) increase DockerHub rate limit with authentication
  Jenkinsfile
Labels: chore

#7418 Announce Microsoft donation to Jenkins
  content/blog/2024/07/2024-07-26-microsoft-donates-to-jenkins.adoc
  content/images/post-images/2024/07/26/2024-07-26-microsoft-donates-to-jenkins.png
Labels: blogpost

#7425 Archive PDF files of some GSoC project ideas
  content/projects/gsoc/2019/ext-workspace-manager-cloud-features.adoc
  content/projects/gsoc/2019/project-ideas/advanced-build-discard-strategy-plugin-draft.pdf
  content/projects/gsoc/2019/project-ideas/advanced-build-discard-strategy-plugin.adoc
  content/projects/gsoc/2019/project-ideas/artifactory-rest-plugin-draft.pdf
  content/projects/gsoc/2019/project-ideas/artifactory-rest-plugin.adoc
  content/projects/gsoc/2019/project-ideas/ath-improvements-draft.pdf
  content/projects/gsoc/2019/project-ideas/ath-improvements.adoc
  content/projects/gsoc/2019/project-ideas/automatic-spec-generator-for-jenkins-rest-api-draft.pdf
  content/projects/gsoc/2019/project-ideas/automatic-spec-generator-for-jenkins-rest-api.adoc
  content/projects/gsoc/2019/project-ideas/bitbucket-rest-plugin-draft.pdf
  content/projects/gsoc/2019/project-ideas/bitbucket-rest-plugin.adoc
  content/projects/gsoc/2019/project-ideas/eda-coverage-adapters-draft.pdf
  content/projects/gsoc/2019/project-ideas/eda-coverage-adapters.adoc
  content/projects/gsoc/2019/project-ideas/eda-plugins-draft.pdf
  content/projects/gsoc/2019/project-ideas/eda-plugins.adoc
  content/projects/gsoc/2019/project-ideas/ext-workspace-manager-cloud-features-draft.pdf
  content/projects/gsoc/2019/project-ideas/ext-workspace-manager-cloud-features.adoc
  content/projects/gsoc/2019/project-ideas/jenkins-rest-plugin-draft.pdf
  content/projects/gsoc/2019/project-ideas/jenkins-rest-plugin.adoc
  content/projects/gsoc/2019/project-ideas/pipeline-step-documentation-generator-draft.pdf
  content/projects/gsoc/2019/project-ideas/pipeline-step-documentation-generator.adoc
  content/projects/gsoc/2020/project-ideas/artifactory-rest-plugin.adoc
  content/projects/gsoc/2020/project-ideas/automatic-spec-generator-for-jenkins-rest-api.adoc
  content/projects/gsoc/2020/project-ideas/bitbucket-rest-plugin.adoc
  content/projects/gsoc/2020/project-ideas/eda-coverage-adapters.adoc
  content/projects/gsoc/2020/project-ideas/eda-plugins.adoc
  content/projects/gsoc/2020/project-ideas/jenkins-rest-plugin.adoc
  content/projects/gsoc/2020/project-ideas/pipeline-step-documentation-generator.adoc
  content/projects/gsoc/2020/projects/machine-learning-draft.pdf
  content/projects/gsoc/2020/projects/machine-learning.adoc
  content/projects/gsoc/2021/project-ideas/automatic-spec-generator-for-jenkins-rest-api.adoc
  content/projects/gsoc/2021/project-ideas/pipeline-step-documentation-generator.adoc
  content/projects/gsoc/2022/project-ideas/automatic-spec-generator-for-jenkins-rest-api.adoc
  content/projects/gsoc/2022/project-ideas/pipeline-step-documentation-generator.adoc
  content/projects/gsoc/2024/project-ideas/automatic-specification-generator-for-jenkins-rest-api.adoc
Labels: gsoc

#7406 Add 2.462.1 changelog and upgrade guide
  content/_data/changelogs/lts.yml
  content/_data/upgrades/2-462-1.adoc
Labels: changelog
