Repository jenkins-infra/jenkins.io, pull requests merged in 2024-04, with the labels that each got.

#7209 Apply and fixup some code block languages
  content/doc/developer/publishing/continuous-integration.adoc
  content/doc/developer/security/index.adoc
  content/doc/developer/tutorial/create.adoc
  content/participate/report-issue.adoc
Labels: documentation

#7215 Quote to prevent glob expansion
  content/doc/book/installing/linux.adoc
Labels: documentation

#7226 Example for @LocalData and explain how to use it
  content/doc/developer/testing/index.adoc
Labels: documentation

#7229 Update jelly-form-controls.adoc to link to design-library-plugin
  content/doc/developer/forms/jelly-form-controls.adoc
Labels: documentation

#7224 Add installation notice for required declarative pipeline plugin
  content/doc/book/pipeline/syntax.adoc
Labels: documentation

#7231 Improve layout of list in docker install instruction
  content/doc/book/installing/_docker.adoc
Labels: documentation

#7230 feat: add blog post for post google summer of code application period
  content/blog/2024/04/2024-04-04-gsoc-2024-contributor-application-period-concludes.adoc
Labels: blogpost

#7235 Jenkins.io Blog - suggestions and updates for GSoC blog post
  content/blog/2024/04/2024-04-04-gsoc-2024-contributor-application-period-concludes.adoc
Labels: blogpost

#7234 fix: typo on webpage running-pipelines
  content/doc/book/pipeline/running-pipelines.adoc
Labels: documentation

#7194 Added a section of Update parent POM page
  content/doc/developer/tutorial-improve/_compile-the-plugin.adoc
  content/doc/developer/tutorial-improve/_install-apache-maven.adoc
  content/doc/developer/tutorial-improve/add-more-spotbugs-checks.adoc
  content/doc/developer/tutorial-improve/convert-translations.adoc
  content/doc/developer/tutorial-improve/move-description-to-index.adoc
  content/doc/developer/tutorial-improve/replace-jsr-305-annotations.adoc
  content/doc/developer/tutorial-improve/update-base-jenkins-version.adoc
  content/doc/developer/tutorial-improve/update-parent-pom.adoc
  content/doc/developer/tutorial-improve/use-plugin-bill-of-materials.adoc
  content/doc/developer/tutorial/prepare.adoc
Labels: documentation

#7228 fix(tutorials): Move to using profiles to work around the docker compose 2.4.27 "breaking" changes;
  content/doc/tutorials/build-a-java-app-with-maven.adoc
  content/doc/tutorials/build-a-multibranch-pipeline-project.adoc
  content/doc/tutorials/build-a-node-js-and-react-app-with-npm.adoc
  content/doc/tutorials/build-a-python-app-with-pyinstaller.adoc
Labels: documentation

#7218 Jenkins LTS 2.440.3 - Creating changelog and upgrade guide
  content/_data/changelogs/lts.yml
  content/_data/changelogs/weekly.yml
  content/_data/upgrades/2-440-3.adoc
Labels: changelog

#7236 Docs changes for jenkins-infra/repository-permissions-updater#3879
  content/doc/developer/publishing/releasing-cd.adoc
Labels: documentation

#7241 Link to governance meeting GitHub repository
  content/project/governance-meeting/index.adoc
Labels: governance

#7244 Clarify that critical issues also result in "Important" security fix …
  content/_data/changelogs/_STYLEGUIDE.adoc
Labels: changelog

#7248 Docs changes for jenkinsci/incrementals-tools#104
  content/doc/developer/publishing/releasing-cd.adoc
Labels: documentation

#7249 Use same Jenkins version in sample diff as in body text
  content/doc/developer/tutorial-improve/update-base-jenkins-version.adoc
Labels: documentation

#7246 Remove date dependent phrase from governance agenda link
  content/project/governance-meeting/index.adoc
Labels: governance

#7251 Pipeline Best Practices - small update to format characters
  content/doc/book/using/best-practices.adoc
Labels: documentation

#7255 Developer Documentation - update for wiki migration page
  content/doc/developer/publishing/wiki-page.adoc
Labels: documentation

#7204 Improve link to GitHub example
  content/doc/developer/publishing/wiki-page.adoc
Labels: documentation

#7257 Blog post to announce community award winners
  content/blog/2024/04/2024-04-19-jenkins-community-award-winners.adoc
  content/images/post-images/2024/04/19/2024-contributor-awards.png
  content/images/post-images/2024/04/19/stefan-spieker.png
Labels: blogpost

#7258 Fix some broken links on ScriptConsole page
  content/doc/book/managing/script-console.adoc
Labels: documentation

#7259 Remove 'Add tooltip' docs page
  content/doc/developer/forms/_chapter.yml
  content/doc/developer/forms/adding-tool-tips.adoc
Labels: documentation

#7208 Refresh the design of the 'Download' page
  content/_partials/pagination.html.haml
  content/blog/index.html.haml
  content/css/jenkins.css
  content/download/index.html.haml
  content/images/symbols/apple.svg
  content/images/symbols/archlinux.svg
  content/images/symbols/aws.svg
  content/images/symbols/azure.svg
  content/images/symbols/bitnami.svg
  content/images/symbols/civo.svg
  content/images/symbols/coffee.svg
  content/images/symbols/docker.svg
  content/images/symbols/freebsd.svg
  content/images/symbols/gentoo.svg
  content/images/symbols/google-cloud.svg
  content/images/symbols/kubernetes.svg
  content/images/symbols/openbsd.svg
  content/images/symbols/openindiana.svg
  content/images/symbols/opensuse.svg
  content/images/symbols/oracle.svg
  content/images/symbols/redhat.svg
  content/images/symbols/ubuntu.svg
  content/images/symbols/windows.svg
  content/participate/index.html.haml
  content/stylesheets/components/_all.scss
  content/stylesheets/components/_button.scss
  content/stylesheets/components/_buttons.scss
  content/stylesheets/components/_cards.scss
  content/stylesheets/components/_tooltips.scss
  content/stylesheets/pages/_all.scss
  content/stylesheets/pages/_contribute.scss
  content/stylesheets/pages/_download.scss
Labels: blogpost

#7270 Fix minor typos in weekly changelog
  content/_data/changelogs/weekly.yml
Labels: changelog

#7263 Use 'app-button' across the site
  content/_layouts/pipelinesteps.html.haml
  content/_partials/_feedback-footer.html
  content/_partials/downloadbanner.html.haml
  content/_partials/jumbotron.html.haml
  content/_partials/projectcarousel.html.haml
  content/_partials/projectjumbotron.html.haml
  content/blog/index.html.haml
  content/css/jenkins.css
  content/images/symbols/rss.svg
  content/participate/report-issue/redirect.html.haml
  content/projects/jam/suggest.html.haml
  content/stylesheets/components/_button.scss
Labels: blogpost

#7260 Added concept of test pyramid with examples how this can be applied w…
  content/doc/developer/testing/index.adoc
Labels: documentation

#7202 added information on to use checkUrl in Form validation #6433
  content/doc/developer/forms/form-validation.adoc
Labels: documentation

#7274 Added examples how to run individual tests and test classes
  content/doc/developer/testing/index.adoc
Labels: documentation

#7277 Update 2.456 changelog
  content/_data/changelogs/weekly.yml
Labels: changelog
