Repository jenkins-infra/jenkins.io, pull requests merged in 2024-03, with the labels that each got.

#7081 Write out 'curl -X' in Jenkinsfile
  Jenkinsfile
Labels: chore

#7148 Update archetypes
  content/doc/developer/tutorial/create.adoc
Labels: documentation

#7152 Remove obsolete space in 'make run'
  Makefile
Labels: chore

#7156 fix(documentation): Adding Bruno Verachten as a co-mentor
  content/projects/gsoc/2024/project-ideas/buiilding-ios-app.adoc
  content/projects/gsoc/2024/project-ideas/enhancing-an-existing-llm-model-with-domain-specific-jenkins-knowledge.adoc
  content/projects/gsoc/2024/project-ideas/plugin-installation-manager-tool.adoc
  content/projects/gsoc/2024/project-ideas/using-openrewrite-recipes-for-plugin-modernization-or-automation-plugin-build-metadata-updates.adoc
Labels: gsoc

#7159 Fix: Make some GSoC 2024-related changes
  content/blog/2018/02/2018-02-19-gsoc2018-announcement.adoc
  content/blog/2019/03/2019-03-04-gsoc2019-announcement.adoc
  content/blog/2020/01/2020-01-29-gsoc-report.adoc
  content/blog/2021/03/2021-03-17-gsoc2021-announcement.adoc
  content/blog/2022/03/2022-03-08-gsoc2022-announcement.adoc
  content/blog/2022/11/2022-11-23-get-prepared-for-gsoc.adoc
  content/blog/2023/02/2023-02-01-gsoc-update.adoc
  content/blog/2023/02/2023-02-23-gsoc2023-announcement.adoc
  content/blog/2024/02/2024-02-23-gsoc2024-announcement.adoc
  content/projects/gsoc/2022/application.adoc
  content/projects/gsoc/2022/index.adoc
  content/projects/gsoc/2023/index.adoc
  content/projects/gsoc/2024/application.adoc
  content/projects/gsoc/2024/project-ideas/cloudevents-plugin.adoc
  content/projects/gsoc/2024/project-ideas/enhancing-an-existing-llm-model-with-domain-specific-jenkins-knowledge.adoc
  content/projects/gsoc/contributors.adoc
  content/projects/gsoc/index.adoc
  content/projects/gsoc/mentors.adoc
  content/projects/gsoc/roles-and-responsibilities.adoc
  content/projects/gsoc/students.adoc
Labels: gsoc

#7153 Update ruby and node
  .node-version
  .ruby-version
  Dockerfile
  Jenkinsfile_k8s
  scripts/node
  scripts/ruby
Labels: chore

#7165 Add developer documentation about usage in plugins
  content/doc/developer/plugin-development/_chapter.yml
  content/doc/developer/plugin-development/usage-in-plugins.adoc
Labels: documentation

#7117 Add individual pages for changelog versions
  content/_ext/changelog_releases.rb
  content/_ext/pipeline.rb
  content/_layouts/changelog_entry.html.haml
  content/changelog-old/index.html.haml
  content/changelog-stable/index.html.haml
  content/changelog/index.html.haml
Labels: work-in-progress, changelog

#7176 Fix YAML Indentation in Kubernetes Jenkins Deployment
  content/doc/book/installing/kubernetes.adoc
Labels: documentation

#7175 Multibranch tutorial revamp
  content/_data/changelogs/weekly.yml
  content/doc/book/resources/tutorials/multibranch-pipeline-01-main-blueocean-interface.png
  content/doc/book/resources/tutorials/multibranch-pipeline-11-branches-page.png
  content/doc/book/resources/tutorials/multibranch-pipeline-12-run-icon.png
  content/doc/book/resources/tutorials/multibranch-pipeline-13-build-and-test-stages-run-successfully-with-output.png
  content/doc/book/resources/tutorials/multibranch-pipeline-21-complete-pipeline-runs-successfully-on-master-branch.png
  content/doc/book/resources/tutorials/multibranch-pipeline-31-deliver-for-development-stage-opened.png
  content/doc/book/resources/tutorials/multibranch-pipeline-32-complete-pipeline-runs-successfully-on-development-branch.png
  content/doc/book/resources/tutorials/multibranch-pipeline-41-deploy-for-production-stage-opened.png
  content/doc/book/resources/tutorials/multibranch-pipeline-42-complete-pipeline-runs-successfully-on-production-branch.png
  content/doc/book/resources/tutorials/multibranch-pipeline/2nd-build-details.png
  content/doc/book/resources/tutorials/multibranch-pipeline/build-2-pipeline-overview.png
  content/doc/book/resources/tutorials/multibranch-pipeline/build-3-pipeline-overview.png
  content/doc/book/resources/tutorials/multibranch-pipeline/build-development-branch.png
  content/doc/book/resources/tutorials/multibranch-pipeline/build-production-branch.png
  content/doc/book/resources/tutorials/multibranch-pipeline/complete-pipeline-runs-successfully-on-development-branch.png
  content/doc/book/resources/tutorials/multibranch-pipeline/complete-pipeline-runs-successfully-on-production-branch.png
  content/doc/book/resources/tutorials/multibranch-pipeline/create-a-multibranch-pipeline.png
  content/doc/book/resources/tutorials/multibranch-pipeline/credentials-ok.png
  content/doc/book/resources/tutorials/multibranch-pipeline/deliver-for-development-shell-script.png
  content/doc/book/resources/tutorials/multibranch-pipeline/deliver-for-development.png
  content/doc/book/resources/tutorials/multibranch-pipeline/deploy-for-production-shell-script.png
  content/doc/book/resources/tutorials/multibranch-pipeline/deploy-for-production.png
  content/doc/book/resources/tutorials/multibranch-pipeline/found-all-branches.png
  content/doc/book/resources/tutorials/multibranch-pipeline/master-build-after-first-modification.png
  content/doc/book/resources/tutorials/multibranch-pipeline/multibranch-pipeline-main-page.png
  content/doc/book/resources/tutorials/multibranch-pipeline/proceed-for-production.png
  content/doc/book/resources/tutorials/multibranch-pipeline/proceed.png
  content/doc/book/resources/tutorials/multibranch-pipeline/run-icon.png
  content/doc/book/resources/tutorials/multibranch-pipeline/schedule-a-build-for-master.png
  content/doc/book/resources/tutorials/multibranch-pipeline/test-stage-details.png
  content/doc/tutorials/build-a-multibranch-pipeline-project.adoc
Labels: changelog, documentation

#7178 Remove mention of supply chain attacks
  content/doc/book/security/controller-isolation.adoc
Labels: documentation

#7179 Restore 2.449 changelog
  content/_data/changelogs/weekly.yml
Labels: changelog

#7173 Move various blog-related pages from /node/... to /blog/...
  content/_ext/pipeline.rb
  content/_layouts/post.html.haml
  content/_partials/pagination.html.haml
  content/blog/2010/2010-03-13-this-week-in-plugins.adoc
  content/blog/2010/2010-03-23-links-for-2010-03-23.adoc
  content/blog/2012/2012-07-26-jenkins-user-conference-san-francisco-call-for-papers.adoc
  content/blog/2016/2016-12-31-what-a-year.adoc
  content/blog/2017/01/2017-01-11-jenkins-world-2017-cfp.adoc
  content/blog/2017/08/2017-08-23-pull-requests-and-more.adoc
  content/blog/2019/11/2019-11-08-board-elections.adoc
  content/blog/2020/12/2020-12-22-gsoc-report.adoc
  content/blog/2022/11/2022-11-04-jenkins-newsletter.adoc
  content/blog/2022/12/2022-12-05-jenkins-newsletter.adoc
  content/blog/2023/09/21/2023-09-21-jenkins-august-newsletter.adoc
  content/blog/2023/10/12/2023-10-12-jenkins-september-newsletter.adoc
  content/blog/2024/01/25/2024-01-25-jenkins-2023-recap.adoc
  content/blog/index.html.haml
  content/doc/tutorials/index.adoc
  content/node/index.adoc
  content/projects/gsoc/2019/application.md
  content/projects/gsoc/2020/application.md
  content/projects/gsoc/contributors.adoc
  content/security/cna.adoc
  content/security/index.adoc
Labels: gsoc, blogpost, documentation

#7180 Replace embedded google doc with hackmd in governance meeting page
  content/project/governance-meeting/index.adoc
Labels: governance

#7162 Jenkins LTS 2.440.2 - changelog & upgrade guide
  content/_data/changelogs/lts.yml
  content/_data/upgrades/2-440-2.adoc
Labels: changelog

#7186 Update archetypes version
  content/doc/developer/tutorial/create.adoc
Labels: documentation

#7185 Fix broken links
  content/blog/2018/09/2018-09-18-automatically-upgrading-with-evergreen.adoc
  content/blog/2019/10/2019-10-21-plugin-docs-on-github.adoc
  content/blog/2020/10/2020-10-28-election-candidates.adoc
  content/blog/2021/07/2021-07-31-remoting-monitoring-phase-1.adoc
  content/blog/2022/12/2022-12-27-run-jenkins-agent-as-a-service.adoc
  content/blog/2023/07/10/2023-07-10-jenkins-june-newsletter.adoc
  content/blog/2023/07/22/2023-07-22-gsoc-2023-midterm.adoc
  content/blog/2023/08/24/2023-08-24-gitlab-plugin-modernization-report.adoc
  content/blog/2023/09/20/2023-09-20-renovate-bot-probe-blog.adoc
  content/doc/developer/publishing/releasing-cd.adoc
  content/doc/developer/publishing/requesting-hosting.adoc
  content/events/fosdem/archive/2020.adoc
  content/images/post-images/jenkins-is-the-way/ebook/ebook3_opengraph.png
Labels: blogpost, documentation

#7189 Remove outdated URL from hosting team page
  content/project/teams/hosting.adoc
Labels: governance

#7191 Update lts.yml: fix typo in 2.440.2
  content/_data/changelogs/lts.yml
Labels: changelog

#7197 Jenkins weekly 2.451 - add entry for Debian 10 & Ubuntu 20.04 requirement
  content/_data/changelogs/weekly.yml
Labels: changelog

#7203 Document exclusive JEP-229 CD mode
  content/doc/developer/publishing/releasing-cd.adoc
Labels: documentation
