Repository jenkins-infra/jenkins.io, pull requests merged in 2024-06, with the labels that each got.

#7350 feat(roadmap) Update Infrastructure top level projects
  content/_data/roadmap/roadmap.yml
Labels: roadmap

#7331 Jenkins LTS 2.452.2 - Create changelog and upgrade guide
  content/_data/changelogs/lts.yml
  content/_data/upgrades/2-452-2.adoc
Labels: changelog

#7355 Require Java 17 or newer
  content/blog/2024/06/2024-06-11-require-java-17.adoc
  content/images/post-images/2024/06/java17.png
  content/images/post-images/2024/06/jvms.png
Labels: blogpost

#7359 Re-order cd releasing page
  content/doc/developer/publishing/releasing-cd.adoc
Labels: documentation

#7358 Update mirrors page, supporters and add a blog post to announce hostico
  content/_data/indexpage/supporters.yml
  content/blog/2024/06/2024-06-13-thanks-mirror-sponsors.adoc
  content/download/mirrors.adoc
Labels: blogpost

#7361 Platform Information - add line for Java 17 requirement in weekly to support table
  content/doc/book/platform-information/support-policy-java.adoc
Labels: documentation

#7364 Update container images versions in hello-world tutorial
  content/doc/pipeline/tour/hello-world.adoc
Labels: documentation

#7368 [Tutorials and Agents Docs] Bump node LTS alpine docker image version to 20.14.0-alpine3.20
  STYLEGUIDE.adoc
  content/doc/book/pipeline/docker.adoc
  content/doc/pipeline/tour/agents.adoc
Labels: dependencies, documentation

#7373 Make it more obvious that this is a new sentence
  content/doc/developer/publishing/releasing-cd.adoc
Labels: documentation

#7374 Add JENKINS-64553 fix ItemListener to 2.452.2 changelog
  content/_data/changelogs/lts.yml
Labels: changelog

#7375 Java 11 no longer has a full test flow
  content/doc/book/platform-information/support-policy-java.adoc
Labels: documentation

#7385 Use `Jenkins.get()` instead of deprecated method
  content/doc/developer/plugin-development/optional-dependencies.adoc
Labels: documentation
