Repository jenkins-infra/jenkins.io, pull requests merged in 2024-08, with the labels that each got.

#7432 Announce 2024 elections
  content/_data/indexpage/carousel.yml
  content/blog/2024/08/01/2024-08-01-board-officer-election-announcement.adoc
  content/images/governance/elections/2024/2024-announcement-opengraph.svg
Labels: blogpost

#7436 Revert "chore(Jenkinsfile) increase DockerHub rate limit with authentication"
  Jenkinsfile
Labels: chore

#7441 Match the automated formatting of changelog
  content/_data/changelogs/weekly.yml
Labels: changelog

#7444 Remove broken link to upgrading plugins
  content/doc/book/platform-information/upgrade-java-to-17.adoc
Labels: documentation

#7454 Make use of UTF-8 in localization example
  content/doc/developer/internationalization/i18n-source-code.adoc
Labels: documentation

#7457 Fix some elements in dark mode
  content/_layouts/changelog.html.haml
  content/_layouts/gsocprojectidea.html.haml
  content/_partials/changelog-old.html
  content/_partials/changelog-stable.html
  content/_partials/release-header.html.haml
  content/changelog-old/index.html.haml
  content/changelog-stable/index.html.haml
  content/stylesheets/components/_all.scss
  content/stylesheets/components/_banner.scss
Labels: changelog

#7461 reverse-proxy-configuration proxy_pass warning
  content/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-nginx.adoc
Labels: documentation

#7463 Reverse proxy configuration - adjust link macro usage
  content/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-nginx.adoc
Labels: documentation

#7466 Updating Managing documentation to remove usage of "Jenkins instance"
  content/doc/book/managing/casc.adoc
  content/doc/book/managing/index.adoc
  content/doc/book/managing/script-console.adoc
  content/doc/book/managing/system-info.adoc
Labels: documentation

#7465 Updating Installing documentation to remove use of "Jenkins instance"
  content/doc/book/installing/_kubernetes.adoc
  content/doc/book/installing/_setup-wizard-for-tutorials.adoc
  content/doc/book/installing/_setup-wizard.adoc
  content/doc/book/installing/other.adoc
Labels: documentation

#7467 Updating Platform Information documentation to remove use of "Jenkins instance"
  content/doc/book/platform-information/upgrade-java-to-11.adoc
  content/doc/book/platform-information/upgrade-java-to-17.adoc
Labels: documentation

#7469 Update to remove usage of "jenkins instance" in Blue Ocean documentation
  content/doc/book/blueocean/dashboard.adoc
  content/doc/book/blueocean/getting-started.adoc
  content/doc/book/blueocean/index.adoc
Labels: documentation

#7470 Update to remove usage of "jenkins instance" in Pipeline documentation
  content/doc/book/pipeline/development.adoc
  content/doc/book/pipeline/getting-started.adoc
  content/doc/book/pipeline/scaling-pipeline.adoc
Labels: documentation

#7472 Update to remove usage of "jenkins instance" in Scaling documentation
  content/doc/book/scaling/architecting-for-manageability.adoc
  content/doc/book/scaling/architecting-for-scale.adoc
  content/doc/book/scaling/hardware-recommendations.adoc
  content/doc/book/scaling/scaling-jenkins-on-kubernetes.adoc
Labels: documentation

#7474 Update to remove usage of "jenkins instance" in System Adminstration documentation
  content/doc/book/system-administration/admin-password-reset-instructions.adoc
  content/doc/book/system-administration/backing-up.adoc
  content/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-iptables.adoc
  content/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-pomerium.adoc
Labels: documentation

#7475 Update to remove usage of "jenkins instance" in Using Jenkins documentation
  content/doc/book/using/best-practices.adoc
  content/doc/book/using/change-time-zone.adoc
  content/doc/book/using/pluggable-storage.adoc
  content/doc/book/using/referencing-another-project-by-name.adoc
  content/doc/book/using/remote-access-api.adoc
  content/doc/book/using/using-credentials.adoc
Labels: documentation

#7476 Update to remove usage of "jenkins instance" in Tutorials
  content/doc/tutorials/build-a-java-app-with-maven.adoc
  content/doc/tutorials/build-a-multibranch-pipeline-project.adoc
  content/doc/tutorials/build-a-node-js-and-react-app-with-npm.adoc
  content/doc/tutorials/build-a-python-app-with-pyinstaller.adoc
  content/doc/tutorials/using-jenkinsfile-runner-github-action-to-build-jenkins-pipeline.adoc
Labels: documentation

#7478 Update to remove usage of "jenkins instance" in Developer documentation
  content/doc/developer/plugin-development/build-process.adoc
  content/doc/developer/publishing/continuous-integration.adoc
  content/doc/developer/publishing/plugin-site.adoc
  content/doc/developer/publishing/requesting-hosting.adoc
  content/doc/developer/publishing/usage-statistics.adoc
  content/doc/developer/security/misc.adoc
  content/doc/developer/security/secrets.adoc
  content/doc/developer/security/xss-prevention.adoc
  content/doc/developer/telemetry/index.adoc
  content/doc/developer/testing/index.adoc
  content/doc/developer/tutorial/extend.adoc
  content/doc/developer/tutorial/run.adoc
  content/doc/developer/views/table-to-div-migration.adoc
Labels: documentation

#7480 LLM project final blog post
  content/_data/authors/nouralmulhem.adoc
  content/blog/2024/08/25/2024-08-25-gsoc-enhancing-llm.adoc
  content/images/avatars/nouralmulhem.jpg
  content/images/post-images/2024/08/llm-chat-page.png
  content/images/post-images/2024/08/llm-landing-dark.png
  content/images/post-images/2024/08/llm-landing-white.png
Labels: blogpost

#7482 Fix weekly changelog entry format
  content/_data/changelogs/weekly.yml
Labels: changelog

#7481 GSoC: Add blog for Plugin Modernizer Tool
  content/blog/2024/08/26/2024-08-26-gsoc-using-openrewrite-for-plugin-modernization.adoc
Labels: blogpost

#7484 GSOC: Manage jenkinsci GitHub permissions as code
  content/_data/authors/Alaurant.adoc
  content/blog/2024/08/26/2024-08-26-gsoc-manage-github-permissions.adoc
  content/images/avatars/Alaurant.jpg
Labels: blogpost

#7487 Update grammar in LLM blog post
  content/blog/2024/08/25/2024-08-25-gsoc-enhancing-llm.adoc
Labels: blogpost

#7486 Remove changes from 2.426.1 changelog that weren't new to LTS.
  content/_data/changelogs/lts.yml
Labels: changelog

#7489 Some grammar and punctuation fixes for Plugin Modernization GSoC blog
  content/blog/2024/08/26/2024-08-26-gsoc-using-openrewrite-for-plugin-modernization.adoc
Labels: blogpost

#7488 Adjust content in GSoC GitHub permissions blog
  content/blog/2024/08/26/2024-08-26-gsoc-manage-github-permissions.adoc
Labels: blogpost

#7492 Remove old blog container style
  content/blog/index.html.haml
  content/stylesheets/pages/_blog.scss
Labels: blogpost

#7459 LTS 2.462.2 - adding changelog and upgrade guide
  content/_data/changelogs/lts.yml
  content/_data/upgrades/2-462-2.adoc
Labels: changelog

#7485 Jenkins Romania logo
  content/_data/logo/romania.yml
  content/images/logos/romania/jenkins_romania.png
  content/images/logos/romania/jenkins_romania256.png
Labels: artwork

#7497 Remove hardlinks to jenkins.io in blog post
  content/blog/2024/08/25/2024-08-25-gsoc-enhancing-llm.adoc
Labels: blogpost

#7499 Add blog post for DevOps World 2024's "What's next for the Jenkins user interface" talk
  content/_data/authors/janfaracik.adoc
  content/blog/2024/08/29/2024-08-29-jenkins-design.adoc
  content/images/post-images/jenkins-redesign-2-preview-social.png
Labels: blogpost

#7479 Refresh the design of the 'Changelogs' pages
  content/_ext/changelog_releases.rb
  content/_layouts/changelog.html.haml
  content/_layouts/changelog_entry.html.haml
  content/_layouts/simplepage.html.haml
  content/_partials/changelog-changes.html.haml
  content/_partials/release-header.html.haml
  content/changelog-old/index.html.haml
  content/changelog-preview/index.html.haml
  content/changelog-stable/index.html.haml
  content/changelog/index.html.haml
  content/css/changelog.css
  content/files/rate.js
  content/images/changelog/cloudy.svg
  content/images/changelog/feed-icon.svg
  content/images/changelog/storm.svg
  content/images/changelog/sunny.svg
  content/stylesheets/components/_all.scss
  content/stylesheets/components/_app-bar.scss
  content/stylesheets/components/_banner.scss
  content/stylesheets/components/_button.scss
  content/stylesheets/components/_weather.scss
  content/stylesheets/core/_container.scss
  content/stylesheets/pages/_all.scss
  content/stylesheets/pages/_releases.scss
Labels: changelog
