Repository jenkins-infra/jenkins.io, pull requests merged in 2024-05, with the labels that each got.

#7275 Jenkins LTS 2.452.1 - create changelog & upgrade guide
  content/_data/changelogs/lts.yml
  content/_data/upgrades/2-452-1.adoc
Labels: changelog

#7282 Create 2024-05-01-google-summer-of-code-congrats-and-welcome.adoc
  content/blog/2024/05/2024-05-01-google-summer-of-code-congrats-and-welcome.adoc
Labels: blogpost

#7287 Minor improvements to adopt-a-plugin and added screenshot
  content/doc/developer/plugin-governance/adopt-a-plugin.adoc
  content/images/developer/plugin-governance/adopt-a-plugin/change-for-adoption.png
Labels: documentation

#7292 Jenkins 2.457 - adjust message for changelog entry
  content/_data/changelogs/weekly.yml
Labels: changelog

#7295 Add a contributing nudge field in issue templates
  .github/ISSUE_TEMPLATE/1-documentation.yml
  .github/ISSUE_TEMPLATE/3-enhancement.yml
  .github/ISSUE_TEMPLATE/4-bug.yml
Labels: chore, community

#4666 security and credentials
  content/doc/book/security/_chapter.yml
  content/doc/book/security/credentials.adoc
Labels: work-in-progress, documentation, stalled

#7293 Add GSoC 2024 OpenRewrite project page
  content/projects/gsoc/2024/projects/using-openrewrite-recipes-for-plugin-modernization-or-automation-plugin-build-metadata-updates.adoc
Labels: gsoc

#7300 Governance meeting happens every 4 weeks
  content/project/governance-meeting/index.adoc
  content/project/governance.adoc
Labels: governance

#7302 feat: add more gsoc 2024 projects
  content/_data/authors/Alaurant.adoc
  content/_data/authors/TheMeinerLP.adoc
  content/_data/authors/krisstern.adoc
  content/_data/authors/nouralmulhem.adoc
  content/_data/authors/shlomomdahan.adoc
  content/projects/gsoc/2022/projects/jenkinsfile-runner-action-for-github-actions.adoc
  content/projects/gsoc/2024/project-ideas/enhancing-an-existing-llm-model-with-domain-specific-jenkins-knowledge.adoc
  content/projects/gsoc/2024/projects/blank_project.adoc
  content/projects/gsoc/2024/projects/enhancing-an-existing-llm-model-with-domain-specific-jenkins-knowledge.adoc
  content/projects/gsoc/2024/projects/implementing-ui-for-jenkins-infra-statistics.adoc
  content/projects/gsoc/index.adoc
Labels: gsoc

#7304 Minor improvements to governance docs
  content/project/governance.adoc
Labels: governance

#7309 Update GSoC project list with RPU
  content/projects/gsoc/2024/projects/automating-rpu-for-jenkinsci-organization.adoc
  content/projects/gsoc/index.adoc
Labels: gsoc

#7310 Update Office hours
  content/projects/gsoc/2024/projects/using-openrewrite-recipes-for-plugin-modernization-or-automation-plugin-build-metadata-updates.adoc
Labels: gsoc

#7314 Add RPU Maintainability docs
  content/projects/gsoc/2024/projects/automating-rpu-for-jenkinsci-organization.adoc
  content/projects/gsoc/2024/projects/improving-maintainability-of-rpu.adoc
  content/projects/gsoc/index.adoc
Labels: gsoc

#7312 [Update authenticating-scripted-clients.adoc] add typescript example
  content/doc/book/system-administration/authenticating-scripted-clients.adoc
Labels: documentation

#7316 feat: add rajiv as co-mentor for gsoc 2024 automating rpu project
  content/projects/gsoc/2024/projects/automating-rpu-for-jenkinsci-organization.adoc
Labels: gsoc

#7318 Use correct link to GSoC project 5
  content/blog/2024/05/2024-05-01-google-summer-of-code-congrats-and-welcome.adoc
Labels: blogpost

#7319 Add direct link to the meeting for GSoC OpenRewrite 2024
  content/projects/gsoc/2024/projects/using-openrewrite-recipes-for-plugin-modernization-or-automation-plugin-build-metadata-updates.adoc
Labels: gsoc

#7321 Fix link
  content/blog/2011/2011-01-11-hudsons-future.adoc
Labels: blogpost

#7322 Update #7294
  content/doc/book/pipeline/jenkinsfile.adoc
Labels: documentation

#7324 Link from plugin build process doc to tutorial
  content/doc/developer/plugin-development/build-process.adoc
Labels: documentation

#7325 Add plugin distribution process to developer docs
  content/doc/developer/plugin-development/_chapter.yml
  content/doc/developer/plugin-development/distribution-process.adoc
  content/doc/developer/tutorial/create.adoc
  content/images/developer/plugin-development/distribution-process/plugin-distribution-diagram.svg
Labels: documentation

#7329 Add a note about the label "Replay" switched to "Rebuild" in some cases
  content/doc/book/pipeline/development.adoc
Labels: documentation

#7335 docker compose down fix
  content/doc/tutorials/build-a-java-app-with-maven.adoc
Labels: documentation
