Repository jenkins-infra/jenkins.io, pull requests merged in 2024-09, with the labels that each got.

#7506 Use standard 'JENKINS-' key for issues
  content/_partials/changelog-changes.html.haml
Labels: changelog

#7507 Update ruby to 3.3.4
  .node-version
  .ruby-version
  Dockerfile
  scripts/node
  scripts/ruby
Labels: chore

#7462 [JENKINS-73422] Document escape hatch for Authenticated user access to Resource URL
  content/doc/book/managing/system-properties.adoc
Labels: documentation

#7509 Update servlet container policy
  content/doc/book/platform-information/support-policy-servlet-containers.adoc
Labels: documentation

#7512 feat(blog) add post for the two 1-hour update center brownouts
  content/blog/2024/09/04/2024-09-04-update-center-brownouts.adoc
Labels: blogpost

#7513 fix(blog) typo + add a detail about the 2 brownouts for `2024-09-04-update-center-brownouts`
  content/blog/2024/09/04/2024-09-04-update-center-brownouts.adoc
Labels: blogpost

#7514 Update center brown out blog - adjusting some grammar and punctuation
  content/blog/2024/09/04/2024-09-04-update-center-brownouts.adoc
Labels: blogpost

#7519 Format weekly changelog to match automation
  content/_data/changelogs/weekly.yml
Labels: changelog

#7520 Weekly 2.475 - adding PR and Issue to references
  content/_data/changelogs/weekly.yml
Labels: changelog

#7516 Added a description how to speed up testing with parallel execution
  content/doc/developer/testing/index.adoc
Labels: documentation

#7522 Fix changelog formatting (add trailing space)
  content/_data/changelogs/weekly.yml
Labels: changelog

#7524 feat(blog): new blogpost for the uc-brownout-3
  content/blog/2024/09/10/2024-09-10-update-center-brownouts-3.adoc
Labels: blogpost

#7532 Update Installing docs usage of "instance"
  content/doc/book/installing/_docker.adoc
  content/doc/book/installing/windows.adoc
Labels: documentation

#7534 Update Pipeline docs usage of "instance"
  content/doc/book/pipeline/shared-libraries.adoc
  content/doc/book/pipeline/syntax.adoc
Labels: documentation

#7537 Update Overall/Read access after removal of People view
  content/doc/book/security/access-control/permissions.adoc
Labels: documentation

#7536 Update usage of instance in scaling documentation
  content/doc/book/scaling/architecting-for-manageability.adoc
  content/doc/book/scaling/architecting-for-scale.adoc
  content/doc/book/scaling/hardware-recommendations.adoc
  content/doc/book/scaling/index.adoc
  content/doc/book/scaling/scaling-jenkins-on-kubernetes.adoc
Labels: documentation

#7533 Update usage of "instance" in Managing documentation
  content/doc/book/managing/_built-in-node-migration.adoc
  content/doc/book/managing/plugins.adoc
  content/doc/book/managing/script-approval.adoc
  content/doc/book/managing/system-properties.adoc
Labels: documentation

#7545 Update GitHub solution page usage of "instance"
  content/solutions/github.adoc
Labels: documentation

#7547 Update Governance, Download, and Hacktoberfest use of "instance"
  content/download/index.html.haml
  content/download/lts/index.adoc
  content/events/hacktoberfest.adoc
  content/project/governance.adoc
Labels: governance

#7538 2.462.3 - Creating Changelog and Upgrade Guide
  content/_data/changelogs/lts.yml
  content/_data/upgrades/2-462-3.adoc
Labels: changelog

#7557 Add Hacktoberfest 2024 blog post, update Hacktoberfest event docs
  content/_data/indexpage/carousel.yml
  content/blog/2024/09/2024-09-30-hacktoberfest.adoc
  content/events/hacktoberfest.adoc
  content/images/hacktoberfest/hacktoberfest_2024_logo.svg
  content/images/hacktoberfest/hacktoberfest_2024_social.jpg
  content/images/hacktoberfest/hacktoberfest_2024_social_600x300.png
Labels: blogpost
