Repository jenkins-infra/jenkins.io, pull requests merged in 2024-01, with the labels that each got.

#6974 Restrict internal workflows to 'jenkins-infra'
  .github/workflows/label-conflicting-prs.yml
  .github/workflows/updatecli.yaml
Labels: chore

#6983 Update archetypes version
  content/doc/developer/tutorial/create.adoc
Labels: documentation

#6984 Update awestruct to 0.6.7
  Gemfile
  Gemfile.lock
Labels: chore

#6985 Document `REQUIRES_DIR_FSYNC` escape hatch
  content/doc/book/managing/system-properties.adoc
Labels: documentation

#6994 Improve remoting documentation
  content/projects/remoting/index.adoc
  content/redirect/project/remoting/changelog.adoc
  content/redirect/project/remoting/protocols/jnlp2-errata.adoc
  content/redirect/project/remoting/protocols/jnlp3-errata.adoc
Labels: changelog

#6995 Update Remoting docs
  content/doc/book/managing/nodes.adoc
  content/projects/remoting/index.adoc
Labels: documentation

#6999 Create 2024-03-15-scale21x.adoc
  content/_data/events/2024-03-15-scale21x.adoc
Labels: events

#6997 Create 2024-02-03-fosdem'24.adoc
  content/_data/events/2024-02-03-fosdem'24.adoc
Labels: events

#7001 Improves phrasing and description of PHS GSOC 2024 project
  content/projects/gsoc/2024/project-ideas/adding-additional-probes-to-plugin-health-score.adoc
Labels: gsoc

#6990 Jenkins 2.426.3 changelog and upgrade guide
  content/_data/changelogs/lts.yml
  content/_data/upgrades/2-426-3.adoc
Labels: changelog

#7006 Update changelog for 2.440
  content/_data/changelogs/weekly.yml
Labels: changelog

#7012 Adding myself as a mentor for OpenTelemetry GSoC project
  content/projects/gsoc/2024/project-ideas/using-opentelemetry-for-jenkins-jobs-on-ci_jenkins_io.adoc
Labels: gsoc

#7013 Fix Throttle Concurrent Build plugins's link
  content/doc/book/using/best-practices.adoc
Labels: documentation

#7011 Updated doc for default connection mode
  content/doc/book/managing/cli.adoc
Labels: documentation

#7017 [JENKINS-72546] Include Amazon Linux 2 in RHEL 7 derivatives
  content/blog/2023/05/30/2023-05-30-operating-system-end-of-life.adoc
Labels: blogpost

#7016 blog - contributor summit update
  content/blog/2024/01/2024-01-17-jenkins-contributor-summit-update.adoc
Labels: blogpost

#7019 Adding myself as a potential mentor for GSoC 2024
  content/images/avatars/iamrajiv.jpg
  content/projects/gsoc/2024/project-ideas/cloudevents-plugin.adoc
  content/projects/gsoc/2024/project-ideas/using-opentelemetry-for-jenkins-jobs-on-ci_jenkins_io.adoc
Labels: gsoc

#6964 Python tutorial revamp
  content/doc/book/resources/tutorials/python-pyinstaller-02-initial-pipeline-runs-successfully-step-opened.png
  content/doc/book/resources/tutorials/python-pyinstaller-03-main-blue-ocean-interface.png
  content/doc/book/resources/tutorials/python-pyinstaller-11-test-stage-runs-successfully-with-output.png
  content/doc/book/resources/tutorials/python-pyinstaller-21-deliver-stage-runs-successfully.png
  content/doc/book/resources/tutorials/python-pyinstaller-22-deliver-stage-output-only.png
  content/doc/book/resources/tutorials/python-pyinstaller-23-main-blue-ocean-interface-with-all-previous-runs-displayed.png
  content/doc/book/resources/tutorials/python-pyinstaller-24-deliver-stage-artifacts-page.png
  content/doc/book/resources/tutorials/python/build-stage-overview.png
  content/doc/book/resources/tutorials/python/deliver-stage-added.png
  content/doc/book/resources/tutorials/python/deliver-stage-output.png
  content/doc/book/resources/tutorials/python/first-build-details.png
  content/doc/book/resources/tutorials/python/first-job-success.png
  content/doc/book/resources/tutorials/python/pipeline-overview.png
  content/doc/book/resources/tutorials/python/pipeline-runs.png
  content/doc/book/resources/tutorials/python/test-stage-added.png
  content/doc/book/resources/tutorials/python/test-stage-output.png
  content/doc/book/resources/tutorials/python/test-stage-visible-pipeline-overview.png
  content/doc/tutorials/_new_prerequisites.adoc
  content/doc/tutorials/build-a-java-app-with-maven.adoc
  content/doc/tutorials/build-a-python-app-with-pyinstaller.adoc
  updatecli/updatecli.d/python.yaml
Labels: documentation

#7035 PHP guide: Update to use new Coverage plugin
  content/_data/solutions/php.yml
  content/solutions/php.adoc
Labels: documentation

#7034 Update npm-run-all to npm-run-all2
  package-lock.json
  package.json
Labels: chore

#7038 Sonar guest blog post regarding security
  content/blog/2024/01/2024-01-25-sonar-vulnerability-report.adoc
  content/images/post-images/2024/01/jenkins-and-sonar-security.png
Labels: blogpost

#7031 2023 recap.
  content/blog/2024/01/25/2024-01-25-jenkins-2023-recap.adoc
  content/images/post-images/2024/01/25/award.png
  content/images/post-images/2024/01/25/image1.png
Labels: blogpost

#7022 Update plugin deprecation page
  content/doc/developer/plugin-governance/deprecating-or-removing-plugin.adoc
Labels: documentation

#7040 Remove 2022 recap link from 2023 recap blog post
  content/blog/2024/01/25/2024-01-25-jenkins-2023-recap.adoc
Labels: blogpost

#7042 Create 2024-01-29-nominate-someone-2024-jenkins-contributor awards.adoc
  content/blog/2024/01/2024-01-29-nominate-someone-2024-jenkins-contributor awards.adoc
Labels: blogpost

#7047 Jenkins.io - update filename for spacing issues
  content/blog/2024/01/2024-01-29-nominate-someone-2024-jenkins-contributor-awards.adoc
Labels: blogpost

#7049 add content for set maven settings.xml
  content/doc/developer/plugin-development/dependency-management.adoc
  content/doc/developer/tutorial/prepare.adoc
Labels: documentation

#7053 Fix typo for contributor summit lunch time
  content/blog/2024/01/2024-01-17-jenkins-contributor-summit-update.adoc
Labels: blogpost
