Repository jenkins-infra/jenkins.io, pull requests merged in 2025-04, with the labels that each got.

#8010 Fix typos and combine unnecessary line breaks
  content/doc/book/pipeline/jenkinsfile.adoc
  content/doc/book/using/best-practices.adoc
Labels: documentation

#8012 Update of GSoC project ideas table UI
  content/projects/gsoc/2025/project-ideas.html.haml
Labels: gsoc

#8018 Improve readability and correct terminology
  content/doc/book/scaling/scaling-jenkins-on-kubernetes.adoc
Labels: documentation

#7977 feat: Add .NET Tutorial
  content/doc/book/resources/tutorials/dotnet/build-stage-overview.png
  content/doc/book/resources/tutorials/dotnet/build-widget.png
  content/doc/book/resources/tutorials/dotnet/deliver-artifacts.png
  content/doc/book/resources/tutorials/dotnet/deliver-stage-added.png
  content/doc/book/resources/tutorials/dotnet/deliver-stage-output.png
  content/doc/book/resources/tutorials/dotnet/first-build-details.png
  content/doc/book/resources/tutorials/dotnet/initial-pipeline.png
  content/doc/book/resources/tutorials/dotnet/pipeline-overview.png
  content/doc/book/resources/tutorials/dotnet/pipeline-runs.png
  content/doc/book/resources/tutorials/dotnet/test-coverage-result.png
  content/doc/book/resources/tutorials/dotnet/test-stage-added.png
  content/doc/book/resources/tutorials/dotnet/test-stage-output.png
  content/doc/book/resources/tutorials/dotnet/test-stage-visible-pipeline-overview.png
  content/doc/tutorials/build-a-dotnet-web-app-with-jenkins.adoc
  content/doc/tutorials/index.adoc
Labels: documentation

#8031 Split developer entry from other changelog entries
  content/_data/changelogs/weekly.yml
Labels: changelog

#8036 Creates health score section in plugin management
  content/doc/book/managing/plugins.adoc
  content/doc/book/resources/managing/plugin-manager-available-health-score.png
  content/doc/book/resources/managing/plugin-site-health-score.png
  content/redirect/plugin-health-score.adoc
Labels: documentation

#8041 Restore LTS changelogs before 2.32.1
  content/changelog-stable-old/index.html.haml
Labels: changelog

#8043 Fix link to reverse proxy config page
  content/doc/book/managing/system-configuration.adoc
Labels: documentation

#8038 add administrative capabilities and best practices of system level Groovy
  content/doc/book/managing/script-console.adoc
Labels: documentation

#8046 Add Java 21 upgrade instructions
  content/doc/book/installing/linux.adoc
  content/doc/book/platform-information/_chapter.yml
  content/doc/book/platform-information/index.adoc
  content/doc/book/platform-information/upgrade-java-to-11.adoc
  content/doc/book/platform-information/upgrade-java-to-17.adoc
  content/doc/book/platform-information/upgrade-java-to-21.adoc
Labels: documentation

#8048 Formatting & syntax updates to Pipeline index
  content/doc/book/pipeline/index.adoc
Labels: documentation

#8049 Update 2025-03-18-jenkins-contributor-awards-2025-nomination-is-open.…
  content/blog/2025/03/18/2025-03-18-jenkins-contributor-awards-2025-nomination-is-open.adoc
Labels: blogpost

#8055 Update Docker installation for jdk21
  content/doc/book/installing/_docker.adoc
Labels: documentation

#8057 Update archetypes to 1.27
  content/doc/developer/tutorial/create.adoc
Labels: documentation

#8060 Update Pipeline Syntax docs to remove role from text
  content/doc/book/pipeline/syntax.adoc
Labels: documentation

#8033 Create LTS 2.504.1 changelog and upgrade guide
  content/_data/changelogs/lts.yml
  content/_data/upgrades/2-504-1.adoc
Labels: changelog

#8063 Update keyring location
  content/doc/book/installing/linux.adoc
Labels: enhancement, documentation

#8067 Additional updates for Java 21 in documentation
  content/doc/book/installing/_docker-for-tutorials.adoc
  content/doc/book/pipeline/shared-libraries.adoc
  content/doc/book/pipeline/syntax.adoc
  content/doc/book/scaling/architecting-for-manageability.adoc
  content/doc/book/scaling/scaling-jenkins-on-kubernetes.adoc
  content/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-pomerium.adoc
  content/doc/book/system-administration/systemd-services.adoc
  content/doc/book/using/using-agents.adoc
  content/doc/developer/tutorial/prepare.adoc
  updatecli/updatecli.d/jenkins-lts.yaml
Labels: documentation

#8071 Update Gradle image for docker in pipeline
  content/doc/book/pipeline/docker.adoc
Labels: documentation
