Repository jenkins-infra/jenkins.io, pull requests merged in 2025-05, with the labels that each got.

#8077 Add blog post on 'Revamped Pipeline visualization in Jenkins'
  content/blog/2025/05/02/2025-05-02-pipeline-graph-view.adoc
  content/images/post-images/2025/05/2025-05-02-pipeline-graph-view/opengraph.png
  content/images/post-images/2025/05/2025-05-02-pipeline-graph-view/sidebar.png
Labels: blogpost

#8080 Add more crowdin config
  content/doc/developer/crowdin/crowdin-integration.adoc
Labels: documentation

#8082 Fix reuseNode sample Pipeline
  content/doc/book/pipeline/docker.adoc
Labels: bug, documentation

#8081 Remove low impact bug fix from 2.508 changelog
  content/_data/changelogs/weekly.yml
Labels: bug, changelog

#8085 Add banner for docker image Java 21 change
  content/_data/changelogs/weekly.yml
Labels: changelog

#8093 Add back Active Directory upgrade instruction for 2.509 changelog
  content/_data/changelogs/weekly.yml
Labels: changelog

#8094 Add separate entry for jbcrypt library removal
  content/_data/changelogs/weekly.yml
Labels: changelog

#8095 docs: update Servlet page to latest info
  content/doc/book/installing/servlet-containers.adoc
Labels: documentation

#8100 Create 2025-05-15-jenkins-contributor-awards-cast-your-vote.adoc
  content/blog/2025/05/15/2025-05-15-jenkins-contributor-awards-cast-your-vote.adoc
Labels: blogpost

#8103 fix: yaml links in kubernetes page
  content/doc/book/installing/_kubernetes.adoc
Labels: documentation

#8109 fix: some grammars and words
  content/blog/2010/2010-11-30-whos-driving-this-thing.adoc
  content/blog/2013/2013-09-05-extreme-feedback-lamp-switch-gear-style.adoc
  content/blog/2016/2016-09-19-blueocean-beta-declarative-pipeline-pipeline-editor.adoc
  content/blog/2016/2016-09-30-jenkins-world-2016-wrap-up-complete.adoc
  content/blog/2016/2016-10-31-xunit-reporting.adoc
  content/blog/2017/02/2017-02-23-declarative-saucelabs-xunit.adoc
  content/blog/2018/08/2018-08-23-speaker-blog-casc-part-1.adoc
  content/blog/2020/01/2020-01-07-happy-new-year.adoc
  content/blog/2020/04/2020-04-16-github-app-authentication.adoc
  content/blog/2023/03/10/2023-03-10-miniJen-and-RISC-V.adoc
  content/blog/2023/09/05/2023-09-06-devops-world-tour.adoc
  content/doc/book/blueocean/getting-started.adoc
  content/doc/book/managing/cli.adoc
  content/doc/book/pipeline/jenkinsfile.adoc
  content/doc/developer/forms/jelly-form-controls.adoc
  content/doc/tutorials/tutorial-for-installing-jenkins-on-AWS.adoc
  content/projects/gsoc/2019/plugin-installation-manager-tool-cli.adoc
  content/projects/gsoc/2020/project-ideas/jenkins-rest-plugin.adoc
  content/security/advisory/2017-04-10.adoc
  content/sites/default/files/js/js_e0fda2721e2af67819e9d6009b448426.js
  content/solutions/python.adoc
  updatecli/scripts/jenkins-split.sh
Labels: gsoc, blogpost, chore, documentation

#8113 fix: grammatical correction
  content/_partials/changelog-old.html
Labels: changelog

#8098 Add changelog and upgrade guide for 2.504.2
  content/_data/changelogs/lts.yml
  content/_data/upgrades/2-504-2.adoc
Labels: changelog

#8117 Recommend `ControllerToAgentCallable`
  content/doc/developer/security/remoting-callables.adoc
Labels: documentation

#8112 feat(blog): Jenkins on Android, part two
  content/blog/2023/03/30/2023-03-30-android-and-jenkins.adoc
  content/blog/2025/05/22/2025-05-22-jenkins-on-android.adoc
  content/images/post-images/2025/05/22/2025-05-22-jenkins-on-android/agent-connected.png
  content/images/post-images/2025/05/22/2025-05-22-jenkins-on-android/first-console-output.png
  content/images/post-images/2025/05/22/2025-05-22-jenkins-on-android/first-maven-build.png
  content/images/post-images/2025/05/22/2025-05-22-jenkins-on-android/jenkins-complaining.png
  content/images/post-images/2025/05/22/2025-05-22-jenkins-on-android/jenkins-home.png
  content/images/post-images/2025/05/22/2025-05-22-jenkins-on-android/love-part-2-16-9.png
  content/images/post-images/2025/05/22/2025-05-22-jenkins-on-android/love-part-2.png
  content/images/post-images/2025/05/22/2025-05-22-jenkins-on-android/no-more-warning.png
  content/images/post-images/2025/05/22/2025-05-22-jenkins-on-android/plugins-install.png
  content/images/post-images/2025/05/22/2025-05-22-jenkins-on-android/security-issue.png
  content/images/post-images/2025/05/22/2025-05-22-jenkins-on-android/set-up-agent.png
  content/images/post-images/2025/05/22/2025-05-22-jenkins-on-android/unlock-jenkins.png
Labels: blogpost

#8116 fix: some important links
  content/_data/changelogs/lts.yml
  content/_data/changelogs/weekly.yml
  content/participate/connect.adoc
  content/sigs/docs/index.adoc
Labels: changelog

#8123 Use ':Z' option to bind mount Docker volumes on SELinux
  scripts/docker-env
Labels: chore

#8124 Document jenkins.security.JettySameSiteCookieSetup.sameSiteDefault
  content/doc/book/managing/system-properties.adoc
Labels: on-hold, documentation

#8129 Update 2.512 packaging entry
  content/_data/changelogs/weekly.yml
Labels: changelog

#8130 Document jenkins.security.JettySameSiteCookieSetup.sameSiteDefault
  content/doc/book/managing/system-properties.adoc
Labels: on-hold, documentation
