Repository jenkins-infra/jenkins.io, pull requests merged in 2025-03, with the labels that each got.

#7935 Update gsoc contributor docs
  content/projects/gsoc/contributors.adoc
Labels: gsoc

#7938 Fix hyperlink to global variable reference
  content/doc/book/pipeline/multibranch.adoc
Labels: documentation

#7939 Added missing lighttpd entry for left menu
  content/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/_section.yml
Labels: documentation

#7934 feat: add more content to `system information` page
  content/doc/book/managing/system-info.adoc
  content/doc/book/resources/managing/environment-variables.png
  content/doc/book/resources/managing/memory-usage.png
  content/doc/book/resources/managing/system-info-page.png
  content/doc/book/resources/managing/system-plugins.png
  content/doc/book/resources/managing/system-properties.png
  content/doc/book/resources/managing/thread-dump.png
Labels: documentation

#7942 Update JEP-229 CD docs
  content/doc/developer/publishing/releasing-cd.adoc
Labels: documentation

#7945 Create Jenkins-in-Google-Summer-of-Code-2025.adoc
  content/blog/2025/03/05/Jenkins-in-Google-Summer-of-Code-2025.adoc
Labels: blogpost

#7933 feat: update the ui/ux of `artwork` page
  content/artwork/index.html.haml
Labels: artwork

#7949 fix(blog): fix naming of latest gsoc blog post to comply with convention
  content/blog/2025/03/05/2025-03-05-Jenkins-in-Google-Summer-of-Code-2025.adoc
  content/images/post-images/2025/03/GSoC2025_opengraph.png
Labels: blogpost

#7955 Update 2025-03-05-Jenkins-in-Google-Summer-of-Code-2025.adoc
  content/blog/2025/03/05/2025-03-05-Jenkins-in-Google-Summer-of-Code-2025.adoc
Labels: blogpost

#7923 feat: add `Manage Users` documentation to jenkins.io
  content/doc/book/managing/users.adoc
  content/doc/book/resources/managing/account-preference.png
  content/doc/book/resources/managing/create-users-click.png
  content/doc/book/resources/managing/create-users-example.png
  content/doc/book/resources/managing/create-users.png
  content/doc/book/resources/managing/delete-user-alternative.png
  content/doc/book/resources/managing/delete-users.png
  content/doc/book/resources/managing/manager-users-home-page.png
  content/doc/book/resources/managing/select-user.png
  content/doc/book/resources/managing/select-users.png
Labels: documentation

#7964 Update index.html.haml - remove reference to broken ordering site
  content/artwork/index.html.haml
Labels: artwork

#7967 fix(ui): patch potential logical bug when thank-you note contributor only has one repo
  content/_partials/thank-you-note.html.haml
  content/download/index.html.haml
  content/index.html.haml
Labels: bug

#7972 feat: add Ashutosh as gsoc 2025 mentor
  content/_data/authors/ashu565.adoc
  content/images/avatars/ashu565.png
  content/projects/gsoc/2025/project-ideas/ai-powered-chatbot-for-quick-access-to-jenkins-resources.adoc
Labels: gsoc

#7974 Update UX SIG page to include Design Library 3
  content/blog/2024/08/29/2024-08-29-jenkins-design.adoc
  content/blog/2024/12/02/2024-12-02-pr-titles.adoc
  content/blog/2025/01/2025-01-10-design-library.adoc
  content/blog/2025/02/2025-02-05-command-palette.adoc
  content/sigs/ux/index.adoc
Labels: community

#7976 feat(gsoc): add cnu1812 as co-mentor to GSoC 2025 domain specific LLM project
  content/projects/gsoc/2025/project-ideas/domain-specific-LLM-based-on-jenkins-usage-using-ci.jenkins.io-data.adoc
Labels: gsoc

#7970 feat(doc): add UDS support documentation for Apache reverse proxy #6890
  content/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-apache.adoc
Labels: documentation

#7963 content/doc/book/installing/kubernetes.adoc: elaborate about file system access
  content/doc/book/installing/kubernetes.adoc
Labels: documentation

#7982 Update _docker-for-tutorials.adoc
  content/doc/book/installing/_docker-for-tutorials.adoc
Labels: documentation

#7988 chore: Update _docker.adoc
  content/doc/book/installing/_docker.adoc
Labels: documentation

#7990 Announce 2025 contributor awards
  content/blog/2025/03/18/2025-03-18-jenkins-contributor-awards-2025-nomination-is-open.adoc
  content/images/post-images/2025/03/community-awards-2025-jenkins.png
Labels: blogpost

#7992 Create LTS 2.492.3 changelog and upgrade guide
  content/_data/changelogs/lts.yml
  content/_data/upgrades/2-492-3.adoc
Labels: changelog

#7998 Add a blog post on 'Redesigning Jenkins'
  content/_data/authors/janfaracik.adoc
  content/blog/2025/04/05/2025-04-05-design-post.adoc
  content/images/post-images/2025/04/2025-04-05-design-post/banner.png
  content/images/post-images/2025/04/2025-04-05-design-post/opengraph.png
Labels: blogpost

#8001 Update date for design post
  content/blog/2025/03/26/2025-03-26-design-post.adoc
  content/images/post-images/2025/03/2025-03-26-design-post/banner.png
  content/images/post-images/2025/03/2025-03-26-design-post/opengraph.png
Labels: blogpost

#8008 Fix typos in pipeline-as-code.adoc
  content/doc/book/pipeline/pipeline-as-code.adoc
Labels: documentation

#8005 feat: update tutorial-for-installing-jenkins-on-AWS.adoc
  content/doc/tutorials/tutorial-for-installing-jenkins-on-AWS.adoc
Labels: documentation

#8009 Combine unnecessary line breaks
  content/doc/book/pipeline/pipeline-as-code.adoc
Labels: documentation
