Repository jenkins-infra/jenkins.io, pull requests merged in 2025-09, with the labels that each got.

#8391 feat (blog): Gradle Convention Plugin for Jenkins Plugin Development
  content/_data/authors/aaravmahajanofficial.adoc
  content/blog/2025/08/31/2025-08-31-aarav-mahajan-gsoc-gradle-convention-plugin-for-jenkins-plugin-development.adoc
  content/images/post-images/2025/08/aaravmahajan/gradle-convention-plugin.png
  content/images/post-images/2025/08/aaravmahajan/jenkins-plugin-with-maven-vs-gradle.png
Labels: blogpost

#8415 Fix location of typos report
  .typos.toml
  Jenkinsfile
  content/blog/2019/07/2019-07-25-azure-artifact-manager.adoc
  scripts/check-typos
Labels: blogpost, chore

#8420 chore(Jenkinsfile) purge cache of only a few pages instead of the whole website during production deployment
  Jenkinsfile
Labels: chore

#8424 feat (docs): Recommend installing Java before Jenkins on Debian/Ubuntu
  content/doc/book/installing/linux.adoc
Labels: documentation

#8449 Insert missing image for Hacktoberfest blog
  content/blog/2025/09/24/2025-09-24-hacktoberfest-2025-intro.adoc
  content/events/hacktoberfest.adoc
  content/images/hacktoberfest/hacktoberfest_2025_logo.svg
Labels: blogpost
